# DORAnet → enzyme hypotheses → DNA design

This notebook converts DORAnet-generated reaction networks into concise downstream design tables: parsed reactions, enzyme hypotheses, enzyme-candidate templates, and non-operational DNA design plans for expert review.

In [1]:
from pathlib import Path
import glob
import json
import os
import re
import textwrap
import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from rdkit import Chem, rdBase
from rdkit.Chem import rdmolfiles, Draw
from IPython.display import display
import time
import requests
from io import StringIO
import ast
import sys
import yaml
from tqdm.auto import tqdm
tqdm.pandas()

from DORA_XGB import DORA_XGB
by_desc_MW_model = DORA_XGB.feasibility_classifier(cofactor_positioning = 'by_descending_MW')
by_asc_MW_model = DORA_XGB.feasibility_classifier(cofactor_positioning = 'by_ascending_MW')
add_concat_model = DORA_XGB.feasibility_classifier(cofactor_positioning = 'add_concat')
add_subtract_model = DORA_XGB.feasibility_classifier(cofactor_positioning = 'add_subtract')

from Bio.Data import CodonTable

from dnachisel import (
    DnaOptimizationProblem,
    EnforceTranslation,
    EnforceGCContent,
    AvoidPattern,
    MaximizeCAI,
)

import hashlib

/users/sghosh6/.conda/envs/doranet_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/users/sghosh6/.conda/envs/doranet_env/lib/python3.10/site-packages/xgboost/compat.py:105: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [2]:
dataDir = '/mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/DrugDesignData/'
resultsDir = os.path.join(dataDir, 'Results/combinedEbolaVirus_bestMACAW_allDB_generative/')
DORANETmoleculesDataDir = os.path.join(resultsDir, 'DORAnet/InoAdeGuoXan/PATHWAY_reconstruction/')
#DORANETmoleculesDataDir = os.path.join(resultsDir, 'DORAnet/InoAdeGuoXan/PATHWAY_reconstruction_run2/')
DNADesignResultsDir = os.path.join(resultsDir, 'DNA_design/')
os.makedirs(DNADesignResultsDir, exist_ok=True)

print("Reading DORAnet results from:", DORANETmoleculesDataDir)
print("DNA design results will be saved at:", DNADesignResultsDir)

Reading DORAnet results from: /mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/DrugDesignData/Results/combinedEbolaVirus_bestMACAW_allDB_generative/DORAnet/InoAdeGuoXan/PATHWAY_reconstruction/
DNA design results will be saved at: /mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/DrugDesignData/Results/combinedEbolaVirus_bestMACAW_allDB_generative/DNA_design/

## 0. Read list of target DORAnet compounds

In [3]:
targetCompound_DF = pd.read_csv(resultsDir + "/combinedEbola_allDORAnetGenerated_Antivirals_wARTprediction_top20.csv")
targetCompound_DF

,Rank,Canonical_SMILES,pPotency_prediction,pPotency_std,IC50 (µM)
0,1,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,6.156,0.476241,0.697981
1,2,CC(C)(COP(=O)(O)OP(=O)(O)OC[C@H]1O[C@@H](n2cnc...,5.989,0.473052,1.025573
2,3,Cc1cc2c(cc1C)N(C[C@H](O)[C@H](O)[C@H](O)COP(=O...,5.907,0.473610,1.238912
3,4,Cc1cc2nc3c(=O)[nH]c(=O)nc-3n(C[C@H](O)[C@H](O)...,5.825,0.472941,1.495337
4,5,CC(=O)OP(=O)(O)OC(C)=O,5.758,0.479591,1.747229
5,6,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,5.729,0.473567,1.865382
6,7,CC(=O)OP(=O)(O)OP(=O)(O)O,5.693,0.478908,2.026785
7,8,Nc1ncnc2c1ncn2[C@@H]1OC(C(O)O)=C[C@H]1O,5.692,0.473252,2.030622
8,9,CC(Cl)[C@H]1O[C@@H](n2cnc3c(NC=O)ncnc32)[C@H](...,5.683,0.471067,2.074770
9,10,O=C(O)CC(=O)OP(=O)(O)O,5.679,0.476017,2.094051
10,11,C[C@H]1O[C@@H](n2cnc3c(=O)[nH]c(NC=O)nc32)[C@H...,5.677,0.471412,2.104081
11,12,O=C1N=C2NC=Nc3c2ncn3[C@@H]2O[C@H]1[C@@H](O)[C@...,5.670,0.471980,2.136730
12,13,NC1=Nc2ncnc3c2ncn3[C@@H]2O[C@H]1[C@@H](O)[C@H]2O,5.669,0.470421,2.140884
13,14,C[C@H]1O[C@@H](n2cnc3c(NC=O)ncnc32)[C@H](O)[C@...,5.667,0.470071,2.155065
14,15,NC(=O)OP(=O)(O)O,5.664,0.478859,2.166036
15,16,O=C(O)CC(=O)O,5.651,0.475530,2.233832
16,17,O=CNc1ncnc2c1ncn2[C@@H]1O[C@H](C=O)[C@@H](O)[C...,5.645,0.472112,2.262352
17,18,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,5.638,0.472788,2.302842
18,19,CC(=O)CC(=O)O,5.637,0.474230,2.304127
19,20,Nc1nc2c(ncn2[C@@H]2OC(C(O)O)=C[C@H]2O)c(=O)[nH]1,5.629,0.475703,2.348605

In [4]:
DORANETmoleculesDataDir = Path(DORANETmoleculesDataDir)

def canonicalizeSmiles(smiles):
    mol = Chem.MolFromSmiles(str(smiles))
    return Chem.MolToSmiles(mol, canonical=True) if mol else None

def canonicalizeSmilesCollection(x):
    if not isinstance(x, (set, list, tuple)):
        return []
    out = []
    for s in x:
        c = canonicalizeSmiles(s)
        if c is not None:
            out.append(c)
    return sorted(set(out))

def parseLiteralFromScript(text, varName):
    # captures lines like: varName = {...} / [...] / "..."
    m = re.search(rf"^\s*{re.escape(varName)}\s*=\s*(.+)\s*$", text, flags=re.MULTILINE)
    if not m:
        return None
    raw = m.group(1).strip()
    try:
        return ast.literal_eval(raw)
    except Exception:
        return None

def parseHelpersFromScript(text):
    # Supports YAML-like line: helpers: ["O", ...]
    m = re.search(r"^\s*helpers\s*:\s*(.+)\s*$", text, flags=re.MULTILINE)
    if not m:
        # fallback in case file uses python assignment: helpers = [...]
        return parseLiteralFromScript(text, "helpers")
    raw = m.group(1).strip()
    try:
        return ast.literal_eval(raw)
    except Exception:
        return None

allReproFiles = sorted(
    DORANETmoleculesDataDir.rglob("reproDoranetJob.py"),
    key=lambda p: str(p).lower()
)

records = []
for reproPath in allReproFiles:
    txt = reproPath.read_text(encoding="utf-8", errors="ignore")

    startersRaw = parseLiteralFromScript(txt, "starters")
    targetRaw = parseLiteralFromScript(txt, "target")
    maxAtomsRaw = parseLiteralFromScript(txt, "maxAtoms")
    generationsRaw = parseLiteralFromScript(txt, "generations")
    helpersRaw = parseHelpersFromScript(txt)

    records.append({
        "dirName": reproPath.parent.name,
        "starters": canonicalizeSmilesCollection(startersRaw),
        "target": canonicalizeSmilesCollection(targetRaw),
        "helpers": canonicalizeSmilesCollection(helpersRaw),   # NEW
        "maxAtoms": maxAtomsRaw if isinstance(maxAtomsRaw, dict) else None,
        "generations": int(generationsRaw) if generationsRaw is not None else None,
    })

targetCompoundDir_DF = pd.DataFrame(
    records,
    columns=["dirName", "starters", "target", "helpers", "maxAtoms", "generations"]  # NEW
)

print(f"Total DORAnet configuration files: {len(targetCompoundDir_DF)}")

# join key from first target smiles
targetCompoundDir_DF = targetCompoundDir_DF.copy()
targetCompoundDir_DF["targetSmiles"] = targetCompoundDir_DF["target"].apply(
    lambda x: x[0] if isinstance(x, (list, tuple)) and len(x) > 0 else None
)

colsToAdd = ["Canonical_SMILES", "pPotency_prediction", "pPotency_std", "IC50 (µM)"]
targetCompoundDir_DF = targetCompoundDir_DF.merge(
    targetCompound_DF[colsToAdd].drop_duplicates(subset=["Canonical_SMILES"]),
    left_on="targetSmiles",
    right_on="Canonical_SMILES",
    how="left"
).drop(columns=["Canonical_SMILES"])

targetCompoundDir_DF = targetCompoundDir_DF.drop(columns=["targetSmiles"])
targetCompoundDir_DF = targetCompoundDir_DF.rename(columns={
    "starters": "starters_Canonical_SMILES",
    "target": "target_Canonical_SMILES",
    "helpers": "helpers_Canonical_SMILES",   
})

for c in ["starters_Canonical_SMILES", "target_Canonical_SMILES"]:
    targetCompoundDir_DF[c] = targetCompoundDir_DF[c].apply(
        lambda x: ".".join(x) if isinstance(x, (list, tuple)) else ("" if pd.isna(x) else str(x))
    )

# Keep helpers as separate entries joined by comma (not dot)
targetCompoundDir_DF["helpers_Canonical_SMILES"] = targetCompoundDir_DF["helpers_Canonical_SMILES"].apply(
    lambda x: ", ".join(x) if isinstance(x, (list, tuple)) else ("" if pd.isna(x) else str(x))
)

targetCompoundDir_DF = targetCompoundDir_DF.sort_values(
    by="pPotency_prediction", ascending=False
).reset_index(drop=True)

# safer path handling
outputPath = Path(DNADesignResultsDir) / "targetCompoundDir_DF.csv"
targetCompoundDir_DF.to_csv(outputPath, index=False)
targetCompoundDir_DF

Total DORAnet configuration files: 20

,dirName,starters_Canonical_SMILES,target_Canonical_SMILES,helpers_Canonical_SMILES,maxAtoms,generations,pPotency_prediction,pPotency_std,IC50 (µM)
0,high_pPotency_molecule_pathway1,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,6.156,0.476241,0.697981
1,high_pPotency_molecule_pathway2,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,CC(C)(COP(=O)(O)OP(=O)(O)OC[C@H]1O[C@@H](n2cnc...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.989,0.473052,1.025573
2,high_pPotency_molecule_pathway3,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,Cc1cc2c(cc1C)N(C[C@H](O)[C@H](O)[C@H](O)COP(=O...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.907,0.473610,1.238912
3,high_pPotency_molecule_pathway4,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,Cc1cc2nc3c(=O)[nH]c(=O)nc-3n(C[C@H](O)[C@H](O)...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.825,0.472941,1.495337
4,high_pPotency_molecule_pathway5,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,CC(=O)OP(=O)(O)OC(C)=O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.758,0.479591,1.747229
5,high_pPotency_molecule_pathway6,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.729,0.473567,1.865382
6,high_pPotency_molecule_pathway7,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,CC(=O)OP(=O)(O)OP(=O)(O)O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.693,0.478908,2.026785
7,high_pPotency_molecule_pathway8,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,Nc1ncnc2c1ncn2[C@@H]1OC(C(O)O)=C[C@H]1O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.692,0.473252,2.030622
8,high_pPotency_molecule_pathway9,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,CC(Cl)[C@H]1O[C@@H](n2cnc3c(NC=O)ncnc32)[C@H](...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.683,0.471067,2.074770
9,high_pPotency_molecule_pathway10,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,O=C(O)CC(=O)OP(=O)(O)O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.679,0.476017,2.094051
10,high_pPotency_molecule_pathway11,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,C[C@H]1O[C@@H](n2cnc3c(=O)[nH]c(NC=O)nc32)[C@H...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.677,0.471412,2.104081
11,high_pPotency_molecule_pathway12,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,O=C1N=C2NC=Nc3c2ncn3[C@@H]2O[C@H]1[C@@H](O)[C@...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.670,0.471980,2.136730
12,high_pPotency_molecule_pathway13,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,NC1=Nc2ncnc3c2ncn3[C@@H]2O[C@H]1[C@@H](O)[C@H]2O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.669,0.470421,2.140884
13,high_pPotency_molecule_pathway14,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,C[C@H]1O[C@@H](n2cnc3c(NC=O)ncnc32)[C@H](O)[C@...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.667,0.470071,2.155065
14,high_pPotency_molecule_pathway15,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,NC(=O)OP(=O)(O)O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.664,0.478859,2.166036
15,high_pPotency_molecule_pathway16,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,O=C(O)CC(=O)O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.651,0.475530,2.233832
16,high_pPotency_molecule_pathway17,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,O=CNc1ncnc2c1ncn2[C@@H]1O[C@H](C=O)[C@@H](O)[C...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.645,0.472112,2.262352
17,high_pPotency_molecule_pathway18,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.638,0.472788,2.302842
18,high_pPotency_molecule_pathway19,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,CC(=O)CC(=O)O,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.637,0.474230,2.304127
19,high_pPotency_molecule_pathway20,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)[C...,Nc1nc2c(ncn2[C@@H]2OC(C(O)O)=C[C@H]2O)c(=O)[nH]1,"Br, BrBr, C#N, C=C, C=O, CO, N, N#CO, N#N, NO,...","{'C': 15, 'N': 6, 'O': 8, 'S': 3}",3,5.629,0.475703,2.348605

## 1. Read DORAnet reaction network files

In [5]:
DORANETmoleculesDataDir = Path(DORANETmoleculesDataDir)  

def extractFirstInt(text):
    match = re.search(r"\d+", text)
    return int(match.group(0)) if match else -1

# Find all JSON files anywhere under root
allJsonPaths = sorted(DORANETmoleculesDataDir.rglob("*.json"), key=lambda p: str(p).lower())

fileInfoList = []
for jsonPath in allJsonPaths:
    parentDir = jsonPath.parent
    fileInfoList.append({
        "dirName": parentDir.name,
        "dirPath": str(parentDir),
        "jsonName": jsonPath.name,
        "jsonPath": str(jsonPath),
        "folderNum": extractFirstInt(parentDir.name),  # optional helper field
    })

print(f"Root directory        : {DORANETmoleculesDataDir}")
print(f"JSON files found      : {len(fileInfoList)}")
print(f"Unique folders w/JSON : {len({x['dirPath'] for x in fileInfoList})}")

Root directory        : /mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/DrugDesignData/Results/combinedEbolaVirus_bestMACAW_allDB_generative/DORAnet/InoAdeGuoXan/PATHWAY_reconstruction
JSON files found      : 20
Unique folders w/JSON : 20

## 2.1 Parse DORAnet reaction pathways

In [6]:
def splitMoleculeString(moleculeString):
    return [mol for mol in str(moleculeString).split(".") if mol]

def parseDoranetReaction(rxnString, fileInfo):
    parts = str(rxnString).split(">")
    if len(parts) != 4:
        raise ValueError(f"Expected 4 fields separated by '>'; found {len(parts)}")

    reactants, ruleName, metaBlock, products = parts
    metaParts = (metaBlock.split("$") + [None, None, None, None])[:4]
    thermo, reactantStoich, productStoich, reactionType = metaParts

    return {
        "reactants": reactants,
        "products": products,
        "reactionString": f"{reactants} >> {products}",
        "ruleName": ruleName,
        "thermo": thermo,
        "reactantStoich": reactantStoich,
        "productStoich": productStoich,
        "reactionType": reactionType,
        "numReactantMolecules": len(splitMoleculeString(reactants)),
        "numProductMolecules": len(splitMoleculeString(products)),
        "sourceFolderNum": fileInfo.get("folderNum", -1),
        "sourceDirectory": fileInfo.get("dirName", ""),
        "sourceDirectoryPath": fileInfo.get("dirPath", ""),
        "sourceJsonName": fileInfo.get("jsonName", ""),
        "sourceJsonPath": fileInfo.get("jsonPath", ""),
    }

reactionRecords = []
jsonReadErrors = []
uniqueReactantMolecules = set()
uniqueProductMolecules = set()

for fileInfo in tqdm(fileInfoList, desc="Reading DORAnet JSON"):
    try:
        with open(fileInfo["jsonPath"], "r", encoding="utf-8") as f:
            reactionList = json.load(f)

        # handle both list and dict payloads
        if isinstance(reactionList, dict):
            # try common key names; otherwise fail clearly
            for k in ["reactions", "reactionList", "data"]:
                if k in reactionList and isinstance(reactionList[k], list):
                    reactionList = reactionList[k]
                    break
            else:
                raise ValueError("JSON is dict but no reaction list key found")

        if not isinstance(reactionList, list):
            raise ValueError(f"Expected list of reaction strings, got {type(reactionList)}")

        for rxnString in reactionList:
            record = parseDoranetReaction(rxnString, fileInfo)
            reactionRecords.append(record)
            uniqueReactantMolecules.update(splitMoleculeString(record["reactants"]))
            uniqueProductMolecules.update(splitMoleculeString(record["products"]))

    except Exception as exc:
        jsonReadErrors.append({**fileInfo, "error": str(exc)})

if not reactionRecords:
    raise RuntimeError("No reactions loaded. Check JSON discovery and reaction format.")

reactionDF = pd.DataFrame(reactionRecords).reset_index(drop=True)

# safer path handling
outputPath = Path(DNADesignResultsDir) / "reactionDF.csv"
reactionDF.to_csv(outputPath, index=False)

print(f"Reactions loaded     : {len(reactionDF):,}")
print(f"Failed JSON files    : {len(jsonReadErrors):,}")
print(f"Unique reactant mols : {len(uniqueReactantMolecules):,}")
print(f"Unique product mols  : {len(uniqueProductMolecules):,}")
print(f"Saved: {outputPath}")

reactionDF.head()

Reading DORAnet JSON: 100%|████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 22.69it/s]

Reactions loaded     : 176,400
Failed JSON files    : 0
Unique reactant mols : 283
Unique product mols  : 4,730
Saved: /mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/DrugDesignData/Results/combinedEbolaVirus_bestMACAW_allDB_generative/DNA_design/reactionDF.csv

,reactants,products,reactionString,ruleName,thermo,reactantStoich,productStoich,reactionType,numReactantMolecules,numProductMolecules,sourceFolderNum,sourceDirectory,sourceDirectoryPath,sourceJsonName,sourceJsonPath
0,CO[C@@H]1[C@H](OC(C)=O)[C@@H](CO)O[C@H]1n1cnc2...,CO[C@@H]1[C@H](OC(C)=O)[C@@H](C=O)O[C@H]1n1cnc...,CO[C@@H]1[C@H](OC(C)=O)[C@@H](CO)O[C@H]1n1cnc2...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,1,high_pPotency_molecule_pathway1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway1_network_pretre...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...
1,COC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H](O)...,COC[C@]1(C)O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H](...,COC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H](O)...,rule0028_51,No_Thermo,"(1,)","(1,)",Enzymatic,1,1,1,high_pPotency_molecule_pathway1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway1_network_pretre...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...
2,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@]2(C(O)O)O[C@H]2[...,O=c1[nH]c(C(O)O)nc2c1ncn2[C@@H]1O[C@@H]2O[C@H]...,O=c1[nH]cnc2c1ncn2[C@@H]1O[C@]2(C(O)O)O[C@H]2[...,rule0028_50,No_Thermo,"(1,)","(1,)",Enzymatic,1,1,1,high_pPotency_molecule_pathway1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway1_network_pretre...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...
3,CC(=O)O[C@H]1[C@H](n2cnc3c(=O)[nH]cnc32)O[C@H]...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)O[C@H]1[C@H](n2cnc3c(=O)[nH]cnc32)O[C@H]...,rule0001_87,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,1,high_pPotency_molecule_pathway1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway1_network_pretre...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...
4,CC(O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc3...,COC(C)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...,CC(O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc3...,rule0011_50,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,1,high_pPotency_molecule_pathway1,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...,high_pPotency_molecule_pathway1_network_pretre...,/mnt/data.ese/nfs/users/sghosh6/DTRA_project/M...

In [7]:
print(reactionDF['reactionString'].iloc[0])
print(reactionDF['reactionString'].iloc[1])
print(reactionDF['reactionString'].iloc[2])

#print(reactionDF['reactionString'].iloc[4])

CO[C@@H]1[C@H](OC(C)=O)[C@@H](CO)O[C@H]1n1cnc2c(=O)[nH]cnc21.NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)(O)O)[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1.O=O >> CO[C@@H]1[C@H](OC(C)=O)[C@@H](C=O)O[C@H]1n1cnc2c(=O)[nH]cnc21.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)(O)O)[C@@H]3O)[C@@H](O)[C@H]2O)c1.O.O
COC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H](O)[C@@H]1OC(C)=O >> COC[C@]1(C)O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H](O)[C@@H]1OC=O
O=c1[nH]cnc2c1ncn2[C@@H]1O[C@]2(C(O)O)O[C@H]2[C@H]1O >> O=c1[nH]c(C(O)O)nc2c1ncn2[C@@H]1O[C@@H]2O[C@H]2[C@H]1O

## 2.2 Read the `reconstructed` pathways metadata for all `DORAnet` reactions

- go to the directory where pathway reconstruction DORAnet results are saved
- run this: `python pathwayReconstruction.py config.yaml`
- this will generate the csv file (`doranet_chain_reconstructed_pathway_steps_by_depth.csv`) with reconstructed pathways
- read the csv file for downstream processing

In [13]:
# -------------------------------------------------------------------
# settings
# -------------------------------------------------------------------
pathwayReconstructionConfigPath = Path(DNADesignResultsDir + "config.yaml")
keepOnlySuccessfulRoutes = True
maxRoutesPerFolderDepth = None  
saveOutput = True


# -------------------------------------------------------------------
# Helper functions
# -------------------------------------------------------------------
def splitMoleculeString(moleculeString):
    if pd.isna(moleculeString):
        return []
    return [mol for mol in str(moleculeString).split(".") if mol]


def extractFolderNum(dirName):
    match = re.search(r"(\d+)$", str(dirName))
    return int(match.group(1)) if match else -1


def parseDoranetReaction(rxnString, fileInfo):
    """
    Parse original DORAnet reaction string:

        reactants > ruleName > thermo$reactantStoich$productStoich$reactionType > products

    Returns a reactionDF-like record.
    """
    parts = str(rxnString).split(">")

    if len(parts) != 4:
        raise ValueError(f"Expected 4 fields separated by '>'; found {len(parts)}")

    reactants, ruleName, metaBlock, products = parts

    metaParts = (metaBlock.split("$") + [None, None, None, None])[:4]
    thermo, reactantStoich, productStoich, reactionType = metaParts

    return {
        "reactants": reactants,
        "products": products,
        "reactionString": f"{reactants} >> {products}",
        "ruleName": ruleName,
        "thermo": thermo,
        "reactantStoich": reactantStoich,
        "productStoich": productStoich,
        "reactionType": reactionType,
        "numReactantMolecules": len(splitMoleculeString(reactants)),
        "numProductMolecules": len(splitMoleculeString(products)),
        "sourceFolderNum": fileInfo.get("folderNum", -1),
        "sourceDirectory": fileInfo.get("dirName", ""),
        "sourceDirectoryPath": fileInfo.get("dirPath", ""),
        "sourceJsonName": fileInfo.get("jsonName", ""),
        "sourceJsonPath": fileInfo.get("jsonPath", ""),
    }


def parseCleanReactionSmiles(reactionSmiles, fileInfo, row):
    """
    Fallback parser for clean reaction SMILES:

        reactants >> products

    Used only if rawReactionString is missing or malformed.
    """
    if pd.isna(reactionSmiles) or ">>" not in str(reactionSmiles):
        raise ValueError("No valid reactionSMILES fallback found")

    reactants, products = str(reactionSmiles).split(">>", 1)

    return {
        "reactants": reactants,
        "products": products,
        "reactionString": f"{reactants} >> {products}",
        "ruleName": row.get("reactionName", ""),
        "thermo": row.get("dH", ""),
        "reactantStoich": None,
        "productStoich": None,
        "reactionType": row.get("reactionType", ""),
        "numReactantMolecules": len(splitMoleculeString(reactants)),
        "numProductMolecules": len(splitMoleculeString(products)),
        "sourceFolderNum": fileInfo.get("folderNum", -1),
        "sourceDirectory": fileInfo.get("dirName", ""),
        "sourceDirectoryPath": fileInfo.get("dirPath", ""),
        "sourceJsonName": fileInfo.get("jsonName", ""),
        "sourceJsonPath": fileInfo.get("jsonPath", ""),
    }


def resolveOutputDirFromConfig(pathwayReconstructionConfigPath):
    with open(pathwayReconstructionConfigPath, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f) or {}

    outputDir = Path(
        cfg.get("paths", {}).get("output_dir", "pathway_reconstruction_results")
    ).expanduser()

    if not outputDir.is_absolute():
        outputDir = Path.cwd() / outputDir

    return outputDir.resolve(), cfg


# -------------------------------------------------------------------
# Locate reconstructed pathway output files
# -------------------------------------------------------------------
outputDir, cfg = resolveOutputDirFromConfig(pathwayReconstructionConfigPath)

stepsPath = Path(DNADesignResultsDir +  "pathway_reconstruction_results/doranet_chain_reconstructed_pathway_steps_by_depth.csv")
routesPath = Path(DNADesignResultsDir +  "pathway_reconstruction_results/doranet_chain_reconstructed_pathways_by_depth.csv")
summaryPath = Path(DNADesignResultsDir +  "pathway_reconstruction_results/doranet_chain_pathway_summary_by_depth.csv")

if not stepsPath.exists():
    raise FileNotFoundError(
        f"Could not find reconstructed pathway steps file:\n{stepsPath}\n\n"
        "Run pathwayReconstruction.py first."
    )

stepsDF = pd.read_csv(stepsPath)

if stepsDF.empty:
    raise RuntimeError(
        f"The reconstructed pathway step file is empty:\n{stepsPath}\n\n"
        "No reconstructed pathways were found."
    )


# -------------------------------------------------------------------
# keep only routes present in route-level file
# -------------------------------------------------------------------
if keepOnlySuccessfulRoutes and routesPath.exists():
    routesDF = pd.read_csv(routesPath)
    validRouteIds = set(routesDF["routeId"].dropna().astype(str))
    stepsDF = stepsDF[stepsDF["routeId"].astype(str).isin(validRouteIds)].copy()


# -------------------------------------------------------------------
# limit number of routes per folder/depth
# -------------------------------------------------------------------
if maxRoutesPerFolderDepth is not None:
    routeSelectorDF = (
        stepsDF[["dirName", "searchDepthUsed", "routeId"]]
        .drop_duplicates()
        .sort_values(["dirName", "searchDepthUsed", "routeId"])
        .groupby(["dirName", "searchDepthUsed"], as_index=False)
        .head(maxRoutesPerFolderDepth)
    )

    keepRouteIds = set(routeSelectorDF["routeId"].astype(str))
    stepsDF = stepsDF[stepsDF["routeId"].astype(str).isin(keepRouteIds)].copy()


# -------------------------------------------------------------------
# Parse reconstructed route steps into reactionDF-like records
# -------------------------------------------------------------------
reconstructedRecords = []
parseErrors = []

for _, row in tqdm(stepsDF.iterrows(), total=len(stepsDF), desc="Parsing reconstructed pathways"):
    dirName = row.get("dirName", "")
    jobName = row.get("jobName", "")

    fileInfo = {
        "folderNum": extractFolderNum(dirName),
        "dirName": dirName,
        "dirPath": str(Path(cfg.get("paths", {}).get("doranet_jobs_dir", "")) / str(dirName)),
        "jsonName": f"{jobName}_network_pretreated.json" if jobName else "",
        "jsonPath": str(
            Path(cfg.get("paths", {}).get("doranet_jobs_dir", ""))
            / str(dirName)
            / f"{jobName}_network_pretreated.json"
        ) if jobName else "",
    }

    try:
        rawReactionString = row.get("rawReactionString", None)

        if pd.notna(rawReactionString) and len(str(rawReactionString).split(">")) == 4:
            record = parseDoranetReaction(rawReactionString, fileInfo)
        else:
            record = parseCleanReactionSmiles(row.get("reactionSMILES", None), fileInfo, row)

        # Add reconstructed-pathway metadata
        record.update({
            "dirName": dirName,
            "jobName": jobName,
            "routeId": row.get("routeId", ""),
            "searchDepthUsed": row.get("searchDepthUsed", None),
            "step": row.get("step", None),
            "numSteps": row.get("numSteps", None),
            "rxnId": row.get("rxnId", None),

            # Chain-connection metadata
            "connectionType": row.get("connectionType", ""),
            "connectionMolecules": row.get("connectionMolecules", ""),
            "sideReactantsAllowedAsCofactors": row.get("sideReactantsAllowedAsCofactors", ""),
            "sideReactantsListedAsHelpers": row.get("sideReactantsListedAsHelpers", ""),
            "sideReactantsNotListedAsHelpers": row.get("sideReactantsNotListedAsHelpers", ""),
            "starterInReactants": row.get("starterInReactants", None),
            "targetInProducts": row.get("targetInProducts", None),

            # Useful downstream identifiers
            "routeStepId": f"{row.get('routeId', '')}_step_{int(row.get('step', 0)):02d}"
            if pd.notna(row.get("step", None)) else "",
            "isReconstructedPathwayStep": True,
        })

        reconstructedRecords.append(record)

    except Exception as exc:
        parseErrors.append({
            "dirName": dirName,
            "jobName": jobName,
            "routeId": row.get("routeId", ""),
            "step": row.get("step", None),
            "reactionSMILES": row.get("reactionSMILES", ""),
            "rawReactionString": row.get("rawReactionString", ""),
            "error": str(exc),
        })


if not reconstructedRecords:
    raise RuntimeError("No reconstructed pathway records could be parsed.")


reconstructedPathwaysDF = (
    pd.DataFrame(reconstructedRecords)
    .sort_values(["sourceFolderNum", "searchDepthUsed", "routeId", "step"])
    .reset_index(drop=True)
)

parseErrorsDF = pd.DataFrame(parseErrors)


# -------------------------------------------------------------------
# Add route-level summary columns to every step
# -------------------------------------------------------------------
if routesPath.exists():
    routeColsToMerge = [
        "routeId",
        "multiStepReactionSMILES",
        "reactionNames",
        "starterSMILES",
        "targetSMILES",
        "connectionMoleculesByStep",
    ]

    routesDF = pd.read_csv(routesPath)
    routeColsToMerge = [c for c in routeColsToMerge if c in routesDF.columns]

    reconstructedPathwaysDF = reconstructedPathwaysDF.merge(
        routesDF[routeColsToMerge].drop_duplicates("routeId"),
        on="routeId",
        how="left",
    )


# -------------------------------------------------------------------
# Save for downstream processing
# -------------------------------------------------------------------
reconstructedPathwaysDF = reconstructedPathwaysDF.rename(columns={'multiStepReactionSMILES' :'reconstructedPathwayString'})
if saveOutput:
    reconstructedPathwaysDF.to_csv(DNADesignResultsDir + "reconstructedPathwaysDF.csv", index=False)
    parseErrorsDF.to_csv(DNADesignResultsDir + "reconstructedPathwaysDF_parseErrors.csv", index=False)

    print(f"Saved reconstructedPathway metadata to {DNADesignResultsDir}")


print(f"Reconstructed pathway steps : {len(reconstructedPathwaysDF):,}")
print(f"Unique routes               : {reconstructedPathwaysDF['routeId'].nunique():,}")
print(f"Unique folders              : {reconstructedPathwaysDF['dirName'].nunique():,}")
print(f"Parse errors                : {len(parseErrorsDF):,}")

reconstructedPathwaysDF.head()

Parsing reconstructed pathways: 100%|█████████████████████████████████████████████████████████████| 12730/12730 [00:01<00:00, 11272.96it/s]

Saved reconstructedPathway metadata to /mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/DrugDesignData/Results/combinedEbolaVirus_bestMACAW_allDB_generative/DNA_design/
Reconstructed pathway steps : 12,730
Unique routes               : 4,489
Unique folders              : 7
Parse errors                : 0

,reactants,products,reactionString,ruleName,thermo,reactantStoich,productStoich,reactionType,numReactantMolecules,numProductMolecules,...,sideReactantsNotListedAsHelpers,starterInReactants,targetInProducts,routeStepId,isReconstructedPathwayStep,reconstructedPathwayString,reactionNames,starterSMILES,targetSMILES,connectionMoleculesByStep
0,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,...,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,True,False,high_pPotency_molecule_pathway1_d3_route_00000...,True,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,rule0073_5 | rule0007_203 | rule0061_4,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O
1,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,rule0007_203,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,COC1C(COC(C)=O)OC(n2cnc3c(=O)[nH]cnc32)C1O,False,False,high_pPotency_molecule_pathway1_d3_route_00000...,True,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,rule0073_5 | rule0007_203 | rule0061_4,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O
2,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc...,False,True,high_pPotency_molecule_pathway1_d3_route_00000...,True,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,rule0073_5 | rule0007_203 | rule0061_4,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O
3,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)...,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](OP...,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)...,rule0017_27,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,O=P(O)(O)O,True,False,high_pPotency_molecule_pathway1_d3_route_00000...,True,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O>>...,rule0017_27 | rule0007_203 | rule0061_4,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O
4,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,rule0007_203,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,COC1C(COC(C)=O)OC(n2cnc3c(=O)[nH]cnc32)C1O,False,False,high_pPotency_molecule_pathway1_d3_route_00000...,True,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O>>...,rule0017_27 | rule0007_203 | rule0061_4,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O

### Print `reconstructed` pathways

In [14]:
print(reconstructedPathwaysDF['reconstructedPathwayString'].iloc[0])

NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4cnc5c(N)ncnc54)C(OP(=O)(O)O)C3O)C(O)C2O)C=CC1.O=O.O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O>>NC(=O)c1ccc[n+](C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4cnc5c(N)ncnc54)C(OP(=O)(O)O)C3O)C(O)C2O)c1.O.O=CC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O  ||  COC1C(COC(C)=O)OC(n2cnc3c(=O)[nH]cnc32)C1O.O>>CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O.CO  ||  CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O.CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc32)C(O)C1OP(=O)(O)O)C(O)C(=O)NCCC(=O)NCCS>>CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc32)C(O)C1OP(=O)(O)O.O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O

### Find unique `starter --> target` from reconstructed pathways

In [21]:
# Count complete starter --> target reconstructed pathways per directory
to_bool = lambda s: s.astype(str).str.lower().isin(["true", "1", "yes"])

first = reconstructedPathwaysDF[reconstructedPathwaysDF["step"].eq(1)]
final = reconstructedPathwaysDF[reconstructedPathwaysDF["step"].eq(reconstructedPathwaysDF["numSteps"])]

complete_ids = set(first.loc[to_bool(first["starterInReactants"]), "routeId"].astype(str)) & \
               set(final.loc[to_bool(final["targetInProducts"]), "routeId"].astype(str))

completeRouteLevelDF = (
    reconstructedPathwaysDF[reconstructedPathwaysDF["routeId"].astype(str).isin(complete_ids)]
    .sort_values(["dirName", "routeId", "step"])
    .groupby("routeId", as_index=False)
    .agg(
        dirName=("dirName", "first"),
        jobName=("jobName", "first"),
        sourceFolderNum=("sourceFolderNum", "first"),
        numSteps=("numSteps", "first"),
        searchDepthUsed=("searchDepthUsed", "first"),
        starterSMILES=("starterSMILES", "first"),
        targetSMILES=("targetSMILES", "first"),
        reconstructedPathwayString=("reconstructedPathwayString", "first"),
    )
)

starterTargetPathwayCountsDF = (
    completeRouteLevelDF
    .pivot_table(
        index=["dirName", "jobName", "starterSMILES", "targetSMILES"],
        columns="numSteps",
        values="routeId",
        aggfunc="nunique",
        fill_value=0,
    )
    .rename(columns={1: "numOneStepPathways", 2: "numTwoStepPathways", 3: "numThreeStepPathways"})
    .reset_index()
)

for c in ["numOneStepPathways", "numTwoStepPathways", "numThreeStepPathways"]:
    if c not in starterTargetPathwayCountsDF.columns:
        starterTargetPathwayCountsDF[c] = 0

starterTargetPathwayCountsDF["totalStarterToTargetPathways"] = (
    starterTargetPathwayCountsDF["numOneStepPathways"] +
    starterTargetPathwayCountsDF["numTwoStepPathways"] +
    starterTargetPathwayCountsDF["numThreeStepPathways"]
)

starterTargetPathwayCountsDF = starterTargetPathwayCountsDF.sort_values(
    "totalStarterToTargetPathways", ascending=False
).reset_index(drop=True)

print(f"Total reaction pathways : {len(reconstructedPathwaysDF):,}")
print(f"Complete starter --> target pathways: {len(completeRouteLevelDF):,}")
print(f"Directories reached starter --> target pathways: {starterTargetPathwayCountsDF['dirName'].nunique():,}")

starterTargetPathwayCountsDF

Total reaction pathways : 12,730
Complete starter --> target pathways: 4,489
Directories reached starter --> target pathways: 7

numSteps,dirName,jobName,starterSMILES,targetSMILES,numOneStepPathways,numTwoStepPathways,numThreeStepPathways,totalStarterToTargetPathways
0,high_pPotency_molecule_pathway6,high_pPotency_molecule_pathway6,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,3,670,797,1470
1,high_pPotency_molecule_pathway2,high_pPotency_molecule_pathway2,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc...,3,27,1018,1048
2,high_pPotency_molecule_pathway16,high_pPotency_molecule_pathway16,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,O=C(O)CC(=O)O,0,21,846,867
3,high_pPotency_molecule_pathway19,high_pPotency_molecule_pathway19,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)CC(=O)O,0,0,508,508
4,high_pPotency_molecule_pathway1,high_pPotency_molecule_pathway1,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,0,0,315,315
5,high_pPotency_molecule_pathway18,high_pPotency_molecule_pathway18,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,NC(=O)c1ccc[n+](C2OC(COP(=O)(O)OP(=O)(O)OCC3OC...,1,5,274,280
6,high_pPotency_molecule_pathway12,high_pPotency_molecule_pathway12,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,O=C1N=C2NC=Nc3c2ncn3C2OC1C(O)C2O,0,0,1,1

### Keep only enzymatic DORAnet reactions

In [23]:
enzymaticReactionDF = reconstructedPathwaysDF[
    reactionDF["reactionType"].astype(str).str.lower().str.contains(
        "enzyme|enzymatic|bio|biological",
        na=False
    )
].copy()

print(f"Total reactions: {len(reconstructedPathwaysDF):,}")
print(f"Likely enzymatic reactions: {len(enzymaticReactionDF):,}")

enzymaticReactionDF.head()

Total reactions: 12,730
Likely enzymatic reactions: 12,730

/tmp/ipykernel_2079939/1451588661.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  enzymaticReactionDF = reconstructedPathwaysDF[

,reactants,products,reactionString,ruleName,thermo,reactantStoich,productStoich,reactionType,numReactantMolecules,numProductMolecules,...,sideReactantsNotListedAsHelpers,starterInReactants,targetInProducts,routeStepId,isReconstructedPathwayStep,reconstructedPathwayString,reactionNames,starterSMILES,targetSMILES,connectionMoleculesByStep
0,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,...,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,True,False,high_pPotency_molecule_pathway1_d3_route_00000...,True,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,rule0073_5 | rule0007_203 | rule0061_4,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O
1,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,rule0007_203,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,COC1C(COC(C)=O)OC(n2cnc3c(=O)[nH]cnc32)C1O,False,False,high_pPotency_molecule_pathway1_d3_route_00000...,True,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,rule0073_5 | rule0007_203 | rule0061_4,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O
2,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc...,False,True,high_pPotency_molecule_pathway1_d3_route_00000...,True,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,rule0073_5 | rule0007_203 | rule0061_4,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O
3,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)...,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](OP...,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)...,rule0017_27,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,O=P(O)(O)O,True,False,high_pPotency_molecule_pathway1_d3_route_00000...,True,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O>>...,rule0017_27 | rule0007_203 | rule0061_4,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O
4,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,rule0007_203,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,COC1C(COC(C)=O)OC(n2cnc3c(=O)[nH]cnc32)C1O,False,False,high_pPotency_molecule_pathway1_d3_route_00000...,True,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O>>...,rule0017_27 | rule0007_203 | rule0061_4,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O

## 2. Use `DORA-XGB` to get feasibility score

In [24]:
reactionDF_DORAXGB = enzymaticReactionDF.copy()
#reactionDF_DORAXGB = enzymaticReactionDF.head(50).copy()

# Clean reaction string for model input
reactionDF_DORAXGB["rxn_str"] = (
    reactionDF_DORAXGB["reactionString"]
    .astype(str)
    .str.replace(" ", "", regex=False)
)

def getFeasibilityScoresAndLabels(rxnStr):
    return pd.Series({
        "feasibilityScore_rule1": by_desc_MW_model.predict_proba(rxnStr),
        "feasibilityLabel_rule1": by_desc_MW_model.predict_label(rxnStr),

        "feasibilityScore_rule2": by_asc_MW_model.predict_proba(rxnStr),
        "feasibilityLabel_rule2": by_asc_MW_model.predict_label(rxnStr),

        "feasibilityScore_rule3": add_concat_model.predict_proba(rxnStr),
        "feasibilityLabel_rule3": add_concat_model.predict_label(rxnStr),

        "feasibilityScore_rule4": add_subtract_model.predict_proba(rxnStr),
        "feasibilityLabel_rule4": add_subtract_model.predict_label(rxnStr),
    })


reactionDF_DORAXGB["rxn_str"] = (
    reactionDF_DORAXGB["reactionString"]
    .astype(str)
    .str.replace(" ", "", regex=False)
)

reactionDF_DORAXGB[
    [
        "feasibilityScore_rule1",
        "feasibilityLabel_rule1",
        "feasibilityScore_rule2",
        "feasibilityLabel_rule2",
        "feasibilityScore_rule3",
        "feasibilityLabel_rule3",
        "feasibilityScore_rule4",
        "feasibilityLabel_rule4",
    ]
] = reactionDF_DORAXGB["rxn_str"].apply(getFeasibilityScoresAndLabels)

reactionDF_DORAXGB.head()

,reactants,products,reactionString,ruleName,thermo,reactantStoich,productStoich,reactionType,numReactantMolecules,numProductMolecules,...,connectionMoleculesByStep,rxn_str,feasibilityScore_rule1,feasibilityLabel_rule1,feasibilityScore_rule2,feasibilityLabel_rule2,feasibilityScore_rule3,feasibilityLabel_rule3,feasibilityScore_rule4,feasibilityLabel_rule4
0,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,0.002562,0.0,0.738403,1.0,0.627660,1.0,0.740460,1.0
1,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,rule0007_203,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,0.029845,0.0,0.343784,0.0,0.247226,0.0,0.590581,0.0
2,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,0.297114,0.0,0.995089,1.0,0.924887,1.0,0.990581,1.0
3,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)...,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](OP...,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)...,rule0017_27,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)...,0.001216,0.0,0.034483,0.0,0.027119,0.0,0.511955,0.0
4,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,rule0007_203,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,0.029845,0.0,0.343784,0.0,0.247226,0.0,0.590581,0.0

### Keep only `high feasible` reactions

In [27]:
# Choose which feasibility label to use
feasibilityLabel = "feasibilityLabel_rule2"   # <- change to rule2/rule3/rule4 as needed
targetValue = 1                               # <- change if you want a different label value

# Optional safety check
validLabels = [
    "feasibilityLabel_rule1",
    "feasibilityLabel_rule2",
    "feasibilityLabel_rule3",
    "feasibilityLabel_rule4",
]
if feasibilityLabel not in validLabels:
    raise ValueError(f"Invalid feasibilityLabel: {feasibilityLabel}. Choose from {validLabels}")

if feasibilityLabel not in reactionDF_DORAXGB.columns:
    raise KeyError(f"Column '{feasibilityLabel}' not found in reactionDF_DORAXGB")

In [28]:
reactionDF_DORAXGB_highFeasibility = (
    reactionDF_DORAXGB[
        (reactionDF_DORAXGB[feasibilityLabel] == targetValue)
        & (reactionDF_DORAXGB[feasibilityLabel].notna())
    ]
    .sort_values(by=feasibilityLabel, ascending=False)
    .reset_index(drop=True)
)

uniqueReactantStrings_high = set(reactionDF_DORAXGB_highFeasibility["reactants"])
uniqueProductStrings_high = set(reactionDF_DORAXGB_highFeasibility["products"])

uniqueReactantMolecules_high = {
    mol.strip()
    for reactants in reactionDF_DORAXGB_highFeasibility["reactants"]
    for mol in str(reactants).split(".")
    if mol.strip()
}

uniqueProductMolecules_high = {
    mol.strip()
    for products in reactionDF_DORAXGB_highFeasibility["products"]
    for mol in str(products).split(".")
    if mol.strip()
}

print(f"Feasibility label used: {feasibilityLabel} == {targetValue}")
print(f"Number of high-feasibility reactions: {len(reactionDF_DORAXGB_highFeasibility)}")
print(f"Number of unique reactant strings: {len(uniqueReactantStrings_high)}")
print(f"Number of unique product strings: {len(uniqueProductStrings_high)}")
print(f"Number of unique individual reactant molecules: {len(uniqueReactantMolecules_high)}")
print(f"Number of unique individual product molecules: {len(uniqueProductMolecules_high)}")

reactionDF_DORAXGB_highFeasibility.to_csv(os.path.join(DNADesignResultsDir, f"DORAXGB_highFeasibility_{feasibilityLabel}.csv"),index=False)
reactionDF_DORAXGB_highFeasibility.head()

Feasibility label used: feasibilityLabel_rule2 == 1
Number of high-feasibility reactions: 4733
Number of unique reactant strings: 285
Number of unique product strings: 227
Number of unique individual reactant molecules: 167
Number of unique individual product molecules: 192

,reactants,products,reactionString,ruleName,thermo,reactantStoich,productStoich,reactionType,numReactantMolecules,numProductMolecules,...,connectionMoleculesByStep,rxn_str,feasibilityScore_rule1,feasibilityLabel_rule1,feasibilityScore_rule2,feasibilityLabel_rule2,feasibilityScore_rule3,feasibilityLabel_rule3,feasibilityScore_rule4,feasibilityLabel_rule4
0,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,No_Thermo,"(1, 1, 1, 1)","(1, 1, 1)",Enzymatic,4,3,...,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,0.166996,0.0,0.967761,1.0,0.922012,1.0,0.886861,1.0
1,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,0.002562,0.0,0.738403,1.0,0.627660,1.0,0.740460,1.0
2,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,0.297114,0.0,0.995089,1.0,0.924887,1.0,0.990581,1.0
3,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,0.297114,0.0,0.995089,1.0,0.924887,1.0,0.990581,1.0
4,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,0.297114,0.0,0.995089,1.0,0.924887,1.0,0.990581,1.0

reactionDF_DORAXGB_highFeasibility = pd.read_csv(os.path.join(DNADesignResultsDir, "DORAXGB_highFeasibility_reactions.csv"))
reactionDF_DORAXGB_highFeasibility

### Summarize unique DORAnet rules

Many reactions may use the same rule. We do not want to annotate millions of reactions one by one. First annotate the rules.

In [29]:
enzymaticReactionDF = reactionDF_DORAXGB_highFeasibility.copy()
ruleSummaryDF = (
    enzymaticReactionDF
    .groupby(["ruleName", "reactionType"], dropna=False)
    .agg(
        numReactions=("reactionString", "count"),
        #numStarterSources=("sourceFolderNum", "nunique"),
        exampleReaction=("reactionString", "first"),
        exampleReactants=("reactants", "first"),
        exampleProducts=("products", "first"),
    )
    .reset_index()
    .sort_values("numReactions", ascending=False)
)

print(f"unique DORAnet rules    : {enzymaticReactionDF['ruleName'].nunique():,}")
ruleSummaryDF

unique DORAnet rules    : 49

,ruleName,reactionType,numReactions,exampleReaction,exampleReactants,exampleProducts
44,rule0165_2,Enzymatic,649,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...
20,rule0017_16,Enzymatic,592,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1OC(CO)[C@@...,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1OC(CO)[C@@...,O.O=c1[nH]cnc2c1ncn2[C@@H]1OC(COP(=O)(O)O)[C@@...
31,rule0062_17,Enzymatic,553,CC(=O)O.CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)...,CC(=O)O.CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)...,CC(=O)OC(C)=O.CC(C)(COP(=O)(O)OP(=O)(O)OC[C@H]...
35,rule0073_5,Enzymatic,511,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...
8,rule0007_198,Enzymatic,452,CC(=O)O[C@@H]1[C@H](O)[C@@H](CO)O[C@]1(C)n1cnc...,CC(=O)O[C@@H]1[C@H](O)[C@@H](CO)O[C@]1(C)n1cnc...,CC(=O)O.C[C@]1(n2cnc3c(=O)[nH]cnc32)O[C@H](CO)...
30,rule0061_4,Enzymatic,330,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...
4,rule0007_161,Enzymatic,239,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,CC(=O)O.CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]...
48,rule0491_2,Enzymatic,238,CC(O)O[C@@H]1[C@H]2CO[C@@]1(O)[C@H](n1cnc3c(=O...,CC(O)O[C@@H]1[C@H]2CO[C@@]1(O)[C@H](n1cnc3c(=O...,CC(=O)O.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(...
32,rule0062_18,Enzymatic,154,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...
33,rule0062_19,Enzymatic,153,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...
15,rule0011_51,Enzymatic,130,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...
12,rule0007_203,Enzymatic,97,CC(O)OC[C@H]1O[C@@H]2[C@H](Oc3nc4c(ncn42)c(=O)...,CC(O)OC[C@H]1O[C@@H]2[C@H](Oc3nc4c(ncn42)c(=O)...,CC(O)O.O=c1[nH]c2nc3c1ncn3[C@@H]1O[C@H](CO)[C@...
41,rule0121_1,Enzymatic,85,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,C[n+]1cn([C@@H]2O[C@H](CO)[C@@H](O)[C@H]2O)c2n...
14,rule0011_50,Enzymatic,75,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...,COCC1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H](O)[C@@...
39,rule0092_4,Enzymatic,46,CC(N)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,CC(N)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...
13,rule0010_65,Enzymatic,44,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...
16,rule0015_21,Enzymatic,37,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O...
7,rule0007_195,Enzymatic,32,CCC(=O)O[C@@H]1[C@H](O)[C@@H](CO)O[C@H]1n1cnc2...,CCC(=O)O[C@@H]1[C@H](O)[C@@H](CO)O[C@H]1n1cnc2...,CCC(=O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C...
42,rule0128_2,Enzymatic,30,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)...,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)...,O=S(=O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO...
5,rule0007_174,Enzymatic,26,CC(O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,CC(O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,CC(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@...
40,rule0120_1,Enzymatic,20,CC(=O)OC[C@H]1O[C@@H](n2c[n+](C)c3c(=O)[nH]cnc...,CC(=O)OC[C@H]1O[C@@H](n2c[n+](C)c3c(=O)[nH]cnc...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...
11,rule0007_202,Enzymatic,20,O.O=CO[C@@H]1[C@H](O)[C@@H](CO)O[C@H]1n1cnc2c(...,O.O=CO[C@@H]1[C@H](O)[C@@H](CO)O[C@H]1n1cnc2c(...,O=CO.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H]...
46,rule0243_3,Enzymatic,18,CC(O)(C#N)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32...,CC(O)(C#N)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32...,CC(O)(OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...
24,rule0047_1,Enzymatic,17,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)O)[C@@H]...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)O)[C@@H]...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OS(=O)(=...
26,rule0048_5,Enzymatic,17,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OS(=O)(=...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OS(=O)(=...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)O)[C@@H]...
9,rule0007_199,Enzymatic,16,O.O=COC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,O.O=COC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,O=CO.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H]...
38,rule0085_2,Enzymatic,12,O.O=C(O)CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]c...,O.O=C(O)CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]c...,CC(=O)O.O=C(O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]c...
17,rule0016_061,Enzymatic,12,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)O)...,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)O)...,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)...
18,rule0016_062,Enzymatic,12,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)...,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)...,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)...
6,rule0007_193,Enzymatic,12,CC(=O)OC(C)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)...,CC(=O)OC(C)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)...,CC(=O)O.CC(O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc3...
10,rule0007_200,Enzymatic,12,CC(=O)OC(=O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32...,CC(=O)OC(=O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32...,CC(=O)O.O=C(O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc...
29,rule0056_18,Enzymatic,12,CC(N)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc3...,CC(N)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc3...,CC(O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc3...
3,rule0003_177,Enzymatic,9,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...
27,rule0048_6,Enzymatic,8,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OS(=O)(=...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OS(=O)(=...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)O)[C@@H]...
47,rule0352_2,Enzymatic,8,CC(=O)O.O=O >> C=O.O.O=C=O,CC(=O)O.O=O,C=O.O.O=C=O
2,rule0003_176,Enzymatic,8,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...,CC(O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc3...
1,rule0003_171,Enzymatic,6,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...
34,rule0070_6,Enzymatic,6,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...,O=C(CO)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cn...
28,rule0056_17,Enzymatic,6,NC(=O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H]...,NC(=O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H]...,N.O=C(O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...
19,rule0016_063,Enzymatic,6,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](OP...,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](OP...,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)...
25,rule0047_2,Enzymatic,6,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)O)[C@@H]...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)O)[C@@H]...,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OS(=O)(=...
22,rule0042_09,Enzymatic,5,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)NC(C)O[C@@H]1[C@H](O)[C@@H](CO)O[C@H]1n1...
43,rule0164_2,Enzymatic,3,CC(=O)OC(=O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32...,CC(=O)OC(=O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...
37,rule0083_11,Enzymatic,3,CC(=O)C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,CC(=O)C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...
45,rule0169_1,Enzymatic,2,O=C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H](O)...,O=C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H](O)...,O=c1[nH]c2nc3c1ncn3[C@@H]1O[C@H](CO)[C@@H](O2)...
0,rule0002_154,Enzymatic,1,CC(=O)O[C@@H]1[C@H](O)[C@@H](CO)O[C@H]1n1c(C)n...,CC(=O)O[C@@H]1[C@H](O)[C@@H](CO)O[C@H]1n1c(C)n...,CC(=O)O[C@@H]1[C@H](O)[C@@H](C=O)O[C@H]1n1c(C)...
23,rule0043_12,Enzymatic,1,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CCC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C...
21,rule0028_35,Enzymatic,1,O=c1[nH]cnc2c1ncn2[C@@]1(CO)OC[C@@H](O)[C@H]1O...,O=c1[nH]cnc2c1ncn2[C@@]1(CO)OC[C@@H](O)[C@H]1O,O=c1[nH]cnc2c1ncn2[C@@H]1OC(CO)[C@@H](O)[C@H]1O
36,rule0074_18,Enzymatic,1,CC(O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,CC(O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...

### Add required placeholder columns

In [30]:
enzymeAnnotationDF = ruleSummaryDF.copy()

enzymeAnnotationDF["suggestedEnzymeClass"] = ""
enzymeAnnotationDF["ecNumber"] = ""
enzymeAnnotationDF["enzymeName"] = ""
enzymeAnnotationDF["uniprotAccession"] = ""
enzymeAnnotationDF["sourceDatabase"] = ""
enzymeAnnotationDF["reactionSimilarity"] = ""
enzymeAnnotationDF["enzymeConfidence"] = ""
enzymeAnnotationDF["notes"] = ""
enzymeAnnotationDF.head()

,ruleName,reactionType,numReactions,exampleReaction,exampleReactants,exampleProducts,suggestedEnzymeClass,ecNumber,enzymeName,uniprotAccession,sourceDatabase,reactionSimilarity,enzymeConfidence,notes
44,rule0165_2,Enzymatic,649,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,,,,,,,,
20,rule0017_16,Enzymatic,592,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1OC(CO)[C@@...,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1OC(CO)[C@@...,O.O=c1[nH]cnc2c1ncn2[C@@H]1OC(COP(=O)(O)O)[C@@...,,,,,,,,
31,rule0062_17,Enzymatic,553,CC(=O)O.CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)...,CC(=O)O.CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)...,CC(=O)OC(C)=O.CC(C)(COP(=O)(O)OP(=O)(O)OC[C@H]...,,,,,,,,
35,rule0073_5,Enzymatic,511,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,,,,,,,,
8,rule0007_198,Enzymatic,452,CC(=O)O[C@@H]1[C@H](O)[C@@H](CO)O[C@]1(C)n1cnc...,CC(=O)O[C@@H]1[C@H](O)[C@@H](CO)O[C@]1(C)n1cnc...,CC(=O)O.C[C@]1(n2cnc3c(=O)[nH]cnc32)O[C@H](CO)...,,,,,,,,

## 3. Read DORAnet reaction ruleset file to extract `UniProt ID` for each `reaction rule`

In [31]:
doranetRulesetDF = pd.read_csv(dataDir + "/DORAnet/JN3604IMT_rules.tsv", sep="\t")

print(doranetRulesetDF.shape)
print(doranetRulesetDF.columns.tolist())
doranetRulesetDF.head()

(3604, 5)
['Name', 'Reactants', 'SMARTS', 'Products', 'Comments']

,Name,Reactants,SMARTS,Products,Comments
0,rule0001_01,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,Any;Any,P97259;P97402;Q08834;Q09328;Q16408;Q3V5L5;Q765...
1,rule0001_02,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,Any;Any,A0K8D0;A0KHH6;A0KZ10;A0L8R9;A0Q7X9;A1A7M6;A1K6...
2,rule0001_03,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,Any;Any,P0DMP6;P0DMP7;P16442;Q15951;Q1RLK6;Q3USF0;Q5HZ...
3,rule0001_04,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,Any;Any,A4IID1;O19071;O77836;P23336;P26572;P27115;P278...
4,rule0001_05,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,Any;Any,NaN

### Find the number of common reaction rules between `DORAnet` diversification and ruleset table from actual package

In [32]:
reactionRuleSet = set(reactionDF_DORAXGB_highFeasibility["ruleName"].dropna().astype(str).str.strip())
tsvRuleSet = set(doranetRulesetDF["Name"].dropna().astype(str).str.strip())

matchedRuleSet = reactionRuleSet.intersection(tsvRuleSet)
missingRuleSet = reactionRuleSet.difference(tsvRuleSet)

print(f"Rules present in DORAnet diversification run: {len(reactionRuleSet):,}")
print(f"Rules matched from DORAnet package: {len(matchedRuleSet):,}")
print(f"Rules missing from DORAnet package: {len(missingRuleSet):,}")

print("\nMatched rules:")
print(sorted(list(matchedRuleSet))[:20])

print("\nMissing rules:")
print(sorted(list(missingRuleSet))[:20])

Rules present in DORAnet diversification run: 49
Rules matched from DORAnet package: 49
Rules missing from DORAnet package: 0

Matched rules:
['rule0002_154', 'rule0003_171', 'rule0003_176', 'rule0003_177', 'rule0007_161', 'rule0007_174', 'rule0007_193', 'rule0007_195', 'rule0007_198', 'rule0007_199', 'rule0007_200', 'rule0007_202', 'rule0007_203', 'rule0010_65', 'rule0011_50', 'rule0011_51', 'rule0015_21', 'rule0016_061', 'rule0016_062', 'rule0016_063']

Missing rules:
[]

### Extract `UniProt IDs` from `DORAnet` reaction rules

In [33]:
def splitUniProtIds(idString):
    if pd.isna(idString):
        return []
    return [x.strip() for x in str(idString).split(";") if x.strip()]


ruleInfoDF = doranetRulesetDF.copy()

ruleInfoDF = ruleInfoDF.rename(columns={
    "Name": "ruleName",
    "Reactants": "ruleReactants",
    "SMARTS": "ruleSMARTS",
    "Products": "ruleProducts",
    "Comments": "candidateUniProtRaw",
})

ruleInfoDF["ruleName"] = ruleInfoDF["ruleName"].astype(str).str.strip()
ruleInfoDF["candidateUniProtList"] = ruleInfoDF["candidateUniProtRaw"].apply(splitUniProtIds)
ruleInfoDF["numCandidateUniProt"] = ruleInfoDF["candidateUniProtList"].apply(len)

ruleInfoDF = ruleInfoDF[
    [
        "ruleName",
        "ruleReactants",
        "ruleProducts",
        "ruleSMARTS",
        "candidateUniProtRaw",
        "numCandidateUniProt",
    ]
].copy()



print(f"ruleInfoDF rows: {len(ruleInfoDF):,}")
ruleInfoDF

ruleInfoDF rows: 3,604

,ruleName,ruleReactants,ruleProducts,ruleSMARTS,candidateUniProtRaw,numCandidateUniProt
0,rule0001_01,Any;Any,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,P97259;P97402;Q08834;Q09328;Q16408;Q3V5L5;Q765...,10
1,rule0001_02,Any;Any,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,A0K8D0;A0KHH6;A0KZ10;A0L8R9;A0Q7X9;A1A7M6;A1K6...,263
2,rule0001_03,Any;Any,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,P0DMP6;P0DMP7;P16442;Q15951;Q1RLK6;Q3USF0;Q5HZ...,29
3,rule0001_04,Any;Any,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,A4IID1;O19071;O77836;P23336;P26572;P27115;P278...,42
4,rule0001_05,Any;Any,Any;Any,[#6;$([#6&R]1(-&!@[#8&!R]-&!@[#15&!R](=&!@[#8&...,NaN,0
...,...,...,...,...,...,...
3599,rule1152_1,Any;Any,Any;Any,[#6;$([#6&R]1-&@[#8&R]-&@[#6&R]-&@[#6&R](-&@[#...,Q8ZUN8,1
3600,rule1152_2,Any;Any,Any;Any,[#6;!$([#6&R]1-&@[#8&R]-&@[#6&R]-&@[#6&R](-&@[...,B9TTF1,1
3601,rule1164_1,Any;WATER,Any;H2O2,[#6;$([#6&!R]-&!@[#6&R]1:&@[#6&R]:&@[#6&R]:&@[...,Q972I2,1
3602,rule1165_1,Any;H2O2,Any;WATER,[#6;$([#6&!R]-[#6&R]1:&@[#6&R]:&@[#6&R]:&@[#6&...,Q972I2,1
3603,rule1165_2,Any;H2O2,Any;WATER,[#6;$([#6&R]1:[#6&R]:&@[#6&R]:&@[#6&R]:&@[#6&R...,B0CN28;B9W4V6;O31440;Q2HHI5,4

## 4. Merge rule information into `reactionDF`

This connects DORAnet reactions with the rule SMARTS and UniProt candidate list.

In [34]:
reactionDF_wUniprotID = reactionDF_DORAXGB_highFeasibility.merge(ruleInfoDF,on="ruleName",how="left")

reactionDF_wUniprotID["hasRuleLookup"] = reactionDF_wUniprotID["ruleSMARTS"].notna()

print(reactionDF_wUniprotID["hasRuleLookup"].value_counts(dropna=False))
reactionDF_wUniprotID

hasRuleLookup
True    4733
Name: count, dtype: int64

,reactants,products,reactionString,ruleName,thermo,reactantStoich,productStoich,reactionType,numReactantMolecules,numProductMolecules,...,feasibilityScore_rule3,feasibilityLabel_rule3,feasibilityScore_rule4,feasibilityLabel_rule4,ruleReactants,ruleProducts,ruleSMARTS,candidateUniProtRaw,numCandidateUniProt,hasRuleLookup
0,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,No_Thermo,"(1, 1, 1, 1)","(1, 1, 1)",Enzymatic,4,3,...,0.922012,1.0,0.886861,1.0,Any;NAD_CoF;NAD_CoF;WATER,NADH_CoF;NADH_CoF;Any,[#6;$([#6&!R]-[#8&!R]);!$([#6&!R](-[#6&R]1-&@[...,A0A0J9X7D2;A1BPP9;A4IP64;A4ISB9;B0S9F2;B0SS41;...,228,True
1,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,...,0.627660,1.0,0.740460,1.0,Any;NADH_CoF;O2,NAD_CoF;Any;WATER;WATER,[#6;$([#6&!R]-&!@[#6&R]);!$([#6&!R]-&!@[#6&R]1...,E3VWJ1;F1T282;F1T283;I1TEM3;O94142;Q16850;Q2MJ...,11,True
2,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,0.924887,1.0,0.990581,1.0,CoA;Any,ACETYL-COA;Any,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True
3,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,0.924887,1.0,0.990581,1.0,CoA;Any,ACETYL-COA;Any,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True
4,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,0.924887,1.0,0.990581,1.0,CoA;Any,ACETYL-COA;Any,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4728,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,...,0.627660,1.0,0.740460,1.0,Any;NADH_CoF;O2,NAD_CoF;Any;WATER;WATER,[#6;$([#6&!R]-&!@[#6&R]);!$([#6&!R]-&!@[#6&R]1...,E3VWJ1;F1T282;F1T283;I1TEM3;O94142;Q16850;Q2MJ...,11,True
4729,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,0.924887,1.0,0.990581,1.0,CoA;Any,ACETYL-COA;Any,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True
4730,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,0.924887,1.0,0.990581,1.0,CoA;Any,ACETYL-COA;Any,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True
4731,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,0.924887,1.0,0.990581,1.0,CoA;Any,ACETYL-COA;Any,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True
4732,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,No_Thermo,"(1, 1, 1, 1)","(1, 1, 1)",Enzymatic,4,3,...,0.922012,1.0,0.886861,1.0,Any;NAD_CoF;NAD_CoF;WATER,NADH_CoF;NADH_CoF;Any,[#6;$([#6&!R]-[#8&!R]);!$([#6&!R](-[#6&R]1-&@[...,A0A0J9X7D2;A1BPP9;A4IP64;A4ISB9;B0S9F2;B0SS41;...,228,True

reactionDF_wUniprotID_display = reactionDF_wUniprotID[
    ["reactants", "products", "reactionString", "ruleName", "candidateUniProtRaw", "feasibilityScore_rule1"]].copy()
reactionDF_wUniprotID_display = reactionDF_wUniprotID_display.drop_duplicates(
    subset=["ruleName"], keep="first"
).copy()
reactionDF_wUniprotID_display

## 4. Find best `UniProt ID` per rule by `Reaction Center Morgan Fingerprint (RCMFP)` enzyme retrieval similarity search 

Implements workflow from the DORAnet/DORA-XGB → atom mapping → RCMFP → known enzyme retrieval. It uses `ruleBase` as the practical bridge between expanded DORAnet rule names such as `rule0003_170` and known reference coarse operator IDs such as `rule0003`, then ranks candidate natural enzyme precedents by RCMFP Tanimoto similarity.

Use this tool: https://github.com/stefanpate/ergochemics/tree/main#

### Patch `RDKit/ergochemics` compatibility

This preserves atom-map labels. Do not use a patch that clears atom-map numbers, because RCMFP needs atom maps to infer reaction centers.

In [35]:
# User paths
ERGOCHEMICS_SRC = "/users/sghosh6/DTRA_project/MACAW/ergochemics/src"
if ERGOCHEMICS_SRC not in sys.path: sys.path.insert(0, ERGOCHEMICS_SRC)

import ergochemics.mapping as egmap
import ergochemics.similarity as egsim
print("RDKit version:", rdBase.rdkitVersion); print("ergochemics mapping file:", egmap.__file__)

_RDKit_MolToSmiles_original = rdmolfiles.MolToSmiles

def MolToSmiles_compat(mol, *args, **kwargs):
    kwargs.pop("ignoreAtomMapNumbers", None)
    return _RDKit_MolToSmiles_original(mol, *args, **kwargs)

Chem.MolToSmiles = MolToSmiles_compat; egmap.Chem.MolToSmiles = MolToSmiles_compat; egsim.Chem.MolToSmiles = MolToSmiles_compat
operator_map_reaction, get_reaction_center = egmap.operator_map_reaction, egmap.get_reaction_center
ReactionFingerprinter, MolFeaturizer = egsim.ReactionFingerprinter, egsim.MolFeaturizer
print("Patch test:", Chem.MolToSmiles(Chem.MolFromSmiles("[CH3:1][OH:2]"), ignoreAtomMapNumbers=True))

RDKit version: 2023.09.5
ergochemics mapping file: /users/sghosh6/DTRA_project/MACAW/ergochemics/src/ergochemics/mapping.py
Patch test: [CH3:1][OH:2]

### Normalize DORAnet reaction strings and `atom-map` all reactions

In [36]:
def normalize_reaction_string(rxn):
    if pd.isna(rxn): return None
    rxn = str(rxn).strip().replace(" ", "")
    if rxn.count(">") == 2 and ">>" in rxn: return rxn
    parts = rxn.split(">")
    return f"{parts[0]}>>{parts[2]}" if len(parts) == 3 else None

def map_query_reaction_with_rule(row):
    rxn, ruleSMARTS = row.get("queryReaction"), row.get("ruleSMARTS")
    if pd.isna(rxn) or str(rxn).strip() == "": return None, "missing_queryReaction"
    if pd.isna(ruleSMARTS) or str(ruleSMARTS).strip() == "": return None, "missing_ruleSMARTS"
    rxn, ruleSMARTS, lastError = str(rxn).replace(" ", ""), str(ruleSMARTS).strip(), None
    if ">>" not in rxn: return None, "invalid_queryReaction_no_double_arrow"
    if ">>" not in ruleSMARTS: return None, "invalid_ruleSMARTS_no_double_arrow"
    for explicitHsFlag, statusLabel in [(False, "mapped"), (True, "mapped_explicit_h")]:
        try:
            result = operator_map_reaction(rxn=rxn, operator=ruleSMARTS, explicit_hs=explicitHsFlag, quiet=True)
            if result.did_map and result.atom_mapped_smarts is not None: return result.atom_mapped_smarts, statusLabel
            lastError = f"{statusLabel}_failed"
        except Exception as exc: lastError = f"mapping_error:{type(exc).__name__}:{exc}"
    return None, lastError

AtomMapDF = reactionDF_wUniprotID.copy()
AtomMapDF["queryReaction"] = AtomMapDF["reactionString"].apply(normalize_reaction_string)
AtomMapDF = AtomMapDF[AtomMapDF["queryReaction"].notna() & AtomMapDF["ruleSMARTS"].notna()].drop(columns=["queryMappedReaction", "rcmfpMappingStatus"], errors="ignore").copy()

mappedPairs = AtomMapDF.progress_apply(map_query_reaction_with_rule, axis=1)
AtomMapDF[["queryMappedReaction", "rcmfpMappingStatus"]] = pd.DataFrame(mappedPairs.tolist(), index=AtomMapDF.index)
sucessAtomMapDF = AtomMapDF[AtomMapDF["queryMappedReaction"].notna()].copy() 
failedAtomMapDF = AtomMapDF[AtomMapDF["queryMappedReaction"].isna()].copy()
print(AtomMapDF["rcmfpMappingStatus"].value_counts(dropna=False))
print("Successful atom mapping:", len(sucessAtomMapDF), "| Failed:", len(failedAtomMapDF))
sucessAtomMapDF.shape

100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 4733/4733 [00:23<00:00, 203.48it/s]

rcmfpMappingStatus
mapped    4733
Name: count, dtype: int64
Successful atom mapping: 4733 | Failed: 0

(4733, 54)

### Compute `RCMFP fingerprints`

In [37]:
TOP_K, MIN_SIMILARITY, FP_SIDE_LENGTH, FP_RADIUS = 20, 0.0, 2048, 2

In [38]:
reactionFingerprinter = ReactionFingerprinter(radius=FP_RADIUS, length=FP_SIDE_LENGTH, mol_featurizer=MolFeaturizer())

def compute_rcmfp_with_status(mappedRxn):
    try:
        if pd.isna(mappedRxn) or str(mappedRxn).strip() == "": return None, "missing_mapped_reaction"
        mappedRxn = str(mappedRxn).replace(" ", "")
        if ">>" not in mappedRxn: return None, "invalid_mapped_reaction_no_double_arrow"
        if not pd.Series([mappedRxn]).str.contains(r":\d+\]", regex=True).iloc[0]: return None, "no_atom_map_labels"
        lrc, rrc = get_reaction_center(mappedRxn, mode="combined")
        if len(lrc) == 0 or len(rrc) == 0: return None, f"empty_reaction_center:lrc={len(lrc)}:rrc={len(rrc)}"
        fp = reactionFingerprinter.fingerprint(mappedRxn, output_type="bit", use_rc=True, rc_dist_ub=None)
        return fp.astype(bool), "rcmfp_success"
    except Exception as exc: return None, f"rcmfp_error:{type(exc).__name__}:{exc}"


rcmfpPairs = sucessAtomMapDF["queryMappedReaction"].progress_apply(compute_rcmfp_with_status)
sucessAtomMapDF[["queryRCMFP", "rcmfpStatus"]] = pd.DataFrame(rcmfpPairs.tolist(), index=sucessAtomMapDF.index)
queryRcmfpFailureDF = sucessAtomMapDF[sucessAtomMapDF["queryRCMFP"].isna()].copy()
sucessAtomMapDF = sucessAtomMapDF[sucessAtomMapDF["queryRCMFP"].notna()].copy().reset_index(drop=True)
sucessAtomMapDF

  0%|                                                                                                             | 0/4733 [00:00<?, ?it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  0%|                                                                                                     | 3/4733 [00:00<11:10,  7.06it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

  0%|▏                                                                                                    | 9/4733 [00:00<04:34, 17.19it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  0%|▎                                                                                                   | 14/4733 [00:00<04:38, 16.97it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

  0%|▎                                                                                                   | 17/4733 [00:01<04:02, 19.45it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  0%|▍                                                                                                   | 23/4733 [00:01<03:53, 20.21it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

  1%|▋                                                                                                   | 30/4733 [00:01<03:05, 25.40it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]

  1%|▊                                                                                                   | 36/4733 [00:01<03:16, 23.96it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]

  1%|▊                                                                                                   | 41/4733 [00:01<02:45, 28.34it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  1%|▉                                                                                                   | 45/4733 [00:02<03:22, 23.10it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  1%|█                                                                                                   | 48/4733 [00:02<05:49, 13.40it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 56, 58: 60, 59: 61, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 56, 58: 60, 59: 61, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 56, 58: 60, 59: 61, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 56, 58: 60, 59: 61, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

  1%|█                                                                                                   | 53/4733 [00:03<05:40, 13.74it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]

  1%|█▏                                                                                                  | 56/4733 [00:03<05:20, 14.58it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]

  1%|█▎                                                                                                  | 62/4733 [00:03<04:15, 18.31it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 56, 58: 60, 59: 61, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 56, 58: 60, 59: 61, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  1%|█▍                                                                                                  | 67/4733 [00:03<04:18, 18.04it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

  1%|█▍                                                                                                  | 69/4733 [00:03<04:14, 18.32it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 7, 4: 8, 5: 3, 6: 5, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 6, 21: 11, 22: 23, 23: 24, 24: 25, 25: 29, 26: 30, 27: 31, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71, 71: 77, 72: 78, 73: 79, 74: 72, 75: 73, 76: 74, 77: 75, 78: 80, 79: 81, 80: 83, 81: 86, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 99, 94: 101, 95: 104, 96: 106, 97: 109, 98: 111, 99: 107, 100: 110, 101: 115, 102: 117, 103: 116, 104: 118, 105: 102, 106: 105, 107: 108, 108: 112, 109: 113, 110: 114, 111: 100, 112: 103, 113: 84, 114: 87, 115: 82, 116: 85, 117: 76, 118: 119}
[0, 1, 5, 2, 6, 20, 3, 4, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24, 28, 29, 69, 25, 26, 27, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70, 74, 75, 76, 77, 117, 71, 72, 73, 78, 79, 115, 80, 113, 116, 81, 114, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 111, 94, 105, 112, 95, 106, 96, 99, 107, 97, 100, 98, 108, 109, 110, 101, 103, 102, 104, 118]
[1, 23, 24, 25, 26, 27, 28, 71, 72, 73, 74, 75, 76, 119]
{0: 1, 1: 2, 2: 4, 3: 7, 4: 8, 5: 3, 6: 5, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 6, 21: 11, 22: 23, 23: 24, 24: 25, 25: 29, 26: 30, 27: 31, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71, 71: 77, 72: 78, 73: 79, 74: 72, 75: 73, 76: 74, 77: 75, 78: 80, 79: 81, 80: 83, 81: 86, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 99, 94: 101, 95: 104, 96: 106, 97: 109, 98: 111, 99: 107, 100: 110, 101: 115, 102: 117, 103: 116, 104: 118, 105: 102, 106: 105, 107: 108, 108: 112, 109: 113, 110: 114, 111: 100, 112: 103, 113: 84, 114: 87, 115: 82, 116: 85, 117: 76, 118: 119}
[0, 1, 5, 2, 6, 20, 3, 4, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24, 28, 29, 69, 25, 26, 27, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70, 74, 75, 76, 77, 117, 71, 72, 73, 78, 79, 115, 80, 113, 116, 81, 114, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 111, 94, 105, 112, 95, 106, 96, 99, 107, 97, 100, 98, 108, 109, 110, 101, 103, 102, 104, 118]
[1, 23, 24, 25, 26, 27, 28, 71, 72, 73, 74, 75, 76, 119]

  2%|█▌                                                                                                  | 72/4733 [00:04<06:24, 12.14it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 7, 4: 8, 5: 3, 6: 5, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 6, 21: 11, 22: 23, 23: 24, 24: 25, 25: 29, 26: 30, 27: 31, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71, 71: 77, 72: 78, 73: 79, 74: 72, 75: 73, 76: 74, 77: 75, 78: 80, 79: 81, 80: 83, 81: 86, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 99, 94: 101, 95: 104, 96: 106, 97: 109, 98: 111, 99: 107, 100: 110, 101: 115, 102: 117, 103: 116, 104: 118, 105: 102, 106: 105, 107: 108, 108: 112, 109: 113, 110: 114, 111: 100, 112: 103, 113: 84, 114: 87, 115: 82, 116: 85, 117: 76, 118: 119}
[0, 1, 5, 2, 6, 20, 3, 4, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24, 28, 29, 69, 25, 26, 27, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70, 74, 75, 76, 77, 117, 71, 72, 73, 78, 79, 115, 80, 113, 116, 81, 114, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 111, 94, 105, 112, 95, 106, 96, 99, 107, 97, 100, 98, 108, 109, 110, 101, 103, 102, 104, 118]
[1, 23, 24, 25, 26, 27, 28, 71, 72, 73, 74, 75, 76, 119]
{0: 1, 1: 2, 2: 4, 3: 7, 4: 8, 5: 3, 6: 5, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 6, 21: 11, 22: 23, 23: 24, 24: 25, 25: 29, 26: 30, 27: 31, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71, 71: 77, 72: 78, 73: 79, 74: 72, 75: 73, 76: 74, 77: 75, 78: 80, 79: 81, 80: 83, 81: 86, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 99, 94: 101, 95: 104, 96: 106, 97: 109, 98: 111, 99: 107, 100: 110, 101: 115, 102: 117, 103: 116, 104: 118, 105: 102, 106: 105, 107: 108, 108: 112, 109: 113, 110: 114, 111: 100, 112: 103, 113: 84, 114: 87, 115: 82, 116: 85, 117: 76, 118: 119}
[0, 1, 5, 2, 6, 20, 3, 4, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24, 28, 29, 69, 25, 26, 27, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70, 74, 75, 76, 77, 117, 71, 72, 73, 78, 79, 115, 80, 113, 116, 81, 114, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 111, 94, 105, 112, 95, 106, 96, 99, 107, 97, 100, 98, 108, 109, 110, 101, 103, 102, 104, 118]
[1, 23, 24, 25, 26, 27, 28, 71, 72, 73, 74, 75, 76, 119]

  2%|█▌                                                                                                  | 74/4733 [00:04<08:27,  9.18it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  2%|█▌                                                                                                  | 76/4733 [00:05<10:01,  7.75it/s]

{0: 1, 1: 2, 2: 4, 3: 7, 4: 8, 5: 3, 6: 5, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 6, 21: 11, 22: 23, 23: 24, 24: 25, 25: 29, 26: 30, 27: 31, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71, 71: 77, 72: 78, 73: 79, 74: 72, 75: 73, 76: 74, 77: 75, 78: 80, 79: 81, 80: 83, 81: 86, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 99, 94: 101, 95: 104, 96: 106, 97: 109, 98: 111, 99: 107, 100: 110, 101: 115, 102: 117, 103: 116, 104: 118, 105: 102, 106: 105, 107: 108, 108: 112, 109: 113, 110: 114, 111: 100, 112: 103, 113: 84, 114: 87, 115: 82, 116: 85, 117: 76, 118: 119}
[0, 1, 5, 2, 6, 20, 3, 4, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24, 28, 29, 69, 25, 26, 27, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70, 74, 75, 76, 77, 117, 71, 72, 73, 78, 79, 115, 80, 113, 116, 81, 114, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 111, 94, 105, 112, 95, 106, 96, 99, 107, 97, 100, 98, 108, 109, 110, 101, 103, 102, 104, 118]
[1, 23, 24, 25, 26, 27, 28, 71, 72, 73, 74, 75, 76, 119]
{0: 1, 1: 2, 2: 4, 3: 7, 4: 8, 5: 3, 6: 5, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 6, 21: 11, 22: 23, 23: 24, 24: 25, 25: 29, 26: 30, 27: 31, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71, 71: 77, 72: 78, 73: 79, 74: 72, 75: 73, 76: 74, 77: 75, 78: 80, 79: 81, 80: 83, 81: 86, 82: 88, 83: 89, 84: 90, 85: 91, 86: 92, 87: 93, 88: 94, 89: 95, 90: 96, 91: 97, 92: 98, 93: 99, 94: 101, 95: 104, 96: 106, 97: 109, 98: 111, 99: 107, 100: 110, 101: 115, 102: 117, 103: 116, 104: 118, 105: 102, 106: 105, 107: 108, 108: 112, 109: 113, 110: 114, 111: 100, 112: 103, 113: 84, 114: 87, 115: 82, 116: 85, 117: 76, 118: 119}
[0, 1, 5, 2, 6, 20, 3, 4, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24, 28, 29, 69, 25, 26, 27, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70, 74, 75, 76, 77, 117, 71, 72, 73, 78, 79, 115, 80, 113, 116, 81, 114, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 111, 94, 105, 112, 95, 106, 96, 99, 107, 97, 100, 98, 108, 109, 110, 101, 103, 102, 104, 118]
[1, 23, 24, 25, 26, 27, 28, 71, 72, 73, 74, 75, 76, 119]

  2%|█▋                                                                                                  | 81/4733 [00:05<08:19,  9.31it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 38, 33: 41, 34: 42, 35: 33, 36: 34, 37: 37, 38: 39, 39: 43, 40: 45, 41: 40, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 31, 48: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 47, 30, 35, 36, 48, 31, 37, 32, 38, 41, 33, 34, 39, 42, 40, 43, 45, 44, 46]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 38, 33: 41, 34: 42, 35: 33, 36: 34, 37: 37, 38: 39, 39: 43, 40: 45, 41: 40, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 31, 48: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 47, 30, 35, 36, 48, 31, 37, 32, 38, 41, 33, 34, 39, 42, 40, 43, 45, 44, 46]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 38, 33: 41, 34: 42, 35: 33, 36: 34, 37: 37, 38: 39, 39: 43, 40: 45, 41: 40, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 31, 48: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 47, 30, 35, 36, 48, 31, 37, 32, 38, 41, 33, 34, 39, 42, 40, 43, 45, 44, 46]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 38, 33: 41, 34: 42, 35: 33, 36: 34, 37: 37, 38: 39, 39: 43, 40: 45, 41: 40, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 31, 48: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 47, 30, 35, 36, 48, 31, 37, 32, 38, 41, 33, 34, 39, 42, 40, 43, 45, 44, 46]
[1, 2, 28]

  2%|█▊                                                                                                  | 87/4733 [00:05<05:22, 14.42it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 38, 33: 41, 34: 42, 35: 33, 36: 34, 37: 37, 38: 39, 39: 43, 40: 45, 41: 40, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 31, 48: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 47, 30, 35, 36, 48, 31, 37, 32, 38, 41, 33, 34, 39, 42, 40, 43, 45, 44, 46]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 38, 33: 41, 34: 42, 35: 33, 36: 34, 37: 37, 38: 39, 39: 43, 40: 45, 41: 40, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 31, 48: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 47, 30, 35, 36, 48, 31, 37, 32, 38, 41, 33, 34, 39, 42, 40, 43, 45, 44, 46]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

  2%|█▉                                                                                                  | 93/4733 [00:06<04:05, 18.87it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 38, 33: 41, 34: 42, 35: 33, 36: 34, 37: 37, 38: 39, 39: 43, 40: 45, 41: 40, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 31, 48: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 47, 30, 35, 36, 48, 31, 37, 32, 38, 41, 33, 34, 39, 42, 40, 43, 45, 44, 46]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 38, 33: 41, 34: 42, 35: 33, 36: 34, 37: 37, 38: 39, 39: 43, 40: 45, 41: 40, 42: 44, 43: 46, 44: 48, 45: 47, 46: 49, 47: 31, 48: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 47, 30, 35, 36, 48, 31, 37, 32, 38, 41, 33, 34, 39, 42, 40, 43, 45, 44, 46]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

  2%|██                                                                                                  | 99/4733 [00:06<03:31, 21.92it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

  2%|██▏                                                                                                | 102/4733 [00:06<03:21, 22.93it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

  2%|██▏                                                                                                | 105/4733 [00:06<03:28, 22.16it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  2%|██▎                                                                                                | 108/4733 [00:07<05:35, 13.79it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

  2%|██▎                                                                                                | 113/4733 [00:07<05:28, 14.07it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 9, 6: 12, 7: 14, 8: 16, 9: 18, 10: 15, 11: 17, 12: 19, 13: 21, 14: 20, 15: 22, 16: 10, 17: 13, 18: 8, 19: 11, 20: 4, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71}
[0, 1, 2, 20, 21, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70]
[1, 2, 3, 23, 24, 25, 26, 27, 28, 71]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 9, 6: 12, 7: 14, 8: 16, 9: 18, 10: 15, 11: 17, 12: 19, 13: 21, 14: 20, 15: 22, 16: 10, 17: 13, 18: 8, 19: 11, 20: 4, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71}
[0, 1, 2, 20, 21, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70]
[1, 2, 3, 23, 24, 25, 26, 27, 28, 71]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

  2%|██▍                                                                                                | 115/4733 [00:07<05:56, 12.94it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 9, 6: 12, 7: 14, 8: 16, 9: 18, 10: 15, 11: 17, 12: 19, 13: 21, 14: 20, 15: 22, 16: 10, 17: 13, 18: 8, 19: 11, 20: 4, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71}
[0, 1, 2, 20, 21, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70]
[1, 2, 3, 23, 24, 25, 26, 27, 28, 71]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 9, 6: 12, 7: 14, 8: 16, 9: 18, 10: 15, 11: 17, 12: 19, 13: 21, 14: 20, 15: 22, 16: 10, 17: 13, 18: 8, 19: 11, 20: 4, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71}
[0, 1, 2, 20, 21, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70]
[1, 2, 3, 23, 24, 25, 26, 27, 28, 71]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  3%|██▍                                                                                                | 119/4733 [00:08<07:41, 10.00it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 9, 6: 12, 7: 14, 8: 16, 9: 18, 10: 15, 11: 17, 12: 19, 13: 21, 14: 20, 15: 22, 16: 10, 17: 13, 18: 8, 19: 11, 20: 4, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71}
[0, 1, 2, 20, 21, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70]
[1, 2, 3, 23, 24, 25, 26, 27, 28, 71]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 9, 6: 12, 7: 14, 8: 16, 9: 18, 10: 15, 11: 17, 12: 19, 13: 21, 14: 20, 15: 22, 16: 10, 17: 13, 18: 8, 19: 11, 20: 4, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28, 70: 71}
[0, 1, 2, 20, 21, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56, 70]
[1, 2, 3, 23, 24, 25, 26, 27, 28, 71]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23]
[1, 2, 23, 24]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23]
[1, 2, 23, 24]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

  3%|██▌                                                                                                | 121/4733 [00:08<07:36, 10.10it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

  3%|██▋                                                                                                | 126/4733 [00:08<05:10, 14.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  3%|██▋                                                                                                | 131/4733 [00:08<05:01, 15.29it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  3%|██▉                                                                                                | 138/4733 [00:09<03:30, 21.80it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  3%|██▉                                                                                                | 141/4733 [00:09<03:25, 22.32it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  3%|███                                                                                                | 147/4733 [00:09<03:36, 21.14it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  3%|███▏                                                                                               | 150/4733 [00:09<03:29, 21.89it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

  3%|███▎                                                                                               | 156/4733 [00:09<03:51, 19.76it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

  3%|███▎                                                                                               | 159/4733 [00:10<03:50, 19.86it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  3%|███▍                                                                                               | 165/4733 [00:10<04:02, 18.86it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  4%|███▌                                                                                               | 168/4733 [00:10<03:42, 20.51it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  4%|███▌                                                                                               | 171/4733 [00:10<03:42, 20.48it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  4%|███▋                                                                                               | 177/4733 [00:11<04:56, 15.37it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  4%|███▊                                                                                               | 180/4733 [00:11<05:15, 14.45it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  4%|███▊                                                                                               | 185/4733 [00:11<04:31, 16.73it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  4%|███▉                                                                                               | 187/4733 [00:12<06:50, 11.08it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  4%|████                                                                                               | 192/4733 [00:12<05:30, 13.72it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  4%|████▏                                                                                              | 198/4733 [00:12<04:29, 16.80it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]

  4%|████▎                                                                                              | 206/4733 [00:13<03:07, 24.20it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]

  4%|████▎                                                                                              | 209/4733 [00:13<03:03, 24.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  5%|████▍                                                                                              | 215/4733 [00:13<03:35, 20.96it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  5%|████▌                                                                                              | 220/4733 [00:14<05:57, 12.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  5%|████▋                                                                                              | 225/4733 [00:14<04:35, 16.38it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  5%|████▊                                                                                              | 231/4733 [00:14<03:48, 19.69it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  5%|████▉                                                                                              | 234/4733 [00:14<03:46, 19.86it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  5%|████▉                                                                                              | 237/4733 [00:15<05:53, 12.73it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  5%|█████                                                                                              | 242/4733 [00:15<06:03, 12.37it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  5%|█████▏                                                                                             | 248/4733 [00:15<04:14, 17.59it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]

  5%|█████▎                                                                                             | 255/4733 [00:16<03:14, 22.99it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  5%|█████▍                                                                                             | 258/4733 [00:16<03:09, 23.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  6%|█████▍                                                                                             | 261/4733 [00:16<03:18, 22.52it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

  6%|█████▌                                                                                             | 267/4733 [00:16<03:38, 20.47it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 40, 33: 41, 34: 33, 35: 37, 36: 42, 37: 34, 38: 31, 39: 35, 40: 38, 41: 43, 42: 45, 43: 39, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 34, 37, 39, 31, 35, 40, 43, 32, 33, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 40, 33: 41, 34: 33, 35: 37, 36: 42, 37: 34, 38: 31, 39: 35, 40: 38, 41: 43, 42: 45, 43: 39, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 34, 37, 39, 31, 35, 40, 43, 32, 33, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 40, 33: 41, 34: 33, 35: 37, 36: 42, 37: 34, 38: 31, 39: 35, 40: 38, 41: 43, 42: 45, 43: 39, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 34, 37, 39, 31, 35, 40, 43, 32, 33, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 40, 33: 41, 34: 33, 35: 37, 36: 42, 37: 34, 38: 31, 39: 35, 40: 38, 41: 43, 42: 45, 43: 39, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 34, 37, 39, 31, 35, 40, 43, 32, 33, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  6%|█████▋                                                                                             | 272/4733 [00:17<04:37, 16.06it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 13, 8: 7, 9: 10, 10: 8, 11: 11, 12: 14, 13: 16, 14: 18, 15: 15, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 4, 8, 10, 5, 9, 11, 6, 7, 12, 15, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 13, 8: 7, 9: 10, 10: 8, 11: 11, 12: 14, 13: 16, 14: 18, 15: 15, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 4, 8, 10, 5, 9, 11, 6, 7, 12, 15, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  6%|█████▊                                                                                             | 278/4733 [00:17<03:41, 20.12it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 40, 33: 41, 34: 33, 35: 37, 36: 42, 37: 34, 38: 31, 39: 35, 40: 38, 41: 43, 42: 45, 43: 39, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 34, 37, 39, 31, 35, 40, 43, 32, 33, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 40, 33: 41, 34: 33, 35: 37, 36: 42, 37: 34, 38: 31, 39: 35, 40: 38, 41: 43, 42: 45, 43: 39, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 34, 37, 39, 31, 35, 40, 43, 32, 33, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 40, 33: 41, 34: 33, 35: 37, 36: 42, 37: 34, 38: 31, 39: 35, 40: 38, 41: 43, 42: 45, 43: 39, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 34, 37, 39, 31, 35, 40, 43, 32, 33, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 40, 33: 41, 34: 33, 35: 37, 36: 42, 37: 34, 38: 31, 39: 35, 40: 38, 41: 43, 42: 45, 43: 39, 44: 44, 45: 46, 46: 48, 47: 47, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 34, 37, 39, 31, 35, 40, 43, 32, 33, 36, 41, 44, 42, 45, 47, 46, 48]
[1, 2, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

  6%|█████▉                                                                                             | 281/4733 [00:17<03:26, 21.52it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 48, 39: 49, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 35, 33, 36, 34, 37, 38, 39]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 13, 8: 7, 9: 10, 10: 8, 11: 11, 12: 14, 13: 16, 14: 18, 15: 15, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 4, 8, 10, 5, 9, 11, 6, 7, 12, 15, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 13, 8: 7, 9: 10, 10: 8, 11: 11, 12: 14, 13: 16, 14: 18, 15: 15, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 4, 8, 10, 5, 9, 11, 6, 7, 12, 15, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  6%|█████▉                                                                                             | 284/4733 [00:17<04:31, 16.36it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 13, 8: 7, 9: 10, 10: 8, 11: 11, 12: 14, 13: 16, 14: 18, 15: 15, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 4, 8, 10, 5, 9, 11, 6, 7, 12, 15, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 12, 7: 13, 8: 7, 9: 10, 10: 8, 11: 11, 12: 14, 13: 16, 14: 18, 15: 15, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 4, 8, 10, 5, 9, 11, 6, 7, 12, 15, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  6%|██████                                                                                             | 289/4733 [00:18<05:39, 13.08it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  6%|██████                                                                                             | 291/4733 [00:18<07:37,  9.71it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  6%|██████▏                                                                                            | 297/4733 [00:19<06:58, 10.61it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  6%|██████▎                                                                                            | 299/4733 [00:19<06:59, 10.56it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  6%|██████▎                                                                                            | 302/4733 [00:19<08:10,  9.04it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  6%|██████▍                                                                                            | 306/4733 [00:20<08:59,  8.20it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  7%|██████▌                                                                                            | 311/4733 [00:20<05:50, 12.61it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 58, 58: 55, 59: 59, 60: 61, 61: 63, 62: 65, 63: 62, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 58, 54, 55, 57, 59, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 58, 58: 55, 59: 59, 60: 61, 61: 63, 62: 65, 63: 62, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 58, 54, 55, 57, 59, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 58, 58: 55, 59: 59, 60: 61, 61: 63, 62: 65, 63: 62, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 58, 54, 55, 57, 59, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 58, 58: 55, 59: 59, 60: 61, 61: 63, 62: 65, 63: 62, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 58, 54, 55, 57, 59, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]

  7%|██████▌                                                                                            | 316/4733 [00:20<04:23, 16.76it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 58, 58: 55, 59: 59, 60: 61, 61: 63, 62: 65, 63: 62, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 58, 54, 55, 57, 59, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 58, 58: 55, 59: 59, 60: 61, 61: 63, 62: 65, 63: 62, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 58, 54, 55, 57, 59, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 58, 58: 55, 59: 59, 60: 61, 61: 63, 62: 65, 63: 62, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 58, 54, 55, 57, 59, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 58, 58: 55, 59: 59, 60: 61, 61: 63, 62: 65, 63: 62, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 58, 54, 55, 57, 59, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 58, 58: 55, 59: 59, 60: 61, 61: 63, 62: 65, 63: 62, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 58, 54, 55, 57, 59, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 58, 58: 55, 59: 59, 60: 61, 61: 63, 62: 65, 63: 62, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 58, 54, 55, 57, 59, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 58, 58: 55, 59: 59, 60: 61, 61: 63, 62: 65, 63: 62, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 58, 54, 55, 57, 59, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 58, 58: 55, 59: 59, 60: 61, 61: 63, 62: 65, 63: 62, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 58, 54, 55, 57, 59, 56, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  7%|██████▋                                                                                            | 319/4733 [00:21<06:29, 11.33it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 61, 57: 57, 58: 58, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 55, 70: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 69, 54, 57, 58, 70, 55, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 61, 57: 57, 58: 58, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 55, 70: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 69, 54, 57, 58, 70, 55, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  7%|██████▋                                                                                            | 321/4733 [00:21<08:22,  8.79it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 61, 57: 57, 58: 58, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 55, 70: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 69, 54, 57, 58, 70, 55, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 61, 57: 57, 58: 58, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 55, 70: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 69, 54, 57, 58, 70, 55, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  7%|██████▊                                                                                            | 323/4733 [00:21<09:52,  7.44it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 61, 57: 57, 58: 58, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 55, 70: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 69, 54, 57, 58, 70, 55, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 61, 57: 57, 58: 58, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 55, 70: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 69, 54, 57, 58, 70, 55, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  7%|██████▊                                                                                            | 328/4733 [00:22<08:19,  8.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 62, 69: 57, 70: 60}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 62, 69: 57, 70: 60}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 62, 69: 57, 70: 60}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 62, 69: 57, 70: 60}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 62, 69: 57, 70: 60}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 62, 69: 57, 70: 60}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 62, 69: 57, 70: 60}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 62, 69: 57, 70: 60}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]

  7%|██████▉                                                                                            | 331/4733 [00:22<06:24, 11.44it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 62, 69: 57, 70: 60}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 62, 69: 57, 70: 60}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 62, 69: 57, 70: 60}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 62, 69: 57, 70: 60}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 55, 69, 56, 67, 70, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  7%|██████▉                                                                                            | 334/4733 [00:22<06:13, 11.77it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  7%|███████                                                                                            | 336/4733 [00:23<07:50,  9.35it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 64, 59: 58, 60: 55, 61: 59, 62: 61, 63: 65, 64: 67, 65: 62, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 60, 54, 55, 59, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 64, 59: 58, 60: 55, 61: 59, 62: 61, 63: 65, 64: 67, 65: 62, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 60, 54, 55, 59, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  7%|███████                                                                                            | 338/4733 [00:23<09:27,  7.75it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 64, 59: 58, 60: 55, 61: 59, 62: 61, 63: 65, 64: 67, 65: 62, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 60, 54, 55, 59, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 64, 59: 58, 60: 55, 61: 59, 62: 61, 63: 65, 64: 67, 65: 62, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 60, 54, 55, 59, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  7%|███████▏                                                                                           | 342/4733 [00:24<09:40,  7.56it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 64, 59: 58, 60: 55, 61: 59, 62: 61, 63: 65, 64: 67, 65: 62, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 60, 54, 55, 59, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 64, 59: 58, 60: 55, 61: 59, 62: 61, 63: 65, 64: 67, 65: 62, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 60, 54, 55, 59, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

  7%|███████▏                                                                                           | 344/4733 [00:24<08:53,  8.22it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  7%|███████▏                                                                                           | 345/4733 [00:24<11:34,  6.32it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 64, 59: 58, 60: 55, 61: 59, 62: 61, 63: 65, 64: 67, 65: 62, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 60, 54, 55, 59, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 64, 59: 58, 60: 55, 61: 59, 62: 61, 63: 65, 64: 67, 65: 62, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 60, 54, 55, 59, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  7%|███████▎                                                                                           | 347/4733 [00:25<12:23,  5.90it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 64, 59: 58, 60: 55, 61: 59, 62: 61, 63: 65, 64: 67, 65: 62, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 60, 54, 55, 59, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 64, 59: 58, 60: 55, 61: 59, 62: 61, 63: 65, 64: 67, 65: 62, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 60, 54, 55, 59, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  7%|███████▎                                                                                           | 352/4733 [00:25<08:51,  8.25it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 64, 59: 58, 60: 55, 61: 59, 62: 61, 63: 65, 64: 67, 65: 62, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 60, 54, 55, 59, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 64, 59: 58, 60: 55, 61: 59, 62: 61, 63: 65, 64: 67, 65: 62, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 60, 54, 55, 59, 61, 56, 62, 65, 57, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  8%|███████▍                                                                                           | 357/4733 [00:25<06:32, 11.14it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

  8%|███████▋                                                                                           | 365/4733 [00:26<03:46, 19.25it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 58, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 55, 68: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 67, 54, 55, 56, 68, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 58, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 55, 68: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 67, 54, 55, 56, 68, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]

  8%|███████▋                                                                                           | 369/4733 [00:26<03:18, 21.99it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 58, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 55, 68: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 67, 54, 55, 56, 68, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 58, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 55, 68: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 67, 54, 55, 56, 68, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 58, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 55, 68: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 67, 54, 55, 56, 68, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 58, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 55, 68: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 67, 54, 55, 56, 68, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 58, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 55, 68: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 67, 54, 55, 56, 68, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 58, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 55, 68: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 67, 54, 55, 56, 68, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  8%|███████▊                                                                                           | 375/4733 [00:26<03:38, 19.93it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 61, 57: 57, 58: 58, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 55, 70: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 69, 54, 57, 58, 70, 55, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 61, 57: 57, 58: 58, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 55, 70: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 69, 54, 57, 58, 70, 55, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 61, 57: 57, 58: 58, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 55, 70: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 69, 54, 57, 58, 70, 55, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 61, 57: 57, 58: 58, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 55, 70: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 69, 54, 57, 58, 70, 55, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  8%|███████▉                                                                                           | 380/4733 [00:27<07:25,  9.77it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 61, 57: 57, 58: 58, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 55, 70: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 69, 54, 57, 58, 70, 55, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 61, 57: 57, 58: 58, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 55, 70: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 69, 54, 57, 58, 70, 55, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 58, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 55, 68: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 67, 54, 55, 56, 68, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 58, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 55, 68: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 67, 54, 55, 56, 68, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]

  8%|████████                                                                                           | 386/4733 [00:27<05:02, 14.36it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 58, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 55, 68: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 67, 54, 55, 56, 68, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 58, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 55, 68: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 67, 54, 55, 56, 68, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

  8%|████████▏                                                                                          | 392/4733 [00:27<03:52, 18.70it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

  8%|████████▎                                                                                          | 395/4733 [00:28<03:27, 20.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

  8%|████████▍                                                                                          | 402/4733 [00:28<03:01, 23.92it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

  9%|████████▍                                                                                          | 405/4733 [00:28<02:57, 24.43it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

  9%|████████▌                                                                                          | 411/4733 [00:28<03:27, 20.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]

  9%|████████▋                                                                                          | 414/4733 [00:28<03:15, 22.07it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  9%|████████▊                                                                                          | 420/4733 [00:29<03:50, 18.69it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

  9%|████████▊                                                                                          | 423/4733 [00:29<03:32, 20.32it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  9%|████████▉                                                                                          | 429/4733 [00:29<03:57, 18.11it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

  9%|█████████                                                                                          | 431/4733 [00:30<05:55, 12.10it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

  9%|█████████▏                                                                                         | 437/4733 [00:30<05:00, 14.28it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

  9%|█████████▎                                                                                         | 443/4733 [00:30<03:45, 19.02it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

  9%|█████████▎                                                                                         | 446/4733 [00:30<03:27, 20.68it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 66, 60: 68, 61: 63, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 59, 62, 60, 63, 65, 64, 66, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 66, 60: 68, 61: 63, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 59, 62, 60, 63, 65, 64, 66, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 73]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 10%|█████████▍                                                                                         | 451/4733 [00:31<04:48, 14.86it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 66, 60: 68, 61: 63, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 59, 62, 60, 63, 65, 64, 66, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 66, 60: 68, 61: 63, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 59, 62, 60, 63, 65, 64, 66, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 73]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 10%|█████████▍                                                                                         | 453/4733 [00:31<07:44,  9.22it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 66, 60: 68, 61: 63, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 59, 62, 60, 63, 65, 64, 66, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 66, 60: 68, 61: 63, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 59, 62, 60, 63, 65, 64, 66, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 73]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 10%|█████████▌                                                                                         | 457/4733 [00:32<06:40, 10.67it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 10%|█████████▋                                                                                         | 462/4733 [00:32<04:42, 15.12it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 10%|█████████▋                                                                                         | 464/4733 [00:32<05:15, 13.54it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 10%|█████████▊                                                                                         | 469/4733 [00:32<04:01, 17.69it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 10%|█████████▊                                                                                         | 472/4733 [00:32<03:50, 18.50it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 10%|█████████▉                                                                                         | 475/4733 [00:33<04:45, 14.90it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 10%|██████████                                                                                         | 479/4733 [00:33<06:16, 11.29it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 10%|██████████▏                                                                                        | 485/4733 [00:33<04:16, 16.59it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 10%|██████████▎                                                                                        | 491/4733 [00:34<03:50, 18.43it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]

 10%|██████████▎                                                                                        | 495/4733 [00:34<03:53, 18.18it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 11%|██████████▍                                                                                        | 501/4733 [00:34<03:27, 20.36it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 11%|██████████▌                                                                                        | 504/4733 [00:34<04:05, 17.23it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 11%|██████████▋                                                                                        | 509/4733 [00:35<03:33, 19.76it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 11%|██████████▋                                                                                        | 512/4733 [00:35<03:33, 19.77it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 11%|██████████▊                                                                                        | 515/4733 [00:35<05:32, 12.70it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 11%|██████████▉                                                                                        | 520/4733 [00:36<04:46, 14.72it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 11%|██████████▉                                                                                        | 523/4733 [00:36<04:21, 16.10it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 11%|███████████                                                                                        | 528/4733 [00:36<06:14, 11.23it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 11%|███████████                                                                                        | 530/4733 [00:37<08:46,  7.99it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 11%|███████████▏                                                                                       | 532/4733 [00:37<08:13,  8.52it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 11%|███████████▎                                                                                       | 538/4733 [00:38<06:59, 10.01it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 11%|███████████▎                                                                                       | 540/4733 [00:38<08:31,  8.21it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 11%|███████████▎                                                                                       | 542/4733 [00:38<08:05,  8.63it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 12%|███████████▍                                                                                       | 546/4733 [00:39<07:41,  9.08it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 55, 66: 58, 67: 61, 68: 64, 69: 68, 70: 69, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 68, 56, 59, 57, 69, 70, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 12%|███████████▌                                                                                       | 551/4733 [00:39<06:45, 10.32it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 55, 66: 58, 67: 61, 68: 62, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 65, 53, 52, 66, 64, 54, 67, 68, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 59, 58: 61, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 54, 53, 57, 55, 58, 56, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]

 12%|███████████▋                                                                                       | 557/4733 [00:39<04:39, 14.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 63, 55: 65, 56: 59, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 60, 64: 61, 65: 66, 66: 57, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 62, 66, 53, 56, 63, 64, 67, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 58, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 68, 53, 55, 57, 54, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 66, 59: 68, 60: 67, 61: 69, 62: 56, 63: 59, 64: 62, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 62, 52, 66, 63, 53, 56, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 12%|███████████▋                                                                                       | 561/4733 [00:39<03:50, 18.09it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 55, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 69, 62, 52, 70, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]

 12%|███████████▊                                                                                       | 564/4733 [00:40<04:21, 15.92it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 12%|███████████▊                                                                                       | 567/4733 [00:40<03:59, 17.43it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 12%|███████████▉                                                                                       | 569/4733 [00:40<05:59, 11.59it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 12%|████████████                                                                                       | 575/4733 [00:41<04:57, 13.97it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 65, 58: 62, 59: 64, 60: 66, 61: 68, 62: 67, 63: 69, 64: 59, 65: 55, 66: 58, 67: 51, 68: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 67, 68, 50, 51, 65, 53, 52, 66, 64, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 12%|████████████▏                                                                                      | 582/4733 [00:41<03:41, 18.78it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 12%|████████████▏                                                                                      | 585/4733 [00:41<04:02, 17.09it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 12%|████████████▎                                                                                      | 587/4733 [00:41<04:32, 15.22it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 12%|████████████▎                                                                                      | 591/4733 [00:42<06:26, 10.72it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 13%|████████████▍                                                                                      | 597/4733 [00:42<05:35, 12.33it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 13%|████████████▌                                                                                      | 602/4733 [00:43<05:41, 12.09it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 38, 34: 41, 35: 43, 36: 39, 37: 42, 38: 44, 39: 46, 40: 45, 41: 47, 42: 35, 43: 31, 44: 34, 45: 37, 46: 40}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 45, 33, 36, 46, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 34, 34: 37, 35: 35, 36: 38, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 31, 33, 35, 32, 34, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 34, 34: 37, 35: 35, 36: 38, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 31, 33, 35, 32, 34, 36, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 13%|████████████▋                                                                                      | 606/4733 [00:43<04:21, 15.80it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 13%|████████████▊                                                                                      | 614/4733 [00:43<03:23, 20.25it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 13%|████████████▉                                                                                      | 617/4733 [00:44<04:55, 13.93it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 13%|████████████▉                                                                                      | 619/4733 [00:44<05:12, 13.17it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 13%|█████████████                                                                                      | 623/4733 [00:44<06:42, 10.21it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 59, 60: 60, 61: 62, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 59, 60: 60, 61: 62, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 13%|█████████████                                                                                      | 625/4733 [00:45<06:37, 10.33it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 13%|█████████████                                                                                      | 627/4733 [00:45<09:12,  7.44it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 59, 60: 60, 61: 62, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 59, 60: 60, 61: 62, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 59, 60: 60, 61: 62, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 59, 60: 60, 61: 62, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 13%|█████████████▏                                                                                     | 633/4733 [00:45<05:30, 12.40it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 14%|█████████████▍                                                                                     | 640/4733 [00:46<03:48, 17.88it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 14%|█████████████▌                                                                                     | 647/4733 [00:46<03:31, 19.32it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 14%|█████████████▌                                                                                     | 650/4733 [00:47<05:45, 11.82it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 14%|█████████████▋                                                                                     | 652/4733 [00:47<05:52, 11.59it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 65, 60: 67, 61: 63, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 58, 69: 61, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 65, 60: 67, 61: 63, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 58, 69: 61, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 14%|█████████████▋                                                                                     | 656/4733 [00:47<05:12, 13.07it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 14%|█████████████▊                                                                                     | 660/4733 [00:48<06:37, 10.26it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 65, 60: 67, 61: 63, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 58, 69: 61, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 65, 60: 67, 61: 63, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 58, 69: 61, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 65, 60: 67, 61: 63, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 58, 69: 61, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 65, 60: 67, 61: 63, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 58, 69: 61, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 14%|█████████████▉                                                                                     | 666/4733 [00:48<04:35, 14.78it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 14%|██████████████                                                                                     | 672/4733 [00:48<03:44, 18.11it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 14%|██████████████                                                                                     | 675/4733 [00:49<05:19, 12.70it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 14%|██████████████▎                                                                                    | 683/4733 [00:49<03:43, 18.16it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 15%|██████████████▍                                                                                    | 690/4733 [00:49<04:01, 16.72it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]

 15%|██████████████▌                                                                                    | 694/4733 [00:49<03:19, 20.29it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 15%|██████████████▋                                                                                    | 701/4733 [00:50<03:00, 22.38it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 14, 10: 17, 11: 11, 12: 8, 13: 12, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 14, 9, 15, 18, 10, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 15%|██████████████▊                                                                                    | 709/4733 [00:50<02:23, 28.08it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 15%|██████████████▉                                                                                    | 713/4733 [00:51<05:03, 13.24it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 62, 59: 57, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 62, 59: 57, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 62, 59: 57, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 62, 59: 57, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 15%|███████████████                                                                                    | 721/4733 [00:51<03:47, 17.64it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 15%|███████████████▏                                                                                   | 724/4733 [00:51<05:02, 13.24it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 62, 59: 57, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 62, 59: 57, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 15%|███████████████▎                                                                                   | 731/4733 [00:52<03:53, 17.15it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 16%|███████████████▎                                                                                   | 734/4733 [00:52<04:00, 16.60it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 16%|███████████████▌                                                                                   | 742/4733 [00:52<03:15, 20.41it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 16%|███████████████▋                                                                                   | 751/4733 [00:52<02:25, 27.44it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 16%|███████████████▊                                                                                   | 755/4733 [00:53<02:14, 29.60it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]

 16%|███████████████▉                                                                                   | 763/4733 [00:53<02:21, 27.96it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 16%|████████████████▏                                                                                  | 772/4733 [00:53<02:01, 32.48it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 16%|████████████████▏                                                                                  | 776/4733 [00:54<04:26, 14.87it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 17%|████████████████▍                                                                                  | 783/4733 [00:54<03:41, 17.86it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 17%|████████████████▍                                                                                  | 786/4733 [00:55<05:33, 11.85it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 59, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 59, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 59, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 59, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 17%|████████████████▌                                                                                  | 789/4733 [00:55<05:59, 10.96it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 17%|████████████████▌                                                                                  | 791/4733 [00:55<06:00, 10.94it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 62, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 67, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 62, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 67, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 17%|████████████████▋                                                                                  | 795/4733 [00:56<07:01,  9.33it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 62, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 67, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 62, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 67, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 62, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 67, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 62, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 67, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 17%|████████████████▋                                                                                  | 797/4733 [00:56<06:48,  9.63it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 59, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 59, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 67, 61: 66, 62: 65, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 57, 55, 58, 56, 59, 62, 61, 60, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 67, 61: 66, 62: 65, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 57, 55, 58, 56, 59, 62, 61, 60, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 17%|████████████████▊                                                                                  | 801/4733 [00:56<07:09,  9.15it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 67, 61: 66, 62: 65, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 57, 55, 58, 56, 59, 62, 61, 60, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 67, 61: 66, 62: 65, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 57, 55, 58, 56, 59, 62, 61, 60, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 17%|████████████████▊                                                                                  | 804/4733 [00:57<07:46,  8.43it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 17%|████████████████▉                                                                                  | 811/4733 [00:57<04:45, 13.75it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 67, 61: 66, 62: 65, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 57, 55, 58, 56, 59, 62, 61, 60, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 67, 61: 66, 62: 65, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 57, 55, 58, 56, 59, 62, 61, 60, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 17%|█████████████████                                                                                  | 813/4733 [00:57<05:04, 12.88it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 17%|█████████████████▏                                                                                 | 819/4733 [00:58<04:36, 14.13it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 17%|█████████████████▏                                                                                 | 823/4733 [00:58<03:42, 17.54it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 18%|█████████████████▍                                                                                 | 831/4733 [00:58<03:54, 16.61it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 18%|█████████████████▌                                                                                 | 838/4733 [00:59<03:16, 19.79it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 18%|█████████████████▋                                                                                 | 847/4733 [00:59<02:25, 26.72it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 18%|█████████████████▊                                                                                 | 851/4733 [00:59<02:13, 29.02it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 18%|█████████████████▉                                                                                 | 855/4733 [00:59<02:40, 24.12it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 18%|██████████████████                                                                                 | 863/4733 [01:00<03:06, 20.77it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 18%|██████████████████▏                                                                                | 867/4733 [01:00<02:43, 23.68it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 18%|██████████████████▏                                                                                | 871/4733 [01:00<04:25, 14.56it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 60, 69: 58, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 60, 69: 58, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 60, 69: 58, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 60, 69: 58, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 19%|██████████████████▎                                                                                | 878/4733 [01:01<04:01, 15.93it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 19%|██████████████████▍                                                                                | 881/4733 [01:01<04:06, 15.66it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 60, 69: 58, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 60, 69: 58, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 19%|██████████████████▌                                                                                | 889/4733 [01:01<03:20, 19.17it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 19%|██████████████████▋                                                                                | 896/4733 [01:02<03:13, 19.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 19%|██████████████████▊                                                                                | 899/4733 [01:02<05:15, 12.14it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 19%|██████████████████▉                                                                                | 905/4733 [01:03<04:03, 15.69it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 19%|███████████████████                                                                                | 911/4733 [01:03<04:05, 15.55it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 19%|███████████████████▏                                                                               | 915/4733 [01:03<03:16, 19.44it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 20%|███████████████████▎                                                                               | 923/4733 [01:03<02:30, 25.32it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 20%|███████████████████▍                                                                               | 930/4733 [01:04<02:16, 27.96it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 20%|███████████████████▌                                                                               | 934/4733 [01:04<02:37, 24.10it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 20%|███████████████████▌                                                                               | 937/4733 [01:04<04:40, 13.52it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 20%|███████████████████▋                                                                               | 940/4733 [01:04<04:33, 13.85it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 20%|███████████████████▊                                                                               | 948/4733 [01:05<03:27, 18.26it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 20%|███████████████████▉                                                                               | 955/4733 [01:05<03:01, 20.76it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 20%|████████████████████▏                                                                              | 964/4733 [01:05<02:17, 27.38it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]

 20%|████████████████████▏                                                                              | 968/4733 [01:05<02:07, 29.45it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 21%|████████████████████▍                                                                              | 976/4733 [01:06<02:14, 27.87it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 21%|████████████████████▌                                                                              | 984/4733 [01:06<01:59, 31.50it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 21%|████████████████████▋                                                                              | 992/4733 [01:07<02:55, 21.27it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 21%|████████████████████▋                                                                             | 1001/4733 [01:07<02:15, 27.63it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 21%|████████████████████▊                                                                             | 1005/4733 [01:07<02:33, 24.22it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 68, 62: 69, 63: 70, 64: 65, 65: 67, 66: 55, 67: 58, 68: 53, 69: 56, 70: 71, 71: 72, 72: 73, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 66, 69, 53, 67, 54, 57, 55, 58, 56, 59, 64, 60, 65, 61, 62, 63, 70, 71, 72, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 75]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 68, 62: 69, 63: 70, 64: 65, 65: 67, 66: 55, 67: 58, 68: 53, 69: 56, 70: 71, 71: 72, 72: 73, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 66, 69, 53, 67, 54, 57, 55, 58, 56, 59, 64, 60, 65, 61, 62, 63, 70, 71, 72, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 75]

 21%|████████████████████▊                                                                             | 1008/4733 [01:07<03:05, 20.12it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 68, 62: 69, 63: 70, 64: 65, 65: 67, 66: 55, 67: 58, 68: 53, 69: 56, 70: 71, 71: 72, 72: 73, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 66, 69, 53, 67, 54, 57, 55, 58, 56, 59, 64, 60, 65, 61, 62, 63, 70, 71, 72, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 75]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 68, 62: 69, 63: 70, 64: 65, 65: 67, 66: 55, 67: 58, 68: 53, 69: 56, 70: 71, 71: 72, 72: 73, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 66, 69, 53, 67, 54, 57, 55, 58, 56, 59, 64, 60, 65, 61, 62, 63, 70, 71, 72, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 75]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 21%|████████████████████▉                                                                             | 1011/4733 [01:07<03:24, 18.21it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 22%|█████████████████████                                                                             | 1019/4733 [01:08<02:51, 21.63it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 68, 62: 69, 63: 70, 64: 65, 65: 67, 66: 55, 67: 58, 68: 53, 69: 56, 70: 71, 71: 72, 72: 73, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 66, 69, 53, 67, 54, 57, 55, 58, 56, 59, 64, 60, 65, 61, 62, 63, 70, 71, 72, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 75]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 68, 62: 69, 63: 70, 64: 65, 65: 67, 66: 55, 67: 58, 68: 53, 69: 56, 70: 71, 71: 72, 72: 73, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 66, 69, 53, 67, 54, 57, 55, 58, 56, 59, 64, 60, 65, 61, 62, 63, 70, 71, 72, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 75]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 22%|█████████████████████▏                                                                            | 1022/4733 [01:08<04:50, 12.77it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 22%|█████████████████████▏                                                                            | 1024/4733 [01:09<06:45,  9.15it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 56, 58: 60, 59: 61, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 56, 58: 60, 59: 61, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 56, 58: 60, 59: 61, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 56, 58: 60, 59: 61, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 22%|█████████████████████▎                                                                            | 1028/4733 [01:09<06:20,  9.74it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 60, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 60, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 22%|█████████████████████▎                                                                            | 1032/4733 [01:10<07:03,  8.75it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 22%|█████████████████████▍                                                                            | 1036/4733 [01:10<04:45, 12.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 56, 58: 60, 59: 61, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 56, 58: 60, 59: 61, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 57, 55, 70, 56, 58, 59, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 22%|█████████████████████▌                                                                            | 1043/4733 [01:10<03:25, 18.00it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 22%|█████████████████████▋                                                                            | 1050/4733 [01:10<03:08, 19.54it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]

 22%|█████████████████████▊                                                                            | 1054/4733 [01:11<02:39, 23.10it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 22%|█████████████████████▉                                                                            | 1062/4733 [01:11<02:33, 23.91it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 62, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 67, 66: 65, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 62, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 67, 66: 65, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 23%|██████████████████████▏                                                                           | 1069/4733 [01:11<02:32, 24.01it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 23%|██████████████████████▏                                                                           | 1072/4733 [01:11<02:57, 20.65it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 62, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 67, 66: 65, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 62, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 67, 66: 65, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 23%|██████████████████████▎                                                                           | 1075/4733 [01:12<03:23, 17.99it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 23%|██████████████████████▎                                                                           | 1078/4733 [01:12<05:19, 11.42it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 62, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 67, 66: 65, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 62, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 67, 66: 65, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 60, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 60, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 23%|██████████████████████▎                                                                           | 1080/4733 [01:12<05:24, 11.27it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 60, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 60, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 23%|██████████████████████▍                                                                           | 1084/4733 [01:13<05:28, 11.10it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 23%|██████████████████████▍                                                                           | 1086/4733 [01:13<07:48,  7.79it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 23%|██████████████████████▌                                                                           | 1088/4733 [01:13<07:12,  8.42it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 23%|██████████████████████▌                                                                           | 1091/4733 [01:14<08:24,  7.22it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 23%|██████████████████████▋                                                                           | 1093/4733 [01:14<07:31,  8.07it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 65, 58: 64, 59: 59, 60: 63, 61: 68, 62: 69, 63: 70, 64: 71, 65: 66, 66: 56, 67: 60, 68: 58, 69: 62, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 65, 58: 64, 59: 59, 60: 63, 61: 68, 62: 69, 63: 70, 64: 71, 65: 66, 66: 56, 67: 60, 68: 58, 69: 62, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 23%|██████████████████████▋                                                                           | 1097/4733 [01:14<05:38, 10.75it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 23%|██████████████████████▊                                                                           | 1100/4733 [01:15<07:17,  8.31it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 65, 58: 64, 59: 59, 60: 63, 61: 68, 62: 69, 63: 70, 64: 71, 65: 66, 66: 56, 67: 60, 68: 58, 69: 62, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 65, 58: 64, 59: 59, 60: 63, 61: 68, 62: 69, 63: 70, 64: 71, 65: 66, 66: 56, 67: 60, 68: 58, 69: 62, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 65, 58: 64, 59: 59, 60: 63, 61: 68, 62: 69, 63: 70, 64: 71, 65: 66, 66: 56, 67: 60, 68: 58, 69: 62, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 65, 58: 64, 59: 59, 60: 63, 61: 68, 62: 69, 63: 70, 64: 71, 65: 66, 66: 56, 67: 60, 68: 58, 69: 62, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 23%|██████████████████████▉                                                                           | 1106/4733 [01:15<04:24, 13.73it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 23%|██████████████████████▉                                                                           | 1108/4733 [01:15<04:39, 12.98it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 24%|███████████████████████                                                                           | 1116/4733 [01:16<03:58, 15.16it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 24%|███████████████████████▏                                                                          | 1120/4733 [01:16<03:17, 18.30it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 24%|███████████████████████▎                                                                          | 1123/4733 [01:16<03:34, 16.83it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 24%|███████████████████████▌                                                                          | 1135/4733 [01:17<02:27, 24.41it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]

 24%|███████████████████████▌                                                                          | 1139/4733 [01:17<02:12, 27.22it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 24%|███████████████████████▋                                                                          | 1143/4733 [01:17<02:37, 22.78it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 24%|███████████████████████▋                                                                          | 1146/4733 [01:17<04:29, 13.30it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 24%|███████████████████████▊                                                                          | 1149/4733 [01:18<04:29, 13.30it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 24%|███████████████████████▉                                                                          | 1157/4733 [01:18<03:57, 15.07it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 64, 59: 59, 60: 57, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 64, 59: 59, 60: 57, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 25%|████████████████████████                                                                          | 1160/4733 [01:18<04:04, 14.60it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 25%|████████████████████████                                                                          | 1162/4733 [01:19<04:21, 13.66it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 25%|████████████████████████                                                                          | 1164/4733 [01:19<06:29,  9.17it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 25%|████████████████████████▏                                                                         | 1166/4733 [01:19<06:15,  9.49it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 64, 59: 59, 60: 57, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 64, 59: 59, 60: 57, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 25%|████████████████████████▏                                                                         | 1170/4733 [01:20<05:10, 11.48it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 25%|████████████████████████▎                                                                         | 1174/4733 [01:20<06:12,  9.55it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 64, 59: 59, 60: 57, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 64, 59: 59, 60: 57, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 25%|████████████████████████▍                                                                         | 1178/4733 [01:20<04:20, 13.66it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 25%|████████████████████████▌                                                                         | 1186/4733 [01:21<03:02, 19.42it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]

 25%|████████████████████████▋                                                                         | 1195/4733 [01:21<02:12, 26.78it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 25%|████████████████████████▊                                                                         | 1199/4733 [01:21<02:34, 22.91it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 26%|████████████████████████▉                                                                         | 1207/4733 [01:21<01:59, 29.42it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 26%|█████████████████████████                                                                         | 1211/4733 [01:21<01:53, 31.07it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 26%|█████████████████████████▏                                                                        | 1219/4733 [01:22<02:02, 28.59it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]

 26%|█████████████████████████▎                                                                        | 1223/4733 [01:22<01:55, 30.39it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 26%|█████████████████████████▍                                                                        | 1231/4733 [01:22<02:04, 28.24it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 26%|█████████████████████████▋                                                                        | 1239/4733 [01:22<01:49, 31.89it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 26%|█████████████████████████▋                                                                        | 1243/4733 [01:22<01:45, 33.12it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]

 26%|█████████████████████████▉                                                                        | 1251/4733 [01:23<01:58, 29.41it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 27%|█████████████████████████▉                                                                        | 1255/4733 [01:23<02:23, 24.17it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 27%|██████████████████████████▏                                                                       | 1262/4733 [01:23<03:02, 19.05it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 27%|██████████████████████████▏                                                                       | 1265/4733 [01:24<04:45, 12.15it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 62, 69: 57, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 62, 69: 57, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 62, 69: 57, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 62, 69: 57, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 27%|██████████████████████████▏                                                                       | 1267/4733 [01:24<04:52, 11.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 27%|██████████████████████████▎                                                                       | 1269/4733 [01:25<06:06,  9.46it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 27%|██████████████████████████▍                                                                       | 1276/4733 [01:25<04:00, 14.39it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 62, 69: 57, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 62, 69: 57, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 27%|██████████████████████████▌                                                                       | 1283/4733 [01:25<03:06, 18.45it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 27%|██████████████████████████▋                                                                       | 1286/4733 [01:25<03:17, 17.49it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 27%|██████████████████████████▊                                                                       | 1293/4733 [01:26<03:29, 16.41it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]

 27%|██████████████████████████▉                                                                       | 1300/4733 [01:26<03:04, 18.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 28%|███████████████████████████                                                                       | 1308/4733 [01:26<02:14, 25.41it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 28%|███████████████████████████▏                                                                      | 1312/4733 [01:27<02:01, 28.08it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 28%|███████████████████████████▎                                                                      | 1319/4733 [01:27<02:45, 20.68it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 28%|███████████████████████████▎                                                                      | 1322/4733 [01:27<03:09, 18.02it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]

 28%|███████████████████████████▍                                                                      | 1327/4733 [01:27<02:57, 19.24it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 28%|███████████████████████████▌                                                                      | 1330/4733 [01:28<03:19, 17.09it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 28%|███████████████████████████▌                                                                      | 1332/4733 [01:28<03:41, 15.37it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 28%|███████████████████████████▌                                                                      | 1334/4733 [01:28<05:07, 11.06it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 28%|███████████████████████████▋                                                                      | 1338/4733 [01:28<04:27, 12.67it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 28%|███████████████████████████▊                                                                      | 1342/4733 [01:29<05:35, 10.12it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 28%|███████████████████████████▊                                                                      | 1345/4733 [01:29<07:00,  8.06it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 60, 60: 58, 61: 61, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 60, 60: 58, 61: 61, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 60, 60: 58, 61: 61, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 60, 60: 58, 61: 61, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 28%|███████████████████████████▉                                                                      | 1347/4733 [01:30<06:28,  8.71it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 29%|███████████████████████████▉                                                                      | 1351/4733 [01:30<07:06,  7.93it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 59, 66: 54, 67: 57, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 59, 66: 54, 67: 57, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 29%|████████████████████████████                                                                      | 1354/4733 [01:31<08:07,  6.93it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 59, 66: 54, 67: 57, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 59, 66: 54, 67: 57, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 59, 66: 54, 67: 57, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 59, 66: 54, 67: 57, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 29%|████████████████████████████                                                                      | 1358/4733 [01:31<06:30,  8.65it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 60, 60: 58, 61: 61, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 60, 60: 58, 61: 61, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 29%|████████████████████████████▏                                                                     | 1362/4733 [01:31<04:56, 11.37it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 29%|████████████████████████████▎                                                                     | 1366/4733 [01:31<03:34, 15.71it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 29%|████████████████████████████▍                                                                     | 1376/4733 [01:32<02:11, 25.53it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 29%|████████████████████████████▋                                                                     | 1383/4733 [01:32<02:13, 25.08it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 29%|████████████████████████████▋                                                                     | 1388/4733 [01:32<01:56, 28.74it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 29%|████████████████████████████▊                                                                     | 1392/4733 [01:33<03:30, 15.89it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 62, 57: 65, 58: 67, 59: 63, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 58, 66: 61, 67: 56, 68: 60, 69: 59, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 62, 57: 65, 58: 67, 59: 63, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 58, 66: 61, 67: 56, 68: 60, 69: 59, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 62, 57: 65, 58: 67, 59: 63, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 58, 66: 61, 67: 56, 68: 60, 69: 59, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 62, 57: 65, 58: 67, 59: 63, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 58, 66: 61, 67: 56, 68: 60, 69: 59, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 29%|████████████████████████████▉                                                                     | 1395/4733 [01:33<03:39, 15.23it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 30%|█████████████████████████████                                                                     | 1401/4733 [01:33<03:56, 14.08it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 30%|█████████████████████████████                                                                     | 1403/4733 [01:34<05:12, 10.66it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 62, 57: 65, 58: 67, 59: 63, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 58, 66: 61, 67: 56, 68: 60, 69: 59, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 62, 57: 65, 58: 67, 59: 63, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 58, 66: 61, 67: 56, 68: 60, 69: 59, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 30%|█████████████████████████████                                                                     | 1405/4733 [01:34<05:11, 10.69it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 30%|█████████████████████████████▎                                                                    | 1413/4733 [01:34<03:22, 16.39it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 30%|█████████████████████████████▍                                                                    | 1422/4733 [01:35<02:16, 24.31it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 30%|█████████████████████████████▌                                                                    | 1425/4733 [01:35<02:35, 21.22it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 30%|█████████████████████████████▋                                                                    | 1433/4733 [01:35<02:56, 18.66it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]

 30%|█████████████████████████████▊                                                                    | 1440/4733 [01:35<02:23, 22.87it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 31%|█████████████████████████████▉                                                                    | 1447/4733 [01:36<02:22, 23.13it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 31%|██████████████████████████████                                                                    | 1450/4733 [01:36<02:47, 19.63it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 31%|██████████████████████████████                                                                    | 1454/4733 [01:36<02:27, 22.21it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 31%|██████████████████████████████▎                                                                   | 1461/4733 [01:36<02:20, 23.30it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 31%|██████████████████████████████▍                                                                   | 1469/4733 [01:37<01:54, 28.49it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 31%|██████████████████████████████▌                                                                   | 1477/4733 [01:37<01:41, 32.07it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 31%|██████████████████████████████▋                                                                   | 1481/4733 [01:37<01:38, 33.06it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 31%|██████████████████████████████▊                                                                   | 1489/4733 [01:37<01:54, 28.37it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 32%|███████████████████████████████                                                                   | 1498/4733 [01:38<01:38, 32.75it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 32%|███████████████████████████████                                                                   | 1502/4733 [01:38<01:59, 27.05it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 32%|███████████████████████████████▎                                                                  | 1510/4733 [01:38<02:05, 25.70it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 32%|███████████████████████████████▍                                                                  | 1517/4733 [01:38<02:09, 24.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 20, 12: 22, 13: 17, 14: 21, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 9, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 23, 10, 13, 24, 25, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 32%|███████████████████████████████▍                                                                  | 1520/4733 [01:39<03:20, 16.01it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 32%|███████████████████████████████▌                                                                  | 1523/4733 [01:39<03:30, 15.22it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 32%|███████████████████████████████▌                                                                  | 1525/4733 [01:40<05:22,  9.94it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]

 32%|███████████████████████████████▋                                                                  | 1529/4733 [01:40<04:33, 11.72it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 32%|███████████████████████████████▊                                                                  | 1537/4733 [01:40<02:55, 18.20it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 33%|███████████████████████████████▉                                                                  | 1540/4733 [01:40<02:42, 19.70it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 33%|███████████████████████████████▉                                                                  | 1543/4733 [01:40<02:54, 18.31it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 33%|████████████████████████████████                                                                  | 1547/4733 [01:41<02:57, 17.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 33%|████████████████████████████████▏                                                                 | 1555/4733 [01:41<02:59, 17.74it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 33%|████████████████████████████████▎                                                                 | 1559/4733 [01:41<03:02, 17.38it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 33%|████████████████████████████████▎                                                                 | 1562/4733 [01:42<04:32, 11.64it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 33%|████████████████████████████████▍                                                                 | 1567/4733 [01:42<03:51, 13.69it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 33%|████████████████████████████████▌                                                                 | 1574/4733 [01:42<03:06, 16.93it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 33%|████████████████████████████████▋                                                                 | 1577/4733 [01:43<03:12, 16.42it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]

 34%|████████████████████████████████▊                                                                 | 1586/4733 [01:43<02:01, 25.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]

 34%|████████████████████████████████▉                                                                 | 1590/4733 [01:43<01:51, 28.10it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 69, 65: 71, 66: 66, 67: 67, 68: 63, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 69, 65: 71, 66: 66, 67: 67, 68: 63, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 34%|█████████████████████████████████                                                                 | 1594/4733 [01:44<03:29, 15.00it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 69, 65: 71, 66: 66, 67: 67, 68: 63, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 69, 65: 71, 66: 66, 67: 67, 68: 63, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 69, 65: 71, 66: 66, 67: 67, 68: 63, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 69, 65: 71, 66: 66, 67: 67, 68: 63, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 34%|█████████████████████████████████▏                                                                | 1601/4733 [01:44<03:17, 15.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]

 34%|█████████████████████████████████▏                                                                | 1605/4733 [01:44<02:42, 19.19it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 34%|█████████████████████████████████▎                                                                | 1608/4733 [01:44<02:53, 18.05it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 34%|█████████████████████████████████▍                                                                | 1615/4733 [01:45<03:06, 16.72it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]

 34%|█████████████████████████████████▌                                                                | 1619/4733 [01:45<02:33, 20.23it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 34%|█████████████████████████████████▋                                                                | 1626/4733 [01:45<02:18, 22.38it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]

 34%|█████████████████████████████████▊                                                                | 1631/4733 [01:45<01:51, 27.88it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 35%|█████████████████████████████████▊                                                                | 1635/4733 [01:46<02:10, 23.66it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 35%|██████████████████████████████████                                                                | 1643/4733 [01:46<02:03, 24.98it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 35%|██████████████████████████████████                                                                | 1647/4733 [01:46<01:57, 26.34it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 35%|██████████████████████████████████▏                                                               | 1653/4733 [01:46<02:13, 23.00it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]

 35%|██████████████████████████████████▎                                                               | 1657/4733 [01:46<01:57, 26.12it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 35%|██████████████████████████████████▎                                                               | 1660/4733 [01:47<02:26, 20.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 35%|██████████████████████████████████▍                                                               | 1663/4733 [01:47<04:12, 12.18it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 47, 36: 48, 37: 49, 38: 43, 39: 45, 40: 39, 41: 42, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 40, 47, 32, 41, 38, 33, 39, 34, 35, 36, 37]
[1, 27, 28]

 35%|██████████████████████████████████▍                                                               | 1666/4733 [01:47<03:35, 14.24it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 67, 58: 66, 59: 63, 60: 65, 61: 68, 62: 70, 63: 69, 64: 71, 65: 59, 66: 61, 67: 56, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 52, 67, 53, 68, 65, 54, 66, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 35%|██████████████████████████████████▌                                                               | 1669/4733 [01:48<04:54, 10.39it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 35%|██████████████████████████████████▌                                                               | 1671/4733 [01:48<05:55,  8.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]

 35%|██████████████████████████████████▋                                                               | 1673/4733 [01:48<05:32,  9.19it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 35%|██████████████████████████████████▋                                                               | 1675/4733 [01:49<07:00,  7.28it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 35%|██████████████████████████████████▊                                                               | 1679/4733 [01:49<05:18,  9.59it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]

 36%|██████████████████████████████████▊                                                               | 1684/4733 [01:49<03:43, 13.65it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 36%|██████████████████████████████████▉                                                               | 1689/4733 [01:50<03:23, 14.92it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 51, 54: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 53, 54, 50, 51, 52]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 61, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 60, 65: 56, 66: 58, 67: 62, 68: 65, 69: 66, 70: 59, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 70, 64, 54, 67, 55, 58, 68, 69, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 61, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 60, 65: 56, 66: 58, 67: 62, 68: 65, 69: 66, 70: 59, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 70, 64, 54, 67, 55, 58, 68, 69, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 73, 62: 72, 63: 71, 64: 74, 65: 59, 66: 55, 67: 58, 68: 61, 69: 64, 70: 68, 71: 69, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 66, 53, 52, 67, 65, 54, 68, 55, 58, 69, 56, 59, 57, 70, 71, 60, 63, 62, 61, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 73, 62: 72, 63: 71, 64: 74, 65: 59, 66: 55, 67: 58, 68: 61, 69: 64, 70: 68, 71: 69, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 66, 53, 52, 67, 65, 54, 68, 55, 58, 69, 56, 59, 57, 70, 71, 60, 63, 62, 61, 64]
[1, 49, 50]

 36%|███████████████████████████████████                                                               | 1691/4733 [01:50<03:12, 15.76it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 36%|███████████████████████████████████▏                                                              | 1697/4733 [01:50<03:31, 14.33it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 64, 56: 60, 57: 63, 58: 65, 59: 66, 60: 68, 61: 70, 62: 67, 63: 69, 64: 71, 65: 73, 66: 72, 67: 74, 68: 59, 69: 62, 70: 55, 71: 57, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 52, 71, 53, 68, 56, 54, 69, 57, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]

 36%|███████████████████████████████████▏                                                              | 1701/4733 [01:50<02:49, 17.84it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 36%|███████████████████████████████████▎                                                              | 1707/4733 [01:51<02:43, 18.48it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]

 36%|███████████████████████████████████▍                                                              | 1710/4733 [01:51<02:41, 18.75it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 36%|███████████████████████████████████▍                                                              | 1713/4733 [01:51<02:58, 16.88it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 36%|███████████████████████████████████▌                                                              | 1715/4733 [01:52<04:47, 10.49it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 36%|███████████████████████████████████▌                                                              | 1717/4733 [01:52<04:39, 10.79it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 36%|███████████████████████████████████▌                                                              | 1719/4733 [01:52<05:53,  8.53it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 36%|███████████████████████████████████▋                                                              | 1721/4733 [01:53<08:41,  5.77it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 36%|███████████████████████████████████▋                                                              | 1722/4733 [01:53<09:55,  5.05it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 109, 102: 111, 103: 105, 104: 110, 105: 113, 106: 115, 107: 114, 108: 116, 109: 102, 110: 106, 111: 107, 112: 112, 113: 103, 114: 108, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 109, 113, 100, 103, 110, 111, 114, 101, 104, 102, 112, 105, 107, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 36%|███████████████████████████████████▋                                                              | 1723/4733 [01:53<11:08,  4.50it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 36%|███████████████████████████████████▋                                                              | 1726/4733 [01:54<09:13,  5.43it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 36%|███████████████████████████████████▊                                                              | 1727/4733 [01:54<10:46,  4.65it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 37%|███████████████████████████████████▊                                                              | 1728/4733 [01:55<12:06,  4.13it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 37%|███████████████████████████████████▊                                                              | 1729/4733 [01:55<13:13,  3.78it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 37%|███████████████████████████████████▊                                                              | 1730/4733 [01:55<14:06,  3.55it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 37%|███████████████████████████████████▉                                                              | 1734/4733 [01:56<07:52,  6.35it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 55, 63: 58, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 57, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 62, 52, 69, 63, 53, 56, 70, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 55, 63: 58, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 57, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 62, 52, 69, 63, 53, 56, 70, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 37%|███████████████████████████████████▉                                                              | 1736/4733 [01:56<08:23,  5.96it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 43, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 44, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 37%|████████████████████████████████████                                                              | 1740/4733 [01:57<07:30,  6.64it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 105, 105: 107, 106: 109, 107: 111, 108: 113, 109: 110, 110: 112, 111: 114, 112: 116, 113: 115, 114: 117, 115: 102, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 115, 101, 100, 104, 102, 105, 103, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 37%|████████████████████████████████████                                                              | 1744/4733 [01:57<05:57,  8.37it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 59, 58: 55, 59: 58, 60: 62, 61: 67, 62: 69, 63: 66, 64: 61, 65: 65, 66: 68, 67: 70, 68: 72, 69: 73, 70: 71, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 56, 59, 57, 53, 64, 60, 54, 55, 65, 63, 61, 66, 62, 67, 70, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 57, 57: 59, 58: 55, 59: 58, 60: 62, 61: 67, 62: 69, 63: 66, 64: 61, 65: 65, 66: 68, 67: 70, 68: 72, 69: 73, 70: 71, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 58, 52, 56, 59, 57, 53, 64, 60, 54, 55, 65, 63, 61, 66, 62, 67, 70, 68, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 61, 55: 64, 56: 65, 57: 57, 58: 60, 59: 63, 60: 59, 61: 62, 62: 66, 63: 68, 64: 70, 65: 67, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 57, 53, 60, 58, 54, 61, 59, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 61, 55: 64, 56: 65, 57: 57, 58: 60, 59: 63, 60: 59, 61: 62, 62: 66, 63: 68, 64: 70, 65: 67, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 57, 53, 60, 58, 54, 61, 59, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]

 37%|████████████████████████████████████▏                                                             | 1750/4733 [01:57<03:35, 13.86it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 61, 55: 64, 56: 65, 57: 57, 58: 60, 59: 63, 60: 59, 61: 62, 62: 66, 63: 68, 64: 70, 65: 67, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 57, 53, 60, 58, 54, 61, 59, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 61, 55: 64, 56: 65, 57: 57, 58: 60, 59: 63, 60: 59, 61: 62, 62: 66, 63: 68, 64: 70, 65: 67, 66: 69, 67: 71, 68: 73, 69: 72, 70: 74, 71: 56, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 52, 71, 57, 53, 60, 58, 54, 61, 59, 55, 56, 62, 65, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 37%|████████████████████████████████████▎                                                             | 1756/4733 [01:58<02:56, 16.88it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 60, 58: 61, 59: 64, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 58, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 37%|████████████████████████████████████▍                                                             | 1759/4733 [01:58<04:40, 10.59it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]

 37%|████████████████████████████████████▌                                                             | 1764/4733 [01:58<03:32, 13.96it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]

 37%|████████████████████████████████████▌                                                             | 1768/4733 [01:59<03:06, 15.92it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 74, 69: 73, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 62, 52, 71, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 69, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 74, 69: 73, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 62, 52, 71, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 69, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 74, 69: 73, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 62, 52, 71, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 69, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 74, 69: 73, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 62, 52, 71, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 69, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 37%|████████████████████████████████████▋                                                             | 1772/4733 [01:59<04:09, 11.84it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 74, 69: 73, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 62, 52, 71, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 69, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 74, 69: 73, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 62, 52, 71, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 69, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 74, 69: 73, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 62, 52, 71, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 69, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 69, 67: 72, 68: 74, 69: 73, 70: 55, 71: 58, 72: 51, 73: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 72, 73, 50, 51, 70, 62, 52, 71, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 69, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 37%|████████████████████████████████████▋                                                             | 1774/4733 [01:59<04:20, 11.38it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 55, 54: 57, 55: 59, 56: 62, 57: 64, 58: 66, 59: 68, 60: 65, 61: 67, 62: 69, 63: 71, 64: 70, 65: 72, 66: 60, 67: 63, 68: 58, 69: 61, 70: 51, 71: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 70, 71, 50, 51, 53, 52, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 5, 3: 6, 4: 7, 5: 8, 6: 9, 7: 3, 8: 4, 9: 11, 10: 12, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 10, 22: 13}
[0, 1, 7, 8, 2, 3, 4, 5, 6, 21, 9, 10, 22, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 5, 3: 6, 4: 7, 5: 8, 6: 9, 7: 3, 8: 4, 9: 11, 10: 12, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 10, 22: 13}
[0, 1, 7, 8, 2, 3, 4, 5, 6, 21, 9, 10, 22, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 5, 3: 6, 4: 7, 5: 8, 6: 9, 7: 3, 8: 4, 9: 11, 10: 12, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 10, 22: 13}
[0, 1, 7, 8, 2, 3, 4, 5, 6, 21, 9, 10, 22, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 5, 3: 6, 4: 7, 5: 8, 6: 9, 7: 3, 8: 4, 9: 11, 10: 12, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 10, 22: 13}
[0, 1, 7, 8, 2, 3, 4, 5, 6, 21, 9, 10, 22, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 5, 3: 6, 4: 7, 5: 8, 6: 9, 7: 3, 8: 4, 9: 11, 10: 12, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 10, 22: 13}
[0, 1, 7, 8, 2, 3, 4, 5, 6, 21, 9, 10, 22, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 5, 3: 6, 4: 7, 5: 8, 6: 9, 7: 3, 8: 4, 9: 11, 10: 12, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 10, 22: 13}
[0, 1, 7, 8, 2, 3, 4, 5, 6, 21, 9, 10, 22, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 5, 3: 6, 4: 7, 5: 8, 6: 9, 7: 3, 8: 4, 9: 11, 10: 12, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 10, 22: 13}
[0, 1, 7, 8, 2, 3, 4, 5, 6, 21, 9, 10, 22, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 5, 3: 6, 4: 7, 5: 8, 6: 9, 7: 3, 8: 4, 9: 11, 10: 12, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 10, 22: 13}
[0, 1, 7, 8, 2, 3, 4, 5, 6, 21, 9, 10, 22, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 3, 4]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 38%|████████████████████████████████████▉                                                             | 1783/4733 [02:00<02:41, 18.30it/s]

{0: 1, 1: 2, 2: 5, 3: 6, 4: 7, 5: 8, 6: 9, 7: 3, 8: 4, 9: 11, 10: 12, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 10, 22: 13}
[0, 1, 7, 8, 2, 3, 4, 5, 6, 21, 9, 10, 22, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 5, 3: 6, 4: 7, 5: 8, 6: 9, 7: 3, 8: 4, 9: 11, 10: 12, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 10, 22: 13}
[0, 1, 7, 8, 2, 3, 4, 5, 6, 21, 9, 10, 22, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 5, 3: 6, 4: 7, 5: 8, 6: 9, 7: 3, 8: 4, 9: 11, 10: 12, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 10, 22: 13}
[0, 1, 7, 8, 2, 3, 4, 5, 6, 21, 9, 10, 22, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 5, 3: 6, 4: 7, 5: 8, 6: 9, 7: 3, 8: 4, 9: 11, 10: 12, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 10, 22: 13}
[0, 1, 7, 8, 2, 3, 4, 5, 6, 21, 9, 10, 22, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 55, 63: 58, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 57, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 62, 52, 69, 63, 53, 56, 70, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 63, 55: 65, 56: 60, 57: 64, 58: 67, 59: 70, 60: 68, 61: 71, 62: 55, 63: 58, 64: 62, 65: 66, 66: 69, 67: 72, 68: 73, 69: 57, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 62, 52, 69, 63, 53, 56, 70, 64, 54, 57, 55, 65, 58, 60, 66, 59, 61, 67, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 38%|█████████████████████████████████████                                                             | 1787/4733 [02:00<02:23, 20.55it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 38%|█████████████████████████████████████                                                             | 1790/4733 [02:00<03:51, 12.69it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 38%|█████████████████████████████████████                                                             | 1792/4733 [02:01<06:26,  7.61it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 38%|█████████████████████████████████████▏                                                            | 1794/4733 [02:02<08:46,  5.58it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 38%|█████████████████████████████████████▏                                                            | 1796/4733 [02:02<08:53,  5.51it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 68, 59: 70, 60: 69, 61: 71, 62: 56, 63: 59, 64: 62, 65: 66, 66: 67, 67: 55, 68: 58, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 67, 62, 52, 68, 63, 53, 56, 64, 54, 57, 55, 65, 66, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 38%|█████████████████████████████████████▏                                                            | 1799/4733 [02:02<08:07,  6.02it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 38%|█████████████████████████████████████▎                                                            | 1801/4733 [02:03<08:12,  5.96it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 38%|█████████████████████████████████████▎                                                            | 1803/4733 [02:03<09:07,  5.36it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 38%|█████████████████████████████████████▎                                                            | 1804/4733 [02:04<10:47,  4.52it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 38%|█████████████████████████████████████▍                                                            | 1809/4733 [02:04<06:15,  7.78it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]

 38%|█████████████████████████████████████▌                                                            | 1815/4733 [02:04<03:49, 12.74it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 37, 34: 39, 35: 41, 36: 38, 37: 40, 38: 42, 39: 44, 40: 43, 41: 45, 42: 35, 43: 31, 44: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 37, 34: 39, 35: 41, 36: 38, 37: 40, 38: 42, 39: 44, 40: 43, 41: 45, 42: 35, 43: 31, 44: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 43, 31, 30, 44, 42, 32, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 58, 65: 61, 66: 64, 67: 68, 68: 69, 69: 56, 70: 59, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 69, 53, 64, 70, 54, 65, 55, 58, 66, 56, 59, 57, 67, 68, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 70, 61: 72, 62: 71, 63: 73, 64: 58, 65: 61, 66: 64, 67: 68, 68: 69, 69: 56, 70: 59, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 69, 53, 64, 70, 54, 65, 55, 58, 66, 56, 59, 57, 67, 68, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 64, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 58, 69: 62, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 68, 55, 56, 67, 69, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 64, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 61, 68: 58, 69: 62, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 68, 55, 56, 67, 69, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 69, 61: 71, 62: 72, 63: 70, 64: 73, 65: 59, 66: 61, 67: 64, 68: 68, 69: 56, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 69, 53, 70, 65, 54, 66, 55, 58, 67, 56, 59, 57, 68, 60, 63, 61, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 65, 57: 67, 58: 63, 59: 66, 60: 69, 61: 71, 62: 72, 63: 70, 64: 73, 65: 59, 66: 61, 67: 64, 68: 68, 69: 56, 70: 58, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 69, 53, 70, 65, 54, 66, 55, 58, 67, 56, 59, 57, 68, 60, 63, 61, 62, 64]
[1, 49, 50]

 38%|█████████████████████████████████████▋                                                            | 1820/4733 [02:05<02:59, 16.20it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 39%|█████████████████████████████████████▊                                                            | 1825/4733 [02:05<02:51, 16.94it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 64, 55: 66, 56: 61, 57: 65, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 63, 65: 55, 66: 58, 67: 62, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 62, 52, 66, 63, 53, 56, 67, 64, 54, 57, 55, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 9, 11: 12, 12: 14, 13: 17, 14: 19, 15: 16, 16: 13, 17: 15, 18: 18, 19: 20, 20: 22, 21: 23, 22: 21}
[0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 9, 11, 16, 12, 17, 15, 13, 18, 14, 19, 22, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 9, 11: 12, 12: 14, 13: 17, 14: 19, 15: 16, 16: 13, 17: 15, 18: 18, 19: 20, 20: 22, 21: 23, 22: 21}
[0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 9, 11, 16, 12, 17, 15, 13, 18, 14, 19, 22, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 9, 11: 12, 12: 14, 13: 17, 14: 19, 15: 16, 16: 13, 17: 15, 18: 18, 19: 20, 20: 22, 21: 23, 22: 21}
[0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 9, 11, 16, 12, 17, 15, 13, 18, 14, 19, 22, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 9, 11: 12, 12: 14, 13: 17, 14: 19, 15: 16, 16: 13, 17: 15, 18: 18, 19: 20, 20: 22, 21: 23, 22: 21}
[0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 9, 11, 16, 12, 17, 15, 13, 18, 14, 19, 22, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]

 39%|█████████████████████████████████████▊                                                            | 1828/4733 [02:05<03:01, 16.04it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 9, 11: 12, 12: 14, 13: 17, 14: 19, 15: 16, 16: 13, 17: 15, 18: 18, 19: 20, 20: 22, 21: 23, 22: 21}
[0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 9, 11, 16, 12, 17, 15, 13, 18, 14, 19, 22, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 9, 11: 12, 12: 14, 13: 17, 14: 19, 15: 16, 16: 13, 17: 15, 18: 18, 19: 20, 20: 22, 21: 23, 22: 21}
[0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 9, 11, 16, 12, 17, 15, 13, 18, 14, 19, 22, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]

 39%|██████████████████████████████████████                                                            | 1837/4733 [02:05<02:02, 23.69it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 8, 12: 12, 13: 15, 14: 18, 15: 17, 16: 14, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 9, 10, 12, 8, 16, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 8, 12: 12, 13: 15, 14: 18, 15: 17, 16: 14, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 9, 10, 12, 8, 16, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 8, 12: 12, 13: 15, 14: 18, 15: 17, 16: 14, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 9, 10, 12, 8, 16, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 8, 12: 12, 13: 15, 14: 18, 15: 17, 16: 14, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 9, 10, 12, 8, 16, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 9, 11: 12, 12: 14, 13: 17, 14: 19, 15: 16, 16: 13, 17: 15, 18: 18, 19: 20, 20: 22, 21: 23, 22: 21}
[0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 9, 11, 16, 12, 17, 15, 13, 18, 14, 19, 22, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 9, 11: 12, 12: 14, 13: 17, 14: 19, 15: 16, 16: 13, 17: 15, 18: 18, 19: 20, 20: 22, 21: 23, 22: 21}
[0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 9, 11, 16, 12, 17, 15, 13, 18, 14, 19, 22, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]

 39%|██████████████████████████████████████                                                            | 1841/4733 [02:06<01:53, 25.52it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 9, 11: 12, 12: 14, 13: 17, 14: 19, 15: 16, 16: 13, 17: 15, 18: 18, 19: 20, 20: 22, 21: 23, 22: 21}
[0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 9, 11, 16, 12, 17, 15, 13, 18, 14, 19, 22, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 9, 11: 12, 12: 14, 13: 17, 14: 19, 15: 16, 16: 13, 17: 15, 18: 18, 19: 20, 20: 22, 21: 23, 22: 21}
[0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 9, 11, 16, 12, 17, 15, 13, 18, 14, 19, 22, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 8, 12: 12, 13: 15, 14: 18, 15: 17, 16: 14, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 9, 10, 12, 8, 16, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 8, 12: 12, 13: 15, 14: 18, 15: 17, 16: 14, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 9, 10, 12, 8, 16, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 8, 12: 12, 13: 15, 14: 18, 15: 17, 16: 14, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 9, 10, 12, 8, 16, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 8, 12: 12, 13: 15, 14: 18, 15: 17, 16: 14, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 9, 10, 12, 8, 16, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 8, 12: 12, 13: 15, 14: 18, 15: 17, 16: 14, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 9, 10, 12, 8, 16, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 8, 12: 12, 13: 15, 14: 18, 15: 17, 16: 14, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 9, 10, 12, 8, 16, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]

 39%|██████████████████████████████████████▏                                                           | 1845/4733 [02:06<01:47, 26.84it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 39%|██████████████████████████████████████▎                                                           | 1848/4733 [02:06<02:56, 16.35it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 4, 3, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]

 39%|██████████████████████████████████████▎                                                           | 1851/4733 [02:07<04:32, 10.57it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 39%|██████████████████████████████████████▍                                                           | 1856/4733 [02:07<04:15, 11.28it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 8, 12: 12, 13: 15, 14: 18, 15: 17, 16: 14, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 9, 10, 12, 8, 16, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 8, 12: 12, 13: 15, 14: 18, 15: 17, 16: 14, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 9, 10, 12, 8, 16, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 39%|██████████████████████████████████████▍                                                           | 1859/4733 [02:07<03:36, 13.24it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]

 39%|██████████████████████████████████████▌                                                           | 1861/4733 [02:07<03:49, 12.50it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 39%|██████████████████████████████████████▋                                                           | 1866/4733 [02:08<03:53, 12.26it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]

 39%|██████████████████████████████████████▋                                                           | 1869/4733 [02:08<03:13, 14.81it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 40%|██████████████████████████████████████▊                                                           | 1873/4733 [02:08<03:51, 12.34it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]

 40%|██████████████████████████████████████▊                                                           | 1875/4733 [02:09<04:05, 11.65it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 40%|██████████████████████████████████████▉                                                           | 1879/4733 [02:09<04:59,  9.51it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 9, 11: 12, 12: 14, 13: 17, 14: 19, 15: 16, 16: 13, 17: 15, 18: 18, 19: 20, 20: 22, 21: 23, 22: 21}
[0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 9, 11, 16, 12, 17, 15, 13, 18, 14, 19, 22, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 9, 11: 12, 12: 14, 13: 17, 14: 19, 15: 16, 16: 13, 17: 15, 18: 18, 19: 20, 20: 22, 21: 23, 22: 21}
[0, 1, 2, 3, 4, 5, 6, 7, 10, 8, 9, 11, 16, 12, 17, 15, 13, 18, 14, 19, 22, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]

 40%|██████████████████████████████████████▉                                                           | 1881/4733 [02:09<04:15, 11.18it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]

 40%|███████████████████████████████████████                                                           | 1885/4733 [02:10<04:25, 10.71it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 56, 56: 58, 57: 61, 58: 64, 59: 66, 60: 63, 61: 60, 62: 62, 63: 65, 64: 67, 65: 69, 66: 70, 67: 68, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 55, 53, 56, 54, 61, 57, 62, 60, 58, 63, 59, 64, 67, 65, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 40%|███████████████████████████████████████▏                                                          | 1890/4733 [02:10<04:05, 11.58it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 40%|███████████████████████████████████████▏                                                          | 1895/4733 [02:10<03:12, 14.76it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 58, 59: 62, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 61, 70: 64, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 58, 59: 62, 60: 65, 61: 67, 62: 69, 63: 66, 64: 68, 65: 70, 66: 72, 67: 71, 68: 73, 69: 61, 70: 64, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 40%|███████████████████████████████████████▍                                                          | 1902/4733 [02:11<02:29, 18.94it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 59, 57: 55, 58: 58, 59: 61, 60: 65, 61: 67, 62: 62, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 57, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 57, 52, 68, 58, 56, 53, 59, 62, 54, 55, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 60, 54: 63, 55: 64, 56: 59, 57: 55, 58: 58, 59: 61, 60: 65, 61: 67, 62: 62, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 57, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 57, 52, 68, 58, 56, 53, 59, 62, 54, 55, 60, 63, 61, 64, 66, 65, 67]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 40%|███████████████████████████████████████▍                                                          | 1907/4733 [02:11<03:25, 13.73it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 57, 66: 60, 67: 62, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 65, 53, 64, 66, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 59, 65: 57, 66: 60, 67: 62, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 65, 53, 64, 66, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 59, 56: 61, 57: 63, 58: 66, 59: 60, 60: 62, 61: 64, 62: 67, 63: 69, 64: 65, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 54, 55, 59, 56, 60, 57, 61, 64, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 59, 56: 61, 57: 63, 58: 66, 59: 60, 60: 62, 61: 64, 62: 67, 63: 69, 64: 65, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 54, 55, 59, 56, 60, 57, 61, 64, 58, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 67, 60: 71, 61: 59, 62: 61, 63: 63, 64: 68, 65: 70, 66: 64, 67: 69, 68: 72, 69: 74, 70: 73, 71: 75, 72: 56, 73: 51, 74: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 73, 74, 50, 51, 52, 72, 54, 53, 61, 55, 62, 56, 63, 66, 57, 58, 59, 64, 67, 65, 60, 68, 70, 69, 71]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 58, 54: 57, 55: 60, 56: 62, 57: 65, 58: 66, 59: 67, 60: 71, 61: 59, 62: 61, 63: 63, 64: 68, 65: 70, 66: 64, 67: 69, 68: 72, 69: 74, 70: 73, 71: 75, 72: 56, 73: 51, 74: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 73, 74, 50, 51, 52, 72, 54, 53, 61, 55, 62, 56, 63, 66, 57, 58, 59, 64, 67, 65, 60, 68, 70, 69, 71]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 66, 55: 56, 56: 60, 57: 64, 58: 67, 59: 69, 60: 65, 61: 68, 62: 70, 63: 72, 64: 71, 65: 73, 66: 59, 67: 55, 68: 58, 69: 62, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 67, 55, 52, 68, 66, 56, 53, 69, 70, 57, 60, 54, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 66, 55: 56, 56: 60, 57: 64, 58: 67, 59: 69, 60: 65, 61: 68, 62: 70, 63: 72, 64: 71, 65: 73, 66: 59, 67: 55, 68: 58, 69: 62, 70: 63, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 67, 55, 52, 68, 66, 56, 53, 69, 70, 57, 60, 54, 58, 61, 59, 62, 64, 63, 65]
[1, 49, 50]

 40%|███████████████████████████████████████▌                                                          | 1911/4733 [02:11<02:58, 15.82it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 61, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 58, 65: 55, 66: 57, 67: 60, 68: 62, 69: 65, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 52, 66, 64, 53, 67, 54, 68, 55, 58, 69, 70, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 61, 55: 63, 56: 67, 57: 69, 58: 64, 59: 68, 60: 70, 61: 72, 62: 71, 63: 73, 64: 58, 65: 55, 66: 57, 67: 60, 68: 62, 69: 65, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 65, 52, 66, 64, 53, 67, 54, 68, 55, 58, 69, 70, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]

 40%|███████████████████████████████████████▌                                                          | 1913/4733 [02:11<02:48, 16.73it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 61, 56: 63, 57: 66, 58: 65, 59: 62, 60: 64, 61: 67, 62: 69, 63: 68, 64: 70, 65: 59, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 53, 52, 67, 65, 54, 55, 59, 56, 60, 58, 57, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 40%|███████████████████████████████████████▋                                                          | 1916/4733 [02:12<04:11, 11.20it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 62, 66: 57, 67: 59, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 58, 54: 61, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 62, 66: 57, 67: 59, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 41%|███████████████████████████████████████▊                                                          | 1921/4733 [02:12<04:17, 10.93it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 41%|███████████████████████████████████████▊                                                          | 1923/4733 [02:13<04:19, 10.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 58, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 58, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]

 41%|███████████████████████████████████████▉                                                          | 1929/4733 [02:13<03:19, 14.05it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 41%|████████████████████████████████████████                                                          | 1934/4733 [02:13<03:39, 12.74it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 41%|████████████████████████████████████████▏                                                         | 1940/4733 [02:14<02:37, 17.69it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 41%|████████████████████████████████████████▏                                                         | 1943/4733 [02:14<02:26, 19.02it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 41%|████████████████████████████████████████▎                                                         | 1946/4733 [02:14<03:42, 12.50it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 41%|████████████████████████████████████████▍                                                         | 1951/4733 [02:15<03:51, 12.03it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 4, 17: 7, 18: 10, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 4, 17: 7, 18: 10, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 41%|████████████████████████████████████████▍                                                         | 1955/4733 [02:15<02:57, 15.66it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 41%|████████████████████████████████████████▌                                                         | 1962/4733 [02:15<02:16, 20.37it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 4, 17: 7, 18: 10, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 4, 17: 7, 18: 10, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 4, 17: 7, 18: 10, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 4, 17: 7, 18: 10, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 42%|████████████████████████████████████████▋                                                         | 1965/4733 [02:15<02:08, 21.48it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 42%|████████████████████████████████████████▋                                                         | 1968/4733 [02:16<03:45, 12.28it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 57, 58: 54, 59: 58, 60: 60, 61: 63, 62: 65, 63: 61, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 58, 53, 54, 57, 59, 55, 60, 63, 56, 61, 64, 62, 65, 67, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 57, 58: 54, 59: 58, 60: 60, 61: 63, 62: 65, 63: 61, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 58, 53, 54, 57, 59, 55, 60, 63, 56, 61, 64, 62, 65, 67, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 57, 58: 54, 59: 58, 60: 60, 61: 63, 62: 65, 63: 61, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 58, 53, 54, 57, 59, 55, 60, 63, 56, 61, 64, 62, 65, 67, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 57, 58: 54, 59: 58, 60: 60, 61: 63, 62: 65, 63: 61, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 58, 53, 54, 57, 59, 55, 60, 63, 56, 61, 64, 62, 65, 67, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]

 42%|████████████████████████████████████████▊                                                         | 1970/4733 [02:16<03:53, 11.82it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 42%|████████████████████████████████████████▊                                                         | 1973/4733 [02:16<04:42,  9.76it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 42%|████████████████████████████████████████▉                                                         | 1978/4733 [02:17<05:03,  9.08it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 58, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 58, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 58, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 58, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]

 42%|████████████████████████████████████████▉                                                         | 1980/4733 [02:17<04:53,  9.38it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 57, 58: 54, 59: 58, 60: 60, 61: 63, 62: 65, 63: 61, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 58, 53, 54, 57, 59, 55, 60, 63, 56, 61, 64, 62, 65, 67, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 56, 55: 59, 56: 62, 57: 57, 58: 54, 59: 58, 60: 60, 61: 63, 62: 65, 63: 61, 64: 64, 65: 66, 66: 68, 67: 67, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 58, 53, 54, 57, 59, 55, 60, 63, 56, 61, 64, 62, 65, 67, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 42%|█████████████████████████████████████████                                                         | 1985/4733 [02:17<03:41, 12.40it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 18, 11: 17, 12: 19, 13: 5, 14: 8, 15: 11, 16: 15, 17: 4, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 10, 12, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 18, 11: 17, 12: 19, 13: 5, 14: 8, 15: 11, 16: 15, 17: 4, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 10, 12, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 42%|█████████████████████████████████████████▏                                                        | 1991/4733 [02:18<03:50, 11.89it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 42%|█████████████████████████████████████████▎                                                        | 1996/4733 [02:18<03:13, 14.13it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 18, 11: 17, 12: 19, 13: 5, 14: 8, 15: 11, 16: 15, 17: 4, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 10, 12, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 18, 11: 17, 12: 19, 13: 5, 14: 8, 15: 11, 16: 15, 17: 4, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 10, 12, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]

 42%|█████████████████████████████████████████▍                                                        | 1999/4733 [02:18<02:46, 16.45it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 18, 11: 17, 12: 19, 13: 5, 14: 8, 15: 11, 16: 15, 17: 4, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 10, 12, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 18, 11: 17, 12: 19, 13: 5, 14: 8, 15: 11, 16: 15, 17: 4, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 10, 12, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 42%|█████████████████████████████████████████▍                                                        | 2001/4733 [02:19<04:07, 11.02it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 42%|█████████████████████████████████████████▍                                                        | 2003/4733 [02:19<04:10, 10.92it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 42%|█████████████████████████████████████████▌                                                        | 2007/4733 [02:20<05:01,  9.03it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]

 42%|█████████████████████████████████████████▌                                                        | 2010/4733 [02:20<04:18, 10.53it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 43%|█████████████████████████████████████████▋                                                        | 2014/4733 [02:20<03:08, 14.44it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 43%|█████████████████████████████████████████▋                                                        | 2016/4733 [02:20<03:26, 13.17it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 43%|█████████████████████████████████████████▊                                                        | 2018/4733 [02:20<03:41, 12.23it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 43%|█████████████████████████████████████████▊                                                        | 2022/4733 [02:21<04:15, 10.60it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 43%|█████████████████████████████████████████▉                                                        | 2027/4733 [02:21<03:44, 12.05it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 43%|██████████████████████████████████████████                                                        | 2029/4733 [02:21<03:55, 11.48it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 43%|██████████████████████████████████████████                                                        | 2034/4733 [02:22<03:52, 11.59it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 43%|██████████████████████████████████████████▏                                                       | 2037/4733 [02:22<03:13, 13.97it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 43%|██████████████████████████████████████████▎                                                       | 2042/4733 [02:22<03:28, 12.93it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 43%|██████████████████████████████████████████▎                                                       | 2045/4733 [02:23<02:53, 15.53it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 43%|██████████████████████████████████████████▍                                                       | 2051/4733 [02:23<03:21, 13.31it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 43%|██████████████████████████████████████████▌                                                       | 2053/4733 [02:23<04:30,  9.89it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 43%|██████████████████████████████████████████▌                                                       | 2058/4733 [02:24<04:25, 10.09it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 44%|██████████████████████████████████████████▋                                                       | 2064/4733 [02:24<02:58, 14.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 44%|██████████████████████████████████████████▊                                                       | 2067/4733 [02:24<02:43, 16.29it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 44%|██████████████████████████████████████████▉                                                       | 2072/4733 [02:25<02:42, 16.38it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 44%|██████████████████████████████████████████▉                                                       | 2074/4733 [02:25<02:35, 17.12it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 44%|███████████████████████████████████████████                                                       | 2079/4733 [02:25<03:22, 13.09it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 44%|███████████████████████████████████████████▏                                                      | 2085/4733 [02:26<02:36, 16.93it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 44%|███████████████████████████████████████████▎                                                      | 2090/4733 [02:26<03:20, 13.17it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 44%|███████████████████████████████████████████▎                                                      | 2092/4733 [02:26<03:32, 12.42it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 44%|███████████████████████████████████████████▍                                                      | 2097/4733 [02:27<03:08, 13.99it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 44%|███████████████████████████████████████████▌                                                      | 2102/4733 [02:27<02:46, 15.80it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 72, 71: 71, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 71, 70, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 72, 71: 71, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 71, 70, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 73]

 44%|███████████████████████████████████████████▌                                                      | 2104/4733 [02:27<03:10, 13.82it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 44%|███████████████████████████████████████████▌                                                      | 2106/4733 [02:28<05:03,  8.64it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 72, 71: 71, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 71, 70, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 72, 71: 71, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 71, 70, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 73]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 72, 71: 71, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 71, 70, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 72, 71: 71, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 71, 70, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 73]

 45%|███████████████████████████████████████████▋                                                      | 2112/4733 [02:28<03:21, 13.03it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 45%|███████████████████████████████████████████▊                                                      | 2114/4733 [02:28<03:21, 12.97it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 45%|███████████████████████████████████████████▊                                                      | 2116/4733 [02:29<05:04,  8.59it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 45%|███████████████████████████████████████████▊                                                      | 2118/4733 [02:29<05:41,  7.65it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]

 45%|███████████████████████████████████████████▉                                                      | 2124/4733 [02:29<03:42, 11.71it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 47, 35: 43, 36: 46, 37: 39, 38: 42, 39: 45, 40: 48, 41: 49, 42: 33, 43: 30, 44: 32, 45: 35, 46: 36, 47: 40, 48: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 43, 29, 44, 42, 30, 45, 46, 48, 31, 37, 47, 32, 38, 35, 33, 39, 36, 34, 40, 41]
[1, 2, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 45%|████████████████████████████████████████████                                                      | 2127/4733 [02:29<03:28, 12.50it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 45%|████████████████████████████████████████████                                                      | 2129/4733 [02:30<05:03,  8.58it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 66, 60: 68, 61: 63, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 59, 62, 60, 63, 65, 64, 66, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 66, 60: 68, 61: 63, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 59, 62, 60, 63, 65, 64, 66, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 73]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 45%|████████████████████████████████████████████                                                      | 2131/4733 [02:30<06:21,  6.82it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 66, 60: 68, 61: 63, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 59, 62, 60, 63, 65, 64, 66, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 66, 60: 68, 61: 63, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 59, 62, 60, 63, 65, 64, 66, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 66, 60: 68, 61: 63, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 59, 62, 60, 63, 65, 64, 66, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 62, 59: 66, 60: 68, 61: 63, 62: 67, 63: 69, 64: 71, 65: 70, 66: 72, 67: 54, 68: 58, 69: 61, 70: 64, 71: 65, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 69, 58, 61, 70, 71, 59, 62, 60, 63, 65, 64, 66, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 73]

 45%|████████████████████████████████████████████▏                                                     | 2133/4733 [02:31<06:08,  7.05it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 7, 5: 6, 6: 9, 7: 11, 8: 14, 9: 15, 10: 8, 11: 10, 12: 12, 13: 16, 14: 18, 15: 13, 16: 17, 17: 19, 18: 21, 19: 20, 20: 22, 21: 5, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 21, 5, 4, 10, 6, 11, 7, 12, 15, 8, 9, 13, 16, 14, 17, 19, 18, 20, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 45%|████████████████████████████████████████████▎                                                     | 2138/4733 [02:31<04:30,  9.60it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 56, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 55, 66: 58, 67: 61, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 65, 53, 52, 66, 64, 54, 67, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 45%|████████████████████████████████████████████▍                                                     | 2144/4733 [02:32<03:29, 12.35it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 60, 57: 63, 58: 66, 59: 61, 60: 58, 61: 62, 62: 64, 63: 67, 64: 69, 65: 65, 66: 68, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 45%|████████████████████████████████████████████▍                                                     | 2148/4733 [02:32<03:27, 12.48it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 46%|████████████████████████████████████████████▌                                                     | 2154/4733 [02:32<02:32, 16.88it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 46%|████████████████████████████████████████████▋                                                     | 2159/4733 [02:33<02:39, 16.15it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]

 46%|████████████████████████████████████████████▊                                                     | 2162/4733 [02:33<02:35, 16.51it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]

 46%|████████████████████████████████████████████▉                                                     | 2170/4733 [02:33<01:38, 25.95it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 39, 36: 43, 37: 45, 38: 40, 39: 44, 40: 46, 41: 48, 42: 47, 43: 49, 44: 31, 45: 35, 46: 38, 47: 41, 48: 42}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 46, 35, 38, 47, 48, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 46%|█████████████████████████████████████████████                                                     | 2176/4733 [02:33<02:05, 20.34it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]

 46%|█████████████████████████████████████████████                                                     | 2179/4733 [02:34<01:58, 21.54it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 56, 66: 58, 67: 61, 68: 65, 69: 69, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 64, 54, 67, 70, 55, 58, 68, 56, 59, 57, 69, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 70, 61: 72, 62: 71, 63: 73, 64: 59, 65: 56, 66: 58, 67: 61, 68: 65, 69: 69, 70: 62, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 65, 53, 66, 64, 54, 67, 70, 55, 58, 68, 56, 59, 57, 69, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 46%|█████████████████████████████████████████████▏                                                    | 2182/4733 [02:34<02:46, 15.36it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 46%|█████████████████████████████████████████████▎                                                    | 2187/4733 [02:34<02:26, 17.33it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 46%|█████████████████████████████████████████████▍                                                    | 2193/4733 [02:34<02:03, 20.55it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 67, 58: 69, 59: 64, 60: 68, 61: 70, 62: 72, 63: 71, 64: 73, 65: 60, 66: 61, 67: 58, 68: 62, 69: 65, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 67, 55, 65, 66, 68, 56, 59, 69, 70, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 59, 56: 63, 57: 67, 58: 69, 59: 64, 60: 68, 61: 70, 62: 72, 63: 71, 64: 73, 65: 60, 66: 61, 67: 58, 68: 62, 69: 65, 70: 66, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 67, 55, 65, 66, 68, 56, 59, 69, 70, 57, 60, 58, 61, 63, 62, 64]
[1, 49, 50]

 46%|█████████████████████████████████████████████▍                                                    | 2196/4733 [02:34<02:05, 20.22it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 56, 55: 60, 56: 64, 57: 68, 58: 69, 59: 59, 60: 55, 61: 58, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 60, 54, 52, 61, 59, 55, 53, 62, 65, 56, 63, 66, 64, 57, 58, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 61, 54: 56, 55: 60, 56: 64, 57: 68, 58: 69, 59: 59, 60: 55, 61: 58, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 70, 68: 72, 69: 71, 70: 73, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 60, 54, 52, 61, 59, 55, 53, 62, 65, 56, 63, 66, 64, 57, 58, 67, 69, 68, 70]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 61, 56: 64, 57: 59, 58: 62, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 54, 57, 59, 55, 58, 60, 56, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 58, 55: 61, 56: 64, 57: 59, 58: 62, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 66, 65: 68, 66: 70, 67: 72, 68: 71, 69: 73, 70: 56, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 70, 53, 54, 57, 59, 55, 58, 60, 56, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 69, 61: 71, 62: 72, 63: 70, 64: 73, 65: 59, 66: 62, 67: 56, 68: 58, 69: 61, 70: 65, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 67, 53, 68, 65, 54, 69, 66, 55, 58, 70, 56, 59, 57, 60, 63, 61, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 63, 56: 66, 57: 68, 58: 64, 59: 67, 60: 69, 61: 71, 62: 72, 63: 70, 64: 73, 65: 59, 66: 62, 67: 56, 68: 58, 69: 61, 70: 65, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 67, 53, 68, 65, 54, 69, 66, 55, 58, 70, 56, 59, 57, 60, 63, 61, 62, 64]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 47%|█████████████████████████████████████████████▋                                                    | 2204/4733 [02:35<02:54, 14.47it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 47%|█████████████████████████████████████████████▊                                                    | 2211/4733 [02:36<02:24, 17.41it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 11, 10: 15, 11: 18, 12: 20, 13: 22, 14: 21, 15: 23, 16: 19, 17: 16, 18: 8, 19: 12, 20: 10, 21: 14, 22: 17}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 9, 19, 8, 21, 10, 17, 22, 11, 16, 12, 14, 13, 15]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 11, 10: 15, 11: 18, 12: 20, 13: 22, 14: 21, 15: 23, 16: 19, 17: 16, 18: 8, 19: 12, 20: 10, 21: 14, 22: 17}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 9, 19, 8, 21, 10, 17, 22, 11, 16, 12, 14, 13, 15]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 11, 10: 15, 11: 18, 12: 20, 13: 22, 14: 21, 15: 23, 16: 19, 17: 16, 18: 8, 19: 12, 20: 10, 21: 14, 22: 17}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 9, 19, 8, 21, 10, 17, 22, 11, 16, 12, 14, 13, 15]
[1, 2, 5]

 47%|█████████████████████████████████████████████▊                                                    | 2215/4733 [02:36<02:04, 20.23it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 11, 10: 15, 11: 18, 12: 20, 13: 22, 14: 21, 15: 23, 16: 19, 17: 16, 18: 8, 19: 12, 20: 10, 21: 14, 22: 17}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 9, 19, 8, 21, 10, 17, 22, 11, 16, 12, 14, 13, 15]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 11, 10: 15, 11: 18, 12: 20, 13: 22, 14: 21, 15: 23, 16: 19, 17: 16, 18: 8, 19: 12, 20: 10, 21: 14, 22: 17}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 9, 19, 8, 21, 10, 17, 22, 11, 16, 12, 14, 13, 15]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 11, 10: 15, 11: 18, 12: 20, 13: 22, 14: 21, 15: 23, 16: 19, 17: 16, 18: 8, 19: 12, 20: 10, 21: 14, 22: 17}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 9, 19, 8, 21, 10, 17, 22, 11, 16, 12, 14, 13, 15]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]

 47%|█████████████████████████████████████████████▉                                                    | 2221/4733 [02:36<01:58, 21.13it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 47%|██████████████████████████████████████████████                                                    | 2224/4733 [02:36<02:21, 17.78it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 47%|██████████████████████████████████████████████                                                    | 2227/4733 [02:36<02:29, 16.72it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]

 47%|██████████████████████████████████████████████▏                                                   | 2230/4733 [02:37<02:21, 17.63it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 47%|██████████████████████████████████████████████▎                                                   | 2234/4733 [02:37<03:39, 11.40it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 47%|██████████████████████████████████████████████▎                                                   | 2236/4733 [02:37<03:45, 11.08it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 47%|██████████████████████████████████████████████▎                                                   | 2238/4733 [02:38<04:49,  8.63it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 47%|██████████████████████████████████████████████▍                                                   | 2240/4733 [02:38<05:27,  7.62it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 47%|██████████████████████████████████████████████▍                                                   | 2245/4733 [02:38<03:35, 11.54it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 48%|██████████████████████████████████████████████▌                                                   | 2251/4733 [02:39<02:38, 15.62it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 48%|██████████████████████████████████████████████▋                                                   | 2254/4733 [02:39<03:12, 12.85it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 48%|██████████████████████████████████████████████▊                                                   | 2258/4733 [02:39<03:38, 11.31it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 62, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 57, 66: 58, 67: 61, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 65, 66, 53, 64, 67, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 56, 53: 59, 54: 62, 55: 63, 56: 65, 57: 67, 58: 64, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 60, 65: 57, 66: 58, 67: 61, 68: 55, 69: 51, 70: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 69, 70, 50, 51, 68, 52, 65, 66, 53, 64, 67, 54, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 64, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 63, 68: 59, 69: 62, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 68, 56, 70, 69, 67, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 56, 54: 57, 55: 58, 56: 60, 57: 64, 58: 65, 59: 67, 60: 69, 61: 66, 62: 68, 63: 70, 64: 72, 65: 71, 66: 73, 67: 63, 68: 59, 69: 62, 70: 61, 71: 51, 72: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 71, 72, 50, 51, 52, 53, 54, 55, 68, 56, 70, 69, 67, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 48%|██████████████████████████████████████████████▉                                                   | 2264/4733 [02:40<03:14, 12.71it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 11, 10: 15, 11: 18, 12: 20, 13: 22, 14: 21, 15: 23, 16: 19, 17: 16, 18: 8, 19: 12, 20: 10, 21: 14, 22: 17}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 9, 19, 8, 21, 10, 17, 22, 11, 16, 12, 14, 13, 15]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 11, 10: 15, 11: 18, 12: 20, 13: 22, 14: 21, 15: 23, 16: 19, 17: 16, 18: 8, 19: 12, 20: 10, 21: 14, 22: 17}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 9, 19, 8, 21, 10, 17, 22, 11, 16, 12, 14, 13, 15]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 48%|███████████████████████████████████████████████                                                   | 2270/4733 [02:40<02:35, 15.87it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 11, 10: 15, 11: 18, 12: 20, 13: 22, 14: 21, 15: 23, 16: 19, 17: 16, 18: 8, 19: 12, 20: 10, 21: 14, 22: 17}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 9, 19, 8, 21, 10, 17, 22, 11, 16, 12, 14, 13, 15]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 11, 10: 15, 11: 18, 12: 20, 13: 22, 14: 21, 15: 23, 16: 19, 17: 16, 18: 8, 19: 12, 20: 10, 21: 14, 22: 17}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 9, 19, 8, 21, 10, 17, 22, 11, 16, 12, 14, 13, 15]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 11, 10: 15, 11: 18, 12: 20, 13: 22, 14: 21, 15: 23, 16: 19, 17: 16, 18: 8, 19: 12, 20: 10, 21: 14, 22: 17}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 9, 19, 8, 21, 10, 17, 22, 11, 16, 12, 14, 13, 15]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 11, 10: 15, 11: 18, 12: 20, 13: 22, 14: 21, 15: 23, 16: 19, 17: 16, 18: 8, 19: 12, 20: 10, 21: 14, 22: 17}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 9, 19, 8, 21, 10, 17, 22, 11, 16, 12, 14, 13, 15]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 59, 55: 62, 56: 56, 57: 58, 58: 61, 59: 60, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 66, 67: 64, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 56, 53, 57, 54, 59, 58, 55, 60, 67, 61, 66, 62, 64, 63, 65]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]

 48%|███████████████████████████████████████████████▏                                                  | 2276/4733 [02:40<01:43, 23.79it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 48%|███████████████████████████████████████████████▏                                                  | 2280/4733 [02:41<02:34, 15.85it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]

 48%|███████████████████████████████████████████████▎                                                  | 2286/4733 [02:41<02:08, 19.05it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 48%|███████████████████████████████████████████████▍                                                  | 2293/4733 [02:41<02:08, 18.99it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 49%|███████████████████████████████████████████████▌                                                  | 2300/4733 [02:42<02:21, 17.17it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]

 49%|███████████████████████████████████████████████▋                                                  | 2305/4733 [02:42<01:50, 21.98it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 49%|███████████████████████████████████████████████▉                                                  | 2315/4733 [02:42<01:31, 26.53it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]

 49%|████████████████████████████████████████████████                                                  | 2319/4733 [02:42<01:24, 28.44it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 49%|████████████████████████████████████████████████▎                                                 | 2333/4733 [02:43<01:06, 35.96it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 49%|████████████████████████████████████████████████▍                                                 | 2338/4733 [02:44<02:38, 15.15it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 49%|████████████████████████████████████████████████▍                                                 | 2342/4733 [02:44<02:56, 13.56it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▌                                                 | 2345/4733 [02:45<05:01,  7.92it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▌                                                 | 2348/4733 [02:45<04:59,  7.96it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▋                                                 | 2350/4733 [02:46<06:27,  6.14it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▋                                                 | 2352/4733 [02:47<07:53,  5.03it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▋                                                 | 2353/4733 [02:47<08:36,  4.61it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▋                                                 | 2354/4733 [02:47<09:21,  4.24it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▊                                                 | 2357/4733 [02:48<07:33,  5.24it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▊                                                 | 2358/4733 [02:48<08:27,  4.68it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|████████████████████████████████████████████████▉                                                 | 2361/4733 [02:48<06:56,  5.70it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|█████████████████████████████████████████████████                                                 | 2372/4733 [02:49<03:04, 12.80it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 118, 115: 119, 116: 103, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 116, 110, 100, 103, 117, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108, 114, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 118, 115: 119, 116: 103, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 116, 110, 100, 103, 117, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108, 114, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|█████████████████████████████████████████████████▏                                                | 2375/4733 [02:49<03:30, 11.22it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 118, 115: 119, 116: 103, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 116, 110, 100, 103, 117, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108, 114, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 118, 115: 119, 116: 103, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 116, 110, 100, 103, 117, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108, 114, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 118, 115: 119, 116: 103, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 116, 110, 100, 103, 117, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108, 114, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 118, 115: 119, 116: 103, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 116, 110, 100, 103, 117, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108, 114, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|█████████████████████████████████████████████████▏                                                | 2377/4733 [02:50<05:19,  7.38it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 118, 115: 119, 116: 103, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 116, 110, 100, 103, 117, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108, 114, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 118, 115: 119, 116: 103, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 116, 110, 100, 103, 117, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108, 114, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|█████████████████████████████████████████████████▍                                                | 2386/4733 [02:50<03:03, 12.80it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 118, 115: 119, 116: 103, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 116, 110, 100, 103, 117, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108, 114, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 118, 115: 119, 116: 103, 117: 107, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 116, 110, 100, 103, 117, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108, 114, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 50%|█████████████████████████████████████████████████▍                                                | 2390/4733 [02:51<03:19, 11.72it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|█████████████████████████████████████████████████▌                                                | 2393/4733 [02:52<05:45,  6.78it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 111, 107: 114, 108: 115, 109: 105, 110: 108, 111: 112, 112: 116, 113: 118, 114: 113, 115: 117, 116: 119, 117: 121, 118: 120, 119: 122, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 109, 101, 105, 110, 102, 103, 106, 111, 114, 107, 108, 112, 115, 113, 116, 118, 117, 119]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|█████████████████████████████████████████████████▌                                                | 2395/4733 [02:52<05:59,  6.50it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|█████████████████████████████████████████████████▋                                                | 2399/4733 [02:53<05:16,  7.38it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|█████████████████████████████████████████████████▊                                                | 2405/4733 [02:53<04:12,  9.21it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|█████████████████████████████████████████████████▊                                                | 2407/4733 [02:53<04:39,  8.31it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|█████████████████████████████████████████████████▉                                                | 2409/4733 [02:54<05:02,  7.67it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|█████████████████████████████████████████████████▉                                                | 2411/4733 [02:54<05:26,  7.11it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|█████████████████████████████████████████████████▉                                                | 2412/4733 [02:54<06:28,  5.98it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|█████████████████████████████████████████████████▉                                                | 2413/4733 [02:55<07:32,  5.13it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|█████████████████████████████████████████████████▉                                                | 2414/4733 [02:55<08:34,  4.51it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|██████████████████████████████████████████████████                                                | 2417/4733 [02:56<06:52,  5.62it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|██████████████████████████████████████████████████                                                | 2418/4733 [02:56<07:57,  4.85it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|██████████████████████████████████████████████████                                                | 2419/4733 [02:56<08:59,  4.29it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|██████████████████████████████████████████████████                                                | 2420/4733 [02:57<09:53,  3.90it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 116, 106: 112, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 106, 110, 113, 111, 105, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|██████████████████████████████████████████████████▎                                               | 2427/4733 [02:57<03:57,  9.69it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 116, 105: 118, 106: 117, 107: 119, 108: 112, 109: 114, 110: 109, 111: 113, 112: 105, 113: 107, 114: 110, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 113, 102, 110, 114, 103, 108, 111, 109, 115, 104, 106, 105, 107]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 116, 105: 118, 106: 117, 107: 119, 108: 112, 109: 114, 110: 109, 111: 113, 112: 105, 113: 107, 114: 110, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 113, 102, 110, 114, 103, 108, 111, 109, 115, 104, 106, 105, 107]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|██████████████████████████████████████████████████▎                                               | 2431/4733 [02:57<03:51,  9.94it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|██████████████████████████████████████████████████▍                                               | 2435/4733 [02:58<03:46, 10.14it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 51%|██████████████████████████████████████████████████▍                                               | 2437/4733 [02:58<05:35,  6.85it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|██████████████████████████████████████████████████▌                                               | 2439/4733 [02:59<07:11,  5.31it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|██████████████████████████████████████████████████▌                                               | 2440/4733 [02:59<07:58,  4.79it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|██████████████████████████████████████████████████▌                                               | 2441/4733 [03:00<08:48,  4.34it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 116, 105: 118, 106: 117, 107: 119, 108: 112, 109: 114, 110: 109, 111: 113, 112: 105, 113: 107, 114: 110, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 113, 102, 110, 114, 103, 108, 111, 109, 115, 104, 106, 105, 107]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 116, 105: 118, 106: 117, 107: 119, 108: 112, 109: 114, 110: 109, 111: 113, 112: 105, 113: 107, 114: 110, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 113, 102, 110, 114, 103, 108, 111, 109, 115, 104, 106, 105, 107]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|██████████████████████████████████████████████████▌                                               | 2443/4733 [03:00<08:07,  4.69it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 116, 105: 118, 106: 117, 107: 119, 108: 112, 109: 114, 110: 109, 111: 113, 112: 105, 113: 107, 114: 110, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 113, 102, 110, 114, 103, 108, 111, 109, 115, 104, 106, 105, 107]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 116, 105: 118, 106: 117, 107: 119, 108: 112, 109: 114, 110: 109, 111: 113, 112: 105, 113: 107, 114: 110, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 113, 102, 110, 114, 103, 108, 111, 109, 115, 104, 106, 105, 107]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|██████████████████████████████████████████████████▌                                               | 2444/4733 [03:00<09:18,  4.10it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 116, 105: 118, 106: 117, 107: 119, 108: 112, 109: 114, 110: 109, 111: 113, 112: 105, 113: 107, 114: 110, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 113, 102, 110, 114, 103, 108, 111, 109, 115, 104, 106, 105, 107]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 116, 105: 118, 106: 117, 107: 119, 108: 112, 109: 114, 110: 109, 111: 113, 112: 105, 113: 107, 114: 110, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 113, 102, 110, 114, 103, 108, 111, 109, 115, 104, 106, 105, 107]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|██████████████████████████████████████████████████▋                                               | 2445/4733 [03:01<10:52,  3.51it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 116, 105: 118, 106: 117, 107: 119, 108: 112, 109: 114, 110: 109, 111: 113, 112: 105, 113: 107, 114: 110, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 113, 102, 110, 114, 103, 108, 111, 109, 115, 104, 106, 105, 107]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 116, 105: 118, 106: 117, 107: 119, 108: 112, 109: 114, 110: 109, 111: 113, 112: 105, 113: 107, 114: 110, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 113, 102, 110, 114, 103, 108, 111, 109, 115, 104, 106, 105, 107]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|██████████████████████████████████████████████████▋                                               | 2451/4733 [03:01<05:06,  7.44it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|██████████████████████████████████████████████████▊                                               | 2453/4733 [03:02<05:30,  6.90it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|██████████████████████████████████████████████████▊                                               | 2455/4733 [03:02<07:23,  5.14it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|██████████████████████████████████████████████████▊                                               | 2457/4733 [03:03<08:46,  4.32it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|██████████████████████████████████████████████████▉                                               | 2463/4733 [03:04<05:21,  7.05it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|███████████████████████████████████████████████████                                               | 2465/4733 [03:04<06:46,  5.58it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|███████████████████████████████████████████████████                                               | 2468/4733 [03:05<06:06,  6.19it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|███████████████████████████████████████████████████                                               | 2469/4733 [03:05<06:55,  5.45it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|███████████████████████████████████████████████████▏                                              | 2470/4733 [03:05<07:46,  4.85it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 114, 106: 118, 107: 115, 108: 119, 109: 101, 110: 104, 111: 108, 112: 113, 113: 103, 114: 107, 115: 112, 116: 116, 117: 117, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 113, 110, 100, 103, 114, 111, 101, 104, 102, 115, 112, 105, 107, 116, 117, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 114, 106: 118, 107: 115, 108: 119, 109: 101, 110: 104, 111: 108, 112: 113, 113: 103, 114: 107, 115: 112, 116: 116, 117: 117, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 113, 110, 100, 103, 114, 111, 101, 104, 102, 115, 112, 105, 107, 116, 117, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|███████████████████████████████████████████████████▏                                              | 2471/4733 [03:06<08:34,  4.40it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 114, 106: 118, 107: 115, 108: 119, 109: 101, 110: 104, 111: 108, 112: 113, 113: 103, 114: 107, 115: 112, 116: 116, 117: 117, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 113, 110, 100, 103, 114, 111, 101, 104, 102, 115, 112, 105, 107, 116, 117, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 114, 106: 118, 107: 115, 108: 119, 109: 101, 110: 104, 111: 108, 112: 113, 113: 103, 114: 107, 115: 112, 116: 116, 117: 117, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 113, 110, 100, 103, 114, 111, 101, 104, 102, 115, 112, 105, 107, 116, 117, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|███████████████████████████████████████████████████▏                                              | 2472/4733 [03:06<09:19,  4.04it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|███████████████████████████████████████████████████▏                                              | 2475/4733 [03:06<07:02,  5.34it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|███████████████████████████████████████████████████▎                                              | 2477/4733 [03:07<06:50,  5.50it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|███████████████████████████████████████████████████▎                                              | 2478/4733 [03:07<07:48,  4.81it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 114, 111: 116, 112: 110, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 114, 111: 116, 112: 110, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|███████████████████████████████████████████████████▎                                              | 2479/4733 [03:07<08:44,  4.30it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 114, 106: 118, 107: 115, 108: 119, 109: 101, 110: 104, 111: 108, 112: 113, 113: 103, 114: 107, 115: 112, 116: 116, 117: 117, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 113, 110, 100, 103, 114, 111, 101, 104, 102, 115, 112, 105, 107, 116, 117, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 114, 106: 118, 107: 115, 108: 119, 109: 101, 110: 104, 111: 108, 112: 113, 113: 103, 114: 107, 115: 112, 116: 116, 117: 117, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 113, 110, 100, 103, 114, 111, 101, 104, 102, 115, 112, 105, 107, 116, 117, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 52%|███████████████████████████████████████████████████▍                                              | 2484/4733 [03:08<05:16,  7.11it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 114, 106: 118, 107: 115, 108: 119, 109: 101, 110: 104, 111: 108, 112: 113, 113: 103, 114: 107, 115: 112, 116: 116, 117: 117, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 113, 110, 100, 103, 114, 111, 101, 104, 102, 115, 112, 105, 107, 116, 117, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 114, 106: 118, 107: 115, 108: 119, 109: 101, 110: 104, 111: 108, 112: 113, 113: 103, 114: 107, 115: 112, 116: 116, 117: 117, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 113, 110, 100, 103, 114, 111, 101, 104, 102, 115, 112, 105, 107, 116, 117, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▍                                              | 2485/4733 [03:08<06:15,  5.98it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 114, 106: 118, 107: 115, 108: 119, 109: 101, 110: 104, 111: 108, 112: 113, 113: 103, 114: 107, 115: 112, 116: 116, 117: 117, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 113, 110, 100, 103, 114, 111, 101, 104, 102, 115, 112, 105, 107, 116, 117, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 114, 106: 118, 107: 115, 108: 119, 109: 101, 110: 104, 111: 108, 112: 113, 113: 103, 114: 107, 115: 112, 116: 116, 117: 117, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 109, 99, 113, 110, 100, 103, 114, 111, 101, 104, 102, 115, 112, 105, 107, 116, 117, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▍                                              | 2486/4733 [03:08<07:16,  5.15it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 104, 104: 107, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 103, 105, 101, 104, 106, 102, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▍                                              | 2487/4733 [03:09<08:12,  4.56it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 114, 111: 116, 112: 110, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 114, 111: 116, 112: 110, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▌                                              | 2491/4733 [03:09<05:42,  6.56it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 114, 111: 116, 112: 110, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 114, 111: 116, 112: 110, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▌                                              | 2492/4733 [03:09<06:43,  5.55it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 114, 111: 116, 112: 110, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 114, 111: 116, 112: 110, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▌                                              | 2493/4733 [03:10<07:44,  4.82it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 114, 111: 116, 112: 110, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 114, 111: 116, 112: 110, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▋                                              | 2494/4733 [03:10<08:39,  4.31it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 103, 115: 106, 116: 109, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 114, 101, 112, 115, 102, 113, 116, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 103, 115: 106, 116: 109, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 114, 101, 112, 115, 102, 113, 116, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▊                                              | 2502/4733 [03:10<03:16, 11.37it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 103, 114: 102, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 114, 113, 100, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 103, 114: 102, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 114, 113, 100, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 103, 114: 102, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 114, 113, 100, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 103, 114: 102, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 114, 113, 100, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 103, 114: 102, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 114, 113, 100, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 103, 114: 102, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 114, 113, 100, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▊                                              | 2505/4733 [03:11<05:47,  6.42it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 103, 115: 106, 116: 109, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 114, 101, 112, 115, 102, 113, 116, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 103, 115: 106, 116: 109, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 114, 101, 112, 115, 102, 113, 116, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▉                                              | 2507/4733 [03:12<05:54,  6.29it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 103, 115: 106, 116: 109, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 114, 101, 112, 115, 102, 113, 116, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 103, 115: 106, 116: 109, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 114, 101, 112, 115, 102, 113, 116, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 103, 115: 106, 116: 109, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 114, 101, 112, 115, 102, 113, 116, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 103, 115: 106, 116: 109, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 114, 101, 112, 115, 102, 113, 116, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▉                                              | 2509/4733 [03:12<07:20,  5.04it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 103, 115: 106, 116: 109, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 114, 101, 112, 115, 102, 113, 116, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 103, 115: 106, 116: 109, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 114, 101, 112, 115, 102, 113, 116, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▉                                              | 2510/4733 [03:13<08:02,  4.61it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 104, 112: 107, 113: 110, 114: 114, 115: 115, 116: 102, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 111, 117, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 104, 112: 107, 113: 110, 114: 114, 115: 115, 116: 102, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 111, 117, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|███████████████████████████████████████████████████▉                                              | 2511/4733 [03:13<08:43,  4.25it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 104, 112: 107, 113: 110, 114: 114, 115: 115, 116: 102, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 111, 117, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 104, 112: 107, 113: 110, 114: 114, 115: 115, 116: 102, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 111, 117, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████                                              | 2512/4733 [03:13<09:21,  3.95it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 103, 114: 102, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 114, 113, 100, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 103, 114: 102, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 114, 113, 100, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████                                              | 2517/4733 [03:14<05:30,  6.71it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 103, 114: 102, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 114, 113, 100, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 103, 114: 102, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 114, 113, 100, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████▏                                             | 2518/4733 [03:14<06:23,  5.78it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████▏                                             | 2519/4733 [03:14<07:22,  5.00it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████▏                                             | 2520/4733 [03:15<08:19,  4.43it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 104, 112: 107, 113: 110, 114: 114, 115: 115, 116: 102, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 111, 117, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 104, 112: 107, 113: 110, 114: 114, 115: 115, 116: 102, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 111, 117, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████▎                                             | 2524/4733 [03:15<05:43,  6.42it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 104, 112: 107, 113: 110, 114: 114, 115: 115, 116: 102, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 111, 117, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 104, 112: 107, 113: 110, 114: 114, 115: 115, 116: 102, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 111, 117, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████▎                                             | 2525/4733 [03:15<06:42,  5.48it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 104, 112: 107, 113: 110, 114: 114, 115: 115, 116: 102, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 111, 117, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 104, 112: 107, 113: 110, 114: 114, 115: 115, 116: 102, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 111, 117, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████▎                                             | 2526/4733 [03:16<07:40,  4.79it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████▎                                             | 2527/4733 [03:16<08:35,  4.28it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████▎                                             | 2528/4733 [03:16<09:22,  3.92it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 53%|████████████████████████████████████████████████████▎                                             | 2529/4733 [03:17<10:01,  3.66it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 101, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 117, 109: 119, 110: 118, 111: 120, 112: 106, 113: 108, 114: 111, 115: 115, 116: 116, 117: 103, 118: 105, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 100, 99, 117, 101, 118, 112, 102, 113, 103, 106, 114, 104, 107, 105, 115, 116, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 101, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 117, 109: 119, 110: 118, 111: 120, 112: 106, 113: 108, 114: 111, 115: 115, 116: 116, 117: 103, 118: 105, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 100, 99, 117, 101, 118, 112, 102, 113, 103, 106, 114, 104, 107, 105, 115, 116, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▍                                             | 2534/4733 [03:17<05:26,  6.73it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 110, 103: 111, 104: 104, 105: 105, 106: 108, 107: 106, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 105, 107, 101, 106, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 110, 103: 111, 104: 104, 105: 105, 106: 108, 107: 106, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 105, 107, 101, 106, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▍                                             | 2535/4733 [03:17<06:27,  5.68it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 110, 103: 111, 104: 104, 105: 105, 106: 108, 107: 106, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 105, 107, 101, 106, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 110, 103: 111, 104: 104, 105: 105, 106: 108, 107: 106, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 105, 107, 101, 106, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▌                                             | 2536/4733 [03:18<07:26,  4.92it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 110, 103: 111, 104: 104, 105: 105, 106: 108, 107: 106, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 105, 107, 101, 106, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 110, 103: 111, 104: 104, 105: 105, 106: 108, 107: 106, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 105, 107, 101, 106, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▌                                             | 2537/4733 [03:18<08:22,  4.37it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▌                                             | 2541/4733 [03:18<05:41,  6.43it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▋                                             | 2542/4733 [03:19<06:41,  5.46it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▋                                             | 2543/4733 [03:19<07:35,  4.81it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▋                                             | 2544/4733 [03:19<08:24,  4.34it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▋                                             | 2545/4733 [03:20<09:08,  3.99it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 110, 103: 111, 104: 104, 105: 105, 106: 108, 107: 106, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 105, 107, 101, 106, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 110, 103: 111, 104: 104, 105: 105, 106: 108, 107: 106, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 105, 107, 101, 106, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▊                                             | 2549/4733 [03:20<05:51,  6.22it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 110, 103: 111, 104: 104, 105: 105, 106: 108, 107: 106, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 105, 107, 101, 106, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 110, 103: 111, 104: 104, 105: 105, 106: 108, 107: 106, 108: 109, 109: 112, 110: 114, 111: 116, 112: 113, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 105, 107, 101, 106, 108, 102, 103, 109, 112, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▊                                             | 2550/4733 [03:20<06:52,  5.29it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▉                                             | 2557/4733 [03:21<03:52,  9.35it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|████████████████████████████████████████████████████▉                                             | 2558/4733 [03:21<04:44,  7.65it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 106, 105, 102, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 106, 105, 102, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|█████████████████████████████████████████████████████                                             | 2562/4733 [03:21<04:09,  8.70it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 106, 105, 102, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 106, 105, 102, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|█████████████████████████████████████████████████████                                             | 2563/4733 [03:22<05:03,  7.16it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 106, 105, 102, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 106, 105, 102, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|█████████████████████████████████████████████████████                                             | 2564/4733 [03:22<06:00,  6.02it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 106, 105, 102, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 106, 105, 102, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|█████████████████████████████████████████████████████                                             | 2565/4733 [03:22<06:57,  5.19it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 106, 105, 102, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 108, 103: 102, 104: 104, 105: 107, 106: 106, 107: 109, 108: 111, 109: 113, 110: 115, 111: 114, 112: 116, 113: 112, 114: 110, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 103, 100, 104, 101, 106, 105, 102, 107, 114, 108, 113, 109, 111, 110, 112]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|█████████████████████████████████████████████████████▏                                            | 2566/4733 [03:23<07:52,  4.59it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|█████████████████████████████████████████████████████▎                                            | 2574/4733 [03:23<03:04, 11.71it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|█████████████████████████████████████████████████████▎                                            | 2577/4733 [03:24<04:31,  7.95it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 54%|█████████████████████████████████████████████████████▍                                            | 2579/4733 [03:24<04:50,  7.42it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|█████████████████████████████████████████████████████▍                                            | 2581/4733 [03:25<06:24,  5.60it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 101, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 117, 109: 119, 110: 118, 111: 120, 112: 106, 113: 108, 114: 111, 115: 115, 116: 116, 117: 103, 118: 105, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 100, 99, 117, 101, 118, 112, 102, 113, 103, 106, 114, 104, 107, 105, 115, 116, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 101, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 117, 109: 119, 110: 118, 111: 120, 112: 106, 113: 108, 114: 111, 115: 115, 116: 116, 117: 103, 118: 105, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 100, 99, 117, 101, 118, 112, 102, 113, 103, 106, 114, 104, 107, 105, 115, 116, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|█████████████████████████████████████████████████████▍                                            | 2583/4733 [03:25<07:42,  4.65it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 101, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 117, 109: 119, 110: 118, 111: 120, 112: 106, 113: 108, 114: 111, 115: 115, 116: 116, 117: 103, 118: 105, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 100, 99, 117, 101, 118, 112, 102, 113, 103, 106, 114, 104, 107, 105, 115, 116, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 101, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 117, 109: 119, 110: 118, 111: 120, 112: 106, 113: 108, 114: 111, 115: 115, 116: 116, 117: 103, 118: 105, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 100, 99, 117, 101, 118, 112, 102, 113, 103, 106, 114, 104, 107, 105, 115, 116, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|█████████████████████████████████████████████████████▌                                            | 2584/4733 [03:26<08:19,  4.30it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 101, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 117, 109: 119, 110: 118, 111: 120, 112: 106, 113: 108, 114: 111, 115: 115, 116: 116, 117: 103, 118: 105, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 100, 99, 117, 101, 118, 112, 102, 113, 103, 106, 114, 104, 107, 105, 115, 116, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 101, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 117, 109: 119, 110: 118, 111: 120, 112: 106, 113: 108, 114: 111, 115: 115, 116: 116, 117: 103, 118: 105, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 100, 99, 117, 101, 118, 112, 102, 113, 103, 106, 114, 104, 107, 105, 115, 116, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|█████████████████████████████████████████████████████▌                                            | 2585/4733 [03:26<08:55,  4.01it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 101, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 117, 109: 119, 110: 118, 111: 120, 112: 106, 113: 108, 114: 111, 115: 115, 116: 116, 117: 103, 118: 105, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 100, 99, 117, 101, 118, 112, 102, 113, 103, 106, 114, 104, 107, 105, 115, 116, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 101, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 117, 109: 119, 110: 118, 111: 120, 112: 106, 113: 108, 114: 111, 115: 115, 116: 116, 117: 103, 118: 105, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 100, 99, 117, 101, 118, 112, 102, 113, 103, 106, 114, 104, 107, 105, 115, 116, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|█████████████████████████████████████████████████████▌                                            | 2586/4733 [03:26<09:29,  3.77it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|█████████████████████████████████████████████████████▌                                            | 2588/4733 [03:27<08:13,  4.35it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|█████████████████████████████████████████████████████▌                                            | 2589/4733 [03:27<08:55,  4.01it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 102, 117: 104, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 116, 100, 117, 112, 101, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|█████████████████████████████████████████████████████▋                                            | 2595/4733 [03:27<04:10,  8.55it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|█████████████████████████████████████████████████████▊                                            | 2600/4733 [03:28<03:33, 10.00it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|█████████████████████████████████████████████████████▉                                            | 2602/4733 [03:29<05:13,  6.79it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|█████████████████████████████████████████████████████▉                                            | 2604/4733 [03:29<06:40,  5.32it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 106, 104: 110, 105: 107, 106: 108, 107: 111, 108: 112, 109: 114, 110: 116, 111: 113, 112: 115, 113: 117, 114: 119, 115: 118, 116: 120, 117: 105, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 117, 103, 105, 106, 118, 104, 107, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 106, 104: 110, 105: 107, 106: 108, 107: 111, 108: 112, 109: 114, 110: 116, 111: 113, 112: 115, 113: 117, 114: 119, 115: 118, 116: 120, 117: 105, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 117, 103, 105, 106, 118, 104, 107, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|██████████████████████████████████████████████████████                                            | 2609/4733 [03:30<04:53,  7.24it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 106, 104: 110, 105: 107, 106: 108, 107: 111, 108: 112, 109: 114, 110: 116, 111: 113, 112: 115, 113: 117, 114: 119, 115: 118, 116: 120, 117: 105, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 117, 103, 105, 106, 118, 104, 107, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 106, 104: 110, 105: 107, 106: 108, 107: 111, 108: 112, 109: 114, 110: 116, 111: 113, 112: 115, 113: 117, 114: 119, 115: 118, 116: 120, 117: 105, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 117, 103, 105, 106, 118, 104, 107, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|██████████████████████████████████████████████████████                                            | 2610/4733 [03:30<05:39,  6.26it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 106, 104: 110, 105: 107, 106: 108, 107: 111, 108: 112, 109: 114, 110: 116, 111: 113, 112: 115, 113: 117, 114: 119, 115: 118, 116: 120, 117: 105, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 117, 103, 105, 106, 118, 104, 107, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 106, 104: 110, 105: 107, 106: 108, 107: 111, 108: 112, 109: 114, 110: 116, 111: 113, 112: 115, 113: 117, 114: 119, 115: 118, 116: 120, 117: 105, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 117, 103, 105, 106, 118, 104, 107, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|██████████████████████████████████████████████████████                                            | 2611/4733 [03:30<06:28,  5.46it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 106, 104: 110, 105: 107, 106: 108, 107: 111, 108: 112, 109: 114, 110: 116, 111: 113, 112: 115, 113: 117, 114: 119, 115: 118, 116: 120, 117: 105, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 117, 103, 105, 106, 118, 104, 107, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 106, 104: 110, 105: 107, 106: 108, 107: 111, 108: 112, 109: 114, 110: 116, 111: 113, 112: 115, 113: 117, 114: 119, 115: 118, 116: 120, 117: 105, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 117, 103, 105, 106, 118, 104, 107, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|██████████████████████████████████████████████████████                                            | 2612/4733 [03:31<07:19,  4.83it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 106, 104: 110, 105: 107, 106: 108, 107: 111, 108: 112, 109: 114, 110: 116, 111: 113, 112: 115, 113: 117, 114: 119, 115: 118, 116: 120, 117: 105, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 117, 103, 105, 106, 118, 104, 107, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 106, 104: 110, 105: 107, 106: 108, 107: 111, 108: 112, 109: 114, 110: 116, 111: 113, 112: 115, 113: 117, 114: 119, 115: 118, 116: 120, 117: 105, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 117, 103, 105, 106, 118, 104, 107, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|██████████████████████████████████████████████████████                                            | 2613/4733 [03:31<08:08,  4.34it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|██████████████████████████████████████████████████████▏                                           | 2616/4733 [03:31<06:18,  5.59it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|██████████████████████████████████████████████████████▏                                           | 2617/4733 [03:32<07:11,  4.90it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|██████████████████████████████████████████████████████▏                                           | 2618/4733 [03:32<07:59,  4.41it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|██████████████████████████████████████████████████████▏                                           | 2619/4733 [03:32<08:42,  4.05it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 55%|██████████████████████████████████████████████████████▎                                           | 2625/4733 [03:33<03:53,  9.04it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]

 56%|██████████████████████████████████████████████████████▍                                           | 2630/4733 [03:33<02:28, 14.18it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 56%|██████████████████████████████████████████████████████▌                                           | 2633/4733 [03:33<03:05, 11.35it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 56%|██████████████████████████████████████████████████████▋                                           | 2639/4733 [03:34<02:40, 13.04it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 56%|██████████████████████████████████████████████████████▊                                           | 2647/4733 [03:34<01:42, 20.43it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 56%|██████████████████████████████████████████████████████▉                                           | 2656/4733 [03:34<01:12, 28.48it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]

 56%|███████████████████████████████████████████████████████▎                                          | 2669/4733 [03:34<00:49, 41.99it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 56%|███████████████████████████████████████████████████████▎                                          | 2674/4733 [03:35<01:23, 24.55it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 57%|███████████████████████████████████████████████████████▌                                          | 2682/4733 [03:35<01:42, 19.94it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]

 57%|███████████████████████████████████████████████████████▊                                          | 2693/4733 [03:35<01:06, 30.59it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]

 57%|████████████████████████████████████████████████████████                                          | 2706/4733 [03:36<00:47, 42.34it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]

 57%|████████████████████████████████████████████████████████▎                                         | 2719/4733 [03:36<00:39, 50.58it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]

 58%|████████████████████████████████████████████████████████▍                                         | 2725/4733 [03:36<00:39, 51.09it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 4, 3, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 4, 3, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]

 58%|████████████████████████████████████████████████████████▋                                         | 2737/4733 [03:36<00:43, 46.22it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 7, 8: 4, 9: 8, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 8, 3, 4, 7, 9, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 7, 8: 4, 9: 8, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 8, 3, 4, 7, 9, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 7, 8: 4, 9: 8, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 8, 3, 4, 7, 9, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 7, 8: 4, 9: 8, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 8, 3, 4, 7, 9, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 7, 8: 4, 9: 8, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 8, 3, 4, 7, 9, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 7, 8: 4, 9: 8, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 8, 3, 4, 7, 9, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 23, 22]
[1, 2, 20]

 58%|████████████████████████████████████████████████████████▉                                         | 2750/4733 [03:37<00:37, 52.50it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 7, 8: 4, 9: 8, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 8, 3, 4, 7, 9, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 7, 8: 4, 9: 8, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 8, 3, 4, 7, 9, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 7, 8: 4, 9: 8, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 8, 3, 4, 7, 9, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 9, 6: 12, 7: 7, 8: 4, 9: 8, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 8, 3, 4, 7, 9, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 4]

 58%|█████████████████████████████████████████████████████████▏                                        | 2764/4733 [03:37<00:33, 58.25it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 4]

 59%|█████████████████████████████████████████████████████████▌                                        | 2778/4733 [03:37<00:31, 61.27it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 4]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 4, 3, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 4, 3, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 4, 3, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 4, 3, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 4, 3, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 4, 3, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 4, 3, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 4, 3, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 57, 56: 60, 57: 63, 58: 58, 59: 55, 60: 59, 61: 61, 62: 64, 63: 66, 64: 62, 65: 65, 66: 67, 67: 69, 68: 68, 69: 70}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 59, 54, 55, 58, 60, 56, 61, 64, 57, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]

 59%|█████████████████████████████████████████████████████████▊                                        | 2791/4733 [03:37<00:40, 48.40it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]

 59%|██████████████████████████████████████████████████████████                                        | 2802/4733 [03:38<00:41, 46.15it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 15, 12: 17, 13: 19, 14: 21, 15: 18, 16: 20, 17: 22, 18: 24, 19: 23, 20: 25, 21: 13, 22: 16, 23: 11, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 23, 10, 21, 24, 11, 22, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]

 59%|██████████████████████████████████████████████████████████▏                                       | 2813/4733 [03:38<00:42, 45.52it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 34, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 35}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 30, 32, 33, 45, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]

 60%|██████████████████████████████████████████████████████████▍                                       | 2820/4733 [03:38<00:38, 50.18it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 12, 11: 15, 12: 18, 13: 13, 14: 10, 15: 14, 16: 16, 17: 19, 18: 21, 19: 17, 20: 20, 21: 22, 22: 24, 23: 23, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 14, 9, 10, 13, 15, 11, 16, 19, 12, 17, 20, 18, 21, 23, 22, 24]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 12, 11: 15, 12: 18, 13: 13, 14: 10, 15: 14, 16: 16, 17: 19, 18: 21, 19: 17, 20: 20, 21: 22, 22: 24, 23: 23, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 14, 9, 10, 13, 15, 11, 16, 19, 12, 17, 20, 18, 21, 23, 22, 24]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 12, 11: 15, 12: 18, 13: 13, 14: 10, 15: 14, 16: 16, 17: 19, 18: 21, 19: 17, 20: 20, 21: 22, 22: 24, 23: 23, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 14, 9, 10, 13, 15, 11, 16, 19, 12, 17, 20, 18, 21, 23, 22, 24]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 12, 11: 15, 12: 18, 13: 13, 14: 10, 15: 14, 16: 16, 17: 19, 18: 21, 19: 17, 20: 20, 21: 22, 22: 24, 23: 23, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 14, 9, 10, 13, 15, 11, 16, 19, 12, 17, 20, 18, 21, 23, 22, 24]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]

 60%|██████████████████████████████████████████████████████████▋                                       | 2833/4733 [03:38<00:35, 53.92it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 12, 11: 15, 12: 18, 13: 13, 14: 10, 15: 14, 16: 16, 17: 19, 18: 21, 19: 17, 20: 20, 21: 22, 22: 24, 23: 23, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 14, 9, 10, 13, 15, 11, 16, 19, 12, 17, 20, 18, 21, 23, 22, 24]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 12, 11: 15, 12: 18, 13: 13, 14: 10, 15: 14, 16: 16, 17: 19, 18: 21, 19: 17, 20: 20, 21: 22, 22: 24, 23: 23, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 14, 9, 10, 13, 15, 11, 16, 19, 12, 17, 20, 18, 21, 23, 22, 24]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 12, 11: 15, 12: 18, 13: 13, 14: 10, 15: 14, 16: 16, 17: 19, 18: 21, 19: 17, 20: 20, 21: 22, 22: 24, 23: 23, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 14, 9, 10, 13, 15, 11, 16, 19, 12, 17, 20, 18, 21, 23, 22, 24]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 12, 11: 15, 12: 18, 13: 13, 14: 10, 15: 14, 16: 16, 17: 19, 18: 21, 19: 17, 20: 20, 21: 22, 22: 24, 23: 23, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 14, 9, 10, 13, 15, 11, 16, 19, 12, 17, 20, 18, 21, 23, 22, 24]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 12, 11: 15, 12: 18, 13: 13, 14: 10, 15: 14, 16: 16, 17: 19, 18: 21, 19: 17, 20: 20, 21: 22, 22: 24, 23: 23, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 14, 9, 10, 13, 15, 11, 16, 19, 12, 17, 20, 18, 21, 23, 22, 24]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 12, 11: 15, 12: 18, 13: 13, 14: 10, 15: 14, 16: 16, 17: 19, 18: 21, 19: 17, 20: 20, 21: 22, 22: 24, 23: 23, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 14, 9, 10, 13, 15, 11, 16, 19, 12, 17, 20, 18, 21, 23, 22, 24]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]

 60%|██████████████████████████████████████████████████████████▉                                       | 2847/4733 [03:38<00:33, 57.03it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 60%|███████████████████████████████████████████████████████████▏                                      | 2859/4733 [03:39<00:39, 47.14it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]

 61%|███████████████████████████████████████████████████████████▎                                      | 2865/4733 [03:39<00:38, 48.70it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23, 24]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23, 24]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23, 24]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23, 24]
[1, 2, 20]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]

 61%|███████████████████████████████████████████████████████████▊                                      | 2886/4733 [03:39<00:31, 58.17it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23, 24]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23, 24]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23, 24]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23, 24]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23, 24]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22, 23, 24]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]
{0: 1, 1: 9, 2: 10, 3: 12, 4: 14, 5: 11, 6: 13, 7: 15, 8: 17, 9: 16, 10: 18, 11: 4, 12: 2, 13: 3, 14: 19, 15: 5, 16: 6, 17: 7, 18: 8}
[0, 12, 13, 11, 15, 16, 17, 18, 1, 2, 5, 3, 6, 4, 7, 9, 8, 10, 14]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]

 61%|███████████████████████████████████████████████████████████▉                                      | 2892/4733 [03:39<00:38, 48.11it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 61%|████████████████████████████████████████████████████████████                                      | 2898/4733 [03:39<00:38, 47.39it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 15, 11: 12, 12: 13, 13: 16, 14: 17, 15: 19, 16: 21, 17: 18, 18: 20, 19: 22, 20: 24, 21: 23, 22: 25, 23: 10, 24: 14}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 23, 9, 11, 12, 24, 10, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 7]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 12, 7: 8, 8: 4, 9: 7, 10: 10, 11: 13, 12: 15, 13: 11, 14: 14, 15: 16, 16: 18, 17: 17, 18: 19, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 8, 4, 3, 9, 7, 5, 10, 13, 6, 11, 14, 12, 15, 17, 16, 18, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]

 61%|████████████████████████████████████████████████████████████▎                                     | 2910/4733 [03:40<00:37, 49.15it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]

 62%|████████████████████████████████████████████████████████████▌                                     | 2922/4733 [03:40<00:37, 48.62it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 5, 6: 8, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 7, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 5, 3, 18, 6, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 22, 23]
[1, 20, 21]

 62%|████████████████████████████████████████████████████████████▋                                     | 2929/4733 [03:40<00:35, 50.48it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 34, 35: 31, 36: 35, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 35, 30, 31, 34, 36, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 2, 28]

 62%|████████████████████████████████████████████████████████████▊                                     | 2935/4733 [03:40<00:42, 42.01it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]

 62%|█████████████████████████████████████████████████████████████                                     | 2947/4733 [03:41<00:41, 43.05it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]

 63%|█████████████████████████████████████████████████████████████▎                                    | 2959/4733 [03:41<00:40, 44.20it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]

 63%|█████████████████████████████████████████████████████████████▍                                    | 2966/4733 [03:41<00:37, 46.78it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 7, 16: 10, 17: 5, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 3, 17, 4, 15, 18, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]

 63%|█████████████████████████████████████████████████████████████▋                                    | 2977/4733 [03:41<00:38, 45.62it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 4, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 4, 3, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 6]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 63%|█████████████████████████████████████████████████████████████▊                                    | 2987/4733 [03:42<00:43, 40.29it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]

 63%|█████████████████████████████████████████████████████████████▉                                    | 2992/4733 [03:42<00:45, 38.12it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]

 63%|██████████████████████████████████████████████████████████████                                    | 3000/4733 [03:42<00:50, 34.29it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 11, 7: 13, 8: 15, 9: 12, 10: 14, 11: 16, 12: 18, 13: 17, 14: 19, 15: 8, 16: 10, 17: 5, 18: 7, 19: 20, 20: 21, 21: 48, 22: 49, 23: 50, 24: 22, 25: 23, 26: 26, 27: 27, 28: 28, 29: 30, 30: 33, 31: 36, 32: 41, 33: 43, 34: 37, 35: 42, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 29, 43: 31, 44: 34, 45: 38, 46: 39, 47: 40, 48: 24, 49: 25}
[0, 1, 2, 3, 17, 4, 18, 15, 5, 16, 6, 9, 7, 10, 8, 11, 13, 12, 14, 19, 20, 24, 25, 48, 49, 26, 27, 28, 42, 29, 43, 40, 30, 44, 41, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 21, 22, 23]
[1, 20, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 56, 55: 60, 56: 57, 57: 58, 58: 61, 59: 62, 60: 64, 61: 66, 62: 63, 63: 65, 64: 67, 65: 69, 66: 68, 67: 70, 68: 55, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 54, 56, 57, 69, 55, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]

 64%|██████████████████████████████████████████████████████████████▎                                   | 3007/4733 [03:42<00:41, 41.56it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 7, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 17, 3, 5, 6, 18, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 7, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 17, 3, 5, 6, 18, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 7, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 17, 3, 5, 6, 18, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 7, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 17, 3, 5, 6, 18, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 7, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 17, 3, 5, 6, 18, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 7, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 17, 3, 5, 6, 18, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 7, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 17, 3, 5, 6, 18, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 7, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 17, 3, 5, 6, 18, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 7, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 17, 3, 5, 6, 18, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 7, 7: 10, 8: 11, 9: 13, 10: 15, 11: 12, 12: 14, 13: 16, 14: 18, 15: 17, 16: 19, 17: 4, 18: 8, 19: 20, 20: 21, 21: 22, 22: 24, 23: 23}
[0, 1, 2, 17, 3, 5, 6, 18, 4, 7, 8, 11, 9, 12, 10, 13, 15, 14, 16, 19, 20, 21, 23, 22]
[1, 2, 20]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 17, 10: 16, 11: 11, 12: 15, 13: 20, 14: 21, 15: 22, 16: 23, 17: 18, 18: 8, 19: 12, 20: 10, 21: 14, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 11, 19, 8, 21, 12, 10, 9, 17, 22, 13, 14, 15, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 17, 10: 16, 11: 11, 12: 15, 13: 20, 14: 21, 15: 22, 16: 23, 17: 18, 18: 8, 19: 12, 20: 10, 21: 14, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 11, 19, 8, 21, 12, 10, 9, 17, 22, 13, 14, 15, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 17, 10: 16, 11: 11, 12: 15, 13: 20, 14: 21, 15: 22, 16: 23, 17: 18, 18: 8, 19: 12, 20: 10, 21: 14, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 11, 19, 8, 21, 12, 10, 9, 17, 22, 13, 14, 15, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 17, 10: 16, 11: 11, 12: 15, 13: 20, 14: 21, 15: 22, 16: 23, 17: 18, 18: 8, 19: 12, 20: 10, 21: 14, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 11, 19, 8, 21, 12, 10, 9, 17, 22, 13, 14, 15, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 17, 10: 16, 11: 11, 12: 15, 13: 20, 14: 21, 15: 22, 16: 23, 17: 18, 18: 8, 19: 12, 20: 10, 21: 14, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 11, 19, 8, 21, 12, 10, 9, 17, 22, 13, 14, 15, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 17, 10: 16, 11: 11, 12: 15, 13: 20, 14: 21, 15: 22, 16: 23, 17: 18, 18: 8, 19: 12, 20: 10, 21: 14, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 11, 19, 8, 21, 12, 10, 9, 17, 22, 13, 14, 15, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 17, 10: 16, 11: 11, 12: 15, 13: 20, 14: 21, 15: 22, 16: 23, 17: 18, 18: 8, 19: 12, 20: 10, 21: 14, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 11, 19, 8, 21, 12, 10, 9, 17, 22, 13, 14, 15, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 17, 10: 16, 11: 11, 12: 15, 13: 20, 14: 21, 15: 22, 16: 23, 17: 18, 18: 8, 19: 12, 20: 10, 21: 14, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 11, 19, 8, 21, 12, 10, 9, 17, 22, 13, 14, 15, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 64%|██████████████████████████████████████████████████████████████▎                                   | 3012/4733 [03:42<01:09, 24.67it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 64%|██████████████████████████████████████████████████████████████▌                                   | 3023/4733 [03:43<01:09, 24.74it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 9, 12: 12, 13: 15, 14: 18, 15: 17, 16: 13, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 11, 8, 9, 12, 16, 10, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 9, 12: 12, 13: 15, 14: 18, 15: 17, 16: 13, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 11, 8, 9, 12, 16, 10, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 9, 12: 12, 13: 15, 14: 18, 15: 17, 16: 13, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 11, 8, 9, 12, 16, 10, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 9, 12: 12, 13: 15, 14: 18, 15: 17, 16: 13, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 11, 8, 9, 12, 16, 10, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 9, 12: 12, 13: 15, 14: 18, 15: 17, 16: 13, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 11, 8, 9, 12, 16, 10, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 9, 12: 12, 13: 15, 14: 18, 15: 17, 16: 13, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 11, 8, 9, 12, 16, 10, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 9, 12: 12, 13: 15, 14: 18, 15: 17, 16: 13, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 11, 8, 9, 12, 16, 10, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 9, 12: 12, 13: 15, 14: 18, 15: 17, 16: 13, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 11, 8, 9, 12, 16, 10, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 9, 12: 12, 13: 15, 14: 18, 15: 17, 16: 13, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 11, 8, 9, 12, 16, 10, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 9, 12: 12, 13: 15, 14: 18, 15: 17, 16: 13, 17: 16, 18: 20, 19: 21, 20: 22, 21: 23, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 7, 11, 8, 9, 12, 16, 10, 13, 17, 15, 14, 22, 18, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 17, 10: 16, 11: 11, 12: 15, 13: 20, 14: 21, 15: 22, 16: 23, 17: 18, 18: 8, 19: 12, 20: 10, 21: 14, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 11, 19, 8, 21, 12, 10, 9, 17, 22, 13, 14, 15, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 17, 10: 16, 11: 11, 12: 15, 13: 20, 14: 21, 15: 22, 16: 23, 17: 18, 18: 8, 19: 12, 20: 10, 21: 14, 22: 19}
[0, 1, 2, 3, 4, 5, 6, 18, 7, 20, 11, 19, 8, 21, 12, 10, 9, 17, 22, 13, 14, 15, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 64%|██████████████████████████████████████████████████████████████▊                                   | 3033/4733 [03:44<01:34, 18.05it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 3, 14: 4, 15: 19, 16: 2, 17: 16, 18: 18}
[0, 16, 13, 14, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 17, 12, 18, 15]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 64%|██████████████████████████████████████████████████████████████▉                                   | 3037/4733 [03:44<01:22, 20.52it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 64%|██████████████████████████████████████████████████████████████▉                                   | 3041/4733 [03:45<02:18, 12.22it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 64%|███████████████████████████████████████████████████████████████                                   | 3044/4733 [03:45<03:12,  8.76it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 64%|███████████████████████████████████████████████████████████████                                   | 3046/4733 [03:46<03:27,  8.12it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 64%|███████████████████████████████████████████████████████████████                                   | 3048/4733 [03:46<03:47,  7.42it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 64%|███████████████████████████████████████████████████████████████▏                                  | 3050/4733 [03:46<04:04,  6.89it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 64%|███████████████████████████████████████████████████████████████▏                                  | 3052/4733 [03:47<05:18,  5.28it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▏                                  | 3054/4733 [03:47<05:14,  5.33it/s]

{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▎                                  | 3056/4733 [03:48<05:09,  5.43it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▎                                  | 3057/4733 [03:48<05:48,  4.80it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▎                                  | 3058/4733 [03:48<06:27,  4.32it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▎                                  | 3060/4733 [03:49<05:58,  4.67it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▍                                  | 3062/4733 [03:49<05:35,  4.98it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▍                                  | 3063/4733 [03:49<06:17,  4.43it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▍                                  | 3065/4733 [03:50<05:51,  4.75it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▌                                  | 3068/4733 [03:50<04:50,  5.73it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▌                                  | 3069/4733 [03:51<05:35,  4.97it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▌                                  | 3072/4733 [03:51<04:47,  5.79it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▋                                  | 3073/4733 [03:51<05:27,  5.07it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▋                                  | 3074/4733 [03:52<06:10,  4.47it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▋                                  | 3075/4733 [03:52<06:49,  4.04it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▋                                  | 3076/4733 [03:52<07:23,  3.74it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▋                                  | 3078/4733 [03:53<06:25,  4.30it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▊                                  | 3079/4733 [03:53<07:01,  3.92it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▊                                  | 3080/4733 [03:53<07:33,  3.65it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▊                                  | 3081/4733 [03:54<07:57,  3.46it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▊                                  | 3082/4733 [03:54<08:16,  3.33it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▊                                  | 3084/4733 [03:54<06:50,  4.01it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▉                                  | 3086/4733 [03:55<06:02,  4.54it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▉                                  | 3087/4733 [03:55<06:42,  4.09it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▉                                  | 3089/4733 [03:55<06:02,  4.53it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|███████████████████████████████████████████████████████████████▉                                  | 3090/4733 [03:56<06:42,  4.08it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|████████████████████████████████████████████████████████████████                                  | 3091/4733 [03:56<07:16,  3.77it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|████████████████████████████████████████████████████████████████                                  | 3092/4733 [03:56<07:43,  3.54it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|████████████████████████████████████████████████████████████████                                  | 3093/4733 [03:57<08:04,  3.38it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|████████████████████████████████████████████████████████████████                                  | 3095/4733 [03:57<06:44,  4.05it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|████████████████████████████████████████████████████████████████▏                                 | 3097/4733 [03:57<06:03,  4.50it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 65%|████████████████████████████████████████████████████████████████▏                                 | 3100/4733 [03:58<04:53,  5.57it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 66%|████████████████████████████████████████████████████████████████▏                                 | 3101/4733 [03:58<05:37,  4.84it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 66%|████████████████████████████████████████████████████████████████▎                                 | 3107/4733 [03:59<02:57,  9.19it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]

 66%|████████████████████████████████████████████████████████████████▌                                 | 3116/4733 [03:59<01:30, 17.83it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 66%|████████████████████████████████████████████████████████████████▋                                 | 3124/4733 [03:59<01:06, 24.04it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 31, 34: 34, 35: 37, 36: 40, 37: 42, 38: 38, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 35, 45: 39}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 33, 31, 30, 34, 44, 32, 35, 38, 45, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 66%|████████████████████████████████████████████████████████████████▊                                 | 3128/4733 [03:59<01:39, 16.07it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 66%|████████████████████████████████████████████████████████████████▊                                 | 3131/4733 [04:00<03:26,  7.75it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 66%|████████████████████████████████████████████████████████████████▊                                 | 3133/4733 [04:01<03:50,  6.95it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 120, 116: 121, 117: 122, 118: 117, 119: 119, 120: 102, 121: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 121, 99, 120, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 118, 114, 119, 115, 116, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 66%|████████████████████████████████████████████████████████████████▉                                 | 3135/4733 [04:02<04:58,  5.35it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 66%|████████████████████████████████████████████████████████████████▉                                 | 3137/4733 [04:02<04:57,  5.37it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 66%|████████████████████████████████████████████████████████████████▉                                 | 3139/4733 [04:02<04:51,  5.48it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 66%|█████████████████████████████████████████████████████████████████                                 | 3140/4733 [04:03<05:26,  4.89it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 66%|█████████████████████████████████████████████████████████████████                                 | 3141/4733 [04:03<06:01,  4.41it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 66%|█████████████████████████████████████████████████████████████████                                 | 3144/4733 [04:03<04:54,  5.40it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 66%|█████████████████████████████████████████████████████████████████▏                                | 3146/4733 [04:04<04:48,  5.50it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▏                                | 3148/4733 [04:04<04:48,  5.50it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▏                                | 3151/4733 [04:04<04:12,  6.25it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 32, 31: 36, 32: 33, 33: 37, 34: 39, 35: 41, 36: 43, 37: 40, 38: 42, 39: 44, 40: 46, 41: 45, 42: 47, 43: 35, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 30, 32, 45, 43, 31, 33, 46, 34, 37, 35, 38, 36, 39, 41, 40, 42]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▎                                | 3154/4733 [04:05<03:55,  6.69it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▎                                | 3156/4733 [04:05<04:07,  6.37it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▍                                | 3158/4733 [04:06<04:16,  6.13it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▍                                | 3160/4733 [04:06<04:23,  5.98it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▍                                | 3163/4733 [04:06<04:02,  6.46it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▌                                | 3167/4733 [04:07<03:30,  7.45it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▌                                | 3168/4733 [04:07<04:09,  6.28it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▌                                | 3169/4733 [04:07<04:50,  5.38it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▋                                | 3170/4733 [04:08<05:31,  4.71it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▋                                | 3172/4733 [04:08<05:14,  4.97it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▋                                | 3173/4733 [04:08<05:53,  4.42it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▋                                | 3174/4733 [04:09<06:27,  4.02it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▋                                | 3175/4733 [04:09<06:57,  3.73it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▊                                | 3176/4733 [04:09<07:21,  3.53it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▊                                | 3178/4733 [04:10<06:04,  4.27it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▊                                | 3180/4733 [04:10<05:32,  4.67it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▉                                | 3183/4733 [04:10<04:30,  5.73it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▉                                | 3185/4733 [04:11<04:32,  5.68it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▉                                | 3186/4733 [04:11<05:14,  4.91it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|█████████████████████████████████████████████████████████████████▉                                | 3187/4733 [04:11<05:53,  4.37it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|██████████████████████████████████████████████████████████████████                                | 3189/4733 [04:12<05:26,  4.73it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|██████████████████████████████████████████████████████████████████                                | 3191/4733 [04:12<05:09,  4.99it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 67%|██████████████████████████████████████████████████████████████████                                | 3193/4733 [04:13<04:54,  5.24it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▏                               | 3195/4733 [04:13<04:48,  5.33it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▏                               | 3196/4733 [04:13<05:29,  4.67it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▏                               | 3198/4733 [04:14<05:10,  4.95it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▎                               | 3200/4733 [04:14<04:57,  5.15it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▎                               | 3205/4733 [04:14<03:03,  8.34it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▍                               | 3207/4733 [04:15<03:27,  7.36it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▍                               | 3209/4733 [04:15<03:45,  6.77it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▍                               | 3210/4733 [04:15<04:30,  5.63it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▌                               | 3212/4733 [04:16<04:35,  5.52it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▌                               | 3213/4733 [04:16<05:15,  4.81it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▌                               | 3214/4733 [04:16<05:54,  4.29it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▌                               | 3215/4733 [04:17<06:27,  3.92it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▌                               | 3217/4733 [04:17<05:37,  4.49it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▋                               | 3219/4733 [04:17<05:14,  4.81it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▋                               | 3220/4733 [04:18<05:50,  4.32it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▋                               | 3221/4733 [04:18<06:38,  3.80it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▋                               | 3222/4733 [04:18<06:59,  3.60it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▋                               | 3223/4733 [04:19<07:16,  3.46it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▊                               | 3224/4733 [04:19<07:29,  3.36it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▊                               | 3226/4733 [04:19<06:08,  4.09it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▊                               | 3227/4733 [04:20<06:36,  3.80it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▊                               | 3228/4733 [04:20<06:58,  3.60it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 104, 103: 107, 104: 109, 105: 105, 106: 108, 107: 110, 108: 112, 109: 114, 110: 111, 111: 113, 112: 115, 113: 117, 114: 116, 115: 118, 116: 102, 117: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 117, 99, 116, 100, 102, 105, 101, 103, 106, 104, 107, 110, 108, 111, 109, 112, 114, 113, 115]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▊                               | 3229/4733 [04:20<07:15,  3.45it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▉                               | 3231/4733 [04:21<06:03,  4.14it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▉                               | 3233/4733 [04:21<05:26,  4.60it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|██████████████████████████████████████████████████████████████████▉                               | 3235/4733 [04:22<05:01,  4.97it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 68%|███████████████████████████████████████████████████████████████████                               | 3241/4733 [04:22<02:48,  8.84it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 69%|███████████████████████████████████████████████████████████████████▏                              | 3243/4733 [04:22<03:14,  7.67it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 69%|███████████████████████████████████████████████████████████████████▎                              | 3250/4733 [04:23<02:07, 11.62it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 69%|███████████████████████████████████████████████████████████████████▍                              | 3259/4733 [04:23<01:11, 20.66it/s]

{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 69%|███████████████████████████████████████████████████████████████████▌                              | 3263/4733 [04:23<01:03, 23.03it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 69%|███████████████████████████████████████████████████████████████████▋                              | 3267/4733 [04:24<02:33,  9.53it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 69%|███████████████████████████████████████████████████████████████████▋                              | 3270/4733 [04:25<02:41,  9.03it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 69%|███████████████████████████████████████████████████████████████████▋                              | 3272/4733 [04:25<03:41,  6.61it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 69%|███████████████████████████████████████████████████████████████████▊                              | 3274/4733 [04:26<03:49,  6.37it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 69%|███████████████████████████████████████████████████████████████████▊                              | 3276/4733 [04:26<04:45,  5.10it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 69%|███████████████████████████████████████████████████████████████████▊                              | 3278/4733 [04:27<04:38,  5.22it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 69%|███████████████████████████████████████████████████████████████████▉                              | 3280/4733 [04:27<04:32,  5.33it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 69%|███████████████████████████████████████████████████████████████████▉                              | 3282/4733 [04:27<04:25,  5.46it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 69%|███████████████████████████████████████████████████████████████████▉                              | 3284/4733 [04:28<04:24,  5.49it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 69%|████████████████████████████████████████████████████████████████████                              | 3285/4733 [04:28<04:58,  4.86it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 69%|████████████████████████████████████████████████████████████████████                              | 3288/4733 [04:28<04:08,  5.82it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 69%|████████████████████████████████████████████████████████████████████                              | 3289/4733 [04:29<04:44,  5.07it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▏                             | 3292/4733 [04:29<04:00,  6.00it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▏                             | 3293/4733 [04:29<04:37,  5.19it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▏                             | 3294/4733 [04:30<05:13,  4.59it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▏                             | 3295/4733 [04:30<05:46,  4.15it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▏                             | 3296/4733 [04:30<06:14,  3.84it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▎                             | 3298/4733 [04:31<05:25,  4.40it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▎                             | 3299/4733 [04:31<05:57,  4.01it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▎                             | 3301/4733 [04:31<05:22,  4.45it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▎                             | 3302/4733 [04:32<05:51,  4.07it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▍                             | 3304/4733 [04:32<05:15,  4.53it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▍                             | 3306/4733 [04:32<04:50,  4.92it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▍                             | 3308/4733 [04:33<04:38,  5.12it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▌                             | 3309/4733 [04:33<05:11,  4.57it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▌                             | 3310/4733 [04:33<05:44,  4.12it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▌                             | 3311/4733 [04:34<06:12,  3.81it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▌                             | 3312/4733 [04:34<06:35,  3.60it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▌                             | 3313/4733 [04:34<06:52,  3.44it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▋                             | 3315/4733 [04:35<05:42,  4.13it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▋                             | 3316/4733 [04:35<06:10,  3.83it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▋                             | 3317/4733 [04:35<06:32,  3.60it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▋                             | 3318/4733 [04:36<06:50,  3.44it/s]

{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▋                             | 3320/4733 [04:36<05:37,  4.19it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▊                             | 3321/4733 [04:36<06:05,  3.86it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▊                             | 3322/4733 [04:37<06:28,  3.63it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▊                             | 3323/4733 [04:37<06:46,  3.47it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▊                             | 3325/4733 [04:37<05:39,  4.15it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 70%|████████████████████████████████████████████████████████████████████▉                             | 3330/4733 [04:38<03:01,  7.73it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6}
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 6]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 18, 14: 17, 15: 14, 16: 16, 17: 19, 18: 21, 19: 20, 20: 22, 21: 10, 22: 12, 23: 7, 24: 9}
[0, 1, 2, 6, 7, 8, 23, 9, 24, 21, 10, 22, 11, 15, 12, 16, 14, 13, 17, 19, 18, 20, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]

 71%|█████████████████████████████████████████████████████████████████████▏                            | 3340/4733 [04:38<01:16, 18.27it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]

 71%|█████████████████████████████████████████████████████████████████████▎                            | 3348/4733 [04:38<00:57, 24.09it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 35, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 32, 31, 35, 33, 36, 34, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 33, 33: 36, 34: 38, 35: 35, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 32}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 46, 32, 31, 35, 33, 36, 34, 37, 40, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 39, 33: 41, 34: 37, 35: 40, 36: 43, 37: 46, 38: 44, 39: 47, 40: 32, 41: 35, 42: 38, 43: 42, 44: 45, 45: 31, 46: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 45, 40, 30, 46, 41, 31, 34, 42, 32, 35, 33, 43, 36, 38, 44, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 71%|█████████████████████████████████████████████████████████████████████▍                            | 3352/4733 [04:39<01:22, 16.68it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 106, 102: 108, 103: 111, 104: 113, 105: 109, 106: 112, 107: 116, 108: 118, 109: 117, 110: 119, 111: 105, 112: 107, 113: 110, 114: 114, 115: 115, 116: 103, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 116, 100, 111, 101, 112, 102, 105, 113, 103, 106, 104, 114, 115, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 71%|█████████████████████████████████████████████████████████████████████▌                            | 3359/4733 [04:39<01:46, 12.84it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]

 71%|█████████████████████████████████████████████████████████████████████▋                            | 3365/4733 [04:40<01:23, 16.32it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 9, 12: 12, 13: 10, 14: 13, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 9, 11, 13, 10, 12, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 71%|█████████████████████████████████████████████████████████████████████▋                            | 3368/4733 [04:40<01:40, 13.56it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 71%|█████████████████████████████████████████████████████████████████████▊                            | 3373/4733 [04:41<01:50, 12.34it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 13, 12: 16, 13: 19, 14: 14, 15: 11, 16: 15, 17: 17, 18: 20, 19: 22, 20: 18, 21: 21, 22: 23, 23: 25, 24: 24, 25: 26}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 15, 10, 11, 14, 16, 12, 17, 20, 13, 18, 21, 19, 22, 24, 23, 25]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 71%|█████████████████████████████████████████████████████████████████████▉                            | 3379/4733 [04:41<01:38, 13.78it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 23, 4: 24, 5: 25, 6: 4, 7: 5, 8: 6, 9: 9, 10: 8, 11: 11, 12: 13, 13: 10, 14: 12, 15: 14, 16: 16, 17: 18, 18: 15, 19: 17, 20: 19, 21: 21, 22: 20, 23: 22, 24: 7}
[0, 1, 2, 6, 7, 8, 24, 10, 9, 13, 11, 14, 12, 15, 18, 16, 19, 17, 20, 22, 21, 23, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 72%|██████████████████████████████████████████████████████████████████████▏                           | 3387/4733 [04:41<01:03, 21.09it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 72%|██████████████████████████████████████████████████████████████████████▏                           | 3390/4733 [04:42<01:33, 14.41it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 72%|██████████████████████████████████████████████████████████████████████▎                           | 3393/4733 [04:42<01:42, 13.08it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 72%|██████████████████████████████████████████████████████████████████████▎                           | 3397/4733 [04:42<01:41, 13.11it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 72%|██████████████████████████████████████████████████████████████████████▍                           | 3401/4733 [04:43<01:41, 13.12it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 72%|██████████████████████████████████████████████████████████████████████▌                           | 3405/4733 [04:43<01:41, 13.12it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]

 72%|██████████████████████████████████████████████████████████████████████▌                           | 3410/4733 [04:43<01:17, 17.12it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 72%|██████████████████████████████████████████████████████████████████████▋                           | 3414/4733 [04:43<01:26, 15.22it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]

 72%|██████████████████████████████████████████████████████████████████████▊                           | 3420/4733 [04:43<00:54, 24.22it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 7, 6: 4, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 6, 3, 4, 5, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 8]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 72%|██████████████████████████████████████████████████████████████████████▉                           | 3423/4733 [04:44<01:13, 17.89it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 72%|██████████████████████████████████████████████████████████████████████▉                           | 3428/4733 [04:44<01:29, 14.59it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 72%|███████████████████████████████████████████████████████████████████████                           | 3430/4733 [04:44<01:31, 14.18it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 106, 112: 102, 113: 104, 114: 108, 115: 111, 116: 112, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 117, 111, 101, 114, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 106, 112: 102, 113: 104, 114: 108, 115: 111, 116: 112, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 117, 111, 101, 114, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 73%|███████████████████████████████████████████████████████████████████████                           | 3432/4733 [04:45<02:03, 10.54it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 106, 112: 102, 113: 104, 114: 108, 115: 111, 116: 112, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 117, 111, 101, 114, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 106, 112: 102, 113: 104, 114: 108, 115: 111, 116: 112, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 117, 111, 101, 114, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 73%|███████████████████████████████████████████████████████████████████████                           | 3434/4733 [04:45<02:48,  7.71it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 73%|███████████████████████████████████████████████████████████████████████▏                          | 3438/4733 [04:45<02:14,  9.60it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 73%|███████████████████████████████████████████████████████████████████████▏                          | 3440/4733 [04:46<02:04, 10.41it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 73%|███████████████████████████████████████████████████████████████████████▎                          | 3442/4733 [04:46<02:18,  9.31it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 106, 112: 102, 113: 104, 114: 108, 115: 111, 116: 112, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 117, 111, 101, 114, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 106, 112: 102, 113: 104, 114: 108, 115: 111, 116: 112, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 117, 111, 101, 114, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 106, 112: 102, 113: 104, 114: 108, 115: 111, 116: 112, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 117, 111, 101, 114, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 106, 112: 102, 113: 104, 114: 108, 115: 111, 116: 112, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 117, 111, 101, 114, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 73%|███████████████████████████████████████████████████████████████████████▎                          | 3444/4733 [04:46<03:40,  5.85it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 106, 112: 102, 113: 104, 114: 108, 115: 111, 116: 112, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 117, 111, 101, 114, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 106, 112: 102, 113: 104, 114: 108, 115: 111, 116: 112, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 117, 111, 101, 114, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 73%|███████████████████████████████████████████████████████████████████████▎                          | 3445/4733 [04:47<04:14,  5.06it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 106, 112: 102, 113: 104, 114: 108, 115: 111, 116: 112, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 117, 111, 101, 114, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 109, 103: 113, 104: 115, 105: 110, 106: 114, 107: 116, 108: 118, 109: 117, 110: 119, 111: 106, 112: 102, 113: 104, 114: 108, 115: 111, 116: 112, 117: 105, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 112, 100, 113, 117, 111, 101, 114, 102, 105, 115, 116, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 73%|███████████████████████████████████████████████████████████████████████▎                          | 3447/4733 [04:47<04:22,  4.91it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 73%|███████████████████████████████████████████████████████████████████████▍                          | 3450/4733 [04:48<03:02,  7.02it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 73%|███████████████████████████████████████████████████████████████████████▌                          | 3454/4733 [04:48<02:12,  9.64it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 73%|███████████████████████████████████████████████████████████████████████▌                          | 3456/4733 [04:48<02:38,  8.05it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 73%|███████████████████████████████████████████████████████████████████████▌                          | 3457/4733 [04:49<03:24,  6.23it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 73%|███████████████████████████████████████████████████████████████████████▋                          | 3460/4733 [04:49<03:13,  6.58it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 73%|███████████████████████████████████████████████████████████████████████▋                          | 3463/4733 [04:49<02:41,  7.86it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 73%|███████████████████████████████████████████████████████████████████████▊                          | 3467/4733 [04:50<02:03, 10.27it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 73%|███████████████████████████████████████████████████████████████████████▊                          | 3469/4733 [04:50<03:33,  5.91it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 105, 102: 102, 103: 104, 104: 107, 105: 110, 106: 112, 107: 109, 108: 106, 109: 108, 110: 111, 111: 113, 112: 115, 113: 116, 114: 114, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 102, 100, 103, 101, 108, 104, 109, 107, 105, 110, 106, 111, 114, 112, 113]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 73%|███████████████████████████████████████████████████████████████████████▉                          | 3472/4733 [04:51<03:14,  6.48it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 73%|███████████████████████████████████████████████████████████████████████▉                          | 3475/4733 [04:51<02:35,  8.07it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 74%|████████████████████████████████████████████████████████████████████████                          | 3479/4733 [04:51<02:02, 10.25it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 74%|████████████████████████████████████████████████████████████████████████                          | 3481/4733 [04:52<02:17,  9.10it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 74%|████████████████████████████████████████████████████████████████████████                          | 3483/4733 [04:52<02:04, 10.04it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 74%|████████████████████████████████████████████████████████████████████████▏                         | 3486/4733 [04:52<02:23,  8.70it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 74%|████████████████████████████████████████████████████████████████████████▏                         | 3487/4733 [04:52<03:14,  6.40it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 74%|████████████████████████████████████████████████████████████████████████▏                         | 3489/4733 [04:53<03:42,  5.59it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 74%|████████████████████████████████████████████████████████████████████████▎                         | 3493/4733 [04:53<02:21,  8.76it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 74%|████████████████████████████████████████████████████████████████████████▍                         | 3496/4733 [04:53<02:07,  9.73it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 74%|████████████████████████████████████████████████████████████████████████▍                         | 3498/4733 [04:54<03:00,  6.84it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 74%|████████████████████████████████████████████████████████████████████████▍                         | 3499/4733 [04:54<03:42,  5.54it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 74%|████████████████████████████████████████████████████████████████████████▍                         | 3500/4733 [04:55<04:19,  4.75it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 107, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 106, 112: 102, 113: 104, 114: 105, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 114, 111, 101, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 74%|████████████████████████████████████████████████████████████████████████▍                         | 3501/4733 [04:55<04:50,  4.24it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 74%|████████████████████████████████████████████████████████████████████████▌                         | 3503/4733 [04:55<04:17,  4.77it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 74%|████████████████████████████████████████████████████████████████████████▌                         | 3505/4733 [04:56<04:00,  5.11it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 74%|████████████████████████████████████████████████████████████████████████▌                         | 3507/4733 [04:56<04:08,  4.93it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 74%|████████████████████████████████████████████████████████████████████████▋                         | 3510/4733 [04:56<02:52,  7.10it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 74%|████████████████████████████████████████████████████████████████████████▋                         | 3513/4733 [04:57<02:27,  8.28it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 74%|████████████████████████████████████████████████████████████████████████▊                         | 3515/4733 [04:57<02:06,  9.59it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 74%|████████████████████████████████████████████████████████████████████████▊                         | 3517/4733 [04:57<03:39,  5.53it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 74%|████████████████████████████████████████████████████████████████████████▊                         | 3519/4733 [04:58<03:54,  5.18it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 74%|████████████████████████████████████████████████████████████████████████▉                         | 3522/4733 [04:58<02:55,  6.89it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 74%|████████████████████████████████████████████████████████████████████████▉                         | 3524/4733 [04:58<02:50,  7.08it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 74%|█████████████████████████████████████████████████████████████████████████                         | 3526/4733 [04:59<02:17,  8.77it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 75%|█████████████████████████████████████████████████████████████████████████                         | 3527/4733 [04:59<03:16,  6.13it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 75%|█████████████████████████████████████████████████████████████████████████                         | 3528/4733 [04:59<04:05,  4.90it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 75%|█████████████████████████████████████████████████████████████████████████                         | 3530/4733 [05:00<03:49,  5.23it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 75%|█████████████████████████████████████████████████████████████████████████▏                        | 3532/4733 [05:00<04:01,  4.98it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 75%|█████████████████████████████████████████████████████████████████████████▏                        | 3534/4733 [05:00<03:26,  5.80it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 75%|█████████████████████████████████████████████████████████████████████████▎                        | 3538/4733 [05:01<02:11,  9.08it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 75%|█████████████████████████████████████████████████████████████████████████▎                        | 3540/4733 [05:01<01:57, 10.14it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 113, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 103, 109, 112, 104, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 75%|█████████████████████████████████████████████████████████████████████████▍                        | 3544/4733 [05:02<02:53,  6.87it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 75%|█████████████████████████████████████████████████████████████████████████▍                        | 3548/4733 [05:02<02:09,  9.16it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 75%|█████████████████████████████████████████████████████████████████████████▌                        | 3552/4733 [05:02<01:48, 10.86it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 75%|█████████████████████████████████████████████████████████████████████████▋                        | 3556/4733 [05:03<01:38, 11.95it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 75%|█████████████████████████████████████████████████████████████████████████▋                        | 3560/4733 [05:03<01:33, 12.49it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 75%|█████████████████████████████████████████████████████████████████████████▊                        | 3564/4733 [05:03<01:31, 12.79it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 75%|█████████████████████████████████████████████████████████████████████████▊                        | 3566/4733 [05:03<01:30, 12.91it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 75%|█████████████████████████████████████████████████████████████████████████▉                        | 3568/4733 [05:04<02:58,  6.53it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 75%|█████████████████████████████████████████████████████████████████████████▉                        | 3570/4733 [05:04<03:04,  6.32it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 75%|█████████████████████████████████████████████████████████████████████████▉                        | 3572/4733 [05:05<03:26,  5.63it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 76%|██████████████████████████████████████████████████████████████████████████                        | 3574/4733 [05:05<03:05,  6.23it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 76%|██████████████████████████████████████████████████████████████████████████                        | 3576/4733 [05:05<02:52,  6.70it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 76%|██████████████████████████████████████████████████████████████████████████▏                       | 3580/4733 [05:06<01:56,  9.86it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 116, 111: 115, 112: 112, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 112, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▏                       | 3582/4733 [05:06<03:28,  5.52it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 109, 114: 102, 115: 104, 116: 108, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 102, 116, 113, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 109, 114: 102, 115: 104, 116: 108, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 102, 116, 113, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▏                       | 3583/4733 [05:07<04:01,  4.76it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 109, 114: 102, 115: 104, 116: 108, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 102, 116, 113, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 109, 114: 102, 115: 104, 116: 108, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 102, 116, 113, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▏                       | 3584/4733 [05:07<04:30,  4.24it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 109, 114: 102, 115: 104, 116: 108, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 102, 116, 113, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 109, 114: 102, 115: 104, 116: 108, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 102, 116, 113, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▏                       | 3585/4733 [05:07<04:55,  3.88it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 109, 114: 102, 115: 104, 116: 108, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 102, 116, 113, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 109, 114: 102, 115: 104, 116: 108, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 102, 116, 113, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▎                       | 3587/4733 [05:08<04:15,  4.49it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 109, 114: 102, 115: 104, 116: 108, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 102, 116, 113, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 109, 114: 102, 115: 104, 116: 108, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 102, 116, 113, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▎                       | 3589/4733 [05:08<04:10,  4.56it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▎                       | 3591/4733 [05:08<03:45,  5.06it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▎                       | 3592/4733 [05:09<04:17,  4.42it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▍                       | 3593/4733 [05:09<04:43,  4.03it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▍                       | 3595/4733 [05:09<04:04,  4.65it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▍                       | 3597/4733 [05:10<04:02,  4.69it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 109, 114: 102, 115: 104, 116: 108, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 102, 116, 113, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 107, 103: 110, 104: 113, 105: 115, 106: 111, 107: 114, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 109, 114: 102, 115: 104, 116: 108, 117: 112, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 102, 116, 113, 103, 106, 117, 104, 107, 105, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▍                       | 3598/4733 [05:10<04:35,  4.12it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 105, 104: 107, 105: 110, 106: 112, 107: 114, 108: 116, 109: 113, 110: 115, 111: 117, 112: 119, 113: 118, 114: 120, 115: 108, 116: 111, 117: 106, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 103, 117, 104, 115, 118, 105, 116, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 105, 104: 107, 105: 110, 106: 112, 107: 114, 108: 116, 109: 113, 110: 115, 111: 117, 112: 119, 113: 118, 114: 120, 115: 108, 116: 111, 117: 106, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 103, 117, 104, 115, 118, 105, 116, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▌                       | 3599/4733 [05:10<05:01,  3.76it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 105, 104: 107, 105: 110, 106: 112, 107: 114, 108: 116, 109: 113, 110: 115, 111: 117, 112: 119, 113: 118, 114: 120, 115: 108, 116: 111, 117: 106, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 103, 117, 104, 115, 118, 105, 116, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 105, 104: 107, 105: 110, 106: 112, 107: 114, 108: 116, 109: 113, 110: 115, 111: 117, 112: 119, 113: 118, 114: 120, 115: 108, 116: 111, 117: 106, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 103, 117, 104, 115, 118, 105, 116, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▌                       | 3601/4733 [05:11<04:14,  4.45it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 105, 104: 107, 105: 110, 106: 112, 107: 114, 108: 116, 109: 113, 110: 115, 111: 117, 112: 119, 113: 118, 114: 120, 115: 108, 116: 111, 117: 106, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 103, 117, 104, 115, 118, 105, 116, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 105, 104: 107, 105: 110, 106: 112, 107: 114, 108: 116, 109: 113, 110: 115, 111: 117, 112: 119, 113: 118, 114: 120, 115: 108, 116: 111, 117: 106, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 103, 117, 104, 115, 118, 105, 116, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▌                       | 3602/4733 [05:11<04:41,  4.02it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▋                       | 3605/4733 [05:12<03:46,  4.98it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 113, 105: 112, 106: 109, 107: 111, 108: 114, 109: 116, 110: 115, 111: 117, 112: 105, 113: 107, 114: 102, 115: 104, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 99, 114, 100, 115, 112, 101, 113, 102, 106, 103, 107, 105, 104, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▋                       | 3608/4733 [05:12<03:07,  6.00it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 76%|██████████████████████████████████████████████████████████████████████████▊                       | 3611/4733 [05:12<02:22,  7.89it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 105, 104: 107, 105: 110, 106: 112, 107: 114, 108: 116, 109: 113, 110: 115, 111: 117, 112: 119, 113: 118, 114: 120, 115: 108, 116: 111, 117: 106, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 103, 117, 104, 115, 118, 105, 116, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 105, 104: 107, 105: 110, 106: 112, 107: 114, 108: 116, 109: 113, 110: 115, 111: 117, 112: 119, 113: 118, 114: 120, 115: 108, 116: 111, 117: 106, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 103, 117, 104, 115, 118, 105, 116, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▊                       | 3612/4733 [05:13<03:11,  5.86it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 105, 104: 107, 105: 110, 106: 112, 107: 114, 108: 116, 109: 113, 110: 115, 111: 117, 112: 119, 113: 118, 114: 120, 115: 108, 116: 111, 117: 106, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 103, 117, 104, 115, 118, 105, 116, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 105, 104: 107, 105: 110, 106: 112, 107: 114, 108: 116, 109: 113, 110: 115, 111: 117, 112: 119, 113: 118, 114: 120, 115: 108, 116: 111, 117: 106, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 103, 117, 104, 115, 118, 105, 116, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▊                       | 3613/4733 [05:13<03:53,  4.80it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 105, 104: 107, 105: 110, 106: 112, 107: 114, 108: 116, 109: 113, 110: 115, 111: 117, 112: 119, 113: 118, 114: 120, 115: 108, 116: 111, 117: 106, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 103, 117, 104, 115, 118, 105, 116, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 103, 102: 104, 103: 105, 104: 107, 105: 110, 106: 112, 107: 114, 108: 116, 109: 113, 110: 115, 111: 117, 112: 119, 113: 118, 114: 120, 115: 108, 116: 111, 117: 106, 118: 109, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 100, 101, 102, 103, 117, 104, 115, 118, 105, 116, 106, 109, 107, 110, 108, 111, 113, 112, 114]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 76%|██████████████████████████████████████████████████████████████████████████▊                       | 3615/4733 [05:14<03:56,  4.73it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 76%|██████████████████████████████████████████████████████████████████████████▉                       | 3619/4733 [05:14<02:17,  8.10it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 77%|██████████████████████████████████████████████████████████████████████████▉                       | 3621/4733 [05:14<02:22,  7.79it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████                       | 3623/4733 [05:14<02:41,  6.87it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████                       | 3625/4733 [05:15<03:11,  5.77it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 77%|███████████████████████████████████████████████████████████████████████████▏                      | 3629/4733 [05:15<02:04,  8.89it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████▏                      | 3631/4733 [05:16<02:26,  7.54it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████▏                      | 3633/4733 [05:16<02:59,  6.14it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████▏                      | 3634/4733 [05:16<03:41,  4.97it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████▎                      | 3635/4733 [05:17<04:15,  4.30it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████▎                      | 3636/4733 [05:17<04:42,  3.89it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████▎                      | 3639/4733 [05:17<03:25,  5.33it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 77%|███████████████████████████████████████████████████████████████████████████▍                      | 3641/4733 [05:18<02:37,  6.92it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████▍                      | 3642/4733 [05:18<03:20,  5.45it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████▍                      | 3643/4733 [05:18<03:56,  4.61it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████▍                      | 3644/4733 [05:19<04:25,  4.10it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 115, 111: 110, 112: 114, 113: 116, 114: 118, 115: 117, 116: 119, 117: 102, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 117, 101, 100, 106, 102, 107, 103, 108, 111, 104, 105, 109, 112, 110, 113, 115, 114, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████▌                      | 3647/4733 [05:19<03:19,  5.45it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 77%|███████████████████████████████████████████████████████████████████████████▌                      | 3650/4733 [05:19<02:32,  7.10it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 77%|███████████████████████████████████████████████████████████████████████████▋                      | 3654/4733 [05:20<01:50,  9.79it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 103, 117: 106, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 116, 101, 112, 117, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 103, 117: 106, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 116, 101, 112, 117, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 103, 117: 106, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 116, 101, 112, 117, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 103, 117: 106, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 116, 101, 112, 117, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████▋                      | 3657/4733 [05:20<03:01,  5.94it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 77%|███████████████████████████████████████████████████████████████████████████▊                      | 3661/4733 [05:21<02:03,  8.67it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 77%|███████████████████████████████████████████████████████████████████████████▊                      | 3663/4733 [05:21<01:49,  9.74it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 77%|███████████████████████████████████████████████████████████████████████████▉                      | 3665/4733 [05:21<02:00,  8.86it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 103, 117: 106, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 116, 101, 112, 117, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 103, 117: 106, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 116, 101, 112, 117, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 103, 117: 106, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 116, 101, 112, 117, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 103, 117: 106, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 116, 101, 112, 117, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████▉                      | 3667/4733 [05:22<03:10,  5.60it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 103, 117: 106, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 116, 101, 112, 117, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 103, 117: 106, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 116, 101, 112, 117, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 77%|███████████████████████████████████████████████████████████████████████████▉                      | 3668/4733 [05:22<03:38,  4.88it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 103, 117: 106, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 116, 101, 112, 117, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 102, 101: 104, 102: 107, 103: 109, 104: 112, 105: 114, 106: 110, 107: 113, 108: 116, 109: 118, 110: 117, 111: 119, 112: 105, 113: 108, 114: 111, 115: 115, 116: 103, 117: 106, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 100, 116, 101, 112, 117, 102, 113, 103, 106, 114, 104, 107, 105, 115, 108, 110, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████                      | 3671/4733 [05:23<03:03,  5.79it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████                      | 3672/4733 [05:23<03:37,  4.88it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████                      | 3673/4733 [05:23<04:07,  4.28it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████                      | 3674/4733 [05:24<04:32,  3.89it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████                      | 3675/4733 [05:24<04:51,  3.63it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▏                     | 3677/4733 [05:24<04:04,  4.32it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 110, 104: 104, 105: 107, 106: 105, 107: 108, 108: 111, 109: 113, 110: 115, 111: 112, 112: 114, 113: 116, 114: 119, 115: 118, 116: 117, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 104, 106, 101, 105, 107, 102, 103, 108, 111, 109, 112, 110, 113, 116, 115, 114, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▏                     | 3679/4733 [05:25<03:56,  4.46it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 78%|████████████████████████████████████████████████████████████████████████████▎                     | 3683/4733 [05:25<02:16,  7.68it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 78%|████████████████████████████████████████████████████████████████████████████▎                     | 3687/4733 [05:25<01:44, 10.04it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▍                     | 3689/4733 [05:26<02:59,  5.82it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▍                     | 3690/4733 [05:26<03:29,  4.99it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▍                     | 3691/4733 [05:27<03:55,  4.42it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▍                     | 3693/4733 [05:27<03:33,  4.87it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 112, 104: 114, 105: 110, 106: 113, 107: 115, 108: 117, 109: 118, 110: 116, 111: 119, 112: 105, 113: 108, 114: 102, 115: 104, 116: 107, 117: 111, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 114, 100, 115, 112, 101, 116, 113, 102, 105, 117, 103, 106, 104, 107, 110, 108, 109, 111]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▌                     | 3695/4733 [05:27<03:36,  4.78it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 78%|████████████████████████████████████████████████████████████████████████████▌                     | 3698/4733 [05:28<02:37,  6.59it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 78%|████████████████████████████████████████████████████████████████████████████▋                     | 3702/4733 [05:28<01:48,  9.46it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 111, 104: 116, 105: 117, 106: 102, 107: 105, 108: 108, 109: 112, 110: 110, 111: 106, 112: 109, 113: 114, 114: 115, 115: 118, 116: 119, 117: 113, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 111, 102, 108, 112, 110, 103, 109, 117, 113, 114, 104, 105, 115, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 111, 104: 116, 105: 117, 106: 102, 107: 105, 108: 108, 109: 112, 110: 110, 111: 106, 112: 109, 113: 114, 114: 115, 115: 118, 116: 119, 117: 113, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 111, 102, 108, 112, 110, 103, 109, 117, 113, 114, 104, 105, 115, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 111, 104: 116, 105: 117, 106: 102, 107: 105, 108: 108, 109: 112, 110: 110, 111: 106, 112: 109, 113: 114, 114: 115, 115: 118, 116: 119, 117: 113, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 111, 102, 108, 112, 110, 103, 109, 117, 113, 114, 104, 105, 115, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 111, 104: 116, 105: 117, 106: 102, 107: 105, 108: 108, 109: 112, 110: 110, 111: 106, 112: 109, 113: 114, 114: 115, 115: 118, 116: 119, 117: 113, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 111, 102, 108, 112, 110, 103, 109, 117, 113, 114, 104, 105, 115, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▋                     | 3704/4733 [05:29<03:04,  5.57it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 111, 104: 116, 105: 117, 106: 102, 107: 105, 108: 108, 109: 112, 110: 110, 111: 106, 112: 109, 113: 114, 114: 115, 115: 118, 116: 119, 117: 113, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 111, 102, 108, 112, 110, 103, 109, 117, 113, 114, 104, 105, 115, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 111, 104: 116, 105: 117, 106: 102, 107: 105, 108: 108, 109: 112, 110: 110, 111: 106, 112: 109, 113: 114, 114: 115, 115: 118, 116: 119, 117: 113, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 111, 102, 108, 112, 110, 103, 109, 117, 113, 114, 104, 105, 115, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▋                     | 3705/4733 [05:29<03:33,  4.82it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 111, 104: 116, 105: 117, 106: 102, 107: 105, 108: 108, 109: 112, 110: 110, 111: 106, 112: 109, 113: 114, 114: 115, 115: 118, 116: 119, 117: 113, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 111, 102, 108, 112, 110, 103, 109, 117, 113, 114, 104, 105, 115, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 111, 104: 116, 105: 117, 106: 102, 107: 105, 108: 108, 109: 112, 110: 110, 111: 106, 112: 109, 113: 114, 114: 115, 115: 118, 116: 119, 117: 113, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 111, 102, 108, 112, 110, 103, 109, 117, 113, 114, 104, 105, 115, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▋                     | 3706/4733 [05:29<03:59,  4.29it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 111, 104: 116, 105: 117, 106: 102, 107: 105, 108: 108, 109: 112, 110: 110, 111: 106, 112: 109, 113: 114, 114: 115, 115: 118, 116: 119, 117: 113, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 111, 102, 108, 112, 110, 103, 109, 117, 113, 114, 104, 105, 115, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 111, 104: 116, 105: 117, 106: 102, 107: 105, 108: 108, 109: 112, 110: 110, 111: 106, 112: 109, 113: 114, 114: 115, 115: 118, 116: 119, 117: 113, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 111, 102, 108, 112, 110, 103, 109, 117, 113, 114, 104, 105, 115, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▊                     | 3708/4733 [05:30<03:33,  4.79it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 111, 104: 116, 105: 117, 106: 102, 107: 105, 108: 108, 109: 112, 110: 110, 111: 106, 112: 109, 113: 114, 114: 115, 115: 118, 116: 119, 117: 113, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 111, 102, 108, 112, 110, 103, 109, 117, 113, 114, 104, 105, 115, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 104, 102: 107, 103: 111, 104: 116, 105: 117, 106: 102, 107: 105, 108: 108, 109: 112, 110: 110, 111: 106, 112: 109, 113: 114, 114: 115, 115: 118, 116: 119, 117: 113, 118: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 118, 99, 106, 100, 101, 107, 111, 102, 108, 112, 110, 103, 109, 117, 113, 114, 104, 105, 115, 116]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▊                     | 3710/4733 [05:30<03:35,  4.75it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▊                     | 3711/4733 [05:30<04:05,  4.17it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▉                     | 3713/4733 [05:31<03:35,  4.74it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 78%|████████████████████████████████████████████████████████████████████████████▉                     | 3715/4733 [05:31<03:36,  4.71it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 79%|█████████████████████████████████████████████████████████████████████████████                     | 3719/4733 [05:32<02:08,  7.91it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 79%|█████████████████████████████████████████████████████████████████████████████                     | 3721/4733 [05:32<02:12,  7.61it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 79%|█████████████████████████████████████████████████████████████████████████████                     | 3723/4733 [05:32<02:14,  7.50it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 79%|█████████████████████████████████████████████████████████████████████████████                     | 3724/4733 [05:32<03:07,  5.37it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 79%|█████████████████████████████████████████████████████████████████████████████▏                    | 3725/4733 [05:33<03:47,  4.43it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 109, 103: 113, 104: 110, 105: 104, 106: 107, 107: 105, 108: 108, 109: 111, 110: 114, 111: 116, 112: 112, 113: 115, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 100, 105, 107, 101, 106, 108, 102, 104, 109, 112, 103, 110, 113, 111, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 79%|█████████████████████████████████████████████████████████████████████████████▏                    | 3727/4733 [05:33<03:41,  4.54it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 79%|█████████████████████████████████████████████████████████████████████████████▎                    | 3731/4733 [05:34<02:04,  8.07it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 79%|█████████████████████████████████████████████████████████████████████████████▎                    | 3735/4733 [05:34<01:36, 10.38it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 79%|█████████████████████████████████████████████████████████████████████████████▍                    | 3737/4733 [05:34<02:50,  5.83it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 79%|█████████████████████████████████████████████████████████████████████████████▍                    | 3738/4733 [05:35<03:20,  4.97it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 79%|█████████████████████████████████████████████████████████████████████████████▍                    | 3739/4733 [05:35<03:46,  4.38it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 79%|█████████████████████████████████████████████████████████████████████████████▍                    | 3741/4733 [05:35<03:25,  4.82it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 116, 107: 105, 108: 107, 109: 109, 110: 113, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 107, 102, 108, 103, 109, 112, 104, 105, 110, 113, 111, 106, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 79%|█████████████████████████████████████████████████████████████████████████████▌                    | 3744/4733 [05:36<02:51,  5.76it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 79%|█████████████████████████████████████████████████████████████████████████████▌                    | 3748/4733 [05:36<01:56,  8.45it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 79%|█████████████████████████████████████████████████████████████████████████████▋                    | 3750/4733 [05:36<01:42,  9.55it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 79%|█████████████████████████████████████████████████████████████████████████████▋                    | 3752/4733 [05:37<02:51,  5.72it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 79%|█████████████████████████████████████████████████████████████████████████████▋                    | 3754/4733 [05:37<02:50,  5.75it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 79%|█████████████████████████████████████████████████████████████████████████████▊                    | 3756/4733 [05:38<03:03,  5.31it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 79%|█████████████████████████████████████████████████████████████████████████████▊                    | 3759/4733 [05:38<02:20,  6.93it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 10, 7: 11, 8: 13, 9: 16, 10: 18, 11: 19, 12: 20, 13: 21, 14: 22, 15: 23, 16: 24, 17: 25, 18: 26, 19: 27, 20: 28, 21: 29, 22: 31, 23: 34, 24: 36, 25: 39, 26: 41, 27: 37, 28: 40, 29: 45, 30: 47, 31: 46, 32: 48, 33: 32, 34: 35, 35: 38, 36: 42, 37: 43, 38: 44, 39: 30, 40: 33, 41: 14, 42: 17, 43: 12, 44: 15, 45: 4, 46: 5, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 65, 63: 67, 64: 61, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53}
[0, 4, 5, 45, 46, 47, 1, 2, 3, 6, 7, 43, 8, 41, 44, 9, 42, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 39, 22, 33, 40, 23, 34, 24, 27, 35, 25, 28, 26, 36, 37, 38, 29, 31, 30, 32, 48, 49, 50, 51, 70, 53, 52, 58, 54, 59, 55, 60, 64, 56, 57, 61, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 3, 4, 5, 6, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 10, 7: 11, 8: 13, 9: 16, 10: 18, 11: 19, 12: 20, 13: 21, 14: 22, 15: 23, 16: 24, 17: 25, 18: 26, 19: 27, 20: 28, 21: 29, 22: 31, 23: 34, 24: 36, 25: 39, 26: 41, 27: 37, 28: 40, 29: 45, 30: 47, 31: 46, 32: 48, 33: 32, 34: 35, 35: 38, 36: 42, 37: 43, 38: 44, 39: 30, 40: 33, 41: 14, 42: 17, 43: 12, 44: 15, 45: 4, 46: 5, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 65, 63: 67, 64: 61, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 53}
[0, 4, 5, 45, 46, 47, 1, 2, 3, 6, 7, 43, 8, 41, 44, 9, 42, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 39, 22, 33, 40, 23, 34, 24, 27, 35, 25, 28, 26, 36, 37, 38, 29, 31, 30, 32, 48, 49, 50, 51, 70, 53, 52, 58, 54, 59, 55, 60, 64, 56, 57, 61, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 3, 4, 5, 6, 49, 50]

 79%|█████████████████████████████████████████████████████████████████████████████▊                    | 3761/4733 [05:38<02:13,  7.29it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 80%|█████████████████████████████████████████████████████████████████████████████▉                    | 3764/4733 [05:39<02:21,  6.85it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 80%|█████████████████████████████████████████████████████████████████████████████▉                    | 3765/4733 [05:39<03:04,  5.25it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 104, 101: 103, 102: 106, 103: 108, 104: 111, 105: 112, 106: 105, 107: 107, 108: 109, 109: 113, 110: 116, 111: 115, 112: 110, 113: 114, 114: 117, 115: 119, 116: 118, 117: 120, 118: 102, 119: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 119, 99, 118, 101, 100, 106, 102, 107, 103, 108, 112, 104, 105, 109, 113, 111, 110, 114, 116, 115, 117]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 80%|█████████████████████████████████████████████████████████████████████████████▉                    | 3767/4733 [05:40<03:15,  4.95it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 80%|██████████████████████████████████████████████████████████████████████████████                    | 3768/4733 [05:40<03:46,  4.27it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 80%|██████████████████████████████████████████████████████████████████████████████                    | 3769/4733 [05:40<04:09,  3.87it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 80%|██████████████████████████████████████████████████████████████████████████████                    | 3770/4733 [05:41<04:25,  3.63it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 80%|██████████████████████████████████████████████████████████████████████████████                    | 3771/4733 [05:41<04:36,  3.47it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 80%|██████████████████████████████████████████████████████████████████████████████                    | 3773/4733 [05:41<03:43,  4.29it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 102, 100: 105, 101: 109, 102: 111, 103: 106, 104: 110, 105: 113, 106: 116, 107: 114, 108: 117, 109: 101, 110: 104, 111: 108, 112: 112, 113: 115, 114: 103, 115: 107, 116: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 116, 109, 99, 114, 110, 100, 103, 115, 111, 101, 104, 102, 112, 105, 107, 113, 106, 108]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 80%|██████████████████████████████████████████████████████████████████████████████▏                   | 3777/4733 [05:42<02:28,  6.45it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 80%|██████████████████████████████████████████████████████████████████████████████▎                   | 3781/4733 [05:42<01:46,  8.91it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 80%|██████████████████████████████████████████████████████████████████████████████▎                   | 3783/4733 [05:43<02:20,  6.78it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 80%|██████████████████████████████████████████████████████████████████████████████▍                   | 3787/4733 [05:43<01:44,  9.07it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 80%|██████████████████████████████████████████████████████████████████████████████▍                   | 3791/4733 [05:43<01:27, 10.80it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 80%|██████████████████████████████████████████████████████████████████████████████▌                   | 3793/4733 [05:43<01:39,  9.48it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 80%|██████████████████████████████████████████████████████████████████████████████▋                   | 3798/4733 [05:44<01:19, 11.78it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 80%|██████████████████████████████████████████████████████████████████████████████▋                   | 3800/4733 [05:44<01:17, 12.11it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 80%|██████████████████████████████████████████████████████████████████████████████▊                   | 3804/4733 [05:44<01:24, 10.97it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 80%|██████████████████████████████████████████████████████████████████████████████▊                   | 3806/4733 [05:44<01:20, 11.52it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 80%|██████████████████████████████████████████████████████████████████████████████▉                   | 3810/4733 [05:45<01:26, 10.69it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 81%|██████████████████████████████████████████████████████████████████████████████▉                   | 3814/4733 [05:45<01:17, 11.83it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 81%|███████████████████████████████████████████████████████████████████████████████                   | 3818/4733 [05:46<01:13, 12.45it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 81%|███████████████████████████████████████████████████████████████████████████████                   | 3820/4733 [05:46<01:28, 10.32it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 81%|███████████████████████████████████████████████████████████████████████████████▏                  | 3824/4733 [05:46<01:18, 11.58it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 81%|███████████████████████████████████████████████████████████████████████████████▎                  | 3828/4733 [05:46<01:13, 12.36it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 81%|███████████████████████████████████████████████████████████████████████████████▎                  | 3830/4733 [05:47<01:27, 10.29it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 81%|███████████████████████████████████████████████████████████████████████████████▎                  | 3832/4733 [05:47<02:26,  6.14it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 81%|███████████████████████████████████████████████████████████████████████████████▎                  | 3833/4733 [05:48<02:51,  5.26it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 81%|███████████████████████████████████████████████████████████████████████████████▍                  | 3835/4733 [05:48<02:43,  5.49it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 102, 113: 104, 114: 107, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 112, 100, 113, 111, 101, 114, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 81%|███████████████████████████████████████████████████████████████████████████████▍                  | 3837/4733 [05:48<02:52,  5.19it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 81%|███████████████████████████████████████████████████████████████████████████████▌                  | 3841/4733 [05:49<01:41,  8.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 81%|███████████████████████████████████████████████████████████████████████████████▌                  | 3844/4733 [05:49<01:16, 11.63it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 62, 57: 63, 58: 56, 59: 58, 60: 60, 61: 64, 62: 66, 63: 61, 64: 65, 65: 67, 66: 69, 67: 68, 68: 70, 69: 53, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 69, 53, 52, 58, 54, 59, 55, 60, 63, 56, 57, 61, 64, 62, 65, 67, 66, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 72]

 81%|███████████████████████████████████████████████████████████████████████████████▋                  | 3849/4733 [05:49<01:12, 12.12it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 81%|███████████████████████████████████████████████████████████████████████████████▊                  | 3852/4733 [05:49<01:01, 14.26it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 81%|███████████████████████████████████████████████████████████████████████████████▊                  | 3857/4733 [05:50<00:59, 14.80it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 58, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 59, 55: 56, 56: 57, 57: 60, 58: 61, 59: 63, 60: 65, 61: 62, 62: 64, 63: 66, 64: 68, 65: 67, 66: 69, 67: 54, 68: 58, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 67, 53, 55, 56, 68, 54, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 82%|███████████████████████████████████████████████████████████████████████████████▉                  | 3860/4733 [05:50<01:01, 14.14it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 57, 53: 60, 54: 63, 55: 65, 56: 61, 57: 64, 58: 67, 59: 69, 60: 68, 61: 70, 62: 56, 63: 59, 64: 62, 65: 66, 66: 55, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 66, 62, 52, 67, 63, 53, 56, 64, 54, 57, 55, 65, 58, 60, 59, 61]
[1, 49, 50]

 82%|███████████████████████████████████████████████████████████████████████████████▉                  | 3862/4733 [05:50<01:03, 13.63it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 29, 24: 30, 25: 31, 26: 24, 27: 25, 28: 26, 29: 27, 30: 32, 31: 33, 32: 35, 33: 38, 34: 40, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 53, 47: 56, 48: 58, 49: 61, 50: 63, 51: 59, 52: 62, 53: 67, 54: 69, 55: 68, 56: 70, 57: 54, 58: 57, 59: 60, 60: 64, 61: 65, 62: 66, 63: 52, 64: 55, 65: 36, 66: 39, 67: 34, 68: 37, 69: 28}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 26, 27, 28, 29, 69, 23, 24, 25, 30, 31, 67, 32, 65, 68, 33, 66, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 63, 46, 57, 64, 47, 58, 48, 51, 59, 49, 52, 50, 60, 61, 62, 53, 55, 54, 56]
[1, 2, 23, 24, 25, 26, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 82%|████████████████████████████████████████████████████████████████████████████████                  | 3866/4733 [05:50<01:04, 13.42it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 82%|████████████████████████████████████████████████████████████████████████████████                  | 3868/4733 [05:51<01:19, 10.95it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 82%|████████████████████████████████████████████████████████████████████████████████▏                 | 3874/4733 [05:51<01:01, 13.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 3, 4]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 3, 4]

 82%|████████████████████████████████████████████████████████████████████████████████▎                 | 3879/4733 [05:51<00:43, 19.43it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 82%|████████████████████████████████████████████████████████████████████████████████▍                 | 3884/4733 [05:51<00:50, 16.73it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 82%|████████████████████████████████████████████████████████████████████████████████▌                 | 3891/4733 [05:52<00:40, 20.91it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]

 82%|████████████████████████████████████████████████████████████████████████████████▋                 | 3897/4733 [05:52<00:34, 24.03it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 47, 39: 48, 40: 49, 41: 50, 42: 40, 43: 43, 44: 30, 45: 34, 46: 38, 47: 36, 48: 32, 49: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 44, 29, 48, 30, 45, 49, 47, 31, 46, 32, 42, 33, 36, 43, 34, 37, 35, 38, 39, 40, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 39, 33: 41, 34: 35, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 36, 42: 37, 43: 42, 44: 33, 45: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 40, 44, 31, 34, 41, 42, 45, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 34, 32: 39, 33: 41, 34: 35, 35: 40, 36: 43, 37: 45, 38: 44, 39: 46, 40: 32, 41: 36, 42: 37, 43: 42, 44: 33, 45: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 40, 44, 31, 34, 41, 42, 45, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 82%|████████████████████████████████████████████████████████████████████████████████▊                 | 3903/4733 [05:52<00:33, 24.60it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 32, 32: 33, 33: 34, 34: 36, 35: 39, 36: 41, 37: 43, 38: 45, 39: 42, 40: 44, 41: 46, 42: 48, 43: 47, 44: 49, 45: 37, 46: 40, 47: 35, 48: 38}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 31, 32, 33, 47, 34, 45, 48, 35, 46, 36, 39, 37, 40, 38, 41, 43, 42, 44]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 3, 4]

 83%|████████████████████████████████████████████████████████████████████████████████▉                 | 3908/4733 [05:52<00:34, 23.68it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 3, 4]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 3, 4]

 83%|█████████████████████████████████████████████████████████████████████████████████                 | 3914/4733 [05:53<00:32, 24.82it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 12, 11: 16, 12: 13, 13: 14, 14: 17, 15: 18, 16: 20, 17: 22, 18: 19, 19: 21, 20: 23, 21: 25, 22: 24, 23: 26, 24: 11, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 24, 10, 12, 13, 25, 11, 14, 15, 18, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 83%|█████████████████████████████████████████████████████████████████████████████████                 | 3918/4733 [05:53<00:34, 23.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20]
[1, 2, 21]

 83%|█████████████████████████████████████████████████████████████████████████████████▏                | 3922/4733 [05:53<00:34, 23.50it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 3, 4]

 83%|█████████████████████████████████████████████████████████████████████████████████▍                | 3932/4733 [05:53<00:29, 27.10it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 3, 4]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 3, 4]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]

 83%|█████████████████████████████████████████████████████████████████████████████████▌                | 3937/4733 [05:53<00:26, 30.04it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 83%|█████████████████████████████████████████████████████████████████████████████████▌                | 3941/4733 [05:54<00:29, 26.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 83%|█████████████████████████████████████████████████████████████████████████████████▊                | 3949/4733 [05:54<00:28, 27.38it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 9, 8: 12, 9: 15, 10: 10, 11: 7, 12: 11, 13: 13, 14: 16, 15: 18, 16: 14, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 11, 6, 7, 10, 12, 8, 13, 16, 9, 14, 17, 15, 18, 20, 19, 21, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 84%|█████████████████████████████████████████████████████████████████████████████████▊                | 3953/4733 [05:54<00:31, 24.69it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 84%|██████████████████████████████████████████████████████████████████████████████████                | 3961/4733 [05:54<00:28, 26.68it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 84%|██████████████████████████████████████████████████████████████████████████████████▏               | 3967/4733 [05:55<00:36, 20.83it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 8, 7: 12, 8: 9, 9: 10, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 7, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 20, 6, 8, 9, 21, 7, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 84%|██████████████████████████████████████████████████████████████████████████████████▏               | 3970/4733 [05:55<00:46, 16.45it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 84%|██████████████████████████████████████████████████████████████████████████████████▎               | 3974/4733 [05:55<00:50, 14.91it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 57, 55: 60, 56: 64, 57: 66, 58: 61, 59: 65, 60: 68, 61: 70, 62: 69, 63: 71, 64: 56, 65: 59, 66: 63, 67: 67, 68: 55, 69: 58, 70: 62}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 64, 54, 69, 65, 55, 58, 70, 66, 56, 59, 57, 67, 60, 62, 61, 63]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 57, 55: 60, 56: 64, 57: 66, 58: 61, 59: 65, 60: 68, 61: 70, 62: 69, 63: 71, 64: 56, 65: 59, 66: 63, 67: 67, 68: 55, 69: 58, 70: 62}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 64, 54, 69, 65, 55, 58, 70, 66, 56, 59, 57, 67, 60, 62, 61, 63]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 84%|██████████████████████████████████████████████████████████████████████████████████▍               | 3979/4733 [05:56<00:51, 14.78it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 84%|██████████████████████████████████████████████████████████████████████████████████▌               | 3985/4733 [05:56<00:47, 15.70it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 49, 23: 50, 24: 51, 25: 23, 26: 24, 27: 27, 28: 28, 29: 29, 30: 31, 31: 34, 32: 37, 33: 42, 34: 44, 35: 38, 36: 43, 37: 45, 38: 47, 39: 46, 40: 48, 41: 33, 42: 36, 43: 30, 44: 32, 45: 35, 46: 39, 47: 40, 48: 41, 49: 25, 50: 26}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 25, 26, 49, 50, 27, 28, 29, 43, 30, 44, 41, 31, 45, 42, 32, 35, 46, 47, 48, 33, 36, 34, 37, 39, 38, 40, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 49, 23: 50, 24: 51, 25: 23, 26: 24, 27: 27, 28: 28, 29: 29, 30: 31, 31: 34, 32: 37, 33: 42, 34: 44, 35: 38, 36: 43, 37: 45, 38: 47, 39: 46, 40: 48, 41: 33, 42: 36, 43: 30, 44: 32, 45: 35, 46: 39, 47: 40, 48: 41, 49: 25, 50: 26}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 25, 26, 49, 50, 27, 28, 29, 43, 30, 44, 41, 31, 45, 42, 32, 35, 46, 47, 48, 33, 36, 34, 37, 39, 38, 40, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 84%|██████████████████████████████████████████████████████████████████████████████████▌               | 3987/4733 [05:56<00:52, 14.26it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 57, 55: 60, 56: 64, 57: 66, 58: 61, 59: 65, 60: 68, 61: 70, 62: 69, 63: 71, 64: 56, 65: 59, 66: 63, 67: 67, 68: 55, 69: 58, 70: 62}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 64, 54, 69, 65, 55, 58, 70, 66, 56, 59, 57, 67, 60, 62, 61, 63]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 57, 55: 60, 56: 64, 57: 66, 58: 61, 59: 65, 60: 68, 61: 70, 62: 69, 63: 71, 64: 56, 65: 59, 66: 63, 67: 67, 68: 55, 69: 58, 70: 62}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 64, 54, 69, 65, 55, 58, 70, 66, 56, 59, 57, 67, 60, 62, 61, 63]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 84%|██████████████████████████████████████████████████████████████████████████████████▌               | 3990/4733 [05:57<00:53, 13.80it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 57, 55: 60, 56: 64, 57: 66, 58: 61, 59: 65, 60: 68, 61: 70, 62: 69, 63: 71, 64: 56, 65: 59, 66: 63, 67: 67, 68: 55, 69: 58, 70: 62}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 64, 54, 69, 65, 55, 58, 70, 66, 56, 59, 57, 67, 60, 62, 61, 63]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 57, 55: 60, 56: 64, 57: 66, 58: 61, 59: 65, 60: 68, 61: 70, 62: 69, 63: 71, 64: 56, 65: 59, 66: 63, 67: 67, 68: 55, 69: 58, 70: 62}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 68, 64, 54, 69, 65, 55, 58, 70, 66, 56, 59, 57, 67, 60, 62, 61, 63]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 84%|██████████████████████████████████████████████████████████████████████████████████▋               | 3993/4733 [05:57<00:46, 15.82it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 49, 23: 50, 24: 51, 25: 23, 26: 24, 27: 27, 28: 28, 29: 29, 30: 31, 31: 34, 32: 37, 33: 42, 34: 44, 35: 38, 36: 43, 37: 45, 38: 47, 39: 46, 40: 48, 41: 33, 42: 36, 43: 30, 44: 32, 45: 35, 46: 39, 47: 40, 48: 41, 49: 25, 50: 26}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 25, 26, 49, 50, 27, 28, 29, 43, 30, 44, 41, 31, 45, 42, 32, 35, 46, 47, 48, 33, 36, 34, 37, 39, 38, 40, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 49, 23: 50, 24: 51, 25: 23, 26: 24, 27: 27, 28: 28, 29: 29, 30: 31, 31: 34, 32: 37, 33: 42, 34: 44, 35: 38, 36: 43, 37: 45, 38: 47, 39: 46, 40: 48, 41: 33, 42: 36, 43: 30, 44: 32, 45: 35, 46: 39, 47: 40, 48: 41, 49: 25, 50: 26}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 25, 26, 49, 50, 27, 28, 29, 43, 30, 44, 41, 31, 45, 42, 32, 35, 46, 47, 48, 33, 36, 34, 37, 39, 38, 40, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 84%|██████████████████████████████████████████████████████████████████████████████████▊               | 3998/4733 [05:57<00:50, 14.62it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 49, 23: 50, 24: 51, 25: 23, 26: 24, 27: 27, 28: 28, 29: 29, 30: 31, 31: 34, 32: 37, 33: 42, 34: 44, 35: 38, 36: 43, 37: 45, 38: 47, 39: 46, 40: 48, 41: 33, 42: 36, 43: 30, 44: 32, 45: 35, 46: 39, 47: 40, 48: 41, 49: 25, 50: 26}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 25, 26, 49, 50, 27, 28, 29, 43, 30, 44, 41, 31, 45, 42, 32, 35, 46, 47, 48, 33, 36, 34, 37, 39, 38, 40, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 49, 23: 50, 24: 51, 25: 23, 26: 24, 27: 27, 28: 28, 29: 29, 30: 31, 31: 34, 32: 37, 33: 42, 34: 44, 35: 38, 36: 43, 37: 45, 38: 47, 39: 46, 40: 48, 41: 33, 42: 36, 43: 30, 44: 32, 45: 35, 46: 39, 47: 40, 48: 41, 49: 25, 50: 26}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 25, 26, 49, 50, 27, 28, 29, 43, 30, 44, 41, 31, 45, 42, 32, 35, 46, 47, 48, 33, 36, 34, 37, 39, 38, 40, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 85%|██████████████████████████████████████████████████████████████████████████████████▊               | 4000/4733 [05:57<00:51, 14.22it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 85%|██████████████████████████████████████████████████████████████████████████████████▉               | 4004/4733 [05:58<00:53, 13.67it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 85%|██████████████████████████████████████████████████████████████████████████████████▉               | 4008/4733 [05:58<00:57, 12.59it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 58, 58: 61, 59: 59, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 56}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 70, 55, 57, 59, 56, 58, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 58, 58: 61, 59: 59, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 56}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 70, 55, 57, 59, 56, 58, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]

 85%|███████████████████████████████████████████████████████████████████████████████████               | 4010/4733 [05:58<00:56, 12.71it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 85%|███████████████████████████████████████████████████████████████████████████████████               | 4014/4733 [05:58<00:56, 12.82it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 85%|███████████████████████████████████████████████████████████████████████████████████▏              | 4016/4733 [05:58<00:57, 12.45it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 85%|███████████████████████████████████████████████████████████████████████████████████▏              | 4020/4733 [05:59<01:08, 10.46it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 58, 58: 61, 59: 59, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 56}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 70, 55, 57, 59, 56, 58, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 58, 58: 61, 59: 59, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 56}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 70, 55, 57, 59, 56, 58, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 85%|███████████████████████████████████████████████████████████████████████████████████▎              | 4023/4733 [05:59<00:51, 13.67it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 58, 58: 61, 59: 59, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 56}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 70, 55, 57, 59, 56, 58, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 58, 58: 61, 59: 59, 60: 62, 61: 63, 62: 65, 63: 67, 64: 64, 65: 66, 66: 68, 67: 70, 68: 69, 69: 71, 70: 56}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 70, 55, 57, 59, 56, 58, 60, 61, 64, 62, 65, 63, 66, 68, 67, 69]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 85%|███████████████████████████████████████████████████████████████████████████████████▎              | 4025/4733 [05:59<01:04, 11.04it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 85%|███████████████████████████████████████████████████████████████████████████████████▍              | 4027/4733 [06:00<01:13,  9.64it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 85%|███████████████████████████████████████████████████████████████████████████████████▍              | 4029/4733 [06:00<01:19,  8.85it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 85%|███████████████████████████████████████████████████████████████████████████████████▍              | 4032/4733 [06:00<01:27,  8.05it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 85%|███████████████████████████████████████████████████████████████████████████████████▌              | 4034/4733 [06:01<01:30,  7.72it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 85%|███████████████████████████████████████████████████████████████████████████████████▌              | 4036/4733 [06:01<01:32,  7.50it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 2, 28]

 85%|███████████████████████████████████████████████████████████████████████████████████▋              | 4041/4733 [06:01<00:54, 12.77it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 2, 28]

 85%|███████████████████████████████████████████████████████████████████████████████████▋              | 4044/4733 [06:01<00:51, 13.34it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 86%|███████████████████████████████████████████████████████████████████████████████████▊              | 4048/4733 [06:02<00:53, 12.72it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 49, 23: 50, 24: 51, 25: 23, 26: 24, 27: 27, 28: 28, 29: 29, 30: 31, 31: 34, 32: 37, 33: 42, 34: 44, 35: 38, 36: 43, 37: 45, 38: 47, 39: 46, 40: 48, 41: 33, 42: 36, 43: 30, 44: 32, 45: 35, 46: 39, 47: 40, 48: 41, 49: 25, 50: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 25, 26, 49, 50, 27, 28, 29, 43, 30, 44, 41, 31, 45, 42, 32, 35, 46, 47, 48, 33, 36, 34, 37, 39, 38, 40, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 49, 23: 50, 24: 51, 25: 23, 26: 24, 27: 27, 28: 28, 29: 29, 30: 31, 31: 34, 32: 37, 33: 42, 34: 44, 35: 38, 36: 43, 37: 45, 38: 47, 39: 46, 40: 48, 41: 33, 42: 36, 43: 30, 44: 32, 45: 35, 46: 39, 47: 40, 48: 41, 49: 25, 50: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 25, 26, 49, 50, 27, 28, 29, 43, 30, 44, 41, 31, 45, 42, 32, 35, 46, 47, 48, 33, 36, 34, 37, 39, 38, 40, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]

 86%|███████████████████████████████████████████████████████████████████████████████████▉              | 4051/4733 [06:02<00:50, 13.45it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 2, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 44, 37: 46, 38: 45, 39: 47, 40: 32, 41: 35, 42: 39, 43: 43, 44: 31, 45: 34, 46: 38}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 43, 36, 38, 37, 39]
[1, 2, 28]

 86%|███████████████████████████████████████████████████████████████████████████████████▉              | 4054/4733 [06:02<00:48, 13.96it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 86%|███████████████████████████████████████████████████████████████████████████████████▉              | 4056/4733 [06:02<00:50, 13.31it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 37, 36: 33, 37: 36, 38: 38, 39: 39, 40: 41, 41: 43, 42: 40, 43: 42, 44: 44, 45: 46, 46: 45, 47: 47, 48: 32, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 48, 36, 34, 49, 37, 35, 38, 39, 42, 40, 43, 41, 44, 46, 45, 47, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 49, 23: 50, 24: 51, 25: 23, 26: 24, 27: 27, 28: 28, 29: 29, 30: 31, 31: 34, 32: 37, 33: 42, 34: 44, 35: 38, 36: 43, 37: 45, 38: 47, 39: 46, 40: 48, 41: 33, 42: 36, 43: 30, 44: 32, 45: 35, 46: 39, 47: 40, 48: 41, 49: 25, 50: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 25, 26, 49, 50, 27, 28, 29, 43, 30, 44, 41, 31, 45, 42, 32, 35, 46, 47, 48, 33, 36, 34, 37, 39, 38, 40, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 49, 23: 50, 24: 51, 25: 23, 26: 24, 27: 27, 28: 28, 29: 29, 30: 31, 31: 34, 32: 37, 33: 42, 34: 44, 35: 38, 36: 43, 37: 45, 38: 47, 39: 46, 40: 48, 41: 33, 42: 36, 43: 30, 44: 32, 45: 35, 46: 39, 47: 40, 48: 41, 49: 25, 50: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 25, 26, 49, 50, 27, 28, 29, 43, 30, 44, 41, 31, 45, 42, 32, 35, 46, 47, 48, 33, 36, 34, 37, 39, 38, 40, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 86%|████████████████████████████████████████████████████████████████████████████████████              | 4061/4733 [06:03<00:49, 13.47it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 49, 23: 50, 24: 51, 25: 23, 26: 24, 27: 27, 28: 28, 29: 29, 30: 31, 31: 34, 32: 37, 33: 42, 34: 44, 35: 38, 36: 43, 37: 45, 38: 47, 39: 46, 40: 48, 41: 33, 42: 36, 43: 30, 44: 32, 45: 35, 46: 39, 47: 40, 48: 41, 49: 25, 50: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 25, 26, 49, 50, 27, 28, 29, 43, 30, 44, 41, 31, 45, 42, 32, 35, 46, 47, 48, 33, 36, 34, 37, 39, 38, 40, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 49, 23: 50, 24: 51, 25: 23, 26: 24, 27: 27, 28: 28, 29: 29, 30: 31, 31: 34, 32: 37, 33: 42, 34: 44, 35: 38, 36: 43, 37: 45, 38: 47, 39: 46, 40: 48, 41: 33, 42: 36, 43: 30, 44: 32, 45: 35, 46: 39, 47: 40, 48: 41, 49: 25, 50: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 25, 26, 49, 50, 27, 28, 29, 43, 30, 44, 41, 31, 45, 42, 32, 35, 46, 47, 48, 33, 36, 34, 37, 39, 38, 40, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 8, 6: 10, 7: 13, 8: 16, 9: 21, 10: 23, 11: 17, 12: 22, 13: 24, 14: 26, 15: 25, 16: 27, 17: 12, 18: 15, 19: 9, 20: 11, 21: 14, 22: 18, 23: 19, 24: 20, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 34, 35: 33, 36: 37, 37: 40, 38: 36, 39: 32, 40: 35, 41: 38, 42: 41, 43: 43, 44: 39, 45: 42, 46: 44, 47: 46, 48: 45, 49: 47}
[0, 1, 2, 25, 26, 3, 4, 5, 19, 6, 20, 17, 7, 21, 18, 8, 11, 22, 23, 24, 9, 12, 10, 13, 15, 14, 16, 27, 28, 32, 33, 39, 35, 34, 40, 38, 36, 41, 44, 37, 42, 45, 43, 46, 48, 47, 49, 29, 30, 31]
[1, 28, 29]

 86%|████████████████████████████████████████████████████████████████████████████████████▏             | 4063/4733 [06:03<00:51, 12.96it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 86%|████████████████████████████████████████████████████████████████████████████████████▏             | 4067/4733 [06:03<00:51, 12.96it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 86%|████████████████████████████████████████████████████████████████████████████████████▎             | 4069/4733 [06:03<00:51, 12.93it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 86%|████████████████████████████████████████████████████████████████████████████████████▎             | 4071/4733 [06:03<01:02, 10.59it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 86%|████████████████████████████████████████████████████████████████████████████████████▍             | 4075/4733 [06:04<01:04, 10.20it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 86%|████████████████████████████████████████████████████████████████████████████████████▍             | 4080/4733 [06:04<00:51, 12.78it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 86%|████████████████████████████████████████████████████████████████████████████████████▌             | 4084/4733 [06:05<00:50, 12.89it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 86%|████████████████████████████████████████████████████████████████████████████████████▌             | 4086/4733 [06:05<01:01, 10.59it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 86%|████████████████████████████████████████████████████████████████████████████████████▋             | 4090/4733 [06:05<00:55, 11.69it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 86%|████████████████████████████████████████████████████████████████████████████████████▋             | 4092/4733 [06:05<00:53, 12.03it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 87%|████████████████████████████████████████████████████████████████████████████████████▊             | 4096/4733 [06:06<00:58, 10.88it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 87%|████████████████████████████████████████████████████████████████████████████████████▉             | 4100/4733 [06:06<00:55, 11.51it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 7, 5: 10, 6: 11, 7: 12, 8: 14, 9: 17, 10: 19, 11: 21, 12: 23, 13: 20, 14: 22, 15: 24, 16: 26, 17: 25, 18: 27, 19: 16, 20: 18, 21: 13, 22: 15, 23: 8, 24: 9, 25: 4, 26: 5, 27: 28, 28: 29, 29: 48, 30: 49, 31: 50, 32: 30, 33: 31, 34: 32, 35: 34, 36: 37, 37: 39, 38: 41, 39: 43, 40: 40, 41: 42, 42: 44, 43: 46, 44: 45, 45: 47, 46: 36, 47: 38, 48: 33, 49: 35}
[0, 1, 2, 25, 26, 3, 4, 23, 24, 5, 6, 7, 21, 8, 22, 19, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18, 27, 28, 32, 33, 34, 48, 35, 49, 46, 36, 47, 37, 40, 38, 41, 39, 42, 44, 43, 45, 29, 30, 31]
[1, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 87%|████████████████████████████████████████████████████████████████████████████████████▉             | 4102/4733 [06:06<01:04,  9.81it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 87%|█████████████████████████████████████████████████████████████████████████████████████             | 4106/4733 [06:07<00:55, 11.21it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 87%|█████████████████████████████████████████████████████████████████████████████████████             | 4108/4733 [06:07<00:53, 11.65it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 87%|█████████████████████████████████████████████████████████████████████████████████████▏            | 4113/4733 [06:07<00:54, 11.46it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 2, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]

 87%|█████████████████████████████████████████████████████████████████████████████████████▏            | 4116/4733 [06:07<00:49, 12.50it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 2, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23, 24]
[1, 21, 22]

 87%|█████████████████████████████████████████████████████████████████████████████████████▎            | 4120/4733 [06:08<00:40, 15.03it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 2, 28]

 87%|█████████████████████████████████████████████████████████████████████████████████████▎            | 4123/4733 [06:08<00:40, 14.98it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 31, 30: 34, 31: 38, 32: 41, 33: 44, 34: 46, 35: 43, 36: 45, 37: 47, 38: 39, 39: 42, 40: 33, 41: 30, 42: 32, 43: 35, 44: 36, 45: 40, 46: 37}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 41, 29, 42, 40, 30, 43, 44, 46, 31, 38, 45, 32, 39, 35, 33, 36, 34, 37]
[1, 2, 28]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 87%|█████████████████████████████████████████████████████████████████████████████████████▍            | 4128/4733 [06:08<00:41, 14.62it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 40, 33: 42, 34: 37, 35: 41, 36: 46, 37: 48, 38: 47, 39: 49, 40: 32, 41: 35, 42: 39, 43: 45, 44: 31, 45: 34, 46: 38, 47: 43, 48: 44}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 40, 30, 45, 41, 31, 34, 46, 42, 32, 35, 33, 47, 48, 43, 36, 38, 37, 39]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 8, 6: 12, 7: 9, 8: 13, 9: 15, 10: 17, 11: 19, 12: 16, 13: 18, 14: 20, 15: 22, 16: 21, 17: 23, 18: 11, 19: 7, 20: 10, 21: 14, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 19, 5, 7, 20, 18, 6, 8, 21, 9, 12, 10, 13, 11, 14, 16, 15, 17, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 8, 6: 12, 7: 9, 8: 13, 9: 15, 10: 17, 11: 19, 12: 16, 13: 18, 14: 20, 15: 22, 16: 21, 17: 23, 18: 11, 19: 7, 20: 10, 21: 14, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 19, 5, 7, 20, 18, 6, 8, 21, 9, 12, 10, 13, 11, 14, 16, 15, 17, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]
{0: 1, 1: 5, 2: 7, 3: 10, 4: 9, 5: 8, 6: 6, 7: 11, 8: 14, 9: 12, 10: 13, 11: 15, 12: 17, 13: 19, 14: 21, 15: 3, 16: 4, 17: 22, 18: 16, 19: 18, 20: 20, 21: 2}
[0, 21, 15, 16, 1, 6, 2, 5, 4, 3, 7, 9, 10, 8, 11, 18, 12, 19, 13, 20, 14, 17]
[1, 2, 3, 4]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 87%|█████████████████████████████████████████████████████████████████████████████████████▌            | 4130/4733 [06:08<00:43, 13.99it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 87%|█████████████████████████████████████████████████████████████████████████████████████▌            | 4134/4733 [06:09<00:54, 11.01it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]

 87%|█████████████████████████████████████████████████████████████████████████████████████▋            | 4136/4733 [06:09<00:54, 10.96it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 87%|█████████████████████████████████████████████████████████████████████████████████████▋            | 4138/4733 [06:09<00:54, 10.93it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 88%|█████████████████████████████████████████████████████████████████████████████████████▊            | 4142/4733 [06:10<00:56, 10.51it/s]

{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 8, 6: 12, 7: 9, 8: 13, 9: 15, 10: 17, 11: 19, 12: 16, 13: 18, 14: 20, 15: 22, 16: 21, 17: 23, 18: 11, 19: 7, 20: 10, 21: 14, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 19, 5, 7, 20, 18, 6, 8, 21, 9, 12, 10, 13, 11, 14, 16, 15, 17, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 6, 5: 8, 6: 12, 7: 9, 8: 13, 9: 15, 10: 17, 11: 19, 12: 16, 13: 18, 14: 20, 15: 22, 16: 21, 17: 23, 18: 11, 19: 7, 20: 10, 21: 14, 22: 4, 23: 24, 24: 30, 25: 31, 26: 32, 27: 25, 28: 26, 29: 27, 30: 28, 31: 33, 32: 34, 33: 36, 34: 39, 35: 41, 36: 42, 37: 43, 38: 44, 39: 45, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 54, 48: 57, 49: 59, 50: 62, 51: 64, 52: 60, 53: 63, 54: 68, 55: 70, 56: 69, 57: 71, 58: 55, 59: 58, 60: 61, 61: 65, 62: 66, 63: 67, 64: 53, 65: 56, 66: 37, 67: 40, 68: 35, 69: 38, 70: 29}
[0, 1, 2, 22, 3, 4, 19, 5, 7, 20, 18, 6, 8, 21, 9, 12, 10, 13, 11, 14, 16, 15, 17, 23, 27, 28, 29, 30, 70, 24, 25, 26, 31, 32, 68, 33, 66, 69, 34, 67, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 64, 47, 58, 65, 48, 59, 49, 52, 60, 50, 53, 51, 61, 62, 63, 54, 56, 55, 57]
[1, 2, 24, 25, 26, 27, 28, 29]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 88%|█████████████████████████████████████████████████████████████████████████████████████▊            | 4144/4733 [06:10<01:03,  9.33it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 88%|█████████████████████████████████████████████████████████████████████████████████████▉            | 4148/4733 [06:10<00:53, 10.85it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 88%|█████████████████████████████████████████████████████████████████████████████████████▉            | 4150/4733 [06:10<01:01,  9.49it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 88%|██████████████████████████████████████████████████████████████████████████████████████            | 4155/4733 [06:11<00:48, 11.94it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 70]

 88%|██████████████████████████████████████████████████████████████████████████████████████            | 4157/4733 [06:11<00:47, 12.19it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 6, 5: 9, 6: 7, 7: 10, 8: 8, 9: 11, 10: 12, 11: 14, 12: 16, 13: 13, 14: 15, 15: 17, 16: 19, 17: 18, 18: 20, 19: 5, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 19, 4, 6, 8, 5, 7, 9, 10, 13, 11, 14, 12, 15, 17, 16, 18, 20, 21, 22, 23, 24]
[1, 21, 22]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 88%|██████████████████████████████████████████████████████████████████████████████████████▎           | 4171/4733 [06:11<00:20, 27.64it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 88%|██████████████████████████████████████████████████████████████████████████████████████▍           | 4175/4733 [06:11<00:21, 25.76it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 13, 11: 14, 12: 16, 13: 18, 14: 15, 15: 17, 16: 19, 17: 21, 18: 20, 19: 22, 20: 8, 21: 12}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 9, 21, 10, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 88%|██████████████████████████████████████████████████████████████████████████████████████▌           | 4180/4733 [06:12<00:21, 25.51it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 88%|██████████████████████████████████████████████████████████████████████████████████████▋           | 4187/4733 [06:12<00:25, 21.41it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 89%|██████████████████████████████████████████████████████████████████████████████████████▊           | 4190/4733 [06:12<00:26, 20.38it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 11, 11: 12, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 9, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 10, 11, 23, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 89%|██████████████████████████████████████████████████████████████████████████████████████▊           | 4193/4733 [06:12<00:27, 19.51it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 89%|██████████████████████████████████████████████████████████████████████████████████████▊           | 4195/4733 [06:13<00:46, 11.59it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 54, 54: 57, 55: 59, 56: 56, 57: 58, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 53, 52, 56, 54, 57, 55, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 89%|██████████████████████████████████████████████████████████████████████████████████████▉           | 4197/4733 [06:13<00:45, 11.78it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 89%|███████████████████████████████████████████████████████████████████████████████████████           | 4203/4733 [06:13<00:32, 16.49it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 62, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 67, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 62, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 67, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 89%|███████████████████████████████████████████████████████████████████████████████████████▏          | 4210/4733 [06:13<00:25, 20.64it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 62, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 67, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 62, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 67, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 62, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 67, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 62, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 67, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 62, 61, 63, 70, 64, 69, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 89%|███████████████████████████████████████████████████████████████████████████████████████▎          | 4215/4733 [06:14<00:41, 12.53it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]

 89%|███████████████████████████████████████████████████████████████████████████████████████▍          | 4220/4733 [06:14<00:33, 15.45it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 23, 19: 22, 20: 21, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 15, 13, 16, 14, 17, 20, 19, 18, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 89%|███████████████████████████████████████████████████████████████████████████████████████▋          | 4232/4733 [06:15<00:19, 25.28it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 10, 10: 11, 11: 15, 12: 16, 13: 18, 14: 20, 15: 17, 16: 19, 17: 21, 18: 23, 19: 22, 20: 24, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 23, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 89%|███████████████████████████████████████████████████████████████████████████████████████▋          | 4236/4733 [06:15<00:20, 24.29it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 12, 10: 14, 11: 13, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 11}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 8, 22, 9, 11, 10, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 90%|███████████████████████████████████████████████████████████████████████████████████████▊          | 4241/4733 [06:15<00:20, 24.59it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 90%|███████████████████████████████████████████████████████████████████████████████████████▉          | 4247/4733 [06:15<00:18, 25.67it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 11, 11: 8, 12: 12, 13: 14, 14: 16, 15: 18, 16: 15, 17: 17, 18: 19, 19: 21, 20: 20, 21: 22}
[0, 1, 2, 3, 4, 5, 6, 11, 7, 8, 10, 12, 9, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 90%|████████████████████████████████████████████████████████████████████████████████████████          | 4256/4733 [06:16<00:19, 24.13it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 66, 59: 65, 60: 62, 61: 64, 62: 68, 63: 69, 64: 70, 65: 71, 66: 67, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 60, 57, 61, 59, 58, 66, 62, 63, 64, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 90%|████████████████████████████████████████████████████████████████████████████████████████▏         | 4259/4733 [06:16<00:35, 13.28it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 69, 65: 71, 66: 66, 67: 67, 68: 63, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 69, 65: 71, 66: 66, 67: 67, 68: 63, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 90%|████████████████████████████████████████████████████████████████████████████████████████▏         | 4261/4733 [06:17<00:47,  9.91it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 69, 65: 71, 66: 66, 67: 67, 68: 63, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 69, 65: 71, 66: 66, 67: 67, 68: 63, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 65, 60: 67, 61: 63, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 58, 69: 61, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 65, 60: 67, 61: 63, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 58, 69: 61, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 90%|████████████████████████████████████████████████████████████████████████████████████████▎         | 4266/4733 [06:17<00:43, 10.74it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]

 90%|████████████████████████████████████████████████████████████████████████████████████████▍         | 4273/4733 [06:17<00:25, 18.15it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 11, 10: 14, 11: 16, 12: 18, 13: 20, 14: 17, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 12, 21: 15, 22: 10, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 22, 9, 20, 23, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 65, 60: 67, 61: 63, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 58, 69: 61, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 65, 60: 67, 61: 63, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 58, 69: 61, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 90%|████████████████████████████████████████████████████████████████████████████████████████▌         | 4276/4733 [06:17<00:25, 17.91it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 65, 60: 67, 61: 63, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 58, 69: 61, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 65, 60: 67, 61: 63, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 58, 69: 61, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 68, 57, 67, 69, 58, 61, 70, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 90%|████████████████████████████████████████████████████████████████████████████████████████▌         | 4279/4733 [06:18<00:41, 10.92it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 90%|████████████████████████████████████████████████████████████████████████████████████████▋         | 4281/4733 [06:19<00:53,  8.49it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 67, 63: 63, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 63, 69, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 91%|████████████████████████████████████████████████████████████████████████████████████████▋         | 4286/4733 [06:19<00:51,  8.73it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 20, 17: 19, 18: 15, 19: 18, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 19, 17, 16, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 62, 69: 57, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 62, 69: 57, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 91%|████████████████████████████████████████████████████████████████████████████████████████▊         | 4288/4733 [06:20<01:02,  7.09it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 62, 69: 57, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 62, 69: 57, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 62, 69: 57, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 60, 68: 62, 69: 57, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 69, 56, 70, 67, 57, 68, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 91%|████████████████████████████████████████████████████████████████████████████████████████▊         | 4291/4733 [06:20<01:02,  7.09it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 91%|████████████████████████████████████████████████████████████████████████████████████████▉         | 4293/4733 [06:20<01:12,  6.03it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 60, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 58, 70, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 91%|████████████████████████████████████████████████████████████████████████████████████████▉         | 4295/4733 [06:21<01:08,  6.40it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 67, 61: 66, 62: 65, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 57, 55, 58, 56, 59, 62, 61, 60, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 67, 61: 66, 62: 65, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 57, 55, 58, 56, 59, 62, 61, 60, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 91%|████████████████████████████████████████████████████████████████████████████████████████▉         | 4298/4733 [06:21<00:52,  8.31it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 91%|█████████████████████████████████████████████████████████████████████████████████████████         | 4300/4733 [06:22<01:09,  6.27it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 91%|█████████████████████████████████████████████████████████████████████████████████████████         | 4301/4733 [06:22<01:07,  6.45it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 91%|█████████████████████████████████████████████████████████████████████████████████████████         | 4302/4733 [06:22<01:25,  5.03it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 67, 61: 66, 62: 65, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 57, 55, 58, 56, 59, 62, 61, 60, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 67, 61: 66, 62: 65, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 57, 55, 58, 56, 59, 62, 61, 60, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 91%|█████████████████████████████████████████████████████████████████████████████████████████▏        | 4308/4733 [06:22<00:36, 11.67it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 91%|█████████████████████████████████████████████████████████████████████████████████████████▏        | 4310/4733 [06:23<00:51,  8.24it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 67, 61: 66, 62: 65, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 57, 55, 58, 56, 59, 62, 61, 60, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 67, 61: 66, 62: 65, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 57, 55, 58, 56, 59, 62, 61, 60, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 69, 65: 71, 66: 66, 67: 67, 68: 63, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 60, 58: 56, 59: 59, 60: 62, 61: 65, 62: 68, 63: 70, 64: 69, 65: 71, 66: 66, 67: 67, 68: 63, 69: 64, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 57, 70, 60, 68, 69, 61, 66, 67, 62, 64, 63, 65, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 91%|█████████████████████████████████████████████████████████████████████████████████████████▎        | 4312/4733 [06:23<00:53,  7.84it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 91%|█████████████████████████████████████████████████████████████████████████████████████████▎        | 4314/4733 [06:23<01:07,  6.23it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 59, 59: 56, 60: 60, 61: 63, 62: 66, 63: 65, 64: 62, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 59, 55, 57, 58, 60, 56, 64, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 91%|█████████████████████████████████████████████████████████████████████████████████████████▍        | 4318/4733 [06:24<00:43,  9.47it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 7, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 11, 18: 6, 19: 9, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 3, 4, 18, 5, 16, 19, 6, 17, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 91%|█████████████████████████████████████████████████████████████████████████████████████████▍        | 4321/4733 [06:24<01:00,  6.83it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 63, 59: 66, 60: 68, 61: 70, 62: 69, 63: 71, 64: 67, 65: 64, 66: 56, 67: 60, 68: 58, 69: 62, 70: 65, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 57, 67, 56, 69, 58, 65, 70, 59, 64, 60, 62, 61, 63, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 91%|█████████████████████████████████████████████████████████████████████████████████████████▍        | 4322/4733 [06:24<01:00,  6.81it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 91%|█████████████████████████████████████████████████████████████████████████████████████████▌        | 4323/4733 [06:25<01:16,  5.36it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 91%|█████████████████████████████████████████████████████████████████████████████████████████▌        | 4324/4733 [06:25<01:29,  4.57it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 92%|█████████████████████████████████████████████████████████████████████████████████████████▋        | 4331/4733 [06:25<00:34, 11.54it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 92%|█████████████████████████████████████████████████████████████████████████████████████████▋        | 4333/4733 [06:26<00:47,  8.45it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 64, 59: 59, 60: 56, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 60, 55, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 92%|█████████████████████████████████████████████████████████████████████████████████████████▊        | 4335/4733 [06:26<00:43,  9.19it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 92%|█████████████████████████████████████████████████████████████████████████████████████████▉        | 4343/4733 [06:26<00:28, 13.75it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 18, 15: 20, 16: 16, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 59, 60: 60, 61: 62, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 59, 60: 60, 61: 62, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 92%|█████████████████████████████████████████████████████████████████████████████████████████▉        | 4345/4733 [06:27<00:41,  9.39it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 59, 60: 60, 61: 62, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 59, 60: 60, 61: 62, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 59, 60: 60, 61: 62, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 59, 60: 60, 61: 62, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 59, 60, 57, 61, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 92%|██████████████████████████████████████████████████████████████████████████████████████████        | 4349/4733 [06:27<00:35, 10.67it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 23, 17: 22, 18: 21, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 13, 11, 14, 12, 15, 18, 17, 16, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]

 92%|██████████████████████████████████████████████████████████████████████████████████████████▏       | 4353/4733 [06:27<00:28, 13.46it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 92%|██████████████████████████████████████████████████████████████████████████████████████████▏       | 4355/4733 [06:28<00:41,  9.10it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 55, 53: 60, 54: 62, 55: 56, 56: 61, 57: 64, 58: 66, 59: 65, 60: 67, 61: 53, 62: 57, 63: 58, 64: 63, 65: 54, 66: 59, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 61, 65, 52, 55, 62, 63, 66, 53, 56, 54, 64, 57, 59, 58, 60, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 92%|██████████████████████████████████████████████████████████████████████████████████████████▎       | 4359/4733 [06:28<00:35, 10.39it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 62, 59: 57, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 62, 59: 57, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 62, 59: 57, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 62, 59: 57, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 92%|██████████████████████████████████████████████████████████████████████████████████████████▎       | 4363/4733 [06:28<00:32, 11.49it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]

 92%|██████████████████████████████████████████████████████████████████████████████████████████▍       | 4367/4733 [06:29<00:25, 14.57it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]

 92%|██████████████████████████████████████████████████████████████████████████████████████████▌       | 4373/4733 [06:29<00:19, 18.79it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 62, 59: 57, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 62, 59: 57, 60: 60, 61: 63, 62: 66, 63: 65, 64: 61, 65: 64, 66: 68, 67: 69, 68: 70, 69: 71, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 59, 56, 57, 60, 64, 58, 61, 65, 63, 62, 70, 66, 67, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 92%|██████████████████████████████████████████████████████████████████████████████████████████▌       | 4375/4733 [06:29<00:30, 11.68it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 23, 21: 22, 22: 21, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 22, 21, 20, 23]
[1, 2, 5]

 93%|██████████████████████████████████████████████████████████████████████████████████████████▋       | 4382/4733 [06:29<00:18, 19.23it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 14, 9: 17, 10: 19, 11: 15, 12: 18, 13: 21, 14: 23, 15: 22, 16: 24, 17: 10, 18: 11, 19: 16, 20: 20, 21: 8, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 17, 18, 22, 23, 8, 11, 19, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 93%|██████████████████████████████████████████████████████████████████████████████████████████▊       | 4388/4733 [06:30<00:15, 21.70it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 93%|██████████████████████████████████████████████████████████████████████████████████████████▉       | 4391/4733 [06:30<00:20, 16.45it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 62, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 67, 66: 65, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 62, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 67, 66: 65, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 62, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 67, 66: 65, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 62, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 67, 66: 65, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 93%|███████████████████████████████████████████████████████████████████████████████████████████       | 4396/4733 [06:30<00:23, 14.11it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 18, 10, 15, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]

 93%|███████████████████████████████████████████████████████████████████████████████████████████       | 4400/4733 [06:31<00:20, 16.00it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 62, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 67, 66: 65, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 63, 58: 62, 59: 64, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 67, 66: 65, 67: 59, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 67, 69, 56, 58, 57, 59, 66, 60, 65, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 93%|███████████████████████████████████████████████████████████████████████████████████████████▎      | 4409/4733 [06:31<00:17, 18.98it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 20, 15: 19, 16: 16, 17: 18, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 16, 13, 17, 15, 14, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 93%|███████████████████████████████████████████████████████████████████████████████████████████▍      | 4418/4733 [06:32<00:17, 17.56it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 5, 5: 9, 6: 11, 7: 14, 8: 16, 9: 12, 10: 15, 11: 17, 12: 19, 13: 18, 14: 20, 15: 8, 16: 4, 17: 7, 18: 10, 19: 13, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 16, 4, 3, 17, 15, 5, 18, 6, 9, 19, 7, 10, 8, 11, 13, 12, 14, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 93%|███████████████████████████████████████████████████████████████████████████████████████████▌      | 4420/4733 [06:32<00:26, 11.63it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 59, 58: 62, 59: 63, 60: 65, 61: 67, 62: 64, 63: 66, 64: 68, 65: 70, 66: 69, 67: 71, 68: 56, 69: 60, 70: 58, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 68, 55, 70, 57, 69, 56, 58, 59, 62, 60, 63, 61, 64, 66, 65, 67, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 93%|███████████████████████████████████████████████████████████████████████████████████████████▌      | 4422/4733 [06:32<00:26, 11.80it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 94%|███████████████████████████████████████████████████████████████████████████████████████████▊      | 4434/4733 [06:32<00:13, 22.22it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 14, 23: 17, 24: 12, 25: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 24, 11, 22, 25, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 5, 6]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 94%|███████████████████████████████████████████████████████████████████████████████████████████▉      | 4438/4733 [06:33<00:13, 21.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 24, 22: 25, 23: 26, 24: 21, 25: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 24, 20, 25, 21, 22, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 24, 20: 25, 21: 26, 22: 21, 23: 23, 24: 8, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 24, 7, 9, 10, 25, 8, 11, 12, 15, 13, 16, 14, 17, 22, 18, 23, 19, 20, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 94%|████████████████████████████████████████████████████████████████████████████████████████████▏     | 4450/4733 [06:33<00:11, 24.95it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 24, 18: 25, 19: 26, 20: 21, 21: 23, 22: 11, 23: 14, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 22, 25, 9, 23, 10, 13, 11, 14, 12, 15, 20, 16, 21, 17, 18, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]

 94%|████████████████████████████████████████████████████████████████████████████████████████████▎     | 4457/4733 [06:33<00:08, 32.01it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 94%|████████████████████████████████████████████████████████████████████████████████████████████▎     | 4461/4733 [06:33<00:09, 29.01it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 19, 13: 16, 14: 18, 15: 20, 16: 22, 17: 21, 18: 23, 19: 11, 20: 14, 21: 9, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 94%|████████████████████████████████████████████████████████████████████████████████████████████▌     | 4470/4733 [06:34<00:08, 30.58it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 95%|████████████████████████████████████████████████████████████████████████████████████████████▋     | 4474/4733 [06:34<00:09, 27.65it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 17, 14: 19, 15: 16, 16: 18, 17: 20, 18: 22, 19: 21, 20: 23, 21: 8, 22: 12}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 12, 15, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 10, 10: 13, 11: 15, 12: 12, 13: 14, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 9, 8, 12, 10, 13, 11, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 95%|████████████████████████████████████████████████████████████████████████████████████████████▋     | 4479/4733 [06:34<00:09, 26.53it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 95%|████████████████████████████████████████████████████████████████████████████████████████████▊     | 4482/4733 [06:35<00:18, 13.90it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 59, 68: 57, 69: 60, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 68, 56, 67, 69, 57, 70, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 95%|████████████████████████████████████████████████████████████████████████████████████████████▊     | 4485/4733 [06:35<00:25,  9.84it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 95%|████████████████████████████████████████████████████████████████████████████████████████████▉     | 4487/4733 [06:36<00:26,  9.23it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 64, 57: 63, 58: 60, 59: 62, 60: 65, 61: 67, 62: 66, 63: 68, 64: 55, 65: 58, 66: 53, 67: 56, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 66, 52, 64, 67, 53, 65, 54, 58, 55, 59, 57, 56, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████     | 4493/4733 [06:36<00:18, 12.96it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████     | 4495/4733 [06:36<00:24,  9.64it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 68, 62: 69, 63: 70, 64: 65, 65: 67, 66: 55, 67: 58, 68: 53, 69: 56, 70: 71, 71: 72, 72: 73, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 66, 69, 53, 67, 54, 57, 55, 58, 56, 59, 64, 60, 65, 61, 62, 63, 70, 71, 72, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 75]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 68, 62: 69, 63: 70, 64: 65, 65: 67, 66: 55, 67: 58, 68: 53, 69: 56, 70: 71, 71: 72, 72: 73, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 66, 69, 53, 67, 54, 57, 55, 58, 56, 59, 64, 60, 65, 61, 62, 63, 70, 71, 72, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 75]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 68, 62: 69, 63: 70, 64: 65, 65: 67, 66: 55, 67: 58, 68: 53, 69: 56, 70: 71, 71: 72, 72: 73, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 66, 69, 53, 67, 54, 57, 55, 58, 56, 59, 64, 60, 65, 61, 62, 63, 70, 71, 72, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 75]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 68, 62: 69, 63: 70, 64: 65, 65: 67, 66: 55, 67: 58, 68: 53, 69: 56, 70: 71, 71: 72, 72: 73, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 66, 69, 53, 67, 54, 57, 55, 58, 56, 59, 64, 60, 65, 61, 62, 63, 70, 71, 72, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 75]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████     | 4497/4733 [06:37<00:30,  7.74it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████▏    | 4499/4733 [06:37<00:39,  5.88it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████▎    | 4504/4733 [06:38<00:29,  7.84it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 20, 13: 19, 14: 16, 15: 18, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 15, 13, 12, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 17, 10: 19, 11: 18, 12: 20, 13: 5, 14: 8, 15: 12, 16: 16, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 16, 9, 11, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 60, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 60, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████▎    | 4506/4733 [06:38<00:34,  6.60it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 60, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 60, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 60, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 58, 58: 60, 59: 62, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 56, 70: 59, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 69, 55, 57, 70, 58, 56, 59, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████▎    | 4507/4733 [06:38<00:33,  6.66it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████▎    | 4509/4733 [06:39<00:38,  5.80it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 68, 62: 69, 63: 70, 64: 65, 65: 67, 66: 55, 67: 58, 68: 53, 69: 56, 70: 71, 71: 72, 72: 73, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 66, 69, 53, 67, 54, 57, 55, 58, 56, 59, 64, 60, 65, 61, 62, 63, 70, 71, 72, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 75]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 68, 62: 69, 63: 70, 64: 65, 65: 67, 66: 55, 67: 58, 68: 53, 69: 56, 70: 71, 71: 72, 72: 73, 73: 74, 74: 75}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 68, 52, 66, 69, 53, 67, 54, 57, 55, 58, 56, 59, 64, 60, 65, 61, 62, 63, 70, 71, 72, 73, 74]
[1, 2, 3, 4, 5, 6, 49, 50, 71, 75]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████▍    | 4511/4733 [06:39<00:41,  5.33it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]

 95%|█████████████████████████████████████████████████████████████████████████████████████████████▌    | 4518/4733 [06:39<00:14, 14.93it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 62, 57: 65, 58: 67, 59: 63, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 58, 66: 61, 67: 56, 68: 60, 69: 59, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 62, 57: 65, 58: 67, 59: 63, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 58, 66: 61, 67: 56, 68: 60, 69: 59, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 96%|█████████████████████████████████████████████████████████████████████████████████████████████▌    | 4521/4733 [06:40<00:22,  9.37it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 59, 66: 54, 67: 57, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 59, 66: 54, 67: 57, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 96%|█████████████████████████████████████████████████████████████████████████████████████████████▋    | 4523/4733 [06:40<00:28,  7.47it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 59, 66: 54, 67: 57, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 59, 66: 54, 67: 57, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 59, 66: 54, 67: 57, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 55, 54: 58, 55: 60, 56: 62, 57: 64, 58: 61, 59: 63, 60: 65, 61: 67, 62: 66, 63: 68, 64: 56, 65: 59, 66: 54, 67: 57, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 66, 53, 64, 67, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 96%|█████████████████████████████████████████████████████████████████████████████████████████████▋    | 4525/4733 [06:41<00:25,  8.26it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 11, 10: 14, 11: 17, 12: 12, 13: 9, 14: 13, 15: 15, 16: 18, 17: 20, 18: 16, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 7, 13, 8, 9, 12, 14, 10, 15, 18, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 62, 57: 65, 58: 67, 59: 63, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 58, 66: 61, 67: 56, 68: 60, 69: 59, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 62, 57: 65, 58: 67, 59: 63, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 58, 66: 61, 67: 56, 68: 60, 69: 59, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 96%|█████████████████████████████████████████████████████████████████████████████████████████████▊    | 4532/4733 [06:41<00:14, 13.62it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 96%|█████████████████████████████████████████████████████████████████████████████████████████████▉    | 4534/4733 [06:41<00:20,  9.85it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 62, 57: 65, 58: 67, 59: 63, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 58, 66: 61, 67: 56, 68: 60, 69: 59, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 62, 57: 65, 58: 67, 59: 63, 60: 66, 61: 68, 62: 70, 63: 69, 64: 71, 65: 58, 66: 61, 67: 56, 68: 60, 69: 59, 70: 64, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 65, 69, 68, 66, 56, 59, 70, 57, 60, 58, 61, 63, 62, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 96%|█████████████████████████████████████████████████████████████████████████████████████████████▉    | 4536/4733 [06:42<00:25,  7.83it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 55, 55: 58, 56: 56, 57: 59, 58: 60, 59: 62, 60: 64, 61: 61, 62: 63, 63: 65, 64: 67, 65: 66, 66: 68, 67: 53, 68: 69, 69: 70, 70: 71, 71: 72, 72: 73}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 67, 52, 54, 56, 53, 55, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 68, 69, 70, 71, 72]
[1, 2, 3, 4, 5, 6, 49, 50, 69, 73]

 96%|█████████████████████████████████████████████████████████████████████████████████████████████▉    | 4538/4733 [06:42<00:25,  7.67it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 12, 6: 14, 7: 10, 8: 13, 9: 16, 10: 19, 11: 17, 12: 20, 13: 5, 14: 8, 15: 11, 16: 15, 17: 18, 18: 4, 19: 7, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 18, 13, 3, 19, 14, 4, 7, 15, 5, 8, 6, 16, 9, 11, 17, 10, 12, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 96%|██████████████████████████████████████████████████████████████████████████████████████████████    | 4544/4733 [06:42<00:17, 10.84it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]

 96%|██████████████████████████████████████████████████████████████████████████████████████████████▏   | 4550/4733 [06:43<00:11, 15.35it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 96%|██████████████████████████████████████████████████████████████████████████████████████████████▎   | 4552/4733 [06:43<00:12, 14.82it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 96%|██████████████████████████████████████████████████████████████████████████████████████████████▍   | 4559/4733 [06:43<00:12, 13.99it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 9, 10, 23, 8, 11, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]

 96%|██████████████████████████████████████████████████████████████████████████████████████████████▌   | 4566/4733 [06:43<00:07, 22.30it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]

 97%|██████████████████████████████████████████████████████████████████████████████████████████████▋   | 4576/4733 [06:44<00:05, 29.50it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 17, 12: 18, 13: 20, 14: 16, 15: 19, 16: 21, 17: 23, 18: 22, 19: 24, 20: 11, 21: 14, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 20, 23, 9, 21, 10, 14, 11, 12, 15, 13, 16, 18, 17, 19]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 14, 10: 10, 11: 11, 12: 15, 13: 16, 14: 18, 15: 20, 16: 17, 17: 19, 18: 21, 19: 23, 20: 22, 21: 24, 22: 8, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 22, 7, 10, 11, 23, 8, 9, 12, 13, 16, 14, 17, 15, 18, 20, 19, 21]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 97%|██████████████████████████████████████████████████████████████████████████████████████████████▊   | 4580/4733 [06:44<00:05, 27.03it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 97%|███████████████████████████████████████████████████████████████████████████████████████████████   | 4593/4733 [06:44<00:04, 34.48it/s]

{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 6, 4: 9, 5: 13, 6: 15, 7: 10, 8: 14, 9: 19, 10: 21, 11: 20, 12: 22, 13: 5, 14: 8, 15: 12, 16: 18, 17: 4, 18: 7, 19: 11, 20: 16, 21: 17, 22: 23, 23: 24, 24: 25, 25: 26}
[0, 1, 2, 17, 13, 3, 18, 14, 4, 7, 19, 15, 5, 8, 6, 20, 21, 16, 9, 11, 10, 12, 22, 23, 24, 25]
[1, 2, 23]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 97%|███████████████████████████████████████████████████████████████████████████████████████████████▏  | 4597/4733 [06:44<00:04, 30.42it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 11, 12: 8, 13: 12, 14: 14, 15: 17, 16: 19, 17: 15, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 12, 7, 8, 11, 13, 9, 14, 17, 10, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 12, 12: 13, 13: 14, 14: 15, 15: 16, 16: 17, 17: 18, 18: 19, 19: 20, 20: 21, 21: 22, 22: 23, 23: 24, 24: 25, 25: 26, 26: 27, 27: 28, 28: 29, 29: 31, 30: 34, 31: 37, 32: 42, 33: 44, 34: 38, 35: 43, 36: 45, 37: 47, 38: 46, 39: 48, 40: 32, 41: 35, 42: 30, 43: 33, 44: 36, 45: 39, 46: 40, 47: 41, 48: 49, 49: 50, 50: 53, 51: 54, 52: 55, 53: 57, 54: 60, 55: 62, 56: 64, 57: 66, 58: 63, 59: 65, 60: 67, 61: 69, 62: 68, 63: 70, 64: 59, 65: 61, 66: 56, 67: 58, 68: 51, 69: 52}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 42, 29, 40, 43, 30, 41, 44, 31, 34, 45, 46, 47, 32, 35, 33, 36, 38, 37, 39, 48, 49, 68, 69, 50, 51, 52, 66, 53, 67, 64, 54, 65, 55, 58, 56, 59, 57, 60, 62, 61, 63]
[1, 49, 50]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]

 97%|███████████████████████████████████████████████████████████████████████████████████████████████▎  | 4601/4733 [06:45<00:05, 26.05it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 97%|███████████████████████████████████████████████████████████████████████████████████████████████▎  | 4604/4733 [06:45<00:09, 13.84it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 55, 64: 58, 65: 53, 66: 56, 67: 68, 68: 69, 69: 70, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 63, 66, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68, 69, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 97%|███████████████████████████████████████████████████████████████████████████████████████████████▍  | 4609/4733 [06:46<00:11, 11.22it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 14, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 15, 21: 9, 22: 12, 23: 13}
[0, 1, 2, 3, 4, 5, 6, 7, 21, 8, 19, 22, 23, 9, 20, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 98%|███████████████████████████████████████████████████████████████████████████████████████████████▌  | 4615/4733 [06:46<00:09, 12.64it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 59, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 59, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 59, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 59, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 98%|███████████████████████████████████████████████████████████████████████████████████████████████▌  | 4617/4733 [06:47<00:10, 11.14it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 98%|███████████████████████████████████████████████████████████████████████████████████████████████▋  | 4619/4733 [06:47<00:13,  8.55it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 64, 59: 59, 60: 57, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 64, 59: 59, 60: 57, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 98%|███████████████████████████████████████████████████████████████████████████████████████████████▋  | 4621/4733 [06:47<00:15,  7.08it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 64, 59: 59, 60: 57, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 64, 59: 59, 60: 57, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 64, 59: 59, 60: 57, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 61, 58: 64, 59: 59, 60: 57, 61: 60, 62: 62, 63: 65, 64: 67, 65: 63, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 60, 56, 59, 61, 57, 62, 65, 58, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 98%|███████████████████████████████████████████████████████████████████████████████████████████████▋  | 4623/4733 [06:48<00:15,  7.12it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 98%|███████████████████████████████████████████████████████████████████████████████████████████████▉  | 4631/4733 [06:48<00:09, 10.69it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 59, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 58, 57: 61, 58: 56, 59: 60, 60: 63, 61: 65, 62: 67, 63: 64, 64: 66, 65: 68, 66: 70, 67: 69, 68: 71, 69: 59, 70: 62, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 58, 55, 56, 69, 59, 57, 70, 60, 63, 61, 64, 62, 65, 67, 66, 68, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 11, 9: 16, 10: 18, 11: 12, 12: 17, 13: 20, 14: 22, 15: 21, 16: 23, 17: 9, 18: 13, 19: 14, 20: 19, 21: 10, 22: 15}
[0, 1, 2, 3, 4, 5, 6, 7, 17, 21, 8, 11, 18, 19, 22, 9, 12, 10, 20, 13, 15, 14, 16]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 60, 60: 58, 61: 61, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 60, 60: 58, 61: 61, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 98%|███████████████████████████████████████████████████████████████████████████████████████████████▉  | 4634/4733 [06:49<00:12,  7.81it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 60, 60: 58, 61: 61, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 60, 60: 58, 61: 61, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 60, 60: 58, 61: 61, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 56, 57: 59, 58: 62, 59: 60, 60: 58, 61: 61, 62: 63, 63: 65, 64: 67, 65: 64, 66: 66, 67: 68, 68: 70, 69: 69, 70: 71, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 56, 55, 60, 57, 59, 61, 58, 62, 65, 63, 66, 64, 67, 69, 68, 70, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 98%|███████████████████████████████████████████████████████████████████████████████████████████████▉  | 4635/4733 [06:49<00:12,  7.66it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 98%|████████████████████████████████████████████████████████████████████████████████████████████████  | 4639/4733 [06:50<00:11,  8.51it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 15, 11: 18, 12: 20, 13: 16, 14: 19, 15: 23, 16: 25, 17: 24, 18: 26, 19: 11, 20: 14, 21: 17, 22: 21, 23: 22, 24: 9, 25: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 24, 8, 19, 25, 9, 20, 10, 13, 21, 11, 14, 12, 22, 23, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 60, 69: 58, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 60, 69: 58, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 98%|████████████████████████████████████████████████████████████████████████████████████████████████  | 4642/4733 [06:50<00:09,  9.36it/s]

{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 65, 58: 64, 59: 59, 60: 63, 61: 68, 62: 69, 63: 70, 64: 71, 65: 66, 66: 56, 67: 60, 68: 58, 69: 62, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 65, 58: 64, 59: 59, 60: 63, 61: 68, 62: 69, 63: 70, 64: 71, 65: 66, 66: 56, 67: 60, 68: 58, 69: 62, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 98%|████████████████████████████████████████████████████████████████████████████████████████████████▏ | 4644/4733 [06:50<00:13,  6.82it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 65, 58: 64, 59: 59, 60: 63, 61: 68, 62: 69, 63: 70, 64: 71, 65: 66, 66: 56, 67: 60, 68: 58, 69: 62, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 65, 58: 64, 59: 59, 60: 63, 61: 68, 62: 69, 63: 70, 64: 71, 65: 66, 66: 56, 67: 60, 68: 58, 69: 62, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 65, 58: 64, 59: 59, 60: 63, 61: 68, 62: 69, 63: 70, 64: 71, 65: 66, 66: 56, 67: 60, 68: 58, 69: 62, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 61, 57: 65, 58: 64, 59: 59, 60: 63, 61: 68, 62: 69, 63: 70, 64: 71, 65: 66, 66: 56, 67: 60, 68: 58, 69: 62, 70: 67, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 66, 55, 68, 59, 67, 56, 69, 60, 58, 57, 65, 70, 61, 62, 63, 64, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 98%|████████████████████████████████████████████████████████████████████████████████████████████████▏ | 4648/4733 [06:51<00:09,  9.40it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 14, 21: 15, 22: 9, 23: 12}
[0, 1, 2, 3, 4, 5, 6, 7, 22, 8, 19, 23, 9, 20, 21, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 98%|████████████████████████████████████████████████████████████████████████████████████████████████▎ | 4650/4733 [06:51<00:11,  7.01it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 56, 56: 58, 57: 59, 58: 57, 59: 60, 60: 62, 61: 65, 62: 67, 63: 64, 64: 61, 65: 63, 66: 66, 67: 68, 68: 70, 69: 71, 70: 69, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 55, 58, 56, 57, 59, 64, 60, 65, 63, 61, 66, 62, 67, 70, 68, 69, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]

 98%|████████████████████████████████████████████████████████████████████████████████████████████████▎ | 4652/4733 [06:51<00:11,  6.96it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 60, 69: 58, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 60, 69: 58, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 98%|████████████████████████████████████████████████████████████████████████████████████████████████▎ | 4654/4733 [06:52<00:13,  5.78it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 60, 69: 58, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 59, 57: 62, 58: 63, 59: 65, 60: 67, 61: 64, 62: 66, 63: 68, 64: 70, 65: 69, 66: 71, 67: 56, 68: 60, 69: 58, 70: 61, 71: 72}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 52, 53, 54, 67, 55, 69, 56, 68, 70, 57, 58, 61, 59, 62, 60, 63, 65, 64, 66, 71]
[1, 2, 3, 4, 5, 6, 49, 50, 53, 72]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 98%|████████████████████████████████████████████████████████████████████████████████████████████████▍ | 4658/4733 [06:52<00:09,  7.75it/s]

{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 9, 5: 6, 6: 10, 7: 12, 8: 14, 9: 16, 10: 13, 11: 15, 12: 17, 13: 19, 14: 18, 15: 20, 16: 8, 17: 4, 18: 7, 19: 11, 20: 21, 21: 22, 22: 23, 23: 24}
[0, 1, 2, 17, 3, 5, 18, 16, 4, 6, 19, 7, 10, 8, 11, 9, 12, 14, 13, 15, 20, 21, 22, 23]
[1, 2, 21]

 99%|████████████████████████████████████████████████████████████████████████████████████████████████▌ | 4665/4733 [06:52<00:04, 14.75it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]

 99%|████████████████████████████████████████████████████████████████████████████████████████████████▋ | 4672/4733 [06:53<00:03, 19.57it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 8, 11: 12, 12: 14, 13: 13, 14: 15, 15: 17, 16: 19, 17: 16, 18: 18, 19: 20, 20: 22, 21: 21, 22: 23}
[0, 1, 2, 3, 4, 5, 6, 10, 7, 8, 9, 11, 13, 12, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]

 99%|████████████████████████████████████████████████████████████████████████████████████████████████▊ | 4678/4733 [06:53<00:02, 25.76it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████ | 4688/4733 [06:53<00:01, 31.03it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 17, 12: 11, 13: 8, 14: 12, 15: 14, 16: 18, 17: 20, 18: 15, 19: 19, 20: 21, 21: 23, 22: 22, 23: 24}
[0, 1, 2, 3, 4, 5, 6, 13, 7, 8, 12, 14, 9, 15, 18, 10, 11, 16, 19, 17, 20, 22, 21, 23]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████▏| 4692/4733 [06:54<00:02, 18.30it/s]

{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████▏| 4695/4733 [06:54<00:02, 14.72it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 13, 9: 10, 10: 11, 11: 14, 12: 16, 13: 20, 14: 22, 15: 17, 16: 21, 17: 23, 18: 25, 19: 24, 20: 26, 21: 8, 22: 12, 23: 15, 24: 18, 25: 19}
[0, 1, 2, 3, 4, 5, 6, 21, 7, 9, 10, 22, 8, 11, 23, 12, 15, 24, 25, 13, 16, 14, 17, 19, 18, 20]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 10, 9: 13, 10: 11, 11: 14, 12: 12, 13: 15, 14: 16, 15: 18, 16: 20, 17: 17, 18: 19, 19: 21, 20: 23, 21: 22, 22: 24, 23: 9}
[0, 1, 2, 3, 4, 5, 6, 7, 23, 8, 10, 12, 9, 11, 13, 14, 17, 15, 18, 16, 19, 21, 20, 22]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████▍| 4704/4733 [06:54<00:01, 19.96it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 13, 10: 16, 11: 18, 12: 20, 13: 17, 14: 19, 15: 21, 16: 23, 17: 22, 18: 24, 19: 11, 20: 8, 21: 12, 22: 14, 23: 15}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 8, 19, 21, 9, 22, 23, 10, 13, 11, 14, 12, 15, 17, 16, 18]
[1, 2, 5]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 43, 35: 46, 36: 47, 37: 34, 38: 31, 39: 35, 40: 37, 41: 40, 42: 42, 43: 38, 44: 41, 45: 44, 46: 48, 47: 45, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 31, 37, 39, 32, 40, 43, 33, 41, 44, 42, 34, 45, 47, 35, 36, 46, 48]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 43, 35: 46, 36: 47, 37: 34, 38: 31, 39: 35, 40: 37, 41: 40, 42: 42, 43: 38, 44: 41, 45: 44, 46: 48, 47: 45, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 31, 37, 39, 32, 40, 43, 33, 41, 44, 42, 34, 45, 47, 35, 36, 46, 48]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 31, 30: 33, 31: 37, 32: 39, 33: 41, 34: 44, 35: 46, 36: 42, 37: 45, 38: 40, 39: 43, 40: 30, 41: 34, 42: 38, 43: 36, 44: 32, 45: 35}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 40, 29, 44, 30, 41, 45, 43, 31, 42, 32, 38, 33, 36, 39, 34, 37, 35]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 43, 35: 46, 36: 47, 37: 34, 38: 31, 39: 35, 40: 37, 41: 40, 42: 42, 43: 38, 44: 41, 45: 44, 46: 48, 47: 45, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 31, 37, 39, 32, 40, 43, 33, 41, 44, 42, 34, 45, 47, 35, 36, 46, 48]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 43, 35: 46, 36: 47, 37: 34, 38: 31, 39: 35, 40: 37, 41: 40, 42: 42, 43: 38, 44: 41, 45: 44, 46: 48, 47: 45, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 31, 37, 39, 32, 40, 43, 33, 41, 44, 42, 34, 45, 47, 35, 36, 46, 48]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████▍| 4707/4733 [06:54<00:01, 21.17it/s]

{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████▌| 4713/4733 [06:55<00:01, 19.99it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 31, 31: 33, 32: 36, 33: 38, 34: 40, 35: 42, 36: 39, 37: 41, 38: 43, 39: 45, 40: 44, 41: 46, 42: 35, 43: 37, 44: 32, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 30, 44, 31, 45, 42, 32, 43, 33, 36, 34, 37, 35, 38, 40, 39, 41]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 43, 35: 46, 36: 47, 37: 34, 38: 31, 39: 35, 40: 37, 41: 40, 42: 42, 43: 38, 44: 41, 45: 44, 46: 48, 47: 45, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 31, 37, 39, 32, 40, 43, 33, 41, 44, 42, 34, 45, 47, 35, 36, 46, 48]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 43, 35: 46, 36: 47, 37: 34, 38: 31, 39: 35, 40: 37, 41: 40, 42: 42, 43: 38, 44: 41, 45: 44, 46: 48, 47: 45, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 31, 37, 39, 32, 40, 43, 33, 41, 44, 42, 34, 45, 47, 35, 36, 46, 48]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 36, 32: 32, 33: 35, 34: 37, 35: 38, 36: 40, 37: 42, 38: 39, 39: 41, 40: 43, 41: 45, 42: 44, 43: 46, 44: 31, 45: 34}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 44, 32, 30, 45, 33, 31, 34, 35, 38, 36, 39, 37, 40, 42, 41, 43]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 43, 35: 46, 36: 47, 37: 34, 38: 31, 39: 35, 40: 37, 41: 40, 42: 42, 43: 38, 44: 41, 45: 44, 46: 48, 47: 45, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 31, 37, 39, 32, 40, 43, 33, 41, 44, 42, 34, 45, 47, 35, 36, 46, 48]
[1, 2, 28]
{0: 1, 1: 2, 2: 3, 3: 5, 4: 7, 5: 10, 6: 15, 7: 19, 8: 21, 9: 23, 10: 20, 11: 22, 12: 24, 13: 26, 14: 25, 15: 27, 16: 12, 17: 16, 18: 8, 19: 11, 20: 4, 21: 6, 22: 9, 23: 13, 24: 14, 25: 17, 26: 18, 27: 28, 28: 29, 29: 30, 30: 32, 31: 33, 32: 36, 33: 39, 34: 43, 35: 46, 36: 47, 37: 34, 38: 31, 39: 35, 40: 37, 41: 40, 42: 42, 43: 38, 44: 41, 45: 44, 46: 48, 47: 45, 48: 49}
[0, 1, 2, 20, 3, 21, 4, 18, 22, 5, 19, 16, 23, 24, 6, 17, 25, 26, 7, 10, 8, 11, 9, 12, 14, 13, 15, 27, 28, 29, 38, 30, 31, 37, 39, 32, 40, 43, 33, 41, 44, 42, 34, 45, 47, 35, 36, 46, 48]
[1, 2, 28]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████▋| 4719/4733 [06:55<00:00, 22.04it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 4, 3: 6, 4: 9, 5: 10, 6: 14, 7: 15, 8: 3, 9: 5, 10: 7, 11: 11, 12: 16, 13: 18, 14: 20, 15: 22, 16: 19, 17: 21, 18: 23, 19: 25, 20: 24, 21: 26, 22: 12, 23: 17, 24: 8, 25: 13, 26: 27, 27: 28, 28: 29, 29: 30, 30: 33, 31: 32, 32: 36, 33: 39, 34: 35, 35: 31, 36: 34, 37: 37, 38: 40, 39: 42, 40: 38, 41: 41, 42: 43, 43: 45, 44: 44, 45: 46}
[0, 1, 8, 2, 9, 3, 10, 24, 4, 5, 11, 22, 25, 6, 7, 12, 23, 13, 16, 14, 17, 15, 18, 20, 19, 21, 26, 27, 28, 29, 35, 31, 30, 36, 34, 32, 37, 40, 33, 38, 41, 39, 42, 44, 43, 45]
[1, 27, 28]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████▊| 4722/4733 [06:55<00:00, 18.37it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 22, 4: 23, 5: 24, 6: 4, 7: 5, 8: 6, 9: 8, 10: 11, 11: 13, 12: 15, 13: 17, 14: 14, 15: 16, 16: 18, 17: 20, 18: 19, 19: 21, 20: 10, 21: 12, 22: 7, 23: 9}
[0, 1, 2, 6, 7, 8, 22, 9, 23, 20, 10, 21, 11, 14, 12, 15, 13, 16, 18, 17, 19, 3, 4, 5]
[1, 2, 3]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████▉| 4728/4733 [06:55<00:00, 21.41it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 12, 9: 14, 10: 16, 11: 18, 12: 15, 13: 17, 14: 19, 15: 21, 16: 20, 17: 22, 18: 10, 19: 13, 20: 8, 21: 11, 22: 23, 23: 24, 24: 25}
[0, 1, 2, 3, 4, 5, 6, 20, 7, 18, 21, 8, 19, 9, 12, 10, 13, 11, 14, 16, 15, 17, 22, 23, 24]
[1, 2, 23, 24, 25]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]
{0: 1, 1: 7, 2: 8, 3: 9, 4: 2, 5: 3, 6: 4, 7: 5, 8: 10, 9: 11, 10: 13, 11: 16, 12: 18, 13: 19, 14: 20, 15: 21, 16: 22, 17: 23, 18: 24, 19: 25, 20: 26, 21: 27, 22: 28, 23: 29, 24: 31, 25: 34, 26: 36, 27: 39, 28: 41, 29: 37, 30: 40, 31: 45, 32: 47, 33: 46, 34: 48, 35: 32, 36: 35, 37: 38, 38: 42, 39: 43, 40: 44, 41: 30, 42: 33, 43: 14, 44: 17, 45: 12, 46: 15, 47: 6, 48: 49, 49: 50, 50: 51, 51: 52, 52: 54, 53: 57, 54: 59, 55: 61, 56: 63, 57: 60, 58: 62, 59: 64, 60: 66, 61: 65, 62: 67, 63: 56, 64: 58, 65: 53, 66: 55, 67: 68, 68: 69}
[0, 4, 5, 6, 7, 47, 1, 2, 3, 8, 9, 45, 10, 43, 46, 11, 44, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 41, 24, 35, 42, 25, 36, 26, 29, 37, 27, 30, 28, 38, 39, 40, 31, 33, 32, 34, 48, 49, 50, 51, 65, 52, 66, 63, 53, 64, 54, 57, 55, 58, 56, 59, 61, 60, 62, 67, 68]
[1, 2, 3, 4, 5, 6, 49, 50, 68, 69]

100%|█████████████████████████████████████████████████████████████████████████████████████████████████▉| 4731/4733 [06:56<00:00, 17.97it/s]

{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 9, 8: 10, 9: 11, 10: 12, 11: 14, 12: 16, 13: 17, 14: 18, 15: 19, 16: 20, 17: 21, 18: 22, 19: 23, 20: 24, 21: 25, 22: 26, 23: 27, 24: 28, 25: 29, 26: 30, 27: 32, 28: 35, 29: 38, 30: 43, 31: 45, 32: 39, 33: 44, 34: 46, 35: 48, 36: 47, 37: 49, 38: 33, 39: 36, 40: 31, 41: 34, 42: 37, 43: 40, 44: 41, 45: 42, 46: 15, 47: 13, 48: 8, 49: 50, 50: 51, 51: 52, 52: 53, 53: 54, 54: 55, 55: 57, 56: 60, 57: 62, 58: 64, 59: 66, 60: 63, 61: 65, 62: 67, 63: 69, 64: 68, 65: 70, 66: 58, 67: 61, 68: 56, 69: 59}
[0, 1, 2, 3, 4, 5, 6, 48, 7, 8, 9, 10, 47, 11, 46, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 40, 27, 38, 41, 28, 39, 42, 29, 32, 43, 44, 45, 30, 33, 31, 34, 36, 35, 37, 49, 50, 51, 52, 53, 54, 68, 55, 66, 69, 56, 67, 57, 60, 58, 61, 59, 62, 64, 63, 65]
[1, 2, 52]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]
{0: 1, 1: 2, 2: 3, 3: 10, 4: 11, 5: 13, 6: 16, 7: 18, 8: 19, 9: 20, 10: 21, 11: 22, 12: 23, 13: 24, 14: 25, 15: 26, 16: 27, 17: 28, 18: 29, 19: 31, 20: 34, 21: 36, 22: 39, 23: 41, 24: 37, 25: 40, 26: 45, 27: 47, 28: 46, 29: 48, 30: 32, 31: 35, 32: 38, 33: 42, 34: 43, 35: 44, 36: 30, 37: 33, 38: 14, 39: 17, 40: 12, 41: 15, 42: 4, 43: 5, 44: 7, 45: 8, 46: 9, 47: 6, 48: 49, 49: 55, 50: 56, 51: 57, 52: 50, 53: 51, 54: 58, 55: 59, 56: 61, 57: 64, 58: 66, 59: 67, 60: 68, 61: 69, 62: 70, 63: 71, 64: 72, 65: 73, 66: 74, 67: 75, 68: 76, 69: 77, 70: 79, 71: 82, 72: 84, 73: 87, 74: 89, 75: 85, 76: 88, 77: 93, 78: 95, 79: 94, 80: 96, 81: 80, 82: 83, 83: 86, 84: 90, 85: 91, 86: 92, 87: 78, 88: 81, 89: 62, 90: 65, 91: 60, 92: 63, 93: 52, 94: 53, 95: 54, 96: 97, 97: 98, 98: 99, 99: 101, 100: 103, 101: 106, 102: 108, 103: 110, 104: 112, 105: 109, 106: 111, 107: 113, 108: 115, 109: 114, 110: 116, 111: 105, 112: 107, 113: 102, 114: 104, 115: 100}
[0, 1, 2, 42, 43, 47, 44, 45, 46, 3, 4, 40, 5, 38, 41, 6, 39, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 36, 19, 30, 37, 20, 31, 21, 24, 32, 22, 25, 23, 33, 34, 35, 26, 28, 27, 29, 48, 52, 53, 93, 94, 95, 49, 50, 51, 54, 55, 91, 56, 89, 92, 57, 90, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 87, 70, 81, 88, 71, 82, 72, 75, 83, 73, 76, 74, 84, 85, 86, 77, 79, 78, 80, 96, 97, 98, 115, 99, 113, 100, 114, 111, 101, 112, 102, 105, 103, 106, 104, 107, 109, 108, 110]
[1, 2, 3, 4, 5, 6, 49, 50, 51, 52, 53, 54, 97, 98]

100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 4733/4733 [06:56<00:00, 11.36it/s]

,reactants,products,reactionString,ruleName,thermo,reactantStoich,productStoich,reactionType,numReactantMolecules,numProductMolecules,...,ruleProducts,ruleSMARTS,candidateUniProtRaw,numCandidateUniProt,hasRuleLookup,queryReaction,queryMappedReaction,rcmfpMappingStatus,queryRCMFP,rcmfpStatus
0,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,No_Thermo,"(1, 1, 1, 1)","(1, 1, 1)",Enzymatic,4,3,...,NADH_CoF;NADH_CoF;Any,[#6;$([#6&!R]-[#8&!R]);!$([#6&!R](-[#6&R]1-&@[...,A0A0J9X7D2;A1BPP9;A4IP64;A4ISB9;B0S9F2;B0SS41;...,228,True,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,[CH2:97]([CH:99]1[O:101][CH:103]([n:106]2[cH:1...,mapped,"[False, False, False, False, False, False, Fal...",rcmfp_success
1,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,...,NAD_CoF;Any;WATER;WATER,[#6;$([#6&!R]-&!@[#6&R]);!$([#6&!R]-&!@[#6&R]1...,E3VWJ1;F1T282;F1T283;I1TEM3;O94142;Q16850;Q2MJ...,11,True,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,[CH2:49]([OH:50])[CH:51]1[O:52][CH:54]([n:57]2...,mapped,"[False, False, False, False, False, False, Fal...",rcmfp_success
2,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,ACETYL-COA;Any,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,[SH:2][CH2:3][CH2:4][NH:5][C:6]([CH2:7][CH2:9]...,mapped,"[False, False, True, False, False, False, Fals...",rcmfp_success
3,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,ACETYL-COA;Any,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,[SH:2][CH2:3][CH2:4][NH:5][C:6]([CH2:7][CH2:9]...,mapped,"[False, False, True, False, False, False, Fals...",rcmfp_success
4,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,ACETYL-COA;Any,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,[SH:2][CH2:3][CH2:4][NH:5][C:6]([CH2:7][CH2:9]...,mapped,"[False, False, True, False, False, False, Fals...",rcmfp_success
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4728,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,...,NAD_CoF;Any;WATER;WATER,[#6;$([#6&!R]-&!@[#6&R]);!$([#6&!R]-&!@[#6&R]1...,E3VWJ1;F1T282;F1T283;I1TEM3;O94142;Q16850;Q2MJ...,11,True,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,[CH2:49]([OH:50])[CH:51]1[O:52][CH:54]([n:57]2...,mapped,"[False, False, False, False, False, False, Fal...",rcmfp_success
4729,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,ACETYL-COA;Any,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,[SH:2][CH2:3][CH2:4][NH:5][C:6]([CH2:7][CH2:9]...,mapped,"[False, False, True, False, False, False, Fals...",rcmfp_success
4730,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,ACETYL-COA;Any,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,[SH:2][CH2:3][CH2:4][NH:5][C:6]([CH2:7][CH2:9]...,mapped,"[False, False, True, False, False, False, Fals...",rcmfp_success
4731,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,ACETYL-COA;Any,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,[SH:2][CH2:3][CH2:4][NH:5][C:6]([CH2:7][CH2:9]...,mapped,"[False, False, True, False, False, False, Fals...",rcmfp_success
4732,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,No_Thermo,"(1, 1, 1, 1)","(1, 1, 1)",Enzymatic,4,3,...,NADH_CoF;NADH_CoF;Any,[#6;$([#6&!R]-[#8&!R]);!$([#6&!R](-[#6&R]1-&@[...,A0A0J9X7D2;A1BPP9;A4IP64;A4ISB9;B0S9F2;B0SS41;...,228,True,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,[CH2:97]([CH:99]1[O:101][CH:103]([n:106]2[cH:1...,mapped,"[False, False, False, False, False, False, Fal...",rcmfp_success

In [39]:
print("RCMFP status counts:")
print(sucessAtomMapDF["rcmfpStatus"].value_counts(dropna=False))
print("Valid RCMFP reactions:", len(sucessAtomMapDF))
print("Failed RCMFP reactions:", len(queryRcmfpFailureDF))

RCMFP status counts:
rcmfpStatus
rcmfp_success    4733
Name: count, dtype: int64
Valid RCMFP reactions: 4733
Failed RCMFP reactions: 0

### Load and align known enzyme reference metadata and RCMFP cache

- loaded from: https://github.com/JBEI/TridentSynthWeb/tree/b17e61040b182ce68b2931f8dbbaf65f370f8c03/data/processed

In [40]:
naturalEnzymeFilePath = os.path.join(dataDir + "/DORAnet/known_enzyme_reactions_union.parquet")
naturalEnzyme_FP_FilePath = os.path.join(dataDir + "/DORAnet/known_rxn_rcmfp_cache.npz")

naturalEnzymeDF = pd.read_parquet(naturalEnzymeFilePath)
naturalEnzymeDF_wFingerprints = np.load(naturalEnzyme_FP_FilePath, allow_pickle=True)
naturalEnzyme_fingerprint_matrix = naturalEnzymeDF_wFingerprints["fingerprints"].astype(bool)
naturalEnzyme_RC_PatternLHS, naturalEnzyme_RC_PatternRHS, knownValidIndices = naturalEnzymeDF_wFingerprints["rc_patterns_lhs"], naturalEnzymeDF_wFingerprints["rc_patterns_rhs"], naturalEnzymeDF_wFingerprints["valid_indices"]
naturalEnzymeReferenceDF = naturalEnzymeDF.iloc[knownValidIndices].reset_index(drop=True).copy()
naturalEnzymeReferenceDF["naturalEnzyme_RC_PatternLHS"], naturalEnzymeReferenceDF["naturalEnzyme_RC_PatternRHS"], naturalEnzymeReferenceDF["knownOriginalIndex"] = naturalEnzyme_RC_PatternLHS, naturalEnzyme_RC_PatternRHS, knownValidIndices
assert len(naturalEnzymeReferenceDF) == naturalEnzyme_fingerprint_matrix.shape[0]
print("Known enzyme reference shape:", naturalEnzymeReferenceDF.shape); print("Known enzyme molecular fingerprint matrix shape:", naturalEnzyme_fingerprint_matrix.shape)

Known enzyme reference shape: (54063, 25)
Known enzyme molecular fingerprint matrix shape: (54063, 4096)

### Compute RCMFP fingerprint matrices for `DORAnet` reactions

In [41]:
def make_reverse_fingerprint_matrix(fpMatrix, sideLength=FP_SIDE_LENGTH): return np.hstack([fpMatrix[:, sideLength:], fpMatrix[:, :sideLength]]).astype(bool)
def make_fingerprint_matrix_from_column(df, fpCol):
    validMask = df[fpCol].notna(); metaDF = df.loc[validMask].drop(columns=[fpCol], errors="ignore").reset_index(drop=True)
    fpMatrix = np.vstack(df.loc[validMask, fpCol].to_numpy()).astype(bool); fpReverseMatrix = make_reverse_fingerprint_matrix(fpMatrix)
    return metaDF, fpMatrix, fpReverseMatrix, fpMatrix.sum(axis=1), fpReverseMatrix.sum(axis=1)

queryMetaDF, query_FP_Matrix, query_FP_MatrixReverse, queryPopcounts, queryReversePopcounts = make_fingerprint_matrix_from_column(sucessAtomMapDF, "queryRCMFP")
naturalEnzyme_fingerprint_matrixReverse = make_reverse_fingerprint_matrix(naturalEnzyme_fingerprint_matrix)
knownPopcounts, knownReversePopcounts = naturalEnzyme_fingerprint_matrix.sum(axis=1), naturalEnzyme_fingerprint_matrixReverse.sum(axis=1)

queryKeepCols = ["reactants", "products", "reactionString", "ruleName", "reactionType", "rxn_str", "ruleSMARTS", "candidateUniProtRaw", "numCandidateUniProt", "hasRuleLookup", "queryReaction", "queryMappedReaction", "rcmfpMappingStatus", "rcmfpStatus", "feasibilityScore_rule1", "feasibilityLabel_rule1", "feasibilityScore_rule2", "feasibilityLabel_rule2", "feasibilityScore_rule3", "feasibilityLabel_rule3", "feasibilityScore_rule4", "feasibilityLabel_rule4"]
queryMetaDF = queryMetaDF[[c for c in queryKeepCols if c in queryMetaDF.columns]].copy()
print("Query metadata shape:", queryMetaDF.shape); print("Query molecular fingerprint matrix shape:", query_FP_Matrix.shape); print("Known enzyme molecular fingerprint matrix shape:", naturalEnzyme_fingerprint_matrix.shape)
queryMetaDF

Query metadata shape: (4733, 22)
Query molecular fingerprint matrix shape: (4733, 4096)
Known enzyme molecular fingerprint matrix shape: (54063, 4096)

,reactants,products,reactionString,ruleName,reactionType,rxn_str,ruleSMARTS,candidateUniProtRaw,numCandidateUniProt,hasRuleLookup,...,rcmfpMappingStatus,rcmfpStatus,feasibilityScore_rule1,feasibilityLabel_rule1,feasibilityScore_rule2,feasibilityLabel_rule2,feasibilityScore_rule3,feasibilityLabel_rule3,feasibilityScore_rule4,feasibilityLabel_rule4
0,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,Enzymatic,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,[#6;$([#6&!R]-[#8&!R]);!$([#6&!R](-[#6&R]1-&@[...,A0A0J9X7D2;A1BPP9;A4IP64;A4ISB9;B0S9F2;B0SS41;...,228,True,...,mapped,rcmfp_success,0.166996,0.0,0.967761,1.0,0.922012,1.0,0.886861,1.0
1,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,Enzymatic,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,[#6;$([#6&!R]-&!@[#6&R]);!$([#6&!R]-&!@[#6&R]1...,E3VWJ1;F1T282;F1T283;I1TEM3;O94142;Q16850;Q2MJ...,11,True,...,mapped,rcmfp_success,0.002562,0.0,0.738403,1.0,0.627660,1.0,0.740460,1.0
2,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,Enzymatic,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True,...,mapped,rcmfp_success,0.297114,0.0,0.995089,1.0,0.924887,1.0,0.990581,1.0
3,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,Enzymatic,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True,...,mapped,rcmfp_success,0.297114,0.0,0.995089,1.0,0.924887,1.0,0.990581,1.0
4,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,Enzymatic,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True,...,mapped,rcmfp_success,0.297114,0.0,0.995089,1.0,0.924887,1.0,0.990581,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4728,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,Enzymatic,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,[#6;$([#6&!R]-&!@[#6&R]);!$([#6&!R]-&!@[#6&R]1...,E3VWJ1;F1T282;F1T283;I1TEM3;O94142;Q16850;Q2MJ...,11,True,...,mapped,rcmfp_success,0.002562,0.0,0.738403,1.0,0.627660,1.0,0.740460,1.0
4729,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,Enzymatic,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True,...,mapped,rcmfp_success,0.297114,0.0,0.995089,1.0,0.924887,1.0,0.990581,1.0
4730,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,Enzymatic,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True,...,mapped,rcmfp_success,0.297114,0.0,0.995089,1.0,0.924887,1.0,0.990581,1.0
4731,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,Enzymatic,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,[#16:1].[#6;$([#6&!R](-&!@[#6&!R])=&!@[#8&!R])...,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,True,...,mapped,rcmfp_success,0.297114,0.0,0.995089,1.0,0.924887,1.0,0.990581,1.0
4732,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,Enzymatic,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,[#6;$([#6&!R]-[#8&!R]);!$([#6&!R](-[#6&R]1-&@[...,A0A0J9X7D2;A1BPP9;A4IP64;A4ISB9;B0S9F2;B0SS41;...,228,True,...,mapped,rcmfp_success,0.166996,0.0,0.967761,1.0,0.922012,1.0,0.886861,1.0

### Add `ruleBase` column to known enzyme reference and query metadata from DORAnet reactions

This avoids forcing known reference rules into expanded DORAnet rule names. It uses coarse operator family IDs such as `rule0003` and then lets RCMFP decide the closest natural reaction within that family.

In [42]:
def get_rule_base(x): return None if pd.isna(x) else str(x).strip().split("_")[0]
def parse_operator_list(x):
    if isinstance(x, np.ndarray): return [str(v).strip() for v in x.tolist() if v is not None and str(v).strip()]
    if isinstance(x, (list, tuple, set)): return [str(v).strip() for v in list(x) if v is not None and str(v).strip()]
    if x is None or pd.isna(x): return []
    s = str(x).strip()
    if s in ["", "nan", "None", "[]"]: return []
    try:
        parsed = ast.literal_eval(s)
        return [str(v).strip() for v in list(parsed)] if isinstance(parsed, (list, tuple, set, np.ndarray)) else [str(parsed).strip()]
    except Exception:
        for sep in ["|", ";", ","]:
            if sep in s: return [v.strip().strip("'\"") for v in s.split(sep) if v.strip()]
        return [s]

def choose_known_rule_base(row):
    top = row.get("top_mapped_operator")
    if top is not None and not pd.isna(top) and str(top).strip().startswith("rule"): return str(top).strip(), "top_mapped_operator"
    for op in parse_operator_list(row.get("all_mapped_operators")):
        if str(op).startswith("rule"): return str(op), "all_mapped_operators"
    return None, "no_ruleBase"



# Build ruleBase in naturalEnzymeReferenceDF
naturalEnzymeReferenceDF = naturalEnzymeReferenceDF.copy()

naturalEnzymeReferenceDF[["ruleBase", "ruleBaseSource"]] = naturalEnzymeReferenceDF.apply(
    lambda row: pd.Series(choose_known_rule_base(row)),
    axis=1
)

# If you want only base (e.g., rule0001 from rule0001_22), normalize:
naturalEnzymeReferenceDF["ruleBase"] = naturalEnzymeReferenceDF["ruleBase"].apply(get_rule_base)

# Rebuild metadata
queryMetaDF = queryMetaDF.reset_index(drop=True).copy()
knownMetaDF = naturalEnzymeReferenceDF.reset_index(drop=True).copy()

queryMetaDF["queryRowId"] = np.arange(len(queryMetaDF))
knownMetaDF["knownRowId"] = np.arange(len(knownMetaDF))

queryMetaDF["ruleBase"] = queryMetaDF["ruleName"].apply(get_rule_base)

queryMetaDF["_ruleKey"] = queryMetaDF["ruleBase"].astype("object")
knownMetaDF["_ruleKey"] = knownMetaDF["ruleBase"].astype("object")

# Create ruleBase first, then use it
queryMetaDF["ruleBase"] = queryMetaDF["ruleName"].apply(get_rule_base)

if "ruleBase" not in knownMetaDF.columns:
    raise KeyError("knownMetaDF does not contain ruleBase after merge. Check knownOriginalIndex alignment.")

queryMetaDF["_ruleKey"] = queryMetaDF["ruleBase"].astype("object")
knownMetaDF["_ruleKey"] = knownMetaDF["ruleBase"].astype("object")

knownIndicesByRuleBase = {
    ruleBase: idx.to_numpy()
    for ruleBase, idx in knownMetaDF.dropna(subset=["_ruleKey"]).groupby("_ruleKey").groups.items()
}

queryRuleBases = set(queryMetaDF["ruleBase"].dropna().astype(str))
knownRuleBases = set(knownMetaDF["ruleBase"].dropna().astype(str))

print("Source of known enzymetic data base:")
print(knownMetaDF["ruleBaseSource"].value_counts(dropna=False))
print("Reaction rules present in DORAnet reaction mechanism:", len(queryRuleBases))
print("Reaction rules present in known enzymetic data base:", len(knownRuleBases))
print("Overlapping base reaction rules:", len(queryRuleBases.intersection(knownRuleBases)))
print("Example overlaps:", sorted(queryRuleBases.intersection(knownRuleBases))[:20])

Source of known enzymetic data base:
ruleBaseSource
top_mapped_operator     45763
all_mapped_operators     6882
no_ruleBase              1418
Name: count, dtype: int64
Reaction rules present in DORAnet reaction mechanism: 31
Reaction rules present in known enzymetic data base: 687
Overlapping base reaction rules: 29
Example overlaps: ['rule0002', 'rule0003', 'rule0007', 'rule0010', 'rule0011', 'rule0016', 'rule0017', 'rule0028', 'rule0042', 'rule0043', 'rule0047', 'rule0048', 'rule0056', 'rule0061', 'rule0062', 'rule0070', 'rule0073', 'rule0074', 'rule0083', 'rule0085']

### Run `ruleBase` constrained RCMFP enzyme retrieval

For each query reaction (present in DORAnet reaction network) it searches the known natural enzyme reaction database, computes RCMFP Tanimoto similarity, keeps the best matches and stores the results in `matchedRCMFP_DF`. Final returned matches are ranked from highest to lowest RCMFP similarity.

In [43]:
# this function calculates Tanimoto similarity between one query fingerprint and many known enzyme reference fingerprints
def compute_tanimoto_similarity(queryPackedRow, queryPop, refPackedMatrix, refPopcounts, popcount8):
    inter = popcount8[np.bitwise_and(refPackedMatrix, queryPackedRow)].sum(axis=1).astype(np.float32); union = refPopcounts + queryPop - inter
    scores = np.zeros(len(refPopcounts), dtype=np.float32); valid = union > 0; scores[valid] = inter[valid] / union[valid]
    return scores

# this function retrieves the top enzyme reference matches for one query reaction
def retrieve_similar_reactions(queryIdx, topK=TOP_K, minSimilarity=MIN_SIMILARITY):
    queryRuleBase = queryMetaDF.loc[queryIdx, "_ruleKey"]
    candidateIdx, searchMode = (knownIndicesByRuleBase[queryRuleBase], "same_ruleBase") if pd.notna(queryRuleBase) and queryRuleBase in knownIndicesByRuleBase else (np.arange(len(knownMetaDF)), "full_database_fallback")
    qPacked, qPop = queryPacked[queryIdx], queryPopcounts[queryIdx]
    scores = np.maximum(compute_tanimoto_similarity(qPacked, qPop, knownPacked[candidateIdx], knownPopcounts[candidateIdx], popcount8), compute_tanimoto_similarity(qPacked, qPop, knownPackedReverse[candidateIdx], knownReversePopcounts[candidateIdx], popcount8))
    validLocal = np.where(scores > minSimilarity)[0]
    if len(validLocal) == 0: return []
    topLocal = validLocal[np.argpartition(-scores[validLocal], topK - 1)[:topK]] if len(validLocal) > topK else validLocal
    topLocal = topLocal[np.argsort(-scores[topLocal])]
    return [{"queryRowId": int(queryIdx), "rank": rank, "knownRowId": int(candidateIdx[localIdx]), "rcmfpSimilarity": float(scores[localIdx]), "searchMode": searchMode, "numCandidatesSearched": int(len(candidateIdx))} for rank, localIdx in enumerate(topLocal, start=1)]

query_FP_Matrix, naturalEnzyme_fingerprint_matrix, naturalEnzyme_fingerprint_matrixReverse = query_FP_Matrix.astype(bool), naturalEnzyme_fingerprint_matrix.astype(bool), naturalEnzyme_fingerprint_matrixReverse.astype(bool)
queryPacked, knownPacked, knownPackedReverse = np.packbits(query_FP_Matrix.astype(np.uint8), axis=1), np.packbits(naturalEnzyme_fingerprint_matrix.astype(np.uint8), axis=1), np.packbits(naturalEnzyme_fingerprint_matrixReverse.astype(np.uint8), axis=1)
queryPopcounts, knownPopcounts, knownReversePopcounts = query_FP_Matrix.sum(axis=1).astype(np.int32), naturalEnzyme_fingerprint_matrix.sum(axis=1).astype(np.int32), naturalEnzyme_fingerprint_matrixReverse.sum(axis=1).astype(np.int32)
popcount8 = np.array([bin(i).count("1") for i in range(256)], dtype=np.uint8)

allHitRecords = []
for queryIdx in tqdm(range(len(queryMetaDF)), desc="RCMFP enzyme retrieval"): allHitRecords.extend(retrieve_similar_reactions(queryIdx))
matchedRCMFP_DF = pd.DataFrame(allHitRecords)
print("Total hits:", len(matchedRCMFP_DF)); print(matchedRCMFP_DF["searchMode"].value_counts(dropna=False))
matchedRCMFP_DF.head()

RCMFP enzyme retrieval: 100%|█████████████████████████████████████████████████████████████████████████| 4733/4733 [00:28<00:00, 164.39it/s]

Total hits: 86771
searchMode
same_ruleBase             85631
full_database_fallback     1140
Name: count, dtype: int64

,queryRowId,rank,knownRowId,rcmfpSimilarity,searchMode,numCandidatesSearched
0,0,1,6153,0.258929,same_ruleBase,41
1,0,2,2936,0.258160,same_ruleBase,41
2,0,3,42275,0.258160,same_ruleBase,41
3,0,4,2940,0.258160,same_ruleBase,41
4,0,5,42137,0.258160,same_ruleBase,41

### Build full summary, filter Moderate/Strong, deduplicate and save outputs

In [44]:
def print_section(title):
    print("\n" + "-" * 80)
    print(title)
    print("-" * 80)

def print_saved_file(label, path):
    print(f"{label}: {path}")

def classify_precedent(sim):
    if pd.isna(sim): return "No natural precedent retrieved"
    if sim >= 0.60: return "Strong natural enzyme precedent"
    if sim >= 0.35: return "Moderate natural enzyme precedent"
    if sim > 0: return "Weak precedent; likely enzyme-engineering risk"
    return "No useful RCMFP precedent"

queryDisplayCols = [c for c in ["queryRowId", "reactionString", "ruleName", "ruleBase", "reactionType", "queryReaction", "queryMappedReaction", "candidateUniProtRaw", "numCandidateUniProt", "rcmfpMappingStatus", "rcmfpStatus", "feasibilityScore_rule1", "feasibilityLabel_rule1", "feasibilityScore_rule2", "feasibilityLabel_rule2", "feasibilityScore_rule3", "feasibilityLabel_rule3", "feasibilityScore_rule4", "feasibilityLabel_rule4"] if c in queryMetaDF.columns]
knownDisplayCols = [c for c in ["knownRowId", "knownOriginalIndex", "ruleBase", "ruleBaseSource", "rxn_idx", "mapped", "unmapped", "orig_rxn_text", "rule", "source", "quality", "natural", "organism", "protein_refs", "protein_db", "ec_num", "top_mapped_operator", "all_mapped_operators"] if c in knownMetaDF.columns]

matchedRCMFP_DF = matchedRCMFP_DF.merge(queryMetaDF[queryDisplayCols], on="queryRowId", how="left", suffixes=("", "_query")).merge(knownMetaDF[knownDisplayCols], on="knownRowId", how="left", suffixes=("", "_known")).sort_values(["queryRowId", "rank"]).reset_index(drop=True)
matchedRCMFP_DF.head()

,queryRowId,rank,knownRowId,rcmfpSimilarity,searchMode,numCandidatesSearched,reactionString,ruleName,ruleBase,reactionType,...,rule,source,quality,natural,organism,protein_refs,protein_db,ec_num,top_mapped_operator,all_mapped_operators
0,0,1,6153,0.258929,same_ruleBase,41,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,rule0165,Enzymatic,...,[#6:1].[#6:2]1:[#6:3]:[#6:4]:[#6:5]:[#7+:6]:[#...,direct,0.008197,0.0,Ovis aries,[],None,1.2.1.3,rule0165,[rule0165]
1,0,2,2936,0.258160,same_ruleBase,41,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,rule0165,Enzymatic,...,[#6:1].[#6:2]1:[#6:3]:[#6:4]:[#6:5]:[#7+:6]:[#...,direct,1.000000,0.0,Pseudomonas aeruginosa,['O86422'],swissprot,1.1.1.22,None,[rule0165]
2,0,3,42275,0.258160,same_ruleBase,41,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,rule0165,Enzymatic,...,[#6:1].[#6:2]1:[#6:3]:[#6:4]:[#6:5]:[#7+:6]:[#...,direct,1.000000,NaN,None,[],None,1.1.1.22,None,[rule0165]
3,0,4,2940,0.258160,same_ruleBase,41,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,rule0165,Enzymatic,...,[#6:1].[#6:2]1:[#6:3]:[#6:4]:[#6:5]:[#7+:6]:[#...,direct,1.000000,0.0,Bos taurus,[],None,1.1.1.22,rule0165,[rule0165]
4,0,5,42137,0.258160,same_ruleBase,41,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,rule0165,Enzymatic,...,[#6:1].[#6:2]1:[#6:3]:[#6:4]:[#6:5]:[#7+:6]:[#...,direct,1.000000,NaN,None,[],None,1.1.1.186,rule0165,[rule0165]

### Marge information of natural enzyme reference to `reactionDF_wUniprotID`

In [45]:
# User options
keyCol = "reactionString"
scoreCol = "rcmfpSimilarity"
keepMode = "best"   # "best" or "all"
bestAscending = False  # False => highest score is best, True => lowest is best

sourceDF = matchedRCMFP_DF.copy()

if keepMode == "best":
    sourceToMerge = (
        sourceDF
        .sort_values(scoreCol, ascending=bestAscending, na_position="last")
        .drop_duplicates(subset=[keyCol], keep="first")
    )
elif keepMode == "all":
    sourceToMerge = sourceDF
else:
    raise ValueError("keepMode must be 'best' or 'all'")

# only add columns that don't already exist in target
newCols = [c for c in sourceToMerge.columns if c not in reactionDF_wUniprotID.columns and c != keyCol]

reactionDF_wUniprotID = reactionDF_wUniprotID.merge(
    sourceToMerge[[keyCol] + newCols],
    on=keyCol,
    how="inner"   # keep only rows present in source
)

print(f"Mode: {keepMode}")
print(f"Rows after merge: {len(reactionDF_wUniprotID):,}")
print(f"Added columns: {len(newCols)}")
reactionDF_wUniprotID

Mode: best
Rows after merge: 4,733
Added columns: 28

,reactants,products,reactionString,ruleName,thermo,reactantStoich,productStoich,reactionType,numReactantMolecules,numProductMolecules,...,rule,source,quality,natural,organism,protein_refs,protein_db,ec_num,top_mapped_operator,all_mapped_operators
0,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,No_Thermo,"(1, 1, 1, 1)","(1, 1, 1)",Enzymatic,4,3,...,[#6:1].[#6:2]1:[#6:3]:[#6:4]:[#6:5]:[#7+:6]:[#...,direct,0.008197,0.0,Ovis aries,[],None,1.2.1.3,rule0165,[rule0165]
1,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,...,[#6:1]-[#8:2].[#6:3]1=[#6:4]-[#7:5]-[#6:6]=[#6...,direct,0.333333,NaN,None,[],None,1.14.13.246,rule0073,"[rule0073, rule0491]"
2,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,[#6:1]-[#16:2].[#8:3]>>[#16:2].[#6:1]-[#8:3],direct reversed,1.000000,1.0,Cavia porcellus,[],None,2.3.1.44,rule0061,"[rule0021, rule0059, rule0061, rule0089, rule0..."
3,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,[#6:1]-[#16:2].[#8:3]>>[#16:2].[#6:1]-[#8:3],direct reversed,1.000000,1.0,Cavia porcellus,[],None,2.3.1.44,rule0061,"[rule0021, rule0059, rule0061, rule0089, rule0..."
4,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,[#6:1]-[#16:2].[#8:3]>>[#16:2].[#6:1]-[#8:3],direct reversed,1.000000,1.0,Cavia porcellus,[],None,2.3.1.44,rule0061,"[rule0021, rule0059, rule0061, rule0089, rule0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4728,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,...,[#6:1]-[#8:2].[#6:3]1=[#6:4]-[#7:5]-[#6:6]=[#6...,direct,0.333333,NaN,None,[],None,1.14.13.246,rule0073,"[rule0073, rule0491]"
4729,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,[#6:1]-[#16:2].[#8:3]>>[#16:2].[#6:1]-[#8:3],direct reversed,1.000000,1.0,Cavia porcellus,[],None,2.3.1.44,rule0061,"[rule0021, rule0059, rule0061, rule0089, rule0..."
4730,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,[#6:1]-[#16:2].[#8:3]>>[#16:2].[#6:1]-[#8:3],direct reversed,1.000000,1.0,Cavia porcellus,[],None,2.3.1.44,rule0061,"[rule0021, rule0059, rule0061, rule0089, rule0..."
4731,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,[#6:1]-[#16:2].[#8:3]>>[#16:2].[#6:1]-[#8:3],direct reversed,1.000000,1.0,Cavia porcellus,[],None,2.3.1.44,rule0061,"[rule0021, rule0059, rule0061, rule0089, rule0..."
4732,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,No_Thermo,"(1, 1, 1, 1)","(1, 1, 1)",Enzymatic,4,3,...,[#6:1].[#6:2]1:[#6:3]:[#6:4]:[#6:5]:[#7+:6]:[#...,direct,0.008197,0.0,Ovis aries,[],None,1.2.1.3,rule0165,[rule0165]

### Find best `UniProt ID` per DORANet reaction rule

In [47]:
uniprotPattern = re.compile(
    r"([OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9](?:[A-Z0-9]{3}[0-9]){1,2})"
)

def extractUniProtID(x):
    if pd.isna(x):
        return []
    ids = uniprotPattern.findall(str(x))
    seen, out = set(), []
    for uid in ids:
        if uid not in seen:
            out.append(uid)
            seen.add(uid)
    return out


tmp = matchedRCMFP_DF.copy()

tmp["knownProteinRefList"] = tmp["protein_refs"].apply(extractUniProtID)

tmp = tmp[
    tmp["knownProteinRefList"].apply(len) > 0
].copy()

tmp = tmp.explode("knownProteinRefList").rename(
    columns={"knownProteinRefList": "rcmfpSupportedUniProt"}
)

tmp["rcmfpSimilarity"] = pd.to_numeric(
    tmp["rcmfpSimilarity"],
    errors="coerce"
)

tmp["rank"] = pd.to_numeric(
    tmp["rank"],
    errors="coerce"
)

ruleRcmfpUniProtScoreDF = (
    tmp
    .groupby(["ruleName", "ruleBase", "rcmfpSupportedUniProt"])
    .agg(
        numSupportingHits=("knownRowId", "nunique"),
        bestRCMFPSimilarity=("rcmfpSimilarity", "max"),
        meanRCMFPSimilarity=("rcmfpSimilarity", "mean"),
        bestRank=("rank", "min"),
        exampleKnownRowId=("knownRowId", "first"),
        exampleKnownReaction=("orig_rxn_text", "first"),
        exampleKnownOrganism=("organism", "first"),
        exampleKnownEcNumber=("ec_num", "first"),
        exampleProteinRefs=("protein_refs", "first"),
    )
    .reset_index()
)

ruleRcmfpUniProtScoreDF["rcmfpProteinRefScore"] = (
    ruleRcmfpUniProtScoreDF["bestRCMFPSimilarity"] * 100
    + np.log1p(ruleRcmfpUniProtScoreDF["numSupportingHits"]) * 10
    - ruleRcmfpUniProtScoreDF["bestRank"] * 0.1
)

ruleRcmfpUniProtScoreDF = ruleRcmfpUniProtScoreDF.sort_values(
    [
        "ruleName",
        "rcmfpProteinRefScore",
        "bestRCMFPSimilarity",
        "numSupportingHits",
        "bestRank",
    ],
    ascending=[True, False, False, False, True]
)

bestRCMFPUniProtByRuleDF = (
    ruleRcmfpUniProtScoreDF
    .groupby("ruleName")
    .head(1)
    .reset_index(drop=True)
)

bestRCMFPUniProtByRuleDF[
    [
        "ruleName",
        "rcmfpSupportedUniProt",
        "rcmfpProteinRefScore",
        "bestRCMFPSimilarity",
        "meanRCMFPSimilarity",
        "numSupportingHits",
        "bestRank",
        "exampleKnownOrganism",
        "exampleKnownEcNumber",
        "exampleKnownReaction",
    ]
].head()

,ruleName,rcmfpSupportedUniProt,rcmfpProteinRefScore,bestRCMFPSimilarity,meanRCMFPSimilarity,numSupportingHits,bestRank,exampleKnownOrganism,exampleKnownEcNumber,exampleKnownReaction
0,rule0003_171,B2KJ46,31.739969,0.211538,0.211538,2,4,Candida parapsilosis,1.1.1.1,2-hydroxyacetophenone + NADPH + H+ = (S)-1-phe...
1,rule0003_176,A0A0H4SN47,30.228112,0.204420,0.201273,2,12,Ogataea glucozyma,1.1.1.320,1-(2-nitrophenyl)ethanone + NADPH + H+ = (1S)-...
2,rule0007_161,P27169,31.731694,0.179688,0.167985,3,1,Homo sapiens,3.1.1.2,"2,2,2-trifluoroethyl acetate + H2O = 2,2,2-tri..."
3,rule0007_174,B1P195,23.828464,0.187970,0.180622,1,19,Bifidobacterium breve,3.2.1.37,ginsenoside Ra2 + H2O = ginsenoside Rc + D-xylose
4,rule0007_193,Q8NKS0,24.876584,0.180451,0.180451,1,1,Pyrobaculum calidifontis,3.1.1.1,sec-butyl acetate + H2O = sec-butanol + acetate

### Merge back `RCMFP-supported UniProt ID` with `reactionDF_wUniprotID`

In [48]:
# Columns to keep + rename map
rename_map = {
    "rcmfpSupportedUniProt": "bestRCMFP_UniProtID",
    "rcmfpProteinRefScore": "bestRCMFP_UniProtScore",
    "bestRCMFPSimilarity": "bestRCMFP_SimilarityScore",
    "meanRCMFPSimilarity": "meanRCMFP_Similarity_byRule",
    "numSupportingHits": "numRCMFP_SupportingHits_byRule",
    "bestRank": "bestRCMFPRank_byRule",
    "exampleKnownRowId": "bestRCMFP_RowId",
    "exampleKnownReaction": "bestRCMFP_Reaction",
    "exampleKnownOrganism": "bestRCMFP_Organism",
    "exampleKnownEcNumber": "bestRCMFP_ECnumber",
    "exampleProteinRefs": "bestRCMFP_ProteinRefs",
}

bestRCMFPForMergeDF = (
    bestRCMFPUniProtByRuleDF[["ruleName", *rename_map]]
    .rename(columns=rename_map)
)

reactionDF_wBestRCMFP_Similarity = (
    reactionDF_wUniprotID
    .merge(bestRCMFPForMergeDF, on="ruleName", how="left")
    .assign(
        hasbestRCMFP_UniProtID=lambda df: (
            df["bestRCMFP_UniProtID"].fillna("").astype(str).str.len().gt(0)
        )
    )
)

print("reactionDF_wBestRCMFP_Similarity created")
print(f"Rows in reactionDF_wUniprotID              : {len(reactionDF_wUniprotID):,}")
print(f"Rows in reactionDF_wBestRCMFP_Similarity   : {len(reactionDF_wBestRCMFP_Similarity):,}")
print(f"Rows with best RCMFP UniProt               : {reactionDF_wBestRCMFP_Similarity['hasbestRCMFP_UniProtID'].sum():,}")
print(f"Unique best RCMFP UniProt IDs              : {reactionDF_wBestRCMFP_Similarity['bestRCMFP_UniProtID'].nunique():,}")

reactionDF_wBestRCMFP_Similarity.head()

reactionDF_wBestRCMFP_Similarity created
Rows in reactionDF_wUniprotID              : 4,733
Rows in reactionDF_wBestRCMFP_Similarity   : 4,733
Rows with best RCMFP UniProt               : 3,513
Unique best RCMFP UniProt IDs              : 35

,reactants,products,reactionString,ruleName,thermo,reactantStoich,productStoich,reactionType,numReactantMolecules,numProductMolecules,...,bestRCMFP_SimilarityScore,meanRCMFP_Similarity_byRule,numRCMFP_SupportingHits_byRule,bestRCMFPRank_byRule,bestRCMFP_RowId,bestRCMFP_Reaction,bestRCMFP_Organism,bestRCMFP_ECnumber,bestRCMFP_ProteinRefs,hasbestRCMFP_UniProtID
0,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,No_Thermo,"(1, 1, 1, 1)","(1, 1, 1)",Enzymatic,4,3,...,0.207386,0.199784,6.0,4.0,2280.0,1-octadecanol + 2 NAD+ + H2O = octadecanoic ac...,Geobacillus thermodenitrificans,1.1.1.192,['A4IP64'],True
1,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,0.101695,0.095830,1.0,2.0,11708.0,acetyl-CoA + ethanol = CoA + ethyl acetate {r},Wickerhamomyces anomalus,2.3.1.268,['A0A1E3P8S6'],True
3,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,0.101695,0.095830,1.0,2.0,11708.0,acetyl-CoA + ethanol = CoA + ethyl acetate {r},Wickerhamomyces anomalus,2.3.1.268,['A0A1E3P8S6'],True
4,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,0.101695,0.095830,1.0,2.0,11708.0,acetyl-CoA + ethanol = CoA + ethyl acetate {r},Wickerhamomyces anomalus,2.3.1.268,['A0A1E3P8S6'],True

In [49]:
reactionDF_wBestRCMFP_Similarity = reactionDF_wBestRCMFP_Similarity.drop(
    columns=[
        'reactantSetCanonical', 'productSetCanonical',
        'rxn_str', 'feasibilityScore_rule1', 'feasibilityLabel_rule1',
        'feasibilityLabel_rule2', 'feasibilityScore_rule3', 'feasibilityLabel_rule3',
        'feasibilityScore_rule4', 'feasibilityLabel_rule4', 'ruleReactants',
        'ruleProducts', 'ruleSMARTS', 'hasRuleLookup', 'queryRowId', 'rank',
        'knownRowId', 'rcmfpSimilarity', 'searchMode', 'numCandidatesSearched',
        'ruleBase', 'queryReaction', 'queryMappedReaction','rcmfpMappingStatus', 'rcmfpStatus', 'knownOriginalIndex',
        'ruleBase_known', 'ruleBaseSource', 'rxn_idx', 'mapped', 'unmapped','orig_rxn_text', 'rule', 'source', 'quality', 'natural', 
        'organism','protein_refs', 'protein_db', 'ec_num', 'top_mapped_operator',
        'all_mapped_operators','bestRCMFP_UniProtScore', 'meanRCMFP_Similarity_byRule','numRCMFP_SupportingHits_byRule',      
        'bestRCMFPRank_byRule','bestRCMFP_RowId', 'bestRCMFP_Reaction', 'bestRCMFP_ProteinRefs', 'hasbestRCMFP_UniProtID'               
    ],
    errors='ignore'  
)

reactionDF_wBestRCMFP_Similarity

,reactants,products,reactionString,ruleName,thermo,reactantStoich,productStoich,reactionType,numReactantMolecules,numProductMolecules,...,starterSMILES,targetSMILES,connectionMoleculesByStep,feasibilityScore_rule2,candidateUniProtRaw,numCandidateUniProt,bestRCMFP_UniProtID,bestRCMFP_SimilarityScore,bestRCMFP_Organism,bestRCMFP_ECnumber
0,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,No_Thermo,"(1, 1, 1, 1)","(1, 1, 1)",Enzymatic,4,3,...,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)CC(=O)O,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,0.967761,A0A0J9X7D2;A1BPP9;A4IP64;A4ISB9;B0S9F2;B0SS41;...,228,A4IP64,0.207386,Geobacillus thermodenitrificans,1.1.1.192
1,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,...,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O,0.738403,E3VWJ1;F1T282;F1T283;I1TEM3;O94142;Q16850;Q2MJ...,11,NaN,NaN,NaN,NaN
2,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O,0.995089,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,A0A1E3P8S6,0.101695,Wickerhamomyces anomalus,2.3.1.268
3,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O,0.995089,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,A0A1E3P8S6,0.101695,Wickerhamomyces anomalus,2.3.1.268
4,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,O | CC(=O)OCC1OC(n2cnc3c(=O)[nH]cnc32)C(O)C1O,0.995089,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,A0A1E3P8S6,0.101695,Wickerhamomyces anomalus,2.3.1.268
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4728,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,...,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,NC(=O)c1ccc[n+](C2OC(COP(=O)(O)OP(=O)(O)OCC3OC...,0.738403,E3VWJ1;F1T282;F1T283;I1TEM3;O94142;Q16850;Q2MJ...,11,NaN,NaN,NaN,NaN
4729,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,NC(=O)c1ccc[n+](C2OC(COP(=O)(O)OP(=O)(O)OCC3OC...,0.995089,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,A0A1E3P8S6,0.101695,Wickerhamomyces anomalus,2.3.1.268
4730,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,0.995089,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,A0A1E3P8S6,0.101695,Wickerhamomyces anomalus,2.3.1.268
4731,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,0.995089,A0A0B4VSM7;A0MPB1;A1XWY7;B1PBV3;B5KRF3;B5KRF5;...,46,A0A1E3P8S6,0.101695,Wickerhamomyces anomalus,2.3.1.268
4732,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,No_Thermo,"(1, 1, 1, 1)","(1, 1, 1)",Enzymatic,4,3,...,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,0.967761,A0A0J9X7D2;A1BPP9;A4IP64;A4ISB9;B0S9F2;B0SS41;...,228,A4IP64,0.207386,Geobacillus thermodenitrificans,1.1.1.192

reactionDF_wUniprotID_display = reactionDF_wUniprotID[
    ["reactants", "products", "ruleName", "candidateUniProtRaw", "feasibilityScore_rule1", "rcmfpBestSimilarity"]].copy()
reactionDF_wUniprotID_display = reactionDF_wUniprotID_display.drop_duplicates(
    subset=["ruleName"], keep="first"
).copy()
reactionDF_wUniprotID_display

## 5. Query UniProt for EC numbers, protein names, organisms and sequences

```text
DORAnet rule ID → UniProt accession → EC number/protein sequence
```

### Summarize unique DORAnet reaction rules with `UniProt ID`

In [50]:
tmp = reactionDF_wBestRCMFP_Similarity.copy()

tmp["prioritizedUniProt"] = (
    tmp["bestRCMFP_UniProtID"].fillna("").astype(str).str.strip()
)
fallback_mask = tmp["prioritizedUniProt"].eq("")
tmp.loc[fallback_mask, "prioritizedUniProt"] = (
    tmp.loc[fallback_mask, "candidateUniProtRaw"].fillna("").astype(str).str.strip()
)

usedRuleSummaryDF = (
    tmp
    .groupby(["ruleName", "reactionType", "prioritizedUniProt"], dropna=False)
    .agg(
        numReactions=("reactionString", "count"),
        exampleReaction=("reactionString", "first"),
    )
    .reset_index()
    .sort_values("numReactions", ascending=False)
)

usedRuleSummaryDF

,ruleName,reactionType,prioritizedUniProt,numReactions,exampleReaction
44,rule0165_2,Enzymatic,A4IP64,649,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...
20,rule0017_16,Enzymatic,A0B8M6;A0KGH8;A0KU87;A0L4K6;A0LHG0;A0M5L6;A0RM...,592,O=P(O)(O)O.O=c1[nH]cnc2c1ncn2[C@@H]1OC(CO)[C@@...
31,rule0062_17,Enzymatic,Q4WZ64,553,CC(=O)O.CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)...
35,rule0073_5,Enzymatic,E3VWJ1;F1T282;F1T283;I1TEM3;O94142;Q16850;Q2MJ...,511,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...
8,rule0007_198,Enzymatic,Q86W56,452,CC(=O)O[C@@H]1[C@H](O)[C@@H](CO)O[C@]1(C)n1cnc...
30,rule0061_4,Enzymatic,A0A1E3P8S6,330,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...
4,rule0007_161,Enzymatic,P27169,239,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...
48,rule0491_2,Enzymatic,Q2KQ78,238,CC(O)O[C@@H]1[C@H]2CO[C@@]1(O)[C@H](n1cnc3c(=O...
32,rule0062_18,Enzymatic,P77791,154,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...
33,rule0062_19,Enzymatic,Q5Y9C7,153,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...
15,rule0011_51,Enzymatic,C5IWW0,130,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...
12,rule0007_203,Enzymatic,P0A784,97,CC(O)OC[C@H]1O[C@@H]2[C@H](Oc3nc4c(ncn42)c(=O)...
41,rule0121_1,Enzymatic,P0C6X7,85,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...
14,rule0011_50,Enzymatic,A0A0U2YR01,75,C[S+](CC[C@H](N)C(=O)O)C[C@H]1O[C@@H](n2cnc3c(...
39,rule0092_4,Enzymatic,P00371,46,CC(N)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...
13,rule0010_65,Enzymatic,G0FUS0,44,CO[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc32)O[...
16,rule0015_21,Enzymatic,A2WXV8;A2YQL4;A5U4N0;D4GYE6;E9AD19;G4N8F5;G4V7...,37,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O...
7,rule0007_195,Enzymatic,P0A784,32,CCC(=O)O[C@@H]1[C@H](O)[C@@H](CO)O[C@H]1n1cnc2...
42,rule0128_2,Enzymatic,K9NCQ5,30,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)...
5,rule0007_174,Enzymatic,B1P195,26,CC(O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...
40,rule0120_1,Enzymatic,P0C6X7,20,CC(=O)OC[C@H]1O[C@@H](n2c[n+](C)c3c(=O)[nH]cnc...
11,rule0007_202,Enzymatic,Q86W56,20,O.O=CO[C@@H]1[C@H](O)[C@@H](CO)O[C@H]1n1cnc2c(...
46,rule0243_3,Enzymatic,A4LA85;A5DNJ4;B6HVR6;B6Q5I3;C5IIS9;P10045;P209...,18,CC(O)(C#N)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32...
24,rule0047_1,Enzymatic,P49888,17,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)O)[C@@H]...
26,rule0048_5,Enzymatic,Q7LFX5,17,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OS(=O)(=...
9,rule0007_199,Enzymatic,A0A060S684,16,O.O=COC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...
38,rule0085_2,Enzymatic,P27169,12,O.O=C(O)CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]c...
17,rule0016_061,Enzymatic,P00634,12,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)O)...
18,rule0016_062,Enzymatic,Q05209,12,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](O)...
6,rule0007_193,Enzymatic,Q8NKS0,12,CC(=O)OC(C)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)...
10,rule0007_200,Enzymatic,D8QLP9,12,CC(=O)OC(=O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32...
29,rule0056_18,Enzymatic,P95896,12,CC(N)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc3...
3,rule0003_177,Enzymatic,B2ZRE3;H1ZV38;NCED52;O14295;O85057;O94521;P259...,9,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...
27,rule0048_6,Enzymatic,Q7LGC8,8,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OS(=O)(=...
47,rule0352_2,Enzymatic,A8NBN1;E3KNM7;P06617;P0A3V2;P0A3V3;P21795;P250...,8,CC(=O)O.O=O >> C=O.O.O=C=O
2,rule0003_176,Enzymatic,A0A0H4SN47,8,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...
1,rule0003_171,Enzymatic,B2KJ46,6,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...
34,rule0070_6,Enzymatic,P23495,6,CC(=O)O[C@H]1[C@@H](O)[C@H](n2cnc3c(=O)[nH]cnc...
28,rule0056_17,Enzymatic,Q76KX0,6,NC(=O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H]...
19,rule0016_063,Enzymatic,Q05209,6,O.O=c1[nH]cnc2c1ncn2[C@@H]1O[C@H](CO)[C@@H](OP...
25,rule0047_2,Enzymatic,O00204,6,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)O)[C@@H]...
22,rule0042_09,Enzymatic,P9WJI5,5,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...
43,rule0164_2,Enzymatic,A4IP64,3,CC(=O)OC(=O)[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32...
37,rule0083_11,Enzymatic,B7T912,3,CC(=O)C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...
45,rule0169_1,Enzymatic,A4XGA6,2,O=C[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H](O)...
0,rule0002_154,Enzymatic,B2ZRE3;H1ZV38;O85057,1,CC(=O)O[C@@H]1[C@H](O)[C@@H](CO)O[C@H]1n1c(C)n...
23,rule0043_12,Enzymatic,A0A3Q9KTF8,1,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...
21,rule0028_35,Enzymatic,P24300,1,O=c1[nH]cnc2c1ncn2[C@@]1(CO)OC[C@@H](O)[C@H]1O...
36,rule0074_18,Enzymatic,Q6UG02,1,CC(O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@H...

### Fetch `UniProt` metadata

In [51]:
def chunkList(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i+n]


def cleanUniProtAccession(x):
    if pd.isna(x):
        return None

    x = str(x).strip()
    x = x.replace("UniProtKB:", "").replace("UniProt:", "").replace("uniprot:", "")
    x = x.replace("sp|", "").replace("tr|", "")

    # Handles strings like sp|P77791|NAME
    if "|" in x:
        parts = [p.strip() for p in x.split("|") if p.strip()]
        for p in parts:
            if isValidUniProtAccession(p):
                return p

    x = x.split()[0].split("-")[0].strip()
    return x if x else None


uniprotAccessionPattern = re.compile(
    r"^([OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z0-9]{3}[0-9]){1,2})$"
)


def isValidUniProtAccession(x):
    return False if pd.isna(x) else bool(
        uniprotAccessionPattern.match(str(x).strip())
    )


def fetchUniProtMetadata(accessionList, chunkSize=20, sleepSeconds=0.5):
    fields = [
        "accession",
        "reviewed",
        "id",
        "protein_name",
        "gene_names",
        "organism_name",
        "organism_id",
        "ec",
        "length",
        "sequence",
    ]

    allDf = []
    errors = 0

    for chunk in tqdm(list(chunkList(accessionList, chunkSize)), desc="Querying UniProt"):
        q = " OR ".join([f"(accession_id:{a})" for a in chunk])

        try:
            r = requests.get(
                "https://rest.uniprot.org/uniprotkb/search",
                params={
                    "query": q,
                    "format": "tsv",
                    "fields": ",".join(fields),
                    "size": chunkSize,
                },
                timeout=120,
            )

            if r.status_code != 200:
                errors += 1
            else:
                df = pd.read_csv(StringIO(r.text), sep="\t")

                if len(df) == 0:
                    errors += 1
                else:
                    allDf.append(df)

        except Exception:
            errors += 1

        time.sleep(sleepSeconds)

    out = (
        pd.concat(allDf, ignore_index=True).drop_duplicates()
        if allDf
        else pd.DataFrame()
    )

    return out, errors


# -----------------------------------------------
# Filter best RCMFP UniProt IDs
# -----------------------------------------------
reactionDF_wBestRCMFP_Similarity = reactionDF_wBestRCMFP_Similarity.copy()

reactionDF_wBestRCMFP_Similarity["bestRCMFP_UniProtID_clean"] = (
    reactionDF_wBestRCMFP_Similarity["bestRCMFP_UniProtID"]
    .apply(cleanUniProtAccession)
)

reactionDF_wBestRCMFP_Similarity["isValidBestRCMFP_UniProtID"] = (
    reactionDF_wBestRCMFP_Similarity["bestRCMFP_UniProtID_clean"]
    .apply(isValidUniProtAccession)
)

uniqueAccessionList = sorted(
    reactionDF_wBestRCMFP_Similarity.loc[
        reactionDF_wBestRCMFP_Similarity["isValidBestRCMFP_UniProtID"],
        "bestRCMFP_UniProtID_clean",
    ]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

print(f"Unique valid best RCMFP UniProt IDs: {len(uniqueAccessionList):,}")

if not uniqueAccessionList:
    raise RuntimeError("No valid best RCMFP UniProt IDs found.")


# -----------------------------------------------
# Query UniProt
# -----------------------------------------------
uniprotMetadataRawDF, failedChunks = fetchUniProtMetadata(
    uniqueAccessionList,
    chunkSize=20,
    sleepSeconds=0.5,
)

totalChunks = int(np.ceil(len(uniqueAccessionList) / 20))
successChunks = totalChunks - failedChunks

print(f"Successful query chunks: {successChunks}")
print(f"Failed query chunks    : {failedChunks}")


# -----------------------------------------------
# Standardize UniProt columns
# -----------------------------------------------
renameMap = {
    "Entry": "uniprotAccession",
    "Reviewed": "uniprotReviewed",
    "Entry Name": "entryName",
    "Protein names": "proteinName",
    "Gene Names": "geneNames",
    "Organism": "organism",
    "Organism (ID)": "organismTaxId",
    "EC number": "ecNumber",
    "Length": "proteinLengthAa",
    "Sequence": "proteinSequence",
}

uniprotMetadataDF = uniprotMetadataRawDF.rename(columns=renameMap)

requiredCols = [
    "uniprotAccession",
    "uniprotReviewed",
    "entryName",
    "proteinName",
    "geneNames",
    "organism",
    "organismTaxId",
    "ecNumber",
    "proteinLengthAa",
    "proteinSequence",
]

for c in requiredCols:
    if c not in uniprotMetadataDF.columns:
        uniprotMetadataDF[c] = np.nan

uniprotMetadataDF = uniprotMetadataDF[requiredCols].copy()


# -----------------------------------------------
# Merge UniProt metadata back to reactionDF_wBestRCMFP_Similarity
# -----------------------------------------------
reactionDF_wBestRCMFP_Similarity = reactionDF_wBestRCMFP_Similarity.rename(
    columns={"bestRCMFP_UniProtID_clean": "uniprotAccession"}
)

reactionDF_wBestRCMFP_wUniProtMetadata = reactionDF_wBestRCMFP_Similarity.merge(
    uniprotMetadataDF,
    on="uniprotAccession",
    how="left",
    suffixes=("", "_uniprot"),
)

reactionDF_wBestRCMFP_wUniProtMetadata["hasUniProtMetadata"] = (
    reactionDF_wBestRCMFP_wUniProtMetadata["proteinName"]
    .fillna("")
    .astype(str)
    .str.len() > 0
)

reactionDF_wBestRCMFP_wUniProtMetadata["hasProteinSequence"] = (
    reactionDF_wBestRCMFP_wUniProtMetadata["proteinSequence"]
    .fillna("")
    .astype(str)
    .str.len() > 0
)

print("reactionDF_wBestRCMFP_wUniProtMetadata created")
print(f"Rows total             : {len(reactionDF_wBestRCMFP_wUniProtMetadata):,}")
print(f"Rows with metadata     : {reactionDF_wBestRCMFP_wUniProtMetadata['hasUniProtMetadata'].sum():,}")
print(f"Rows with protein seq  : {reactionDF_wBestRCMFP_wUniProtMetadata['hasProteinSequence'].sum():,}")

reactionDF_wBestRCMFP_wUniProtMetadata.head()

Unique valid best RCMFP UniProt IDs: 35

Querying UniProt: 100%|██████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.42s/it]

Successful query chunks: 2
Failed query chunks    : 0
reactionDF_wBestRCMFP_wUniProtMetadata created
Rows total             : 4,733
Rows with metadata     : 3,513
Rows with protein seq  : 3,483

,reactants,products,reactionString,ruleName,thermo,reactantStoich,productStoich,reactionType,numReactantMolecules,numProductMolecules,...,entryName,proteinName,geneNames,organism,organismTaxId,ecNumber,proteinLengthAa,proteinSequence,hasUniProtMetadata,hasProteinSequence
0,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,No_Thermo,"(1, 1, 1, 1)","(1, 1, 1)",Enzymatic,4,3,...,ADH1_GEOTN,Long-chain-alcohol dehydrogenase 1 (EC 1.1.1.1...,adh1 GTNG_1754,Geobacillus thermodenitrificans (strain NG80-2),420246.0,1.1.1.192; 1.1.1.6,395.0,MSVARIVFPPLSHVGWGALDQLVPEVKRLGAKHILVITDPMLVKIG...,True,True
1,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,False
2,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,EAT1_WICAA,Ethanol acetyltransferase 1 (EC 2.3.1.268) (Ac...,EAT1 WICANDRAFT_27004,Wickerhamomyces anomalus (strain ATCC 58044 / ...,683960.0,2.3.1.268; 3.1.1.-; 3.1.2.1,391.0,MFFTKVLNNQVANGLKQLPVHKRVQMAYDLHIPNKTVNPNLNIRSH...,True,True
3,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,EAT1_WICAA,Ethanol acetyltransferase 1 (EC 2.3.1.268) (Ac...,EAT1 WICANDRAFT_27004,Wickerhamomyces anomalus (strain ATCC 58044 / ...,683960.0,2.3.1.268; 3.1.1.-; 3.1.2.1,391.0,MFFTKVLNNQVANGLKQLPVHKRVQMAYDLHIPNKTVNPNLNIRSH...,True,True
4,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,EAT1_WICAA,Ethanol acetyltransferase 1 (EC 2.3.1.268) (Ac...,EAT1 WICANDRAFT_27004,Wickerhamomyces anomalus (strain ATCC 58044 / ...,683960.0,2.3.1.268; 3.1.1.-; 3.1.2.1,391.0,MFFTKVLNNQVANGLKQLPVHKRVQMAYDLHIPNKTVNPNLNIRSH...,True,True

## 6. Fetch `DNA sequences` from `GenBank`

In [52]:
# -----------------------------------------------
# settings
# -----------------------------------------------

NCBI_EMAIL = "sghosh6@lbl.gov"
NCBI_API_KEY = None
NCBI_TOOL = "DORAnet_GenBank_CDS_Fetch"

ncbiSleepSeconds = 0.40 if NCBI_API_KEY is None else 0.12
uniprotSleepSeconds = 0.15

# For testing, set 20 or 50. For full run, keep None.
maxUniProtToFetch = None


# -----------------------------------------------
# UniProt column setup
# -----------------------------------------------
if "reactionDF_wBestRCMFP_wUniProtMetadata" not in globals():
    raise RuntimeError("reactionDF_wBestRCMFP_wUniProtMetadata is not defined.")

reactionDF_wBestRCMFP_wUniProtMetadata = reactionDF_wBestRCMFP_wUniProtMetadata.copy()

# Prefer existing uniprotAccession column.
# Otherwise use bestRCMFP_UniProtID.
if "uniprotAccession" not in reactionDF_wBestRCMFP_wUniProtMetadata.columns:
    if "bestRCMFP_UniProtID" in reactionDF_wBestRCMFP_wUniProtMetadata.columns:
        reactionDF_wBestRCMFP_wUniProtMetadata["uniprotAccession"] = (
            reactionDF_wBestRCMFP_wUniProtMetadata["bestRCMFP_UniProtID"]
        )
    else:
        raise ValueError("Need either 'uniprotAccession' or 'bestRCMFP_UniProtID' column.")


# -----------------------------------------------
# Helper functions
# -----------------------------------------------
def dedupeKeepOrder(valueList):
    seen = set()
    out = []

    for value in valueList:
        if value is None:
            continue

        value = str(value).strip()

        if value and value not in seen:
            out.append(value)
            seen.add(value)

    return out


def cleanUniProtAccession(x):
    if pd.isna(x):
        return None

    x = str(x).strip()
    x = (
        x.replace("UniProtKB:", "")
        .replace("UniProt:", "")
        .replace("uniprot:", "")
        .replace("sp|", "")
        .replace("tr|", "")
    )

    if "|" in x:
        parts = [p.strip() for p in x.split("|") if p.strip()]
        for p in parts:
            if isValidUniProtAccession(p):
                return p

    x = x.split()[0].split("-")[0].strip()

    return x if x else None


uniprotAccessionPattern = re.compile(
    r"^([OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z0-9]{3}[0-9]){1,2})$"
)


def isValidUniProtAccession(x):
    return False if pd.isna(x) else bool(
        uniprotAccessionPattern.match(str(x).strip())
    )


def parseFastaRecords(fastaText):
    records = []
    header = None
    seqLines = []

    for line in str(fastaText).splitlines():
        line = line.strip()

        if not line:
            continue

        if line.startswith(">"):
            if header is not None:
                records.append({
                    "header": header,
                    "sequence": "".join(seqLines),
                })

            header = line[1:]
            seqLines = []

        else:
            seqLines.append(line)

    if header is not None:
        records.append({
            "header": header,
            "sequence": "".join(seqLines),
        })

    return records


def cleanDnaSequence(seq):
    seq = str(seq).upper()
    seq = re.sub(r"[^ACGTN]", "", seq)
    return seq


def fetchUniProtCrossRefs(uniprotAccession, sleepSeconds=0.15):
    url = f"https://rest.uniprot.org/uniprotkb/{uniprotAccession}.json"

    result = {
        "uniprotAccession": uniprotAccession,
        "refseqProteinIds": [],
        "emblProteinIds": [],
        "nucleotideIds": [],
        "rawCrossRefSummary": "",
        "uniprotCrossRefStatus": "not_queried",
        "uniprotCrossRefError": "",
    }

    try:
        response = requests.get(url, timeout=60)

        if response.status_code != 200:
            result["uniprotCrossRefStatus"] = "failed"
            result["uniprotCrossRefError"] = f"{response.status_code}: {response.text[:300]}"
            time.sleep(sleepSeconds)
            return result

        entryJson = response.json()
        crossRefs = entryJson.get("uniProtKBCrossReferences", [])

        refseqProteinIds = []
        emblProteinIds = []
        nucleotideIds = []
        rawSummaryParts = []

        for xref in crossRefs:
            databaseName = str(xref.get("database", "")).strip()
            xrefId = str(xref.get("id", "")).strip()
            properties = xref.get("properties", [])

            propertyDict = {}

            for prop in properties:
                key = str(prop.get("key", "")).strip()
                value = str(prop.get("value", "")).strip()

                if key and value:
                    propertyDict.setdefault(key, []).append(value)

            if databaseName in ["RefSeq", "EMBL", "GenBank", "DDBJ"]:
                rawSummaryParts.append(f"{databaseName}:{xrefId}")

            if databaseName == "RefSeq" and xrefId:
                refseqProteinIds.append(xrefId)

            if databaseName in ["EMBL", "GenBank", "DDBJ"]:
                if xrefId:
                    nucleotideIds.append(xrefId)

                for key, values in propertyDict.items():
                    normalizedKey = (
                        key.lower()
                        .replace(" ", "")
                        .replace("_", "")
                        .replace("-", "")
                    )

                    if "proteinid" in normalizedKey or normalizedKey == "protein":
                        emblProteinIds.extend(values)

                    if "nucleotidesequenceid" in normalizedKey or "nucleotide" in normalizedKey:
                        nucleotideIds.extend(values)

        result["refseqProteinIds"] = dedupeKeepOrder(refseqProteinIds)
        result["emblProteinIds"] = dedupeKeepOrder(emblProteinIds)
        result["nucleotideIds"] = dedupeKeepOrder(nucleotideIds)
        result["rawCrossRefSummary"] = ";".join(rawSummaryParts)
        result["uniprotCrossRefStatus"] = "success"

    except Exception as exc:
        result["uniprotCrossRefStatus"] = "failed"
        result["uniprotCrossRefError"] = str(exc)

    time.sleep(sleepSeconds)

    return result


def fetchNcbiCdsFromProteinAccession(proteinAccession, sleepSeconds=0.40):
    url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"

    params = {
        "db": "protein",
        "id": proteinAccession,
        "rettype": "fasta_cds_na",
        "retmode": "text",
        "tool": NCBI_TOOL,
        "email": NCBI_EMAIL,
    }

    if NCBI_API_KEY is not None:
        params["api_key"] = NCBI_API_KEY

    result = {
        "proteinAccessionQueried": proteinAccession,
        "ncbiFetchStatus": "not_queried",
        "ncbiFetchError": "",
        "genbankCdsFastaHeader": "",
        "genbankCdsSequence": "",
        "genbankCdsLengthBp": np.nan,
        "numFastaRecordsReturned": 0,
    }

    try:
        response = requests.get(url, params=params, timeout=120)

        if response.status_code != 200:
            result["ncbiFetchStatus"] = "failed"
            result["ncbiFetchError"] = f"{response.status_code}: {response.text[:300]}"
            time.sleep(sleepSeconds)
            return result

        fastaRecords = parseFastaRecords(response.text.strip())

        if len(fastaRecords) == 0:
            result["ncbiFetchStatus"] = "no_cds_returned"
            result["ncbiFetchError"] = response.text[:300]
            time.sleep(sleepSeconds)
            return result

        firstRecord = fastaRecords[0]
        cleanSeq = cleanDnaSequence(firstRecord["sequence"])

        if len(cleanSeq) == 0:
            result["ncbiFetchStatus"] = "empty_cds_sequence"
            result["ncbiFetchError"] = "No valid DNA sequence parsed."
            time.sleep(sleepSeconds)
            return result

        result["ncbiFetchStatus"] = "success"
        result["genbankCdsFastaHeader"] = firstRecord["header"]
        result["genbankCdsSequence"] = cleanSeq
        result["genbankCdsLengthBp"] = len(cleanSeq)
        result["numFastaRecordsReturned"] = len(fastaRecords)

    except Exception as exc:
        result["ncbiFetchStatus"] = "failed"
        result["ncbiFetchError"] = str(exc)

    time.sleep(sleepSeconds)

    return result


def fetchBestGenBankCdsForUniProt(uniprotAccession):
    crossRefResult = fetchUniProtCrossRefs(
        uniprotAccession,
        sleepSeconds=uniprotSleepSeconds,
    )

    candidateProteinIds = dedupeKeepOrder(
        crossRefResult["refseqProteinIds"] + crossRefResult["emblProteinIds"]
    )

    output = {
        "uniprotAccession": uniprotAccession,
        "genbankProteinIdsFromUniProt": ";".join(candidateProteinIds),
        "genbankNucleotideIdsFromUniProt": ";".join(crossRefResult["nucleotideIds"]),
        "rawCrossRefSummary": crossRefResult["rawCrossRefSummary"],
        "uniprotCrossRefStatus": crossRefResult["uniprotCrossRefStatus"],
        "uniprotCrossRefError": crossRefResult["uniprotCrossRefError"],
        "genbankProteinAccessionUsed": "",
        "genbankCdsFastaHeader": "",
        "genbankCdsSequence": "",
        "genbankCdsLengthBp": np.nan,
        "numFastaRecordsReturned": 0,
        "genbankCdsFetchStatus": "not_attempted",
        "genbankCdsFetchError": "",
    }

    if len(candidateProteinIds) == 0:
        output["genbankCdsFetchStatus"] = "no_protein_crossref"
        output["genbankCdsFetchError"] = (
            "No RefSeq/EMBL/GenBank protein cross-reference found in UniProt JSON."
        )
        return output

    fetchErrors = []

    for proteinAccession in candidateProteinIds:
        cdsResult = fetchNcbiCdsFromProteinAccession(
            proteinAccession,
            sleepSeconds=ncbiSleepSeconds,
        )

        if cdsResult["ncbiFetchStatus"] == "success":
            output["genbankProteinAccessionUsed"] = proteinAccession
            output["genbankCdsFastaHeader"] = cdsResult["genbankCdsFastaHeader"]
            output["genbankCdsSequence"] = cdsResult["genbankCdsSequence"]
            output["genbankCdsLengthBp"] = cdsResult["genbankCdsLengthBp"]
            output["numFastaRecordsReturned"] = cdsResult["numFastaRecordsReturned"]
            output["genbankCdsFetchStatus"] = "success"
            output["genbankCdsFetchError"] = ""
            return output

        fetchErrors.append(
            f"{proteinAccession}: {cdsResult['ncbiFetchStatus']} | {cdsResult['ncbiFetchError']}"
        )

    output["genbankCdsFetchStatus"] = "failed_all_protein_crossrefs"
    output["genbankCdsFetchError"] = " || ".join(fetchErrors[:5])

    return output


# -----------------------------------------------
# Choose UniProt IDs from reactionDF_wBestRCMFP_wUniProtMetadata
# -----------------------------------------------
reactionDF_wBestRCMFP_wUniProtMetadata["uniprotAccession"] = (
    reactionDF_wBestRCMFP_wUniProtMetadata["uniprotAccession"]
    .apply(cleanUniProtAccession)
)

reactionDF_wBestRCMFP_wUniProtMetadata["isValidUniProtAccession"] = (
    reactionDF_wBestRCMFP_wUniProtMetadata["uniprotAccession"]
    .apply(isValidUniProtAccession)
)

uniqueUniProtForGenBankList = sorted(
    reactionDF_wBestRCMFP_wUniProtMetadata.loc[
        reactionDF_wBestRCMFP_wUniProtMetadata["isValidUniProtAccession"],
        "uniprotAccession",
    ]
    .dropna()
    .astype(str)
    .str.strip()
    .unique()
)

if maxUniProtToFetch is not None:
    uniqueUniProtForGenBankList = uniqueUniProtForGenBankList[:maxUniProtToFetch]

print(f"Unique UniProt accessions selected for GenBank CDS fetch: {len(uniqueUniProtForGenBankList):,}")

if len(uniqueUniProtForGenBankList) == 0:
    raise RuntimeError("No valid UniProt accessions found for GenBank CDS fetch.")


# -----------------------------------------------
# Fetch GenBank CDS sequences
# -----------------------------------------------
genbankLookupRecords = []

for uniprotAccession in tqdm(
    uniqueUniProtForGenBankList,
    desc="Fetching GenBank CDS via UniProt crossrefs",
):
    record = fetchBestGenBankCdsForUniProt(uniprotAccession)
    genbankLookupRecords.append(record)

genbankLookupDF = pd.DataFrame(genbankLookupRecords)

print("\nGenBank CDS fetch status:")
print(genbankLookupDF["genbankCdsFetchStatus"].value_counts(dropna=False))


# -----------------------------------------------
# Merge GenBank CDS back to reaction dataframe
# -----------------------------------------------
reactionDF_wBestRCMFP_wDNAseq = reactionDF_wBestRCMFP_wUniProtMetadata.merge(
    genbankLookupDF,
    on="uniprotAccession",
    how="left",
)

reactionDF_wBestRCMFP_wDNAseq["hasGenBankCdsSequence"] = (
    reactionDF_wBestRCMFP_wDNAseq["genbankCdsSequence"]
    .fillna("")
    .astype(str)
    .str.len() > 0
)

print("\nreactionDF_wBestRCMFP_wDNAseq created")
print(f"Rows total              : {len(reactionDF_wBestRCMFP_wDNAseq):,}")
print(f"Rows with GenBank CDS   : {reactionDF_wBestRCMFP_wDNAseq['hasGenBankCdsSequence'].sum():,}")

reactionDF_wBestRCMFP_wDNAseq.head()

Unique UniProt accessions selected for GenBank CDS fetch: 35

Fetching GenBank CDS via UniProt crossrefs: 100%|██████████████████████████████████████████████████████████| 35/35 [01:07<00:00,  1.93s/it]

GenBank CDS fetch status:
genbankCdsFetchStatus
success                33
no_protein_crossref     2
Name: count, dtype: int64

reactionDF_wBestRCMFP_wDNAseq created
Rows total              : 4,733
Rows with GenBank CDS   : 3,477

,reactants,products,reactionString,ruleName,thermo,reactantStoich,productStoich,reactionType,numReactantMolecules,numProductMolecules,...,uniprotCrossRefStatus,uniprotCrossRefError,genbankProteinAccessionUsed,genbankCdsFastaHeader,genbankCdsSequence,genbankCdsLengthBp,numFastaRecordsReturned,genbankCdsFetchStatus,genbankCdsFetchError,hasGenBankCdsSequence
0,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,No_Thermo,"(1, 1, 1, 1)","(1, 1, 1)",Enzymatic,4,3,...,success,,ABO67118.1,lcl|CP000557.1_cds_ABO67118.1_1 [locus_tag=GTN...,ATGAGTGTAGCCCGCATTGTCTTTCCGCCGCTCAGCCATGTCGGCT...,1188.0,1.0,success,,True
1,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,rule0073_5,No_Thermo,"(1, 1, 1)","(1, 1, 1, 1)",Enzymatic,3,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,success,,XP_019041020.1,lcl|XM_019181327.1_cds_XP_019041020.1_1 [locus...,ATGTTTTTCACAAAAGTACTAAATAACCAAGTTGCCAATGGTTTAA...,1176.0,1.0,success,,True
3,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,success,,XP_019041020.1,lcl|XM_019181327.1_cds_XP_019041020.1_1 [locus...,ATGTTTTTCACAAAAGTACTAAATAACCAAGTTGCCAATGGTTTAA...,1176.0,1.0,success,,True
4,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,success,,XP_019041020.1,lcl|XM_019181327.1_cds_XP_019041020.1_1 [locus...,ATGTTTTTCACAAAAGTACTAAATAACCAAGTTGCCAATGGTTTAA...,1176.0,1.0,success,,True

### Remove those coumns if no DNA sequence found from `GenBank`

In [56]:
before_rows = len(reactionDF_wBestRCMFP_wDNAseq)

reactionDF_wBestRCMFP_wDNAseq = reactionDF_wBestRCMFP_wDNAseq[reactionDF_wBestRCMFP_wDNAseq["hasGenBankCdsSequence"] != False].copy()
after_rows = len(reactionDF_wBestRCMFP_wDNAseq)
dropped_rows = before_rows - after_rows

print(f"Total reaction : {before_rows:,}")
print(f"Reaction with GenBank CDS  : {after_rows:,}")
print(f"Reaction dropped : {dropped_rows:,}")

Total reaction : 4,733
Reaction with GenBank CDS  : 3,477
Reaction dropped : 1,256

## 7. Codon-optimize selected enzymes for `target_species` using `DNA Chisel`

### Print Organisms details: `E.coli/Pseudomonas putida` etc

In [57]:
organismCountsDF = (
    reactionDF_wBestRCMFP_wDNAseq["organism"]
    .fillna("Unknown")
    .astype(str)
    .str.strip()
    .value_counts(dropna=False)
    .rename_axis("organism")
    .reset_index(name="count")
)

totalRows = len(reactionDF_wBestRCMFP_wDNAseq)
organismCountsDF["percentage"] = (organismCountsDF["count"] / totalRows * 100).round(2)

print(f"Unique organisms: {organismCountsDF['organism'].nunique()}\n")
organismCountsDF

Unique organisms: 25

                                             organism  count  percentage
0                                Homo sapiens (Human)    789       22.69
1     Geobacillus thermodenitrificans (strain NG80-2)    652       18.75
2   Aspergillus fumigatus (strain ATCC MYA-4609 / ...    553       15.90
3   Wickerhamomyces anomalus (strain ATCC 58044 / ...    330        9.49
4                       Escherichia coli (strain K12)    295        8.48
5   Comamonas testosteroni (Pseudomonas testosteroni)    238        6.84
6                      Taxus cuspidata (Japanese yew)    153        4.40
7                              Bluetongue virus (BTV)    130        3.74
8   Severe acute respiratory syndrome coronavirus ...    105        3.02
9                         Plagiochasma appendiculatum     75        2.16
10                                   Sus scrofa (Pig)     46        1.32
11                              Bifidobacterium breve     26        0.75
12  Mycosarcoma maydis (Corn smut fungus) (Ustilag...     16        0.46
13  Saccharolobus solfataricus (strain ATCC 35092 ...     12        0.35
14                           Pyrobaculum calidifontis     12        0.35
15  Schizophyllum commune (strain H4-8 / FGSC 9210...     12        0.35
16                                  Ogataea glucozyma      8        0.23
17                           Pseudomonas azotoformans      6        0.17
18  Lactococcus lactis subsp. lactis (Streptococcu...      6        0.17
19  Mycobacterium tuberculosis (strain ATCC 25618 ...      5        0.14
20  Pseudomonas putida (Arthrobacter siderocapsula...      3        0.09
21  Caldicellulosiruptor saccharolyticus (strain A...      2        0.06
22  Phlebiopsis gigantea (White-rot fungus) (Penio...      1        0.03
23  Streptomyces pseudogriseolus (Streptomyces gan...      1        0.03
24                         Streptomyces griseoviridis      1        0.03

### Codon optimization settings

In [58]:
targetSpecies = "e_coli"
minGc = 0.30
maxGc = 0.70
gcWindow = 50
stopCodon = "TAA"

forbiddenPatternList = [
    "BsaI_site",
    "BsmBI_site",
    "EcoRI_site",
    "XbaI_site",
    "SpeI_site",
    "PstI_site",
    "NotI_site",
]

stopCodons = {"TAA", "TAG", "TGA"}

In [59]:
# -----------------------------------------------
# Helper functions
# -----------------------------------------------
def cleanDna(seq):
    if pd.isna(seq):
        return ""
    return re.sub(r"[^ACGTN]", "", str(seq).upper())


def removeTerminalStop(cds):
    cds = cleanDna(cds)
    if len(cds) >= 3 and len(cds) % 3 == 0 and cds[-3:] in stopCodons:
        return cds[:-3]
    return cds


def hasInternalStop(cds):
    cds = cleanDna(cds)
    if len(cds) % 3 != 0:
        return True
    codons = [cds[i:i+3] for i in range(0, len(cds), 3)]
    return any(codon in stopCodons for codon in codons)


def classifyCdsForOptimization(cds):
    cds = cleanDna(cds)
    cdsNoStop = removeTerminalStop(cds)

    if len(cds) == 0:
        return "no_cds"
    if len(cdsNoStop) == 0:
        return "empty_after_stop_removal"
    if len(cdsNoStop) % 3 != 0:
        return "length_not_multiple_of_3"
    if "N" in cdsNoStop:
        return "contains_N"
    if hasInternalStop(cdsNoStop):
        return "contains_internal_stop"

    return "ready_for_optimization"


def safeText(x):
    if pd.isna(x):
        return ""
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", str(x))[:80]


def wrapFasta(seq, width=80):
    seq = str(seq)
    return "\n".join(seq[i:i+width] for i in range(0, len(seq), width))


def optimizeCdsForEcoli(initialCds):
    sequenceLength = len(initialCds)
    geneLocation = (0, sequenceLength)

    constraints = [
        EnforceTranslation(location=geneLocation),
        EnforceGCContent(mini=minGc, maxi=maxGc, window=gcWindow),
    ]

    for patternName in forbiddenPatternList:
        constraints.append(AvoidPattern(patternName))

    objectives = [
        MaximizeCAI(species=targetSpecies, location=geneLocation)
    ]

    optimizationProblem = DnaOptimizationProblem(
        sequence=initialCds,
        constraints=constraints,
        objectives=objectives,
    )

    optimizationProblem.resolve_constraints()
    optimizationProblem.optimize()

    return optimizationProblem.sequence, optimizationProblem


# -----------------------------------------------
# Prepare input from reactionDF_wBestRCMFP_wDNAseq
# -----------------------------------------------
reactionDF_wBestRCMFP_wDNAseq_forOpt = reactionDF_wBestRCMFP_wDNAseq.copy()

reactionDF_wBestRCMFP_wDNAseq_forOpt["genbankCdsSequence"] = (
    reactionDF_wBestRCMFP_wDNAseq_forOpt["genbankCdsSequence"]
    .apply(cleanDna)
)

reactionDF_wBestRCMFP_wDNAseq_forOpt["genbankCdsSequenceForOptimization"] = (
    reactionDF_wBestRCMFP_wDNAseq_forOpt["genbankCdsSequence"]
    .apply(removeTerminalStop)
)

reactionDF_wBestRCMFP_wDNAseq_forOpt["codonOptimizationInputStatus"] = (
    reactionDF_wBestRCMFP_wDNAseq_forOpt["genbankCdsSequence"]
    .apply(classifyCdsForOptimization)
)

reactionDF_wBestRCMFP_wDNAseq_forOpt["isReadyForCodonOptimization"] = (
    reactionDF_wBestRCMFP_wDNAseq_forOpt["codonOptimizationInputStatus"]
    == "ready_for_optimization"
)

reactionDF_wBestRCMFP_wDNAseq_forOpt["optimizationInputKey"] = (
    reactionDF_wBestRCMFP_wDNAseq_forOpt["uniprotAccession"].fillna("").astype(str)
    + "|"
    + reactionDF_wBestRCMFP_wDNAseq_forOpt["genbankProteinAccessionUsed"].fillna("").astype(str)
    + "|"
    + reactionDF_wBestRCMFP_wDNAseq_forOpt["genbankCdsSequenceForOptimization"].fillna("").astype(str)
).apply(lambda x: hashlib.sha1(x.encode("utf-8")).hexdigest())

print("Input status:")
print(reactionDF_wBestRCMFP_wDNAseq_forOpt["codonOptimizationInputStatus"].value_counts(dropna=False))


# -----------------------------------------------
# Optimize unique GenBank CDS records only
# -----------------------------------------------
geneInputDF = (
    reactionDF_wBestRCMFP_wDNAseq_forOpt[
        reactionDF_wBestRCMFP_wDNAseq_forOpt["isReadyForCodonOptimization"]
    ]
    .drop_duplicates("optimizationInputKey")
    .reset_index(drop=True)
)

optimizedGeneRecords = []

for idx, row in tqdm(
    geneInputDF.iterrows(),
    total=len(geneInputDF),
    desc="Optimizing RCMFP-supported GenBank CDS for E. coli"
):
    optimizationInputKey = row["optimizationInputKey"]
    initialCds = row["genbankCdsSequenceForOptimization"]

    try:
        optimizedCdsNoStop, optimizationProblem = optimizeCdsForEcoli(initialCds)
        optimizedCds = optimizedCdsNoStop + stopCodon

        optimizationStatus = "success"
        optimizationError = ""
        constraintsSummary = optimizationProblem.constraints_text_summary()
        objectivesSummary = optimizationProblem.objectives_text_summary()

    except Exception as exc:
        optimizedCds = ""
        optimizationStatus = "failed"
        optimizationError = str(exc)
        constraintsSummary = ""
        objectivesSummary = ""

    optimizedGeneRecords.append({
        "optimizationInputKey": optimizationInputKey,
        "optimizedGeneId": f"ecoli_rcmfp_opt_gene_{idx:06d}",
        "optimizedCds": optimizedCds,
        "optimizedCdsLengthBp": len(optimizedCds),
        "expressionHost": "Escherichia coli",
        "targetSpecies": targetSpecies,
        "minGc": minGc,
        "maxGc": maxGc,
        "gcWindow": gcWindow,
        "stopCodonUsed": stopCodon,
        "codonOptimizationStatus": optimizationStatus,
        "codonOptimizationError": optimizationError,
        "constraintsSummary": constraintsSummary,
        "objectivesSummary": objectivesSummary,
    })

optimizedGeneDF = pd.DataFrame(optimizedGeneRecords)

print("\nOptimization status:")
print(optimizedGeneDF["codonOptimizationStatus"].value_counts(dropna=False))


# -----------------------------------------------
# Merge optimized CDS back to reaction dataframe
# -----------------------------------------------
reactionDF_wOptimizedDNAseq = reactionDF_wBestRCMFP_wDNAseq_forOpt.merge(
    optimizedGeneDF,
    on="optimizationInputKey",
    how="left"
)

reactionDF_wOptimizedDNAseq["hasOptimizedCds"] = (
    reactionDF_wOptimizedDNAseq["optimizedCds"]
    .fillna("")
    .astype(str)
    .str.len() > 0
)

print("\nFinal reactionDF_wOptimizedDNAseq:")
print(f"Rows total           : {len(reactionDF_wOptimizedDNAseq):,}")
print(f"Rows optimized       : {reactionDF_wOptimizedDNAseq['hasOptimizedCds'].sum():,}")
print(f"Unique optimized CDS : {reactionDF_wOptimizedDNAseq.loc[reactionDF_wOptimizedDNAseq['hasOptimizedCds'], 'optimizationInputKey'].nunique():,}")
reactionDF_wOptimizedDNAseq.head()

Input status:
codonOptimizationInputStatus
ready_for_optimization    3477
Name: count, dtype: int64

Optimizing RCMFP-supported GenBank CDS for E. coli:   0%|                                                           | 0/33 [00:00<?, ?it/s]
constraint:   0%|                                                                                          | 0/8 [00:00<?, ?it/s, now=None]
constraint:   0%|                                                                  | 0/8 [00:00<?, ?it/s, now=AvoidPattern[0-1185](patt...]

objective:   0%|                                                                                           | 0/1 [00:00<?, ?it/s, now=None]
objective:   0%|                                                                   | 0/1 [00:00<?, ?it/s, now=MaximizeCAI[0-1185](e_col...]

location:   0%|                                                                                          | 0/216 [00:00<?, ?it/s, now=None]

location:   0%|                                                                                           | 0/216 [00:00<?, ?it/s, now=3-6]


Optimizing RCMFP-supported GenBank CDS for E. coli:   3%|█▌                                                 | 1/33 [00:00<00:03,  8.48it/s]
constraint:   0%|                                                                                          | 0/8 [00:00<?, ?it/s, now=None]
constraint:   0%|                                                                  | 0/8 [00:00<?, ?it/s, now=AvoidPattern[0-1173](patt...]

location:   0%|                                                                                           | 0/17 [00:00<?, ?it/s, now=None]

location:   0%|                                                                                           | 0/17 [00:00<?, ?it/s, now=0-54]



objective:   0%|                                                                                           | 0/1 [00:00<?, ?it/s, now=None]
objective:   0%|                                                                   | 0/1 [00:00<?, ?it/s, now=MaximizeCAI[0-1173](e_col...]

location:   0%|                                                                                          | 0/243 [00:00<?, ?it/s, now=0-54]

location:   0%|                                                                                           | 0/243 [00:00<?, ?it/s, now=3-6]



location:   0%|                                                                                           | 0/243 [00:00<?, ?it/s, now=3-6]


Optimizing RCMFP-supported GenBank CDS for E. coli:   6%|███                                                | 2/33 [00:00<00:04,  7.69it/s]
constraint:   0%|                                                                                          | 0/8 [00:00<?, ?it/s, now=None]
constraint:   0%|                                                                  | 0/8 [00:00<?, ?it/s, now=AvoidPattern[0-1041](patt...]

location:   0%|                                                                                            | 0/4 [00:00<?, ?it/s, now=None]

location:   0%|                                                                                        | 0/4 [00:00<?, ?it/s, now=78-84(+)]



location:   0%|                                                                                        | 0/1 [00:00<?, ?it/s, now=78-84(+)]

location:   0%|                                                                                         | 0/1 [00:00<?, ?it/s, now=546-604]



location:   0%|                                                                                         | 0/1 [00:00<?, ?it/s, now=546-604]



objective:   0%|                                                                                           | 0/1 [00:00<?, ?it/s, now=None]
objective:   0%|                                                                   | 0/1 [00:00<?, ?it/s, now=MaximizeCAI[0-1041](e_col...]

location:   0%|                                                                                       | 0/200 [00:00<?, ?it/s, now=546-604]

location:   0%|                                                                                           | 0/200 [00:00<?, ?it/s, now=3-6]



location:   0%|                                                                                           | 0/200 [00:00<?, ?it/s, now=3-6]


Optimizing RCMFP-supported GenBank CDS for E. coli:   9%|████▋                                              | 3/33 [00:00<00:03,  7.97it/s]
constraint:   0%|                                                                                          | 0/8 [00:00<?, ?it/s, now=None]
constraint:   0%|                                                                  | 0/8 [00:00<?, ?it/s, now=AvoidPattern[0-2682](patt...]

location:   0%|                                                                                            | 0/2 [00:00<?, ?it/s, now=None]

location:   0%|                                                                                    | 0/2 [00:00<?, ?it/s, now=1175-1181(-)]



location:   0%|                                                                                    | 0/2 [00:00<?, ?it/s, now=1175-1181(-)]

location:   0%|                                                                                      | 0/2 [00:00<?, ?it/s, now=793-799(-)]



location:   0%|                                                                                      | 0/2 [00:00<?, ?it/s, now=793-799(-)]



location:   0%|                                                                                      | 0/3 [00:00<?, ?it/s, now=793-799(-)]

location:   0%|                                                                                      | 0/3 [00:00<?, ?it/s, now=205-211(+)]



location:   0%|                                                                                      | 0/3 [00:00<?, ?it/s, now=205-211(+)]



location:   0%|                                                                                      | 0/3 [00:00<?, ?it/s, now=205-211(+)]

location:   0%|                                                                                          | 0/3 [00:00<?, ?it/s, now=26-123]



location:   0%|                                                                                          | 0/3 [00:00<?, ?it/s, now=26-123]



objective:   0%|                                                                                           | 0/1 [00:00<?, ?it/s, now=None]
objective:   0%|                                                                   | 0/1 [00:00<?, ?it/s, now=MaximizeCAI[0-2682](e_col...]

location:   0%|                                                                                        | 0/581 [00:00<?, ?it/s, now=26-123]

location:   0%|                                                                                           | 0/581 [00:00<?, ?it/s, now=3-6]



location:   0%|                                                                                           | 0/581 [00:00<?, ?it/s, now=3-6]

location:   0%|▏                                                                            | 1/581 [00:00<01:54,  5.06it/s, now=2220-2223]

location:   0%|▏                                                                            | 1/581 [00:00<01:55,  5.02it/s, now=2220-2223]


Optimizing RCMFP-supported GenBank CDS for E. coli:  12%|██████▏                                            | 4/33 [00:00<00:05,  5.08it/s]
constraint:   0%|                                                                                          | 0/8 [00:00<?, ?it/s, now=None]
constraint:   0%|                                                                  | 0/8 [00:00<?, ?it/s, now=AvoidPattern[0-1065](patt...]

location:   0%|                                                                                            | 0/1 [00:00<?, ?it/s, now=None]

location:   0%|                                                                                      | 0/1 [00:00<?, ?it/s, now=832-838(-)]



location:   0%|                                                                                      | 0/1 [00:00<?, ?it/s, now=832-838(-)]

location:   0%|                                                                                         | 0/1 [00:00<?, ?it/s, now=421-513]



location:   0%|                                                                                         | 0/1 [00:00<?, ?it/s, now=421-513]



objective:   0%|                                                                                           | 0/1 [00:00<?, ?it/s, now=None]
objective:   0%|                                                                   | 0/1 [00:00<?, ?it/s, now=MaximizeCAI[0-1065](e_col...]

location:   0%|                                                                                       | 0/216 [00:00<?, ?it/s, now=421-513]

location:   0%|                                                                                           | 0/216 [00:00<?, ?it/s, now=6-9]



location:   0%|                                                                                           | 0/216 [00:00<?, ?it/s, now=6-9]


Optimizing RCMFP-supported GenBank CDS for E. coli:  15%|███████▋                                           | 5/33 [00:00<00:04,  5.91it/s]
constraint:   0%|                                                                                          | 0/8 [00:00<?, ?it/s, now=None]
constraint:   0%|                                                                  | 0/8 [00:00<?, ?it/s, now=AvoidPattern[0-966](patte...]

location:   0%|                                                                                            | 0/3 [00:00<?, ?it/s, now=None]

location:   0%|                                                                                        | 0/3 [00:00<?, ?it/s, now=62-68(+)]



location:   0%|                                                                                        | 0/7 [00:00<?, ?it/s, now=62-68(+)]

location:   0%|                                                                                          | 0/7 [00:00<?, ?it/s, now=67-162]



location:   0%|                                                                                          | 0/7 [00:00<?, ?it/s, now=67-162]



objective:   0%|                                                                                           | 0/1 [00:00<?, ?it/s, now=None]
objective:   0%|                                                                   | 0/1 [00:00<?, ?it/s, now=MaximizeCAI[0-966](e_coli...]

location:   0%|                                                                                        | 0/159 [00:00<?, ?it/s, now=67-162]

location:   0%|                                                                                           | 0/159 [00:00<?, ?it/s, now=3-6]



location:   0%|                                                                                           | 0/159 [00:00<?, ?it/s, now=3-6]


Optimizing RCMFP-supported GenBank CDS for E. coli:  18%|█████████▎                                         | 6/33 [00:00<00:03,  6.77it/s]
constraint:   0%|                                                                                          | 0/8 [00:00<?, ?it/s, now=None]
constraint:   0%|                                                                  | 0/8 [00:00<?, ?it/s, now=AvoidPattern[0-1932](patt...]

location:   0%|                                                                                            | 0/3 [00:00<?, ?it/s, now=None]

location:   0%|                                                                                      | 0/3 [00:00<?, ?it/s, now=411-417(-)]



location:   0%|                                                                                      | 0/1 [00:00<?, ?it/s, now=411-417(-)]

location:   0%|                                                                                    | 0/1 [00:00<?, ?it/s, now=1400-1406(+)]



location:   0%|                                                                                    | 0/1 [00:00<?, ?it/s, now=1400-1406(+)]



location:   0%|                                                                                    | 0/1 [00:00<?, ?it/s, now=1400-1406(+)]

location:   0%|                                                                                    | 0/1 [00:00<?, ?it/s, now=1777-1783(+)]



location:   0%|                                                                                    | 0/1 [00:00<?, ?it/s, now=1777-1783(+)]



location:   0%|                                                                                    | 0/3 [00:00<?, ?it/s, now=1777-1783(+)]

location:   0%|                                                                                         | 0/3 [00:00<?, ?it/s, now=698-797]



location:   0%|                                                                                         | 0/3 [00:00<?, ?it/s, now=698-797]



objective:   0%|                                                                                           | 0/1 [00:00<?, ?it/s, now=None]
objective:   0%|                                                                   | 0/1 [00:00<?, ?it/s, now=MaximizeCAI[0-1932](e_col...]

location:   0%|                                                                                       | 0/394 [00:00<?, ?it/s, now=698-797]

location:   0%|                                                                                           | 0/394 [00:00<?, ?it/s, now=3-6]



location:   0%|                                                                                           | 0/394 [00:00<?, ?it/s, now=3-6]

location: 100%|███████████████████████████████████████████████████████████████████████████████| 394/394 [00:00<00:00, 2394.58it/s, now=3-6]


Optimizing RCMFP-supported GenBank CDS for E. coli:  21%|██████████▊                                        | 7/33 [00:01<00:04,  5.84it/s]
constraint:   0%|                                                                                          | 0/8 [00:00<?, ?it/s, now=None]
constraint:   0%|                                                                  | 0/8 [00:00<?, ?it/s, now=AvoidPattern[0-21219](pat...]

location:   0%|                                                                                            | 0/6 [00:00<?, ?it/s, now=None]

location:   0%|                                                                                    | 0/6 [00:00<?, ?it/s, now=1329-1335(-)]



location:   0%|                                                                                    | 0/4 [00:00<?, ?it/s, now=1329-1335(-)]

location:   0%|                                                                                        | 0/4 [00:00<?, ?it/s, now=70-76(-)]



location:   0%|                                                                                        | 0/4 [00:00<?, ?it/s, now=70-76(-)]



location:   0%|                                                                                        | 0/4 [00:00<?, ?it/s, now=70-76(-)]

location:   0%|                                                                                  | 0/4 [00:00<?, ?it/s, now=15324-15330(+)]



location:   0%|                                                                                  | 0/4 [00:00<?, ?it/s, now=15324-15330(+)]



location:   0%|                                                                                  | 0/2 [00:00<?, ?it/s, now=15324-15330(+)]

location:   0%|                                                                                    | 0/2 [00:00<?, ?it/s, now=6492-6498(+)]



location:   0%|                                                                                    | 0/2 [00:00<?, ?it/s, now=6492-6498(+)]



location:   0%|                                                                                    | 0/5 [00:00<?, ?it/s, now=6492-6498(+)]

location:   0%|                                                                                    | 0/5 [00:00<?, ?it/s, now=3801-3807(+)]



location:   0%|                                                                                    | 0/5 [00:00<?, ?it/s, now=3801-3807(+)]



location:   0%|                                                                                    | 0/3 [00:00<?, ?it/s, now=3801-3807(+)]

location:   0%|                                                                                    | 0/3 [00:00<?, ?it/s, now=9714-9720(+)]



location:   0%|                                                                                    | 0/3 [00:00<?, ?it/s, now=9714-9720(+)]



location:   0%|                                                                                   | 0/30 [00:00<?, ?it/s, now=9714-9720(+)]

location:   0%|                                                                                      | 0/30 [00:00<?, ?it/s, now=1458-1509]



location:   0%|                                                                                      | 0/30 [00:00<?, ?it/s, now=1458-1509]



objective:   0%|                                                                                           | 0/1 [00:00<?, ?it/s, now=None]
objective:   0%|                                                                   | 0/1 [00:00<?, ?it/s, now=MaximizeCAI[0-21219](e_co...]

location:   0%|                                                                                    | 0/4728 [00:00<?, ?it/s, now=1458-1509]

location:   0%|                                                                                          | 0/4728 [00:00<?, ?it/s, now=3-6]



location:   0%|                                                                                          | 0/4728 [00:00<?, ?it/s, now=3-6]

location:   0%|                                                                            | 1/4728 [00:00<15:32,  5.07it/s, now=2172-2175]

location:   0%|                                                                            | 1/4728 [00:00<15:39,  5.03it/s, now=2172-2175]

location:  10%|███████▎                                                                  | 467/4728 [00:00<14:07,  5.03it/s, now=4233-4236]

location:  10%|███████                                                                 | 467/4728 [00:00<00:03, 1373.29it/s, now=4233-4236]

location:  20%|██████████████▏                                                         | 930/4728 [00:00<00:02, 1373.29it/s, now=6150-6153]

location:  20%|██████████████▏                                                         | 930/4728 [00:00<00:02, 1806.14it/s, now=6150-6153]

location:  29%|████████████████████▋                                                  | 1379/4728 [00:00<00:01, 1806.14it/s, now=8127-8130]

location:  29%|████████████████████▋                                                  | 1379/4728 [00:00<00:01, 1972.88it/s, now=8127-8130]

location:  38%|██████████████████████████▌                                          | 1819/4728 [00:00<00:01, 1972.88it/s, now=10047-10050]

location:  38%|██████████████████████████▌                                          | 1819/4728 [00:01<00:01, 2054.83it/s, now=10047-10050]

location:  48%|████████████████████████████████▊                                    | 2248/4728 [00:01<00:01, 2054.83it/s, now=11847-11850]

location:  48%|████████████████████████████████▊                                    | 2248/4728 [00:01<00:01, 2085.55it/s, now=11847-11850]

location:  56%|██████████████████████████████████████▊                              | 2663/4728 [00:01<00:00, 2085.55it/s, now=13668-13671]

location:  56%|██████████████████████████████████████▊                              | 2663/4728 [00:01<00:00, 2082.38it/s, now=13668-13671]

location:  65%|████████████████████████████████████████████▊                        | 3074/4728 [00:01<00:00, 2082.38it/s, now=15519-15522]

location:  65%|████████████████████████████████████████████▊                        | 3074/4728 [00:01<00:00, 2072.02it/s, now=15519-15522]


Optimization status:
codonOptimizationStatus
success    33
Name: count, dtype: int64

Final reactionDF_wOptimizedDNAseq:
Rows total           : 3,477
Rows optimized       : 3,477
Unique optimized CDS : 33

,reactants,products,reactionString,ruleName,thermo,reactantStoich,productStoich,reactionType,numReactantMolecules,numProductMolecules,...,targetSpecies,minGc,maxGc,gcWindow,stopCodonUsed,codonOptimizationStatus,codonOptimizationError,constraintsSummary,objectivesSummary,hasOptimizedCds
0,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)(O)OP(=O)(O)O...,NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)(O)OP(=O)...,rule0165_2,No_Thermo,"(1, 1, 1, 1)","(1, 1, 1)",Enzymatic,4,3,...,e_coli,0.3,0.7,50,TAA,success,,===> SUCCESS - all constraints evaluations pas...,===> TOTAL OBJECTIVES SCORE: -12.57\n -1...,True
1,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,e_coli,0.3,0.7,50,TAA,success,,===> SUCCESS - all constraints evaluations pas...,===> TOTAL OBJECTIVES SCORE: -7.88\n -...,True
2,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,e_coli,0.3,0.7,50,TAA,success,,===> SUCCESS - all constraints evaluations pas...,===> TOTAL OBJECTIVES SCORE: -7.88\n -...,True
3,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,e_coli,0.3,0.7,50,TAA,success,,===> SUCCESS - all constraints evaluations pas...,===> TOTAL OBJECTIVES SCORE: -7.88\n -...,True
4,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)(...,CC(=O)OC[C@H]1O[C@@H](n2cnc3c(=O)[nH]cnc32)[C@...,rule0061_4,No_Thermo,"(1, 1)","(1, 1)",Enzymatic,2,2,...,e_coli,0.3,0.7,50,TAA,success,,===> SUCCESS - all constraints evaluations pas...,===> TOTAL OBJECTIVES SCORE: -7.88\n -...,True

## 8. Export `DNA design` files for `Teselagen`

In [60]:
optimizedDNAFilePath = os.path.join(DNADesignResultsDir,"reactionDF_wBestRCMFP_optimized_Ecoli.fasta")

fastaDF = (reactionDF_wOptimizedDNAseq[reactionDF_wOptimizedDNAseq["hasOptimizedCds"]].drop_duplicates("optimizationInputKey").copy())

with open(optimizedDNAFilePath, "w", encoding="utf-8") as f:
    for _, row in fastaDF.iterrows():
        fastaHeader = (
            f">{row['optimizedGeneId']}|"
            f"rule={safeText(row.get('ruleName', ''))}|"
            f"UniProt={safeText(row.get('uniprotAccession', ''))}|"
            f"GenBankProtein={safeText(row.get('genbankProteinAccessionUsed', ''))}|"
            f"EC={safeText(row.get('ecNumber', ''))}|"
            f"host=Escherichia_coli"
        )

        f.write(fastaHeader + "\n")
        f.write(wrapFasta(row["optimizedCds"]) + "\n\n")

print(f"\nSaved FASTA at: {optimizedDNAFilePath}")

Saved FASTA at: /mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/DrugDesignData/Results/combinedEbolaVirus_bestMACAW_allDB_generative/DNA_design/reactionDF_wBestRCMFP_optimized_Ecoli.fasta

### Find unique `starter --> target` from reconstructed pathways

In [61]:
# Count complete starter --> target reconstructed pathways per directory
to_bool = lambda s: s.astype(str).str.lower().isin(["true", "1", "yes"])

first = reactionDF_wOptimizedDNAseq[reactionDF_wOptimizedDNAseq["step"].eq(1)]
final = reactionDF_wOptimizedDNAseq[reactionDF_wOptimizedDNAseq["step"].eq(reactionDF_wOptimizedDNAseq["numSteps"])]

complete_ids = set(first.loc[to_bool(first["starterInReactants"]), "routeId"].astype(str)) & \
               set(final.loc[to_bool(final["targetInProducts"]), "routeId"].astype(str))

completeRouteLevelDF = (
    reactionDF_wOptimizedDNAseq[reactionDF_wOptimizedDNAseq["routeId"].astype(str).isin(complete_ids)]
    .sort_values(["dirName", "routeId", "step"])
    .groupby("routeId", as_index=False)
    .agg(
        dirName=("dirName", "first"),
        jobName=("jobName", "first"),
        sourceFolderNum=("sourceFolderNum", "first"),
        numSteps=("numSteps", "first"),
        searchDepthUsed=("searchDepthUsed", "first"),
        starterSMILES=("starterSMILES", "first"),
        targetSMILES=("targetSMILES", "first"),
        reconstructedPathwayString=("reconstructedPathwayString", "first"),
    )
)

starterTargetPathwayCountsDF = (
    completeRouteLevelDF
    .pivot_table(
        index=["dirName", "jobName", "starterSMILES", "targetSMILES"],
        columns="numSteps",
        values="routeId",
        aggfunc="nunique",
        fill_value=0,
    )
    .rename(columns={1: "numOneStepPathways", 2: "numTwoStepPathways", 3: "numThreeStepPathways"})
    .reset_index()
)

for c in ["numOneStepPathways", "numTwoStepPathways", "numThreeStepPathways"]:
    if c not in starterTargetPathwayCountsDF.columns:
        starterTargetPathwayCountsDF[c] = 0

starterTargetPathwayCountsDF["totalStarterToTargetPathways"] = (
    starterTargetPathwayCountsDF["numOneStepPathways"] +
    starterTargetPathwayCountsDF["numTwoStepPathways"] +
    starterTargetPathwayCountsDF["numThreeStepPathways"]
)

starterTargetPathwayCountsDF = starterTargetPathwayCountsDF.sort_values(
    "totalStarterToTargetPathways", ascending=False
).reset_index(drop=True)

print(f"Total reaction pathways : {len(reactionDF_wOptimizedDNAseq):,}")
print(f"Complete starter --> target pathways: {len(completeRouteLevelDF):,}")
print(f"Directories reached starter --> target pathways: {starterTargetPathwayCountsDF['dirName'].nunique():,}")

starterTargetPathwayCountsDF

Total reaction pathways : 3,477
Complete starter --> target pathways: 233
Directories reached starter --> target pathways: 4

numSteps,dirName,jobName,starterSMILES,targetSMILES,numOneStepPathways,numTwoStepPathways,numThreeStepPathways,totalStarterToTargetPathways
0,high_pPotency_molecule_pathway2,high_pPotency_molecule_pathway2,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(C)(COP(=O)(O)OP(=O)(O)OCC1OC(n2cnc3c(N)ncnc...,1,7,112,120
1,high_pPotency_molecule_pathway6,high_pPotency_molecule_pathway6,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,NC(=O)C1=CN(C2OC(COP(=O)(O)OP(=O)(O)OCC3OC(n4c...,1,0,58,59
2,high_pPotency_molecule_pathway1,high_pPotency_molecule_pathway1,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,CC(=O)SCCNC(=O)CCNC(=O)C(O)C(C)(C)COP(=O)(O)OP...,0,0,50,50
3,high_pPotency_molecule_pathway18,high_pPotency_molecule_pathway18,O=c1[nH]cnc2c1ncn2C1OC(CO)C(O)C1O,NC(=O)c1ccc[n+](C2OC(COP(=O)(O)OP(=O)(O)OCC3OC...,0,1,3,4