# Extract Bio-Assay Data from Pubchem Database for all target `Viruses`

### Import packages

In [63]:
import io
import os
import time
import random
from typing import Dict, List, Optional

import requests
import pandas as pd
import numpy as np
from rdkit import Chem
import matplotlib.pyplot as plt

### Define data paths

In [6]:
dataDir = '/mnt/data.ese/nfs/users/sghosh6/DTRA_project/MACAW/DrugDesignData/'
modelBuildingDataDir = os.path.join(dataDir, 'modelBuildingData')

In [75]:
PubchemDataDir = os.path.join(dataDir, 'PubChem')
Ebola_PubchemDataDir = os.path.join(PubchemDataDir, 'PubChem_Ebola')
Lassa_PubchemDataDir = os.path.join(PubchemDataDir, 'PubChem_Lassa')
Marburg_PubchemDataDir = os.path.join(PubchemDataDir, 'PubChem_Marburg')
Nipah_PubchemDataDir = os.path.join(PubchemDataDir, 'PubChem_Nipah')
SARSCoV_PubchemDataDir = os.path.join(PubchemDataDir, 'PubChem_SARS-CoV')
VEEV_PubchemDataDir = os.path.join(PubchemDataDir, 'PubChem_VEEV')

In [76]:
def loadAllCsvsToOneDF(ebolaPubchemDataDir: str | Path) -> pd.DataFrame:
    ebolaPubchemDataDir = Path(ebolaPubchemDataDir)

    DFList = []
    for csvPath in sorted(ebolaPubchemDataDir.glob("*.csv")):
        try:
            DF = pd.read_csv(csvPath, dtype=str, low_memory=False)
            DF.insert(0, "sourceFile", csvPath.name)   # keep provenance
            DFList.append(DF)
        except Exception as e:
            print(f"[SKIP] {csvPath.name}: {e}")

    Ebola_PubchemData = pd.concat(DFList, ignore_index=True, sort=False) if DFList else pd.DataFrame()
    return Ebola_PubchemData


Ebola_PubchemData = loadAllCsvsToOneDF(Ebola_PubchemDataDir)
Ebola_PubchemData['Virus'] = 'Ebola'

In [77]:
def loadAllCsvsToOneDF(virusPubchemDataDir: str | Path) -> pd.DataFrame:
    virusPubchemDataDir = Path(virusPubchemDataDir)

    DFList = []
    for csvPath in sorted(virusPubchemDataDir.glob("*.csv")):
        try:
            DF = pd.read_csv(csvPath, dtype=str, low_memory=False)
            DF.insert(0, "sourceFile", csvPath.name)
            DFList.append(DF)
        except Exception as e:
            print(f"[SKIP] {csvPath.name}: {e}")

    return pd.concat(DFList, ignore_index=True, sort=False) if DFList else pd.DataFrame()


# ---- Provide the directory for each virus ----
virusToDirDict = {
    "Ebola":   Ebola_PubchemDataDir,
    "Lassa":   Lassa_PubchemDataDir,
    "Marburg": Marburg_PubchemDataDir,
    "Nipah":   Nipah_PubchemDataDir,
    "SARSCoV": SARSCoV_PubchemDataDir,
    "VEEV":    VEEV_PubchemDataDir,
}

DFList = []
for virusName, virusDir in virusToDirDict.items():
    DF = loadAllCsvsToOneDF(virusDir)
    DF["Virus"] = virusName
    DFList.append(DF)

allVirus_Pubchem = pd.concat(DFList, ignore_index=True, sort=False)
allVirus_Pubchem

[SKIP] AID_463114.csv: No columns to parse from file
[SKIP] AID_540249.csv: No columns to parse from file
[SKIP] AID_540278.csv: No columns to parse from file
[SKIP] AID_1859.csv: No columns to parse from file
[SKIP] AID_485354.csv: No columns to parse from file

/tmp/ipykernel_2416250/505014990.py:29: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  DF["Virus"] = virusName

[SKIP] AID_588723.csv: No columns to parse from file

/tmp/ipykernel_2416250/505014990.py:29: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  DF["Virus"] = virusName

,sourceFile,PUBCHEM_RESULT_TAG,PUBCHEM_SID,PUBCHEM_CID,PUBCHEM_EXT_DATASOURCE_SMILES,PUBCHEM_ACTIVITY_OUTCOME,PUBCHEM_ACTIVITY_SCORE,PUBCHEM_ACTIVITY_URL,PUBCHEM_ASSAYDATA_COMMENT,PubChem Standard Value,...,% Inhibition @ 0.039 uM Test 4,% Inhibition @ 0.02 uM Test 4,% Inhibition @ 0.313 uM Test 1,% Inhibition @ 0.01 uM Test 1,% Inhibition @ 0.005 uM Test 1,% Inhibition @ 0.01 uM Test 2,% Inhibition @ 0.005 uM Test 2,% Inhibition @ 0.313 uM Test 3,% Inhibition @ 0.01 uM Test 3,% Inhibition @ 0.005 uM Test 3
0,AID_1161561.csv,RESULT_TYPE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLOAT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AID_1161561.csv,RESULT_DESCR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PubChem standardized value transformed from 'S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AID_1161561.csv,RESULT_UNIT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MICROMOLAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AID_1161561.csv,RESULT_IS_ACTIVE_CONCENTRATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,TRUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AID_1161561.csv,RESULT_IS_ACTIVE_CONCENTRATION_QUALIFIER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1785195,AID_672904.csv,2,160701578,66552950,C1=C([C@H]([C@H]([C@@H]1N2C=NC3=C2C(=CN=C3N)Br...,Inactive,NaN,NaN,Potential missing data,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1785196,AID_756347.csv,RESULT_TYPE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1785197,AID_756347.csv,RESULT_DESCR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1785198,AID_756347.csv,1,174517400,71723319,C[C@H](C[C@H]1C[C@H]([C@@H]([C@@H]1O)O)N2C=NC3...,Inactive,NaN,NaN,Potential missing data,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1785199,AID_756347.csv,2,174522617,71723318,C[C@@H](C[C@H]1C[C@H]([C@@H]([C@@H]1O)O)N2C=NC...,Inactive,NaN,NaN,Potential missing data,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
allVirus_Pubchem = allVirus_Pubchem[['PUBCHEM_CID', 'PUBCHEM_EXT_DATASOURCE_SMILES', 'PubChem Standard Value', 'Standard Type',
                                      'Standard Relation', 'Standard Value', 'Standard Units', 'Virus']]
allVirus_Pubchem = allVirus_Pubchem.dropna(subset=["PUBCHEM_EXT_DATASOURCE_SMILES"])
allVirus_Pubchem

,PUBCHEM_CID,PUBCHEM_EXT_DATASOURCE_SMILES,PubChem Standard Value,Standard Type,Standard Relation,Standard Value,Standard Units,Virus
5,12187083,C1=C([C@@H]([C@@H]([C@H]1CO)O)O)N2C=NC3=C(N=CN...,0.38,EC50,=,380,nM,Ebola
6,118714010,C1=C([C@H]([C@H]([C@@H]1CO)O)O)N2C=NC3=C(N=CN=...,0.76,EC50,=,760,nM,Ebola
12,66552950,C1=C([C@H]([C@H]([C@@H]1N2C=NC3=C2C(=CN=C3N)Br...,0.32,EC50,<,320,nM,Ebola
13,66552950,C1=C([C@H]([C@H]([C@@H]1N2C=NC3=C2C(=CN=C3N)Br...,3.02,EC90,=,3.02,uM,Ebola
14,118895044,C1=CN=C(C2=C1N(C=N2)C3=C[C@H]([C@@H]([C@@H]3O)...,0.32,EC50,<,320,nM,Ebola
...,...,...,...,...,...,...,...,...
1785191,71301449,CN1CCN(C(=NC2=C(C=C(C=C2)C#N)C(=O)NC3=CC(=CC=C...,NaN,NaN,NaN,NaN,NaN,VEEV
1785194,66552951,C1[C@@H]([C@H]([C@H]([C@@H]1N2C=NC3=C2C(=CN=C3...,NaN,Activity,NaN,NaN,NaN,VEEV
1785195,66552950,C1=C([C@H]([C@H]([C@@H]1N2C=NC3=C2C(=CN=C3N)Br...,NaN,Activity,NaN,NaN,NaN,VEEV
1785198,71723319,C[C@H](C[C@H]1C[C@H]([C@@H]([C@@H]1O)O)N2C=NC3...,NaN,Activity,NaN,NaN,NaN,VEEV
1785199,71723318,C[C@@H](C[C@H]1C[C@H]([C@@H]([C@@H]1O)O)N2C=NC...,NaN,Activity,NaN,NaN,NaN,VEEV

In [79]:
# Normalize Standard Units (handles µ, NBSP, spaces, and case)
unitNormalized = (
    allVirus_Pubchem["Standard Units"]
    .astype(str)
    .str.replace("\u00a0", " ", regex=False)   # non-breaking space
    .str.strip()
    .str.replace("µ", "u", regex=False)        # µM -> uM
    .str.replace(" ", "", regex=False)         # remove internal spaces
    .str.lower()
)

# Units that can be converted to molar concentrations for pIC50/pPotency
convertibleUnitsSet = {
    "nm",        # nM
    "um",        # uM (including µM -> uM)
    "mm",        # mM
    "m",         # M
    "umol/l",    # umol/L == uM
    "nmol/l",    # nmol/L == nM (in case it shows up)
    "mmol/l",    # mmol/L == mM (in case it shows up)
    "mol/l",     # mol/L == M (in case it shows up)
}

unitMask = unitNormalized.isin(convertibleUnitsSet)

allVirus_Pubchem = allVirus_Pubchem[unitMask].copy()
allVirus_Pubchem

,PUBCHEM_CID,PUBCHEM_EXT_DATASOURCE_SMILES,PubChem Standard Value,Standard Type,Standard Relation,Standard Value,Standard Units,Virus
5,12187083,C1=C([C@@H]([C@@H]([C@H]1CO)O)O)N2C=NC3=C(N=CN...,0.38,EC50,=,380,nM,Ebola
6,118714010,C1=C([C@H]([C@H]([C@@H]1CO)O)O)N2C=NC3=C(N=CN=...,0.76,EC50,=,760,nM,Ebola
12,66552950,C1=C([C@H]([C@H]([C@@H]1N2C=NC3=C2C(=CN=C3N)Br...,0.32,EC50,<,320,nM,Ebola
13,66552950,C1=C([C@H]([C@H]([C@@H]1N2C=NC3=C2C(=CN=C3N)Br...,3.02,EC90,=,3.02,uM,Ebola
14,118895044,C1=CN=C(C2=C1N(C=N2)C3=C[C@H]([C@@H]([C@@H]3O)...,0.32,EC50,<,320,nM,Ebola
...,...,...,...,...,...,...,...,...
1436682,11708526,C1=C([C@H]([C@H]([C@@H]1N2C=C(N=N2)C(=O)N)O)O)CO,100,EC50,>,100000,nM,VEEV
1436683,11550471,C1=C([C@H]([C@H]([C@@H]1N2C=NC(=N2)C(=O)N)O)O)CO,100,EC50,>,100000,nM,VEEV
1436689,11500074,C1=C([C@H]([C@H]([C@@H]1N2C=C(N=C2)C(=O)N)O)O)CO,100,IC50,>,100000,nM,VEEV
1436690,11708526,C1=C([C@H]([C@H]([C@@H]1N2C=C(N=N2)C(=O)N)O)O)CO,100,IC50,>,100000,nM,VEEV
1436691,11550471,C1=C([C@H]([C@H]([C@@H]1N2C=NC(=N2)C(=O)N)O)O)CO,100,IC50,>,100000,nM,VEEV

### compute `pPotency = -log10(value_in_M)` to match all the standards

In [80]:
# numeric standard value
standardValueNum = pd.to_numeric(allVirus_Pubchem["Standard Value"], errors="coerce")

# normalize units
unitNormalized = (
    allVirus_Pubchem["Standard Units"]
    .astype(str)
    .str.replace("\u00a0", " ", regex=False)  # NBSP
    .str.strip()
    .str.replace("µ", "u", regex=False)       # µM -> uM
    .str.replace(" ", "", regex=False)
    .str.lower()
)

# unit -> factor to convert to molar
unitToMolarFactorDict = {
    "nm": 1e-9,
    "um": 1e-6,
    "mm": 1e-3,
    "m": 1.0,
    # optional common aliases:
    "umol/l": 1e-6,
    "nmol/l": 1e-9,
    "mmol/l": 1e-3,
    "mol/l": 1.0,
}

molarFactor = unitNormalized.map(unitToMolarFactorDict)

# compute pPotency = -log10(value_in_M)
valueM = standardValueNum * molarFactor
allVirus_Pubchem["pPotency"] = np.where(valueM > 0, -np.log10(valueM), np.nan)
allVirus_Pubchem

/users/sghosh6/.conda/envs/pubchemData/lib/python3.13/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)
/users/sghosh6/.conda/envs/pubchemData/lib/python3.13/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)

,PUBCHEM_CID,PUBCHEM_EXT_DATASOURCE_SMILES,PubChem Standard Value,Standard Type,Standard Relation,Standard Value,Standard Units,Virus,pPotency
5,12187083,C1=C([C@@H]([C@@H]([C@H]1CO)O)O)N2C=NC3=C(N=CN...,0.38,EC50,=,380,nM,Ebola,6.420216
6,118714010,C1=C([C@H]([C@H]([C@@H]1CO)O)O)N2C=NC3=C(N=CN=...,0.76,EC50,=,760,nM,Ebola,6.119186
12,66552950,C1=C([C@H]([C@H]([C@@H]1N2C=NC3=C2C(=CN=C3N)Br...,0.32,EC50,<,320,nM,Ebola,6.494850
13,66552950,C1=C([C@H]([C@H]([C@@H]1N2C=NC3=C2C(=CN=C3N)Br...,3.02,EC90,=,3.02,uM,Ebola,5.519993
14,118895044,C1=CN=C(C2=C1N(C=N2)C3=C[C@H]([C@@H]([C@@H]3O)...,0.32,EC50,<,320,nM,Ebola,6.494850
...,...,...,...,...,...,...,...,...,...
1436682,11708526,C1=C([C@H]([C@H]([C@@H]1N2C=C(N=N2)C(=O)N)O)O)CO,100,EC50,>,100000,nM,VEEV,4.000000
1436683,11550471,C1=C([C@H]([C@H]([C@@H]1N2C=NC(=N2)C(=O)N)O)O)CO,100,EC50,>,100000,nM,VEEV,4.000000
1436689,11500074,C1=C([C@H]([C@H]([C@@H]1N2C=C(N=C2)C(=O)N)O)O)CO,100,IC50,>,100000,nM,VEEV,4.000000
1436690,11708526,C1=C([C@H]([C@H]([C@@H]1N2C=C(N=N2)C(=O)N)O)O)CO,100,IC50,>,100000,nM,VEEV,4.000000
1436691,11550471,C1=C([C@H]([C@H]([C@@H]1N2C=NC(=N2)C(=O)N)O)O)CO,100,IC50,>,100000,nM,VEEV,4.000000

In [81]:
# Rename columns
allVirus_Pubchem = allVirus_Pubchem.rename(
    columns={'PUBCHEM_EXT_DATASOURCE_SMILES': 'Smiles', 'PUBCHEM_CID': 'compound_id'})
# Reorder columns
allVirus_Pubchem = allVirus_Pubchem[
    ['Virus', 'compound_id', 'Smiles', 'pPotency']]
allVirus_Pubchem

,Virus,compound_id,Smiles,pPotency
5,Ebola,12187083,C1=C([C@@H]([C@@H]([C@H]1CO)O)O)N2C=NC3=C(N=CN...,6.420216
6,Ebola,118714010,C1=C([C@H]([C@H]([C@@H]1CO)O)O)N2C=NC3=C(N=CN=...,6.119186
12,Ebola,66552950,C1=C([C@H]([C@H]([C@@H]1N2C=NC3=C2C(=CN=C3N)Br...,6.494850
13,Ebola,66552950,C1=C([C@H]([C@H]([C@@H]1N2C=NC3=C2C(=CN=C3N)Br...,5.519993
14,Ebola,118895044,C1=CN=C(C2=C1N(C=N2)C3=C[C@H]([C@@H]([C@@H]3O)...,6.494850
...,...,...,...,...
1436682,VEEV,11708526,C1=C([C@H]([C@H]([C@@H]1N2C=C(N=N2)C(=O)N)O)O)CO,4.000000
1436683,VEEV,11550471,C1=C([C@H]([C@H]([C@@H]1N2C=NC(=N2)C(=O)N)O)O)CO,4.000000
1436689,VEEV,11500074,C1=C([C@H]([C@H]([C@@H]1N2C=C(N=C2)C(=O)N)O)O)CO,4.000000
1436690,VEEV,11708526,C1=C([C@H]([C@H]([C@@H]1N2C=C(N=N2)C(=O)N)O)O)CO,4.000000
1436691,VEEV,11550471,C1=C([C@H]([C@H]([C@@H]1N2C=NC(=N2)C(=O)N)O)O)CO,4.000000

### Canonicalize `SMILES`

In [82]:
def canonicalize_smiles(smi):
    mol = Chem.MolFromSmiles(smi)
    return Chem.MolToSmiles(mol, canonical=True) if mol else None

allVirus_Pubchem['Smiles'] = (
    allVirus_Pubchem['Smiles']
    .astype(str)
    .apply(canonicalize_smiles)
)
allVirus_Pubchem

,Virus,compound_id,Smiles,pPotency
5,Ebola,12187083,Nc1ncnc2c1ncn2C1=C[C@H](CO)[C@@H](O)[C@H]1O,6.420216
6,Ebola,118714010,Nc1ncnc2c1ncn2C1=C[C@@H](CO)[C@H](O)[C@@H]1O,6.119186
12,Ebola,66552950,Nc1ncc(Br)c2c1ncn2[C@@H]1C=C(CO)[C@@H](O)[C@H]1O,6.494850
13,Ebola,66552950,Nc1ncc(Br)c2c1ncn2[C@@H]1C=C(CO)[C@@H](O)[C@H]1O,5.519993
14,Ebola,118895044,Nc1nccc2c1ncn2C1=C[C@@H](CO)[C@H](O)[C@@H]1O,6.494850
...,...,...,...,...
1436682,VEEV,11708526,NC(=O)c1cn([C@@H]2C=C(CO)[C@@H](O)[C@H]2O)nn1,4.000000
1436683,VEEV,11550471,NC(=O)c1ncn([C@@H]2C=C(CO)[C@@H](O)[C@H]2O)n1,4.000000
1436689,VEEV,11500074,NC(=O)c1cn([C@@H]2C=C(CO)[C@@H](O)[C@H]2O)cn1,4.000000
1436690,VEEV,11708526,NC(=O)c1cn([C@@H]2C=C(CO)[C@@H](O)[C@H]2O)nn1,4.000000
1436691,VEEV,11550471,NC(=O)c1ncn([C@@H]2C=C(CO)[C@@H](O)[C@H]2O)n1,4.000000

In [84]:
typeCountSeries = allVirus_Pubchem["Virus"].dropna()

uniqueTypeCount = typeCountSeries.nunique()
totalCount = typeCountSeries.shape[0]

countDF = (
    typeCountSeries.value_counts()
    .rename_axis("Virus")
    .reset_index(name="count")
)
countDF["percent"] = (countDF["count"] / totalCount) * 100

print(f"Unique virus type: {uniqueTypeCount}")
print(countDF)

Unique virus type: 6
     Virus  count    percent
0  SARSCoV  28600  87.978344
1    Lassa   1276   3.925188
2    Ebola   1118   3.439153
3  Marburg    987   3.036176
4     VEEV    495   1.522702
5    Nipah     32   0.098437

In [85]:
allVirus_Pubchem.to_csv(os.path.join(modelBuildingDataDir, "allVirus_Pubchem.csv"), index=False)

### Use pubchem API to fecth data for all target viruses

In [ ]:
def requestWithRetry(
    url: str,
    params: Optional[dict] = None,
    timeoutSec: int = 60,
    maxRetries: int = 8,
    baseSleepSec: float = 0.5,
    userAgent: str = "virus-bioassay-harvester/1.0 (email: your_email@domain)"
) -> requests.Response:
    """
    GET with exponential backoff. PubChem can throttle and return HTTP 503. :contentReference[oaicite:3]{index=3}
    """
    headers = {"User-Agent": userAgent}
    lastErr = None

    for attempt in range(maxRetries):
        try:
            resp = requests.get(url, params=params, headers=headers, timeout=timeoutSec)

            if resp.status_code == 503:
                sleepSec = (2 ** attempt) * baseSleepSec + random.random()
                time.sleep(sleepSec)
                continue

            resp.raise_for_status()
            time.sleep(0.2)  # polite pacing
            return resp

        except Exception as e:
            lastErr = e
            sleepSec = (2 ** attempt) * baseSleepSec + random.random()
            time.sleep(sleepSec)

    raise RuntimeError(f"Request failed after retries. url={url} lastErr={lastErr}")


def esearchPcAssayAids(
    term: str,
    retmax: int = 200,
    toolName: str = "virusBioassayHarvester",
    email: str = "your_email@domain",
    apiKey: Optional[str] = None
) -> List[int]:
    """
    Find PubChem BioAssay IDs (AIDs) via NCBI ESearch:
    Base: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/ :contentReference[oaicite:4]{index=4}
    Use tool/email (and optionally api_key) per E-utilities guidelines. :contentReference[oaicite:5]{index=5}
    """
    url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
    params = {
        "db": "pcassay",
        "term": term,
        "retmax": retmax,
        "retmode": "json",
        "tool": toolName,
        "email": email,
    }
    if apiKey:
        params["api_key"] = apiKey

    resp = requestWithRetry(url, params=params)
    data = resp.json()
    idList = data.get("esearchresult", {}).get("idlist", [])
    return [int(x) for x in idList]


def fetchConciseAssayCsv(aid: int) -> pd.DataFrame:
    """
    PubChem PUG-REST concise table for one assay:
    https://pubchem.ncbi.nlm.nih.gov/rest/pug/assay/aid/<AID>/concise/CSV :contentReference[oaicite:6]{index=6}
    """
    url = f"https://pubchem.ncbi.nlm.nih.gov/rest/pug/assay/aid/{aid}/concise/CSV"
    resp = requestWithRetry(url)
    DF = pd.read_csv(io.StringIO(resp.text))
    DF["AID"] = aid
    return DF


def buildAllVirusPubchem(
    virusQueryMap: Dict[str, str],
    aidsPerVirus: int = 200,
    onlyActive: bool = False,
    toolName: str = "virusBioassayHarvester",
    email: str = "your_email@domain",
    apiKey: Optional[str] = None
) -> pd.DataFrame:
    rows = []

    for virusName, entrezTerm in virusQueryMap.items():
        aids = esearchPcAssayAids(
            term=entrezTerm,
            retmax=aidsPerVirus,
            toolName=toolName,
            email=email,
            apiKey=apiKey
        )

        for aid in aids:
            try:
                DF = fetchConciseAssayCsv(aid)
                DF["Virus"] = virusName
                DF["EntrezTerm"] = entrezTerm
                rows.append(DF)
            except Exception:
                # Skip failures; they are often caused by very large or unusual assays
                continue

    if not rows:
        return pd.DataFrame()

    DF = pd.concat(rows, ignore_index=True)

    # Optional filter: keep only rows with an "Active" outcome if the column exists
    if onlyActive:
        outcomeColCandidates = [c for c in DF.columns if c.strip().lower() in ["activityoutcome", "outcome"]]
        if outcomeColCandidates:
            outcomeCol = outcomeColCandidates[0]
            DF = DF[DF[outcomeCol].astype(str).str.lower().eq("active")].copy()

    # User-requested name
    allVirus_pubchem = DF
    return allVirus_pubchem


# ---------------------------
# Customize your virus terms
# ---------------------------
virusQueryMap = {
    "Ebola": '(Ebola OR Ebolavirus OR "Zaire ebolavirus") AND (antiviral OR inhibitor OR neutralization OR IC50 OR EC50)',
    "Marburg": '(Marburg OR Marburgvirus) AND (antiviral OR inhibitor OR neutralization OR IC50 OR EC50)',
    "Lassa": '(Lassa OR "Lassa virus") AND (antiviral OR inhibitor OR neutralization OR IC50 OR EC50)',
    "VEEV": '("Venezuelan equine encephalitis" OR VEEV) AND (antiviral OR inhibitor OR neutralization OR IC50 OR EC50)',
    "Nipah": '(Nipah OR "Nipah virus") AND (antiviral OR inhibitor OR neutralization OR IC50 OR EC50)',
    "Hanta": '(Hantavirus OR "Hanta virus") AND (antiviral OR inhibitor OR neutralization OR IC50 OR EC50)',
    "SARS-CoV": '("SARS-CoV" OR "SARS coronavirus") AND (antiviral OR inhibitor OR neutralization OR IC50 OR EC50)',
    "SARS-CoV-2": '("SARS-CoV-2" OR COVID-19 OR "2019-nCoV") AND (antiviral OR inhibitor OR neutralization OR IC50 OR EC50)',
}

# Build the dataset
allVirus_pubchem = buildAllVirusPubchem(
    virusQueryMap=virusQueryMap,
    aidsPerVirus=150,   # increase carefully; SARS-CoV-2 can explode in size
    onlyActive=False,   # set True if you want only active outcomes (when available)
    toolName="virusBioassayHarvester",
    email="sghosh6@lbl.gov",
    apiKey="0ffd39fe99552944ce9a9204efef27be7109"         # add an NCBI api_key if you will run high-throughput calls :contentReference[oaicite:7]{index=7}
)

# Optional: persist
# allVirus_pubchem.to_parquet("allVirus_pubchem.parquet", index=False)
# allVirus_pubchem.to_csv("allVirus_pubchem.csv", index=False)

allVirus_pubchem

In [13]:
allVirus_pubchem.to_csv(os.path.join(modelBuildingDataDir, "allVirusData_pubchem.csv"), index=False)

In [14]:
allVirus_pubchem =  allVirus_pubchem.filter(
    items=['AID', 'SID', 'CID', 'Activity Value [uM]', 'Activity Name', 'Virus']
)
allVirus_pubchem

,AID,SID,CID,Activity Value [uM],Activity Name,Virus
0,2030413,504833062,172466261.0,NaN,NaN,Ebola
1,2030412,504815714,172454212.0,NaN,NaN,Ebola
2,2030411,482047675,168269649.0,NaN,NaN,Ebola
3,2030411,504795164,172439945.0,NaN,NaN,Ebola
4,2030411,504815714,172454212.0,NaN,NaN,Ebola
...,...,...,...,...,...,...
909454,2023137,504827342,172462264.0,0.13,EC50,SARS-CoV-2
909455,2023137,504837231,169494153.0,0.21,EC50,SARS-CoV-2
909456,2023136,461563615,155903259.0,0.28,EC50,SARS-CoV-2
909457,2023136,504827342,172462264.0,0.24,EC50,SARS-CoV-2
909458,2023136,504837231,169494153.0,0.21,EC50,SARS-CoV-2

### Types of Viruses

In [15]:
virusCounts = allVirus_pubchem["Virus"].value_counts(dropna=False)
virusPercents = allVirus_pubchem["Virus"].value_counts(normalize=True, dropna=False).mul(100).round(2)

virusSummaryDF_pubchem = pd.DataFrame({
    "count": virusCounts,
    "percent": virusPercents
})

print("\nNumber of virus labels:", allVirus_pubchem["Virus"].nunique(dropna=False))
virusSummaryDF_pubchem

Number of virus labels: 8

             count  percent
Virus
Lassa       678532    74.61
Hanta       215688    23.72
SARS-CoV-2    6656     0.73
SARS-CoV      6302     0.69
Marburg        816     0.09
VEEV           705     0.08
Ebola          677     0.07
Nipah           83     0.01

### Types of Bio-Activity

In [16]:
# Clean strings
allVirus_pubchem["Activity Name"] = allVirus_pubchem["Activity Name"].astype("string").str.strip()
allVirus_pubchem["Virus"] = allVirus_pubchem["Virus"].astype("string").str.strip()

# Normalize activity names for robust matching
DF = allVirus_pubchem.copy()
DF["activityNameNorm"] = (
    DF["Activity Name"]
    .astype("string")
    .str.strip()
    .str.upper()
)

# Keep only IC50/EC50-like endpoints
keepEndpoints = {"IC50", "EC50", "AC50", "POTENCY"}  # AC50/Potency are treated similarly in PubChem :contentReference[oaicite:1]{index=1}
DF = DF[DF["activityNameNorm"].isin(keepEndpoints)].copy()

# Ensure numeric Activity Value [uM] and keep valid values
DF["Activity Value [uM]"] = pd.to_numeric(DF["Activity Value [uM]"], errors="coerce")
DF = DF[DF["Activity Value [uM]"].notna() & (DF["Activity Value [uM]"] > 0)].copy()

# Optional: collapse "Potency" into AC50 label for consistency
DF["endpointType"] = DF["activityNameNorm"].replace({"POTENCY": "AC50"})

# Log-scale potency (pX): p = -log10(value in M) = 6 - log10(value in uM)
DF["pPotency"] = 6.0 - np.log10(DF["Activity Value [uM]"])

# Overwrite original if you want
allVirus_pubchem = DF.drop(columns=["activityNameNorm"])

# --- Activity summary after filtering ---
activityCounts = allVirus_pubchem["Activity Name"].value_counts(dropna=False)
activityPercents = allVirus_pubchem["Activity Name"].value_counts(normalize=True, dropna=False).mul(100).round(2)

activitySummaryDF = pd.DataFrame({"count": activityCounts, "percent": activityPercents})

print("Unique Activity Name values (IC50/EC50-like with numeric uM):",
      allVirus_pubchem["Activity Name"].nunique(dropna=False))
activitySummaryDF

Unique Activity Name values (IC50/EC50-like with numeric uM): 3

                count  percent
Activity Name
Potency        160043    92.34
IC50            11282     6.51
EC50             1989     1.15

In [17]:
allVirus_pubchem

,AID,SID,CID,Activity Value [uM],Activity Name,Virus,endpointType,pPotency
9,2030409,242407125,3779088.0,100.00,EC50,Ebola,EC50,4.000000
10,2030409,482047675,168269649.0,1.50,EC50,Ebola,EC50,5.823909
11,2030409,504795164,172439945.0,0.52,EC50,Ebola,EC50,6.283997
12,2030409,504804946,172446737.0,100.00,EC50,Ebola,EC50,4.000000
13,2030409,504815714,172454212.0,0.30,EC50,Ebola,EC50,6.522879
...,...,...,...,...,...,...,...,...
909454,2023137,504827342,172462264.0,0.13,EC50,SARS-CoV-2,EC50,6.886057
909455,2023137,504837231,169494153.0,0.21,EC50,SARS-CoV-2,EC50,6.677781
909456,2023136,461563615,155903259.0,0.28,EC50,SARS-CoV-2,EC50,6.552842
909457,2023136,504827342,172462264.0,0.24,EC50,SARS-CoV-2,EC50,6.619789
909458,2023136,504837231,169494153.0,0.21,EC50,SARS-CoV-2,EC50,6.677781

### Add `SMILES` from Pubchem to all the BioAssay data

In [23]:
def requestWithRetry(
    url: str,
    params: Optional[dict] = None,
    timeoutSec: int = 60,
    maxRetries: int = 10,
    baseSleepSec: float = 0.6,
    userAgent: str = "pubchem-smiles-fetcher/1.0 (email: your_email@domain)",
) -> requests.Response:
    headers = {"User-Agent": userAgent}

    for attempt in range(maxRetries):
        try:
            resp = requests.get(url, params=params, headers=headers, timeout=timeoutSec)

            # PubChem may throttle; backoff helps. :contentReference[oaicite:2]{index=2}
            if resp.status_code == 503:
                time.sleep((2**attempt) * baseSleepSec + random.random())
                continue

            resp.raise_for_status()
            time.sleep(0.15)  # polite pacing
            return resp

        except Exception:
            time.sleep((2**attempt) * baseSleepSec + random.random())

    raise RuntimeError(f"Failed after {maxRetries} retries: {url}")


def chunked(items: List[int], chunkSize: int) -> List[List[int]]:
    return [items[i : i + chunkSize] for i in range(0, len(items), chunkSize)]


def fetchSmilesForCidChunk(cidChunk: List[int], debug: bool = False) -> pd.DataFrame:
    """
    Fetch SMILES-like properties for multiple CIDs.
    Note: PubChem may return 'ConnectivitySMILES' instead of 'CanonicalSMILES'. :contentReference[oaicite:3]{index=3}
    """
    cidStr = ",".join(str(x) for x in cidChunk)

    # Request both Isomeric and Connectivity SMILES explicitly
    url = (
        "https://pubchem.ncbi.nlm.nih.gov/rest/pug/"
        f"compound/cid/{cidStr}/property/IsomericSMILES,ConnectivitySMILES,CanonicalSMILES/CSV"
    )

    resp = requestWithRetry(url)
    text = resp.text.lstrip()

    if not (text.startswith("CID,") or text.startswith('"CID"')):
        raise ValueError(f"Non-CSV response (first 200 chars): {text[:200]}")

    DF = pd.read_csv(io.StringIO(resp.text))

    if debug:
        print("[DEBUG] Returned columns:", DF.columns.tolist())
        print(DF.head(5))

    # Prefer isomeric (stereo), fall back to connectivity/canonical
    smilesColCandidates = [
        "IsomericSMILES",
        "ConnectivitySMILES",  # commonly returned for "canonical-like" SMILES :contentReference[oaicite:4]{index=4}
        "CanonicalSMILES",
        "SMILES",
    ]
    DF["smiles"] = pd.NA
    for col in smilesColCandidates:
        if col in DF.columns:
            DF["smiles"] = DF["smiles"].fillna(DF[col])

    return DF[["CID", "smiles"]]


def sanityCheckSmilesFetch(cidList: List[int], nTest: int = 10) -> None:
    # Known-good connectivity sanity: Aspirin CID 2244 returns ConnectivitySMILES. :contentReference[oaicite:5]{index=5}
    knownUrl = "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/2244/property/CanonicalSMILES/CSV"
    knownResp = requestWithRetry(knownUrl)
    print("[SANITY] Known CID (2244) response head:", knownResp.text[:120])

    testCids = cidList[:nTest]
    DF = fetchSmilesForCidChunk(testCids, debug=True)

    gotCount = int(DF["smiles"].notna().sum())
    print(f"[SANITY] Requested {len(testCids)} CIDs, received {len(DF)} rows, SMILES present for {gotCount} rows.")
    print(DF)

    if gotCount == 0:
        raise RuntimeError(
            "Sanity check failed: no SMILES columns were populated. "
            "The debug print above should show which SMILES column name PubChem returned."
        )


def fetchSmilesMapForCids(
    cidList: List[int],
    chunkSize: int = 50,
    verbose: bool = True,
) -> Dict[int, str]:
    smilesMap: Dict[int, str] = {}

    for cidChunk in chunked(cidList, chunkSize):
        try:
            DF = fetchSmilesForCidChunk(cidChunk, debug=False)
            for cid, smi in zip(DF["CID"], DF["smiles"]):
                if pd.notna(cid) and pd.notna(smi):
                    smilesMap[int(cid)] = str(smi)
        except Exception as e:
            if verbose:
                print(f"[WARN] Chunk failed (n={len(cidChunk)}): {e}")

    return smilesMap


# ---------------------------
# Main: sanity check -> full run
# ---------------------------
DF = allVirus_pubchem.copy()

DF["CID"] = pd.to_numeric(DF["CID"], errors="coerce")
uniqueCids = (
    DF["CID"]
    .dropna()
    .astype(int)
    .loc[lambda s: s > 0]
    .drop_duplicates()
    .tolist()
)

# 1) Sanity check (first 10)
sanityCheckSmilesFetch(uniqueCids, nTest=10)

# 2) Full fetch
smilesMap = fetchSmilesMapForCids(uniqueCids, chunkSize=50, verbose=True)

# 3) Add SMILES
DF["smiles"] = DF["CID"].astype("Int64").map(smilesMap)
allVirus_pubchem = DF

print(allVirus_pubchem[["CID", "smiles"]].head(10))
print("Missing SMILES rows:", int(allVirus_pubchem["smiles"].isna().sum()))

[SANITY] Known CID (2244) response head: "CID","ConnectivitySMILES"
2244,"CC(=O)OC1=CC=CC=C1C(=O)O"

[DEBUG] Returned columns: ['CID', 'SMILES', 'ConnectivitySMILES', 'ConnectivitySMILES.1']
         CID                                             SMILES  \
0    3779088       CN1CCN(CC1)CC(=O)NN(CC2=CC=CC=C2)C3=CC=CC=C3
1  168269649  C1CN(CCC1CCNCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)C...
2  172439945  C1CN(CCC1CCNCCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)...
3  172446737       CN1CCN(CC1)CCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3
4  172454212  C1CN(CCC1CCNCCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3)...

                                  ConnectivitySMILES  \
0       CN1CCN(CC1)CC(=O)NN(CC2=CC=CC=C2)C3=CC=CC=C3
1  C1CN(CCC1CCNCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)C...
2  C1CN(CCC1CCNCCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)...
3       CN1CCN(CC1)CCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3
4  C1CN(CCC1CCNCCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3)...

                                ConnectivitySMILES.1
0       CN1CCN(CC1)CC(=O)NN(CC2=CC=CC=C2)C3=CC=CC=C3
1  C1CN(CCC1CCNCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)C...
2  C1CN(CCC1CCNCCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)...
3       CN1CCN(CC1)CCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3
4  C1CN(CCC1CCNCCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3)...
[SANITY] Requested 10 CIDs, received 10 rows, SMILES present for 10 rows.
         CID                                             smiles
0    3779088       CN1CCN(CC1)CC(=O)NN(CC2=CC=CC=C2)C3=CC=CC=C3
1  168269649  C1CN(CCC1CCNCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)C...
2  172439945  C1CN(CCC1CCNCCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)...
3  172446737       CN1CCN(CC1)CCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3
4  172454212  C1CN(CCC1CCNCCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3)...
5  172457917  C1CN(CCC1CCNCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3)C...
6  172463060  C1CN(CCC1CCNCC(=O)NC2C3=CC=CC=C3C4=CC=CC=C24)C...
7  172466261  C1CN(CCN1CCNCCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3)...
8  172466407  C1CN(CCN1CCNCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3)C...
9    3005573  CN(C)CCOC1=CC=C(C=C1)C(=C(CCCl)C2=CC=CC=C2)C3=...
            CID                                             smiles
9     3779088.0       CN1CCN(CC1)CC(=O)NN(CC2=CC=CC=C2)C3=CC=CC=C3
10  168269649.0  C1CN(CCC1CCNCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)C...
11  172439945.0  C1CN(CCC1CCNCCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)...
12  172446737.0       CN1CCN(CC1)CCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3
13  172454212.0  C1CN(CCC1CCNCCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3)...
14  172457917.0  C1CN(CCC1CCNCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3)C...
15  172463060.0  C1CN(CCC1CCNCC(=O)NC2C3=CC=CC=C3C4=CC=CC=C24)C...
16  172466261.0  C1CN(CCN1CCNCCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3)...
17  172466407.0  C1CN(CCN1CCNCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3)C...
63    3005573.0  CN(C)CCOC1=CC=C(C=C1)C(=C(CCCl)C2=CC=CC=C2)C3=...
Missing SMILES rows: 390

In [25]:

allVirus_pubchem_wSMILES

,AID,SID,CID,Activity Value [uM],Activity Name,Virus,endpointType,pPotency,smiles
9,2030409,242407125,3779088.0,100.00,EC50,Ebola,EC50,4.000000,CN1CCN(CC1)CC(=O)NN(CC2=CC=CC=C2)C3=CC=CC=C3
10,2030409,482047675,168269649.0,1.50,EC50,Ebola,EC50,5.823909,C1CN(CCC1CCNCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)C...
11,2030409,504795164,172439945.0,0.52,EC50,Ebola,EC50,6.283997,C1CN(CCC1CCNCCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)...
12,2030409,504804946,172446737.0,100.00,EC50,Ebola,EC50,4.000000,CN1CCN(CC1)CCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3
13,2030409,504815714,172454212.0,0.30,EC50,Ebola,EC50,6.522879,C1CN(CCC1CCNCCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3)...
...,...,...,...,...,...,...,...,...,...
909454,2023137,504827342,172462264.0,0.13,EC50,SARS-CoV-2,EC50,6.886057,C1CN(C(CN1C(=O)C2=C3C(=CN=C2)C=CN3)C(=O)NCC4=C...
909455,2023137,504837231,169494153.0,0.21,EC50,SARS-CoV-2,EC50,6.677781,COC1=CC=C(C=C1)NC(=O)C2CN(CCN2C3=CC(=C(C=C3)Cl...
909456,2023136,461563615,155903259.0,0.28,EC50,SARS-CoV-2,EC50,6.552842,CC1(C2C1C(N(C2)C(=O)C(C(C)(C)C)NC(=O)C(F)(F)F)...
909457,2023136,504827342,172462264.0,0.24,EC50,SARS-CoV-2,EC50,6.619789,C1CN(C(CN1C(=O)C2=C3C(=CN=C2)C=CN3)C(=O)NCC4=C...
909458,2023136,504837231,169494153.0,0.21,EC50,SARS-CoV-2,EC50,6.677781,COC1=CC=C(C=C1)NC(=O)C2CN(CCN2C3=CC(=C(C=C3)Cl...

### Count and remove compounds missing `SMILES`

In [33]:
allVirus_pubchem_wSMILES = allVirus_pubchem.copy()
print(f"Shape before removing compounds with missing SMILES: {allVirus_pubchem_wSMILES.shape}")

missingSmilesCount = allVirus_pubchem_wSMILES["smiles"].isna().sum()
totalCount = len(allVirus_pubchem_wSMILES)
missingSmilesPercent = (missingSmilesCount / totalCount) * 100 if totalCount else 0.0

print(f"Missing SMILES: {missingSmilesCount} / {totalCount} ({missingSmilesPercent:.2f}%)")
allVirus_pubchem_wSMILES = allVirus_pubchem_wSMILES.dropna(subset=["smiles"]).reset_index(drop=True)
print(f"Shape after removing compounds with missing SMILES: {allVirus_pubchem_wSMILES.shape}")
allVirus_pubchem_wSMILES.to_csv(os.path.join(modelBuildingDataDir, "allVirus_pubchem_wSMILES.csv"), index=False)

Shape before removing compounds with missing SMILES: (173314, 9)
Missing SMILES: 390 / 173314 (0.23%)
Shape after removing compounds with missing SMILES: (172924, 9)

### Filter pPotency data

In [34]:
allVirus_pubchem_wSMILES = allVirus_pubchem_wSMILES[allVirus_pubchem_wSMILES['pPotency'].notna() 
    & (allVirus_pubchem_wSMILES['pPotency'] > 0) & (allVirus_pubchem_wSMILES['pPotency'] < 12)]

print("Shape after cleaning 'pPotency' value:", allVirus_pubchem_wSMILES.shape)

Shape after cleaning 'pPotency' value: (172924, 9)

In [36]:
allVirus_pubchem_wSMILES = (
    allVirus_pubchem_wSMILES
    .loc[:, ["CID", "Activity Value [uM]", "Activity Name", "Virus", "pPotency", "smiles"]]
    .rename(columns={"Activity Value [uM]": "value_uM"})
    .loc[:, ["CID", "smiles", "value_uM", "pPotency", "Activity Name", "Virus"]]
)
allVirus_pubchem_wSMILES

,CID,smiles,value_uM,pPotency,Activity Name,Virus
0,3779088.0,CN1CCN(CC1)CC(=O)NN(CC2=CC=CC=C2)C3=CC=CC=C3,100.00,4.000000,EC50,Ebola
1,168269649.0,C1CN(CCC1CCNCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)C...,1.50,5.823909,EC50,Ebola
2,172439945.0,C1CN(CCC1CCNCCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)...,0.52,6.283997,EC50,Ebola
3,172446737.0,CN1CCN(CC1)CCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3,100.00,4.000000,EC50,Ebola
4,172454212.0,C1CN(CCC1CCNCCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3)...,0.30,6.522879,EC50,Ebola
...,...,...,...,...,...,...
172919,172462264.0,C1CN(C(CN1C(=O)C2=C3C(=CN=C2)C=CN3)C(=O)NCC4=C...,0.13,6.886057,EC50,SARS-CoV-2
172920,169494153.0,COC1=CC=C(C=C1)NC(=O)C2CN(CCN2C3=CC(=C(C=C3)Cl...,0.21,6.677781,EC50,SARS-CoV-2
172921,155903259.0,CC1(C2C1C(N(C2)C(=O)C(C(C)(C)C)NC(=O)C(F)(F)F)...,0.28,6.552842,EC50,SARS-CoV-2
172922,172462264.0,C1CN(C(CN1C(=O)C2=C3C(=CN=C2)C=CN3)C(=O)NCC4=C...,0.24,6.619789,EC50,SARS-CoV-2
172923,169494153.0,COC1=CC=C(C=C1)NC(=O)C2CN(CCN2C3=CC(=C(C=C3)Cl...,0.21,6.677781,EC50,SARS-CoV-2

In [37]:
allVirus_pubchem_wSMILES.to_csv(os.path.join(modelBuildingDataDir, "allVirus_pubchem_uM.csv"), index=False)

### Read back fetched data and plot the distribution of data

In [8]:
allVirus_pubchem_wSMILES = pd.read_csv(os.path.join(modelBuildingDataDir, "allVirus_pubchem_uM.csv"))
allVirus_pubchem_wSMILES

,CID,smiles,value_uM,pPotency,Activity Name,Virus
0,3779088.0,CN1CCN(CC1)CC(=O)NN(CC2=CC=CC=C2)C3=CC=CC=C3,100.00,4.000000,EC50,Ebola
1,168269649.0,C1CN(CCC1CCNCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)C...,1.50,5.823909,EC50,Ebola
2,172439945.0,C1CN(CCC1CCNCCC(=O)NN2C3=CC=CC=C3C4=CC=CC=C42)...,0.52,6.283997,EC50,Ebola
3,172446737.0,CN1CCN(CC1)CCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3,100.00,4.000000,EC50,Ebola
4,172454212.0,C1CN(CCC1CCNCCC(=O)NN(C2=CC=CC=C2)C3=CC=CC=C3)...,0.30,6.522879,EC50,Ebola
...,...,...,...,...,...,...
172919,172462264.0,C1CN(C(CN1C(=O)C2=C3C(=CN=C2)C=CN3)C(=O)NCC4=C...,0.13,6.886057,EC50,SARS-CoV-2
172920,169494153.0,COC1=CC=C(C=C1)NC(=O)C2CN(CCN2C3=CC(=C(C=C3)Cl...,0.21,6.677781,EC50,SARS-CoV-2
172921,155903259.0,CC1(C2C1C(N(C2)C(=O)C(C(C)(C)C)NC(=O)C(F)(F)F)...,0.28,6.552842,EC50,SARS-CoV-2
172922,172462264.0,C1CN(C(CN1C(=O)C2=C3C(=CN=C2)C=CN3)C(=O)NCC4=C...,0.24,6.619789,EC50,SARS-CoV-2
172923,169494153.0,COC1=CC=C(C=C1)NC(=O)C2CN(CCN2C3=CC(=C(C=C3)Cl...,0.21,6.677781,EC50,SARS-CoV-2

### Pie Chart

In [14]:
print(allVirus_pubchem_wSMILES['Virus'].unique())

['Ebola' 'Marburg' 'Lassa' 'VEEV' 'Nipah' 'Hanta' 'SARS-CoV' 'SARS-CoV-2']

In [13]:
total = len(allVirus_pubchem_wSMILES)

# Unique Virus types with counts and percentages
print(f"Virus Types ({allVirus_pubchem_wSMILES['Virus'].nunique()} unique) | Total: {total}")
virus_counts = allVirus_pubchem_wSMILES['Virus'].value_counts()
for i, (virus, count) in enumerate(virus_counts.items(), 1):
    print(f"  {i}. {virus:<30} {count:>6} ({count/total*100:.2f}%)")

print()

# Unique Activity Name types with counts and percentages
print(f"Activity Types ({allVirus_pubchem_wSMILES['Activity Name'].nunique()} unique) | Total: {total}")
activity_counts = allVirus_pubchem_wSMILES['Activity Name'].value_counts()
for i, (activity, count) in enumerate(activity_counts.items(), 1):
    print(f"  {i}. {activity:<30} {count:>6} ({count/total*100:.2f}%)")

Virus Types (8 unique) | Total: 172924
  1. Lassa                          154444 (89.31%)
  2. Hanta                            8402 (4.86%)
  3. SARS-CoV-2                       4656 (2.69%)
  4. SARS-CoV                         4300 (2.49%)
  5. Marburg                           465 (0.27%)
  6. Ebola                             379 (0.22%)
  7. VEEV                              253 (0.15%)
  8. Nipah                              25 (0.01%)

Activity Types (3 unique) | Total: 172924
  1. Potency                        159654 (92.33%)
  2. IC50                            11282 (6.52%)
  3. EC50                             1988 (1.15%)